import type { WordEntry } from './types';

/**
 * da-DK "Word of the Day" seed list — 732 entries (2 × 366) so the
 * selection cycle in word-of-day-data.ts covers two full years without
 * a repeat. Kept alphabetized (æ, ø, å sidst, dansk stil): presentation
 * order comes from the year-seeded shuffle, so storage order is purely
 * for maintenance (duplicates land adjacent and diffs stay readable).
 */
export const DA_DK_WORDS: WordEntry[] = [
  { word: 'Adstadig', pos: 'adjective', definition: 'Rolig, sindig og værdig i bevægelse og væsen' },
  { word: 'Afdæmpet', pos: 'adjective', definition: 'Behersket og dæmpet i udtryk eller farve' },
  { word: 'Afgrundsdyb', pos: 'adjective', definition: 'Umådelig dyb, som en afgrund' },
  { word: 'Afholdt', pos: 'adjective', definition: 'Vellidt og værdsat af sin omgangskreds' },
  { word: 'Afklaret', pos: 'adjective', definition: 'I ro med sig selv efter moden overvejelse' },
  { word: 'Afkrog', pos: 'noun', definition: 'Fjernt og afsides sted, langt fra alfarvej' },
  { word: 'Afsavn', pos: 'noun', definition: 'Følelsen af at måtte undvære noget kært' },
  { word: 'Afsides', pos: 'adjective', definition: 'Beliggende fjernt fra byer og trafikerede veje' },
  { word: 'Aftenskumring', pos: 'noun', definition: 'Det svindende lys mellem solnedgang og mørke' },
  { word: 'Aftenstund', pos: 'noun', definition: 'Den stille tid sidst på dagen' },
  { word: 'Agtelse', pos: 'noun', definition: 'Dyb respekt for en persons karakter og virke' },
  { word: 'Agtpågivende', pos: 'adjective', definition: 'Opmærksom og på vagt over for det mindste tegn' },
  { word: 'Agtværdig', pos: 'adjective', definition: 'Som fortjener respekt og anseelse' },
  { word: 'Almue', pos: 'noun', definition: 'Den jævne landbefolkning i ældre tid' },
  { word: 'Alsidig', pos: 'adjective', definition: 'Med evner og interesser på mange felter' },
  { word: 'Altfavnende', pos: 'adjective', definition: 'Som rummer og omfatter alt uden undtagelse' },
  { word: 'Alvidende', pos: 'adjective', definition: 'Som ved alt, hvad der kan vides' },
  { word: 'Alvorsfuld', pos: 'adjective', definition: 'Præget af dyb og rolig alvor' },
  { word: 'Andagt', pos: 'noun', definition: 'Stille fordybelse og indre ro' },
  { word: 'Andægtig', pos: 'adjective', definition: 'Opfyldt af stille ærefrygt' },
  { word: 'Ane', pos: 'verb', definition: 'Fornemme svagt uden at vide det bestemt' },
  { word: 'Anelse', pos: 'noun', definition: 'Svag fornemmelse af noget forestående' },
  { word: 'Anfægte', pos: 'verb', definition: 'Rejse tvivl om gyldigheden af noget' },
  { word: 'Anprise', pos: 'verb', definition: 'Fremhæve og rose i høje toner' },
  { word: 'Anselig', pos: 'adjective', definition: 'Betydelig i størrelse eller omfang' },
  { word: 'Anskuelse', pos: 'noun', definition: 'Grundlæggende opfattelse af tingenes sammenhæng' },
  { word: 'Anspore', pos: 'verb', definition: 'Tilskynde og give ny drivkraft' },
  { word: 'Ansvarsfuld', pos: 'adjective', definition: 'Som tager sine forpligtelser dybt alvorligt' },
  { word: 'Arbejdsglæde', pos: 'noun', definition: 'Den lyst og energi et meningsfuldt arbejde giver' },
  { word: 'Arnested', pos: 'noun', definition: 'Sted hvorfra noget udspringer og næres' },
  { word: 'Arvesølv', pos: 'noun', definition: 'Dyrebar ejendom der går i arv gennem slægter' },
  { word: 'Askese', pos: 'noun', definition: 'Bevidst afkald på nydelse og overflod' },
  { word: 'Attrå', pos: 'noun', definition: 'Stærk og brændende længsel efter noget' },
  { word: 'Attråværdig', pos: 'adjective', definition: 'Så tillokkende at man begærer det' },
  { word: 'Ave', pos: 'verb', definition: 'Holde i tømme med fast hånd' },
  { word: 'Balstyrisk', pos: 'adjective', definition: 'Vild, kåd og umulig at styre' },
  { word: 'Barmhjertig', pos: 'adjective', definition: 'Fuld af medfølelse og mildhed mod de svage' },
  { word: 'Bedaget', pos: 'adjective', definition: 'Til års og præget af alderen, lettere spøgende' },
  { word: 'Bedrift', pos: 'noun', definition: 'Stor og modig præstation der huskes' },
  { word: 'Bedårende', pos: 'adjective', definition: 'Så yndig at man helt betages' },
  { word: 'Befordre', pos: 'verb', definition: 'Fremme og hjælpe noget på vej' },
  { word: 'Begavet', pos: 'adjective', definition: 'Udrustet med usædvanligt gode evner' },
  { word: 'Begribe', pos: 'verb', definition: 'Fatte og forstå til bunds' },
  { word: 'Behjertet', pos: 'adjective', definition: 'Modig og handlekraftig af et godt hjerte' },
  { word: 'Behændig', pos: 'adjective', definition: 'Adræt og fingernem i sine bevægelser' },
  { word: 'Bejle', pos: 'verb', definition: 'Søge at vinde nogens gunst eller hjerte' },
  { word: 'Beklemt', pos: 'adjective', definition: 'Trykket af ængstelse og indre uro' },
  { word: 'Bemærkelsesværdig', pos: 'adjective', definition: 'Så usædvanlig at den fortjener opmærksomhed' },
  { word: 'Benovet', pos: 'adjective', definition: 'Imponeret og en smule forlegen' },
  { word: 'Beredvillig', pos: 'adjective', definition: 'Straks parat til at hjælpe' },
  { word: 'Besindig', pos: 'adjective', definition: 'Rolig og velovervejet i sin dømmekraft' },
  { word: 'Besjæle', pos: 'verb', definition: 'Fylde med liv, ånd og begejstring' },
  { word: 'Besnærende', pos: 'adjective', definition: 'Fristende på en næsten uimodståelig måde' },
  { word: 'Besynge', pos: 'verb', definition: 'Hylde i digt og sang' },
  { word: 'Betage', pos: 'verb', definition: 'Fylde med beundring og fortryllelse' },
  { word: 'Betuttet', pos: 'adjective', definition: 'Forvirret og let forlegen' },
  { word: 'Bevæget', pos: 'adjective', definition: 'Grebet af stærke følelser' },
  { word: 'Bifalde', pos: 'verb', definition: 'Give sin udtrykkelige tilslutning' },
  { word: 'Billige', pos: 'verb', definition: 'Godkende og erklære sig enig i' },
  { word: 'Bjergtage', pos: 'verb', definition: 'Fortrylle og tage fuldstændig fangen' },
  { word: 'Blidhed', pos: 'noun', definition: 'Mild og nænsom venlighed' },
  { word: 'Blivende', pos: 'adjective', definition: 'Som varer ved og ikke forgår' },
  { word: 'Blufærdig', pos: 'adjective', definition: 'Tilbageholdende af naturlig undseelse' },
  { word: 'Blændværk', pos: 'noun', definition: 'Skuffende skin uden virkelighed bag' },
  { word: 'Bod', pos: 'noun', definition: 'Soning der gør en begået uret god igen' },
  { word: 'Boglig', pos: 'adjective', definition: 'Knyttet til læsning og lærdom' },
  { word: 'Bramfri', pos: 'adjective', definition: 'Ligefrem og uden omsvøb' },
  { word: 'Bravur', pos: 'noun', definition: 'Glansfuld dygtighed og dristighed' },
  { word: 'Brusende', pos: 'adjective', definition: 'Voldsom og skummende i sin kraft' },
  { word: 'Brændpunkt', pos: 'noun', definition: 'Sted hvor alt samler sig og afgøres' },
  { word: 'Bugne', pos: 'verb', definition: 'Være fyldt til overflod' },
  { word: 'Bundsolid', pos: 'adjective', definition: 'Grundig og pålidelig helt igennem' },
  { word: 'Bølgegang', pos: 'noun', definition: 'Skiftende op- og nedture i følelser eller begivenheder' },
  { word: 'Bønfalde', pos: 'verb', definition: 'Bede indtrængende og ydmygt' },
  { word: 'Bævende', pos: 'adjective', definition: 'Skælvende af sindsbevægelse' },
  { word: 'Dagdrømmer', pos: 'noun', definition: 'En der fortaber sig i fantasier og luftkasteller' },
  { word: 'Daggry', pos: 'noun', definition: 'Den første lysning på himlen før solopgang' },
  { word: 'Dannelse', pos: 'noun', definition: 'Åndelig modenhed og kultiveret optræden' },
  { word: 'Delagtiggøre', pos: 'verb', definition: 'Lade andre få del i noget man ved eller ejer' },
  { word: 'Digterisk', pos: 'adjective', definition: 'Med poetisk skaberkraft og billedrigdom' },
  { word: 'Diskret', pos: 'adjective', definition: 'Taktfuld og uden at vække opsigt' },
  { word: 'Distingveret', pos: 'adjective', definition: 'Fornem og elegant i sin fremtoning' },
  { word: 'Dorsk', pos: 'adjective', definition: 'Træg, sløv og uden handlekraft' },
  { word: 'Drabelig', pos: 'adjective', definition: 'Vældig og frygtindgydende, ofte med et glimt i øjet' },
  { word: 'Dragende', pos: 'adjective', definition: 'Som uimodståeligt trækker én til sig' },
  { word: 'Drilsk', pos: 'adjective', definition: 'Fuld af godmodige narrestreger' },
  { word: 'Dristig', pos: 'adjective', definition: 'Modig på grænsen af det forvovne' },
  { word: 'Drivkraft', pos: 'noun', definition: 'Den indre kraft der får noget til at ske' },
  { word: 'Drømmende', pos: 'adjective', definition: 'Fjern og hensunken i egne tanker' },
  { word: 'Drømmesyn', pos: 'noun', definition: 'Fantasibillede så levende som en drøm' },
  { word: 'Dulme', pos: 'verb', definition: 'Lindre og berolige smerte eller uro' },
  { word: 'Dunkel', pos: 'adjective', definition: 'Halvmørk og svær at gennemskue' },
  { word: 'Duve', pos: 'verb', definition: 'Vugge langsomt og roligt op og ned' },
  { word: 'Dvale', pos: 'noun', definition: 'Dyb hvile hvor alt liv står på lavt blus' },
  { word: 'Dvæle', pos: 'verb', definition: 'Blive hængende ved noget i tanker eller blik' },
  { word: 'Dyd', pos: 'noun', definition: 'Moralsk fortræffelighed og god karakter' },
  { word: 'Dygtiggøre', pos: 'verb', definition: 'Udvikle sine færdigheder målrettet' },
  { word: 'Dyrebar', pos: 'adjective', definition: 'Af stor og uerstattelig værdi' },
  { word: 'Dyster', pos: 'adjective', definition: 'Mørk og tung i stemning' },
  { word: 'Dæmre', pos: 'verb', definition: 'Langsomt begynde at blive lyst eller klart' },
  { word: 'Dømmekraft', pos: 'noun', definition: 'Evnen til at skønne klogt og retfærdigt' },
  { word: 'Dåd', pos: 'noun', definition: 'Stor og modig handling der huskes' },
  { word: 'Efterglød', pos: 'noun', definition: 'Lys og varme der bliver hængende, når kilden er væk' },
  { word: 'Efterhånden', pos: 'adverb', definition: 'Lidt efter lidt, som tiden går' },
  { word: 'Eftermæle', pos: 'noun', definition: 'Det ry og minde man efterlader sig' },
  { word: 'Efterstræbe', pos: 'verb', definition: 'Stræbe ihærdigt efter at opnå' },
  { word: 'Eftertanke', pos: 'noun', definition: 'Rolig overvejelse i stilhed' },
  { word: 'Eftertragtet', pos: 'adjective', definition: 'Som mange ønsker sig brændende' },
  { word: 'Eftertrykkelig', pos: 'adjective', definition: 'Med stor kraft og tydelighed' },
  { word: 'Egenhændigt', pos: 'adverb', definition: 'Med egen hånd, helt uden hjælp' },
  { word: 'Egenrådig', pos: 'adjective', definition: 'Som stædigt følger sin egen vilje' },
  { word: 'Egensindig', pos: 'adjective', definition: 'Med en stærk og ubøjelig egen vilje' },
  { word: 'Ejegod', pos: 'adjective', definition: 'Godhjertet helt ind i kernen' },
  { word: 'Ekvilibrist', pos: 'noun', definition: 'En mester i balancekunst og behændighed' },
  { word: 'Elskelig', pos: 'adjective', definition: 'Så venlig og varm at alle holder af én' },
  { word: 'Eminent', pos: 'adjective', definition: 'Fremragende i særklasse' },
  { word: 'Emsig', pos: 'adjective', definition: 'Overivrig i sin tjenstvillighed' },
  { word: 'Enegænger', pos: 'noun', definition: 'En der helst går sine egne veje' },
  { word: 'Enfoldig', pos: 'adjective', definition: 'Troskyldig og uden svig, i ordets gamle betydning' },
  { word: 'Erindring', pos: 'noun', definition: 'Et minde der dukker op af hukommelsen' },
  { word: 'Erkendtlighed', pos: 'noun', definition: 'Lille gave som tak for en tjeneste' },
  { word: 'Eventyrlig', pos: 'adjective', definition: 'Så vidunderlig at det ligner et eventyr' },
  { word: 'Eventyrlysten', pos: 'adjective', definition: 'Ivrig efter oplevelser og vovestykker' },
  { word: 'Fabelagtig', pos: 'adjective', definition: 'Så god at det næsten ikke er til at tro' },
  { word: 'Fabulere', pos: 'verb', definition: 'Digte frit og fantasifuldt' },
  { word: 'Fager', pos: 'adjective', definition: 'Skøn og dejlig, i gammeldags poetisk sprog' },
  { word: 'Falmet', pos: 'adjective', definition: 'Bleget af tid, sol og slid' },
  { word: 'Famle', pos: 'verb', definition: 'Søge sig usikkert frem med hænderne' },
  { word: 'Fandenivoldsk', pos: 'adjective', definition: 'Vildt dumdristig og ligeglad med følgerne' },
  { word: 'Fatning', pos: 'noun', definition: 'Ro og selvbeherskelse i pressede stunder' },
  { word: 'Fattet', pos: 'adjective', definition: 'Rolig og behersket midt i omvæltninger' },
  { word: 'Favne', pos: 'verb', definition: 'Omslutte med åbne arme' },
  { word: 'Ferm', pos: 'adjective', definition: 'Dygtig og hurtig på fingrene' },
  { word: 'Fingernem', pos: 'adjective', definition: 'Dygtig til fint arbejde med hænderne' },
  { word: 'Finurlig', pos: 'adjective', definition: 'Snedigt og morsomt udtænkt' },
  { word: 'Flanere', pos: 'verb', definition: 'Slentre uden mål og med, for fornøjelsens skyld' },
  { word: 'Flegmatisk', pos: 'adjective', definition: 'Uforstyrrelig rolig af temperament' },
  { word: 'Florere', pos: 'verb', definition: 'Trives og brede sig frodigt' },
  { word: 'Flygtig', pos: 'adjective', definition: 'Som hurtigt forsvinder igen' },
  { word: 'Folkekær', pos: 'adjective', definition: 'Elsket af det brede folk' },
  { word: 'Fordre', pos: 'verb', definition: 'Kræve som en berettiget forventning' },
  { word: 'Fordums', pos: 'adjective', definition: 'Fra svundne tider, som i fordums storhed' },
  { word: 'Fordybelse', pos: 'noun', definition: 'Koncentreret optagethed af én ting' },
  { word: 'Forfinet', pos: 'adjective', definition: 'Udviklet til stor finhed og elegance' },
  { word: 'Forfjamsket', pos: 'adjective', definition: 'Befippet og ude af fatning' },
  { word: 'Forgabe', pos: 'verb', definition: 'Blive blindt og hovedkulds betaget' },
  { word: 'Forgæves', pos: 'adverb', definition: 'Uden at det nytter noget' },
  { word: 'Forhippet', pos: 'adjective', definition: 'Alt for ivrig efter at få noget' },
  { word: 'Forjættende', pos: 'adjective', definition: 'Som lover noget vidunderligt forude' },
  { word: 'Forkynde', pos: 'verb', definition: 'Bekendtgøre højtideligt og med vægt' },
  { word: 'Formfuldendt', pos: 'adjective', definition: 'Fuldkommen i form og udførelse' },
  { word: 'Formilde', pos: 'verb', definition: 'Gøre mildere stemt' },
  { word: 'Formå', pos: 'verb', definition: 'Have evne og kraft til at gøre noget' },
  { word: 'Fornøjelig', pos: 'adjective', definition: 'Munter og underholdende' },
  { word: 'Forsage', pos: 'verb', definition: 'Give afkald på og vende ryggen til' },
  { word: 'Forsagt', pos: 'adjective', definition: 'Frygtsom og uden tro på sig selv' },
  { word: 'Forsonlig', pos: 'adjective', definition: 'Villig til at tilgive og slutte fred' },
  { word: 'Forstandig', pos: 'adjective', definition: 'Klog og fornuftig i sin dømmekraft' },
  { word: 'Fortrolighed', pos: 'noun', definition: 'Nært og tillidsfuldt kendskab' },
  { word: 'Fortryllende', pos: 'adjective', definition: 'Så dejlig at man føler sig forhekset' },
  { word: 'Fortræffelig', pos: 'adjective', definition: 'Ualmindelig god og vellykket' },
  { word: 'Fortrøstning', pos: 'noun', definition: 'Tillidsfuld tro på at det nok skal gå' },
  { word: 'Forudanelse', pos: 'noun', definition: 'Fornemmelse af noget der vil ske' },
  { word: 'Forunderlig', pos: 'adjective', definition: 'Mærkelig på en vidunderlig måde' },
  { word: 'Forundring', pos: 'noun', definition: 'Åben og undrende overraskelse' },
  { word: 'Forvoven', pos: 'adjective', definition: 'Dristig ud over det forsvarlige' },
  { word: 'Fostre', pos: 'verb', definition: 'Frembringe og nære, fx en idé' },
  { word: 'Fremelske', pos: 'verb', definition: 'Kalde frem og pleje det bedste i nogen' },
  { word: 'Fremmelig', pos: 'adjective', definition: 'Tidligt udviklet og dygtig for sin alder' },
  { word: 'Fremsynet', pos: 'adjective', definition: 'Med blik for hvad fremtiden kræver' },
  { word: 'Frimodig', pos: 'adjective', definition: 'Åben og uden frygt for at sige sin mening' },
  { word: 'Frisind', pos: 'noun', definition: 'Åbenhed over for andres levevis og tanker' },
  { word: 'Frodig', pos: 'adjective', definition: 'Yppig og rig i sin vækst' },
  { word: 'Fryde', pos: 'verb', definition: 'Glæde inderligt' },
  { word: 'Frydefuld', pos: 'adjective', definition: 'Fuld af jublende glæde' },
  { word: 'Fuldbyrde', pos: 'verb', definition: 'Føre helt til ende' },
  { word: 'Fuldkommen', pos: 'adjective', definition: 'Uden mangler af nogen art' },
  { word: 'Funkle', pos: 'verb', definition: 'Glimte og spille livligt i lyset' },
  { word: 'Fyndig', pos: 'adjective', definition: 'Kraftfuld og rammende i få ord' },
  { word: 'Fyndord', pos: 'noun', definition: 'Kort og rammende udtryk' },
  { word: 'Fyrig', pos: 'adjective', definition: 'Fuld af ild og lidenskab' },
  { word: 'Færd', pos: 'noun', definition: 'Rejse eller foretagende, ofte med vovemod' },
  { word: 'Fæstne', pos: 'verb', definition: 'Gøre fast og varig' },
  { word: 'Fåmælt', pos: 'adjective', definition: 'Som siger lidt, men mener meget' },
  { word: 'Gammelklog', pos: 'adjective', definition: 'Klog på en måde der overgår ens alder' },
  { word: 'Gavmild', pos: 'adjective', definition: 'Rundhåndet og glad for at give' },
  { word: 'Gavnlig', pos: 'adjective', definition: 'Til nytte og gode for nogen' },
  { word: 'Gedigen', pos: 'adjective', definition: 'Ægte og solid i materiale og kvalitet' },
  { word: 'Gemyt', pos: 'noun', definition: 'Sindets grundstemning og temperament' },
  { word: 'Gemytlig', pos: 'adjective', definition: 'Hyggelig og godmodigt afslappet' },
  { word: 'Genklang', pos: 'noun', definition: 'Lyd eller følelse der vækkes som svar' },
  { word: 'Gennemgribende', pos: 'adjective', definition: 'Som forandrer alt til bunds' },
  { word: 'Gennemsyre', pos: 'verb', definition: 'Trænge igennem og præge helt' },
  { word: 'Genstridig', pos: 'adjective', definition: 'Stædigt modvillig og svær at bøje' },
  { word: 'Gevaldig', pos: 'adjective', definition: 'Meget stor og kraftig' },
  { word: 'Gilde', pos: 'noun', definition: 'Festligt lag med mad og drikke' },
  { word: 'Glansfuld', pos: 'adjective', definition: 'Strålende og prægtig' },
  { word: 'Glædesrus', pos: 'noun', definition: 'Overvældende bølge af glæde' },
  { word: 'Gløde', pos: 'verb', definition: 'Brænde indefra med stille styrke' },
  { word: 'Godhjertet', pos: 'adjective', definition: 'Med et varmt og venligt sind' },
  { word: 'Godmodig', pos: 'adjective', definition: 'Fredsommelig og uden ondskab' },
  { word: 'Godte', pos: 'verb', definition: 'Glæde sig lunt, gerne lidt skadefro' },
  { word: 'Grangiveligt', pos: 'adverb', definition: 'Tydeligt og umiskendeligt, som var det virkeligt' },
  { word: 'Granske', pos: 'verb', definition: 'Undersøge grundigt og forskende' },
  { word: 'Gribende', pos: 'adjective', definition: 'Som rører hjertet dybt' },
  { word: 'Gruble', pos: 'verb', definition: 'Tænke dybt og længe over noget svært' },
  { word: 'Grundfæstet', pos: 'adjective', definition: 'Solidt forankret og urokkelig' },
  { word: 'Gry', pos: 'verb', definition: 'Begynde at lysne, om dag og om håb' },
  { word: 'Gunst', pos: 'noun', definition: 'Velvilje og nåde fra en der har magt' },
  { word: 'Gæstfrihed', pos: 'noun', definition: 'Hjertelig åbenhed over for gæster' },
  { word: 'Gæv', pos: 'adjective', definition: 'Rask, retskaffen og pålidelig' },
  { word: 'Gøgl', pos: 'noun', definition: 'Glad gadekunst og muntre narrestreger' },
  { word: 'Gådefuld', pos: 'adjective', definition: 'Fuld af mystik og ubesvarede spørgsmål' },
  { word: 'Gåpåmod', pos: 'noun', definition: 'Frisk vilje til at kaste sig ud i tingene' },
  { word: 'Habil', pos: 'adjective', definition: 'Solidt dygtig til sit fag' },
  { word: 'Halsbrækkende', pos: 'adjective', definition: 'Så dristig at det kan koste hals og ben' },
  { word: 'Handlekraft', pos: 'noun', definition: 'Evne til at gribe ind og få ting gjort' },
  { word: 'Henført', pos: 'adjective', definition: 'Grebet af begejstret fortabelse' },
  { word: 'Hengiven', pos: 'adjective', definition: 'Trofast og kærligt knyttet' },
  { word: 'Henrykkelse', pos: 'noun', definition: 'Overstrømmende glæde og begejstring' },
  { word: 'Hensunken', pos: 'adjective', definition: 'Dybt optaget og fjern fra omverdenen' },
  { word: 'Hensynsfuld', pos: 'adjective', definition: 'Opmærksom på andres behov' },
  { word: 'Himmelfalden', pos: 'adjective', definition: 'Målløs af forbavselse' },
  { word: 'Himmelstræbende', pos: 'adjective', definition: 'Som rækker mod himlen i højde eller ambition' },
  { word: 'Hjemve', pos: 'noun', definition: 'Længsel efter sit hjem og sine egne' },
  { word: 'Hjertelag', pos: 'noun', definition: 'Ens medfølende sindelag' },
  { word: 'Hjertensgod', pos: 'adjective', definition: 'God helt ind i hjertet' },
  { word: 'Hjertevarm', pos: 'adjective', definition: 'Med ægte varme over for andre' },
  { word: 'Hovmod', pos: 'noun', definition: 'Overdreven stolthed der ser ned på andre' },
  { word: 'Hygge', pos: 'noun', definition: 'Varmt og afslappet samvær i trygge rammer' },
  { word: 'Hylde', pos: 'verb', definition: 'Ære og fejre med begejstring' },
  { word: 'Hæder', pos: 'noun', definition: 'Offentlig ære og anerkendelse' },
  { word: 'Hæderlig', pos: 'adjective', definition: 'Redelig og til at stole på' },
  { word: 'Hændelsesrig', pos: 'adjective', definition: 'Fuld af oplevelser og begivenheder' },
  { word: 'Hærdet', pos: 'adjective', definition: 'Gjort stærk gennem modgang' },
  { word: 'Højsindet', pos: 'adjective', definition: 'Ædel og storsindet i sin tankegang' },
  { word: 'Højstemt', pos: 'adjective', definition: 'Festligt og alvorligt løftet i tonen' },
  { word: 'Højtidelig', pos: 'adjective', definition: 'Præget af værdighed og alvor' },
  { word: 'Håbefuld', pos: 'adjective', definition: 'Fuld af håb og lovende udsigter' },
  { word: 'Håndelag', pos: 'noun', definition: 'Naturlig færdighed i praktisk arbejde' },
  { word: 'Håndgribelig', pos: 'adjective', definition: 'Så konkret at man kan tage og føle på det' },
  { word: 'Hårdfør', pos: 'adjective', definition: 'Som tåler vind, vejr og modgang' },
  { word: 'Idelig', pos: 'adjective', definition: 'Stadig tilbagevendende, uophørlig' },
  { word: 'Idérig', pos: 'adjective', definition: 'Fuld af nye indfald og påhit' },
  { word: 'Idyl', pos: 'noun', definition: 'Fredfyldt og harmonisk lille verden' },
  { word: 'Ihukomme', pos: 'verb', definition: 'Mindes højtideligt og med taknemmelighed' },
  { word: 'Ihærdig', pos: 'adjective', definition: 'Vedholdende og utrættelig i sin stræben' },
  { word: 'Ildhu', pos: 'noun', definition: 'Brændende iver og begejstring for en sag' },
  { word: 'Ildne', pos: 'verb', definition: 'Opflamme og tilskynde til handling' },
  { word: 'Ildsjæl', pos: 'noun', definition: 'Person der brænder for en sag og tænder andre' },
  { word: 'Imødekommende', pos: 'adjective', definition: 'Venlig og åben over for andres ønsker' },
  { word: 'Inderlig', pos: 'adjective', definition: 'Dybtfølt og ægte' },
  { word: 'Indfald', pos: 'noun', definition: 'Pludselig og original idé' },
  { word: 'Indlevelse', pos: 'noun', definition: 'Evnen til at sætte sig i andres sted' },
  { word: 'Indsigtsfuld', pos: 'adjective', definition: 'Med dyb forståelse af tingenes sammenhæng' },
  { word: 'Indtagende', pos: 'adjective', definition: 'Charmerende og vindende i sit væsen' },
  { word: 'Islæt', pos: 'noun', definition: 'Tydeligt spor eller element af noget i en helhed' },
  { word: 'Iver', pos: 'noun', definition: 'Brændende lyst til at komme i gang' },
  { word: 'Jomfruelig', pos: 'adjective', definition: 'Uberørt og uspoleret, om natur og nyt land' },
  { word: 'Jordbunden', pos: 'adjective', definition: 'Praktisk og realistisk anlagt' },
  { word: 'Jordnær', pos: 'adjective', definition: 'Ligetil og uden fine fornemmelser' },
  { word: 'Jovial', pos: 'adjective', definition: 'Gemytligt venlig og ligefrem' },
  { word: 'Jubel', pos: 'noun', definition: 'Højlydt og fælles glæde' },
  { word: 'Jærtegn', pos: 'noun', definition: 'Varsel eller tegn på noget skæbnesvangert' },
  { word: 'Kappestrid', pos: 'noun', definition: 'Venskabelig konkurrence om at være bedst' },
  { word: 'Karsk', pos: 'adjective', definition: 'Frisk, sund og rask, i ældre sprog' },
  { word: 'Kernesund', pos: 'adjective', definition: 'Sund helt ind i kernen' },
  { word: 'Klarsyn', pos: 'noun', definition: 'Evnen til at se tingene som de virkelig er' },
  { word: 'Klinge', pos: 'verb', definition: 'Lyde rent og tydeligt' },
  { word: 'Klippefast', pos: 'adjective', definition: 'Urokkeligt fast som klippegrund' },
  { word: 'Klædelig', pos: 'adjective', definition: 'Som pynter og passer godt til' },
  { word: 'Kløgt', pos: 'noun', definition: 'Praktisk snarrådighed og skarpsindighed' },
  { word: 'Knejse', pos: 'verb', definition: 'Rette sig stolt op og rage frem' },
  { word: 'Knirkefrit', pos: 'adverb', definition: 'Uden nogen form for gnidninger eller problemer' },
  { word: 'Knivskarp', pos: 'adjective', definition: 'Ekstremt skarp i tanke eller kant' },
  { word: 'Kry', pos: 'adjective', definition: 'Stolt og veltilfreds med sig selv' },
  { word: 'Kundskab', pos: 'noun', definition: 'Viden erhvervet gennem læring og erfaring' },
  { word: 'Kunstfærdig', pos: 'adjective', definition: 'Udført med stor kunst og snilde' },
  { word: 'Kyndig', pos: 'adjective', definition: 'Med grundigt kendskab til sit område' },
  { word: 'Kæk', pos: 'adjective', definition: 'Frejdig og modig med et smil' },
  { word: 'Kærkommen', pos: 'adjective', definition: 'Modtaget med glæde, netop hvad man ønskede' },
  { word: 'Kølvand', pos: 'noun', definition: 'Sporet noget efterlader sig' },
  { word: 'Kåd', pos: 'adjective', definition: 'Overstadigt legesyg' },
  { word: 'Labyrintisk', pos: 'adjective', definition: 'Snoet og indviklet som en labyrint' },
  { word: 'Landlig', pos: 'adjective', definition: 'Med landets ro og enkelhed' },
  { word: 'Langmodig', pos: 'adjective', definition: 'Tålmodig ud over det sædvanlige' },
  { word: 'Lattermild', pos: 'adjective', definition: 'Hurtig til at le' },
  { word: 'Ledestjerne', pos: 'noun', definition: 'Det ideal man styrer sit liv efter' },
  { word: 'Lediggang', pos: 'noun', definition: 'Tid uden pligter, roden til både hvile og uro' },
  { word: 'Lempe', pos: 'verb', definition: 'Flytte forsigtigt og hensynsfuldt' },
  { word: 'Lempelig', pos: 'adjective', definition: 'Mild og skånsom i sin fremgangsmåde' },
  { word: 'Letbenet', pos: 'adjective', definition: 'Hurtig og ubesværet i sin gang' },
  { word: 'Letsind', pos: 'noun', definition: 'Ubekymret mangel på omtanke' },
  { word: 'Levendegøre', pos: 'verb', definition: 'Gøre nærværende og livagtig' },
  { word: 'Levned', pos: 'noun', definition: 'Et menneskes liv og færden' },
  { word: 'Lidenskab', pos: 'noun', definition: 'Altopslugende følelse og passion' },
  { word: 'Liflig', pos: 'adjective', definition: 'Dejlig frisk og sød for sanserne' },
  { word: 'Ligefrem', pos: 'adjective', definition: 'Naturlig og uden omsvøb' },
  { word: 'Ligevægt', pos: 'noun', definition: 'Indre balance og ro' },
  { word: 'Lindre', pos: 'verb', definition: 'Mildne smerte eller ubehag' },
  { word: 'Listig', pos: 'adjective', definition: 'Snu og opfindsom i det skjulte' },
  { word: 'Livsalig', pos: 'adjective', definition: 'Himmelsk dejlig, i gammelt sprog' },
  { word: 'Livsappetit', pos: 'noun', definition: 'Grådig glæde ved alt hvad livet byder' },
  { word: 'Livsbekræftende', pos: 'adjective', definition: 'Som styrker troen på livets godhed' },
  { word: 'Livsgerning', pos: 'noun', definition: 'Det værk et helt liv er viet til' },
  { word: 'Livsklog', pos: 'adjective', definition: 'Klog af levet liv snarere end af bøger' },
  { word: 'Livskraft', pos: 'noun', definition: 'Den energi der bærer alt levende' },
  { word: 'Livsmod', pos: 'noun', definition: 'Modet til at tage livet på sig med glæde' },
  { word: 'Livsnyder', pos: 'noun', definition: 'En der forstår at nyde tilværelsens goder' },
  { word: 'Lovprise', pos: 'verb', definition: 'Rose i de højeste toner' },
  { word: 'Lun', pos: 'adjective', definition: 'Behageligt varm; stilfærdigt humoristisk' },
  { word: 'Lune', pos: 'noun', definition: 'Stilfærdig humor; skiftende sindsstemning' },
  { word: 'Lunefuld', pos: 'adjective', definition: 'Uforudsigelig i sine pludselige skift' },
  { word: 'Lutre', pos: 'verb', definition: 'Rense og forædle gennem prøvelser' },
  { word: 'Lydefri', pos: 'adjective', definition: 'Uden fejl eller dadel' },
  { word: 'Lydhør', pos: 'adjective', definition: 'Villig til virkelig at lytte' },
  { word: 'Lydløst', pos: 'adverb', definition: 'Uden den mindste lyd' },
  { word: 'Lykketræf', pos: 'noun', definition: 'Heldigt sammenfald af omstændigheder' },
  { word: 'Lyksalig', pos: 'adjective', definition: 'Fuldkommen lykkelig' },
  { word: 'Lysne', pos: 'verb', definition: 'Blive lysere, om himmel og om udsigter' },
  { word: 'Lysvågen', pos: 'adjective', definition: 'Helt vågen og skarpt opmærksom' },
  { word: 'Lægedom', pos: 'noun', definition: 'Helbredelse og lindring, i ældre sprog' },
  { word: 'Lærd', pos: 'adjective', definition: 'Med dyb boglig viden' },
  { word: 'Lærerig', pos: 'adjective', definition: 'Som man bliver klogere af' },
  { word: 'Længselsfuld', pos: 'adjective', definition: 'Fyldt af stille længsel' },
  { word: 'Lødig', pos: 'adjective', definition: 'Af ægte og god kvalitet' },
  { word: 'Løfterig', pos: 'adjective', definition: 'Som tegner lyst for fremtiden' },
  { word: 'Lønlig', pos: 'adjective', definition: 'Skjult og hemmelig, i poetisk sprog' },
  { word: 'Magelig', pos: 'adjective', definition: 'Bekvem og uden anstrengelse' },
  { word: 'Mageløs', pos: 'adjective', definition: 'Uden lige, ganske enestående' },
  { word: 'Majestætisk', pos: 'adjective', definition: 'Ophøjet og værdig som en konge' },
  { word: 'Malerisk', pos: 'adjective', definition: 'Så smuk som et maleri' },
  { word: 'Meddelsom', pos: 'adjective', definition: 'Åben og villig til at fortælle' },
  { word: 'Medfølelse', pos: 'noun', definition: 'Evnen til at føle andres smerte' },
  { word: 'Medgang', pos: 'noun', definition: 'Tid hvor alting lykkes' },
  { word: 'Medgørlig', pos: 'adjective', definition: 'Nem at samarbejde med' },
  { word: 'Medlevende', pos: 'adjective', definition: 'Som deltager med hjertet i andres liv' },
  { word: 'Medmenneskelighed', pos: 'noun', definition: 'Varme og omsorg for andre mennesker' },
  { word: 'Medvind', pos: 'noun', definition: 'Gunstige vilkår der bærer fremad' },
  { word: 'Menneskekender', pos: 'noun', definition: 'En der forstår sig på menneskers natur' },
  { word: 'Mesterstykke', pos: 'noun', definition: 'Arbejde der viser fuldendt kunnen' },
  { word: 'Mildhed', pos: 'noun', definition: 'Blid og overbærende venlighed' },
  { word: 'Mildne', pos: 'verb', definition: 'Gøre blidere og mindre hård' },
  { word: 'Mindelse', pos: 'noun', definition: 'Noget der kalder et minde frem' },
  { word: 'Mindeværdig', pos: 'adjective', definition: 'Værd at huske længe' },
  { word: 'Minsandten', pos: 'adverb', definition: 'Sandelig, tro det eller ej' },
  { word: 'Mismod', pos: 'noun', definition: 'Tungt og modløst sind' },
  { word: 'Modne', pos: 'verb', definition: 'Udvikle sig til fuld styrke og dybde' },
  { word: 'Modstandskraft', pos: 'noun', definition: 'Evnen til at stå imod pres og modgang' },
  { word: 'Modvægt', pos: 'noun', definition: 'Det der holder noget andet i balance' },
  { word: 'Morgenduelig', pos: 'adjective', definition: 'Frisk og veloplagt tidligt om morgenen' },
  { word: 'Morgengry', pos: 'noun', definition: 'Dagens allerførste lys' },
  { word: 'Mundgodt', pos: 'noun', definition: 'Småting der smager dejligt' },
  { word: 'Mundret', pos: 'adjective', definition: 'Let og naturlig at sige højt' },
  { word: 'Muntre', pos: 'verb', definition: 'Sætte i godt humør' },
  { word: 'Musisk', pos: 'adjective', definition: 'Med sans for kunst og musik' },
  { word: 'Myldre', pos: 'verb', definition: 'Vrimle frem i store mængder' },
  { word: 'Myndig', pos: 'adjective', definition: 'Med naturlig autoritet' },
  { word: 'Møjsommeligt', pos: 'adverb', definition: 'Med stort besvær og sej tålmodighed' },
  { word: 'Målbevidst', pos: 'adjective', definition: 'Med blikket fast rettet mod sit mål' },
  { word: 'Nathimmel', pos: 'noun', definition: 'Himlen i mørke med stjerner og måne' },
  { word: 'Naturtro', pos: 'adjective', definition: 'Gengivet nøjagtigt som i virkeligheden' },
  { word: 'Navnkundig', pos: 'adjective', definition: 'Vidt berømt, i ældre sprog' },
  { word: 'Navnlig', pos: 'adverb', definition: 'Især og først og fremmest' },
  { word: 'Nemme', pos: 'noun', definition: 'Naturlig evne til at lære, som i et godt nemme' },
  { word: 'Nidkær', pos: 'adjective', definition: 'Overordentlig ihærdig og pligtopfyldende' },
  { word: 'Nippe', pos: 'verb', definition: 'Drikke i små forsigtige slurke' },
  { word: 'Nobel', pos: 'adjective', definition: 'Ædel og fornem i sindelag' },
  { word: 'Nordlys', pos: 'noun', definition: 'Farvede lysbuer på nattehimlen i nord' },
  { word: 'Nostalgi', pos: 'noun', definition: 'Sødmefuld længsel efter det forgangne' },
  { word: 'Nuance', pos: 'noun', definition: 'Fin forskel i farve eller betydning' },
  { word: 'Nuomstunder', pos: 'adverb', definition: 'Nu om dage, i vor tid' },
  { word: 'Nybagt', pos: 'adjective', definition: 'Helt ny i en rolle, som en nybagt far' },
  { word: 'Nyfigen', pos: 'adjective', definition: 'Nysgerrig på en lidt påtrængende måde' },
  { word: 'Nænsom', pos: 'adjective', definition: 'Forsigtig og skånsom i sin berøring' },
  { word: 'Nærvær', pos: 'noun', definition: 'Fuld tilstedeværelse i øjeblikket' },
  { word: 'Næstekærlighed', pos: 'noun', definition: 'Uselvisk kærlighed til sine medmennesker' },
  { word: 'Nødig', pos: 'adverb', definition: 'Helst ikke, kun modvilligt' },
  { word: 'Nøgtern', pos: 'adjective', definition: 'Saglig og uden overdrivelser' },
  { word: 'Nøjsom', pos: 'adjective', definition: 'Tilfreds med lidt' },
  { word: 'Nåde', pos: 'noun', definition: 'Ufortjent mildhed og tilgivelse' },
  { word: 'Oase', pos: 'noun', definition: 'Frodigt fristed midt i det golde' },
  { word: 'Obsternasig', pos: 'adjective', definition: 'Trodsig og opsætsig, gerne med et glimt i øjet' },
  { word: 'Offervilje', pos: 'noun', definition: 'Villighed til at give afkald for andres skyld' },
  { word: 'Omfavne', pos: 'verb', definition: 'Slutte i sine arme; tage helhjertet til sig' },
  { word: 'Omgængelig', pos: 'adjective', definition: 'Nem og behagelig at være sammen med' },
  { word: 'Omhu', pos: 'noun', definition: 'Kærlig grundighed i alt hvad man gør' },
  { word: 'Omsider', pos: 'adverb', definition: 'Langt om længe' },
  { word: 'Omsigt', pos: 'noun', definition: 'Praktisk overblik og forudseenhed' },
  { word: 'Omskiftelig', pos: 'adjective', definition: 'Ustadig og evigt vekslende' },
  { word: 'Omsorgsfuld', pos: 'adjective', definition: 'Fuld af kærlig opmærksomhed' },
  { word: 'Omtanke', pos: 'noun', definition: 'Hensynsfuld eftertanke før handling' },
  { word: 'Omvæltning', pos: 'noun', definition: 'Gennemgribende forandring' },
  { word: 'Opbyggelig', pos: 'adjective', definition: 'Som styrker sind og moral' },
  { word: 'Opdrift', pos: 'noun', definition: 'Indre trang til at stige og stræbe opad' },
  { word: 'Opfindsom', pos: 'adjective', definition: 'Rig på snilde løsninger' },
  { word: 'Ophav', pos: 'noun', definition: 'Udspring og oprindelse' },
  { word: 'Ophøjet', pos: 'adjective', definition: 'Hævet over det smålige og jordiske' },
  { word: 'Opildne', pos: 'verb', definition: 'Tænde begejstring og kampgejst' },
  { word: 'Oplagt', pos: 'adjective', definition: 'Frisk og i humør til noget' },
  { word: 'Oplive', pos: 'verb', definition: 'Sætte nyt liv og humør i' },
  { word: 'Oplyst', pos: 'adjective', definition: 'Præget af viden og fordomsfrihed' },
  { word: 'Opløftende', pos: 'adjective', definition: 'Som løfter humøret og sindet' },
  { word: 'Opofrende', pos: 'adjective', definition: 'Som sætter andres vel over sit eget' },
  { word: 'Oprigtig', pos: 'adjective', definition: 'Ærlig og uden forstillelse' },
  { word: 'Oprømt', pos: 'adjective', definition: 'I løftet og glad stemning' },
  { word: 'Opstemt', pos: 'adjective', definition: 'Løftet af glad forventning' },
  { word: 'Ordentlighed', pos: 'noun', definition: 'Redelighed og orden i sin færd' },
  { word: 'Ordholden', pos: 'adjective', definition: 'Som holder hvad han lover' },
  { word: 'Ovenud', pos: 'adverb', definition: 'I usædvanlig høj grad' },
  { word: 'Overbærende', pos: 'adjective', definition: 'Tålmodigt tilgivende over for fejl' },
  { word: 'Overdådig', pos: 'adjective', definition: 'Rig og flot i overflod' },
  { word: 'Overflod', pos: 'noun', definition: 'Mere end rigeligt af alt' },
  { word: 'Overgiven', pos: 'adjective', definition: 'Kåd og løssluppen af glæde' },
  { word: 'Overkommelig', pos: 'adjective', definition: 'Til at magte uden at segne' },
  { word: 'Overmod', pos: 'noun', definition: 'Dumdristigt mod uden omtanke' },
  { word: 'Overskud', pos: 'noun', definition: 'Ekstra kraft og venlighed at give af' },
  { word: 'Pejlemærke', pos: 'noun', definition: 'Fast punkt man kan navigere efter' },
  { word: 'Perlerække', pos: 'noun', definition: 'Ubrudt række af fine ting' },
  { word: 'Pertentlig', pos: 'adjective', definition: 'Omhyggelig ned i mindste detalje' },
  { word: 'Pible', pos: 'verb', definition: 'Sive frem i små dryp eller stråler' },
  { word: 'Pletfri', pos: 'adjective', definition: 'Uden en eneste plet på sit ry' },
  { word: 'Pligtopfyldende', pos: 'adjective', definition: 'Trofast mod sine pligter' },
  { word: 'Pludre', pos: 'verb', definition: 'Snakke løst og hyggeligt' },
  { word: 'Pragtfuld', pos: 'adjective', definition: 'Storslået og herlig' },
  { word: 'Prisværdig', pos: 'adjective', definition: 'Som fortjener ros' },
  { word: 'Prunkløs', pos: 'adjective', definition: 'Enkel og uden pral' },
  { word: 'Prægnant', pos: 'adjective', definition: 'Skarpt og fyndigt formuleret' },
  { word: 'Prøvelse', pos: 'noun', definition: 'Hård udfordring der tester ens styrke' },
  { word: 'Purung', pos: 'adjective', definition: 'Helt ung og grøn' },
  { word: 'Pusterum', pos: 'noun', definition: 'Kort tiltrængt pause' },
  { word: 'Pønse', pos: 'verb', definition: 'Gruble over en plan, gerne i det skjulte' },
  { word: 'Påfund', pos: 'noun', definition: 'Opfindsomt indfald og påhit' },
  { word: 'Pålidelig', pos: 'adjective', definition: 'Til at regne med i alle forhold' },
  { word: 'Påpasselig', pos: 'adjective', definition: 'Omhyggeligt forsigtig' },
  { word: 'Påskønne', pos: 'verb', definition: 'Vise at man sætter pris på' },
  { word: 'Rammende', pos: 'adjective', definition: 'Som træffer plet i sin beskrivelse' },
  { word: 'Rank', pos: 'adjective', definition: 'Ret og stolt i holdningen' },
  { word: 'Rastløs', pos: 'adjective', definition: 'Ude af stand til at finde ro' },
  { word: 'Realitetssans', pos: 'noun', definition: 'Sikker sans for det gennemførlige' },
  { word: 'Redebon', pos: 'adjective', definition: 'Straks villig og parat, i ældre sprog' },
  { word: 'Redelig', pos: 'adjective', definition: 'Ærlig og ordentlig i sin færd' },
  { word: 'Refugium', pos: 'noun', definition: 'Fredet tilflugtssted til fordybelse' },
  { word: 'Rejselyst', pos: 'noun', definition: 'Trang til at drage ud og se verden' },
  { word: 'Rendyrke', pos: 'verb', definition: 'Udvikle i sin reneste form' },
  { word: 'Renfærdig', pos: 'adjective', definition: 'Moralsk ren og uden svig' },
  { word: 'Resolut', pos: 'adjective', definition: 'Beslutsom og uden tøven' },
  { word: 'Retfærd', pos: 'noun', definition: 'Retfærdighed, i højtideligt sprog' },
  { word: 'Retlinet', pos: 'adjective', definition: 'Ærlig og principfast i sin adfærd' },
  { word: 'Retsind', pos: 'noun', definition: 'Et retskaffent og redeligt sindelag' },
  { word: 'Retskaffen', pos: 'adjective', definition: 'Hæderlig og moralsk pålidelig' },
  { word: 'Rettesnor', pos: 'noun', definition: 'Princip man retter sig efter' },
  { word: 'Ridderlig', pos: 'adjective', definition: 'Ædelmodig og høflig som en ridder' },
  { word: 'Risle', pos: 'verb', definition: 'Løbe sagte med blød klukkende lyd' },
  { word: 'Rodfæste', pos: 'verb', definition: 'Slå dyb og varig rod' },
  { word: 'Rorgænger', pos: 'noun', definition: 'Den der står ved roret og holder kursen' },
  { word: 'Rummelig', pos: 'adjective', definition: 'Med plads til forskellighed' },
  { word: 'Rundeligt', pos: 'adverb', definition: 'I rigeligt mål' },
  { word: 'Rundhåndet', pos: 'adjective', definition: 'Gavmild uden at tælle efter' },
  { word: 'Rygrad', pos: 'noun', definition: 'Moralsk styrke til at stå fast' },
  { word: 'Rørende', pos: 'adjective', definition: 'Som vækker øm bevægelse' },
  { word: 'Rørig', pos: 'adjective', definition: 'Rask og bevægelig trods alder' },
  { word: 'Rørstrømsk', pos: 'adjective', definition: 'Sentimental på en lidt klæbrig måde' },
  { word: 'Råderum', pos: 'noun', definition: 'Frihed til selv at bestemme' },
  { word: 'Rådsnar', pos: 'adjective', definition: 'Hurtig til at finde udvej i knibe' },
  { word: 'Rådvild', pos: 'adjective', definition: 'Usikker på hvad man skal gribe til' },
  { word: 'Sagn', pos: 'noun', definition: 'Gammel fortælling på grænsen af det historiske' },
  { word: 'Sagte', pos: 'adverb', definition: 'Stille og dæmpet' },
  { word: 'Sagtmodig', pos: 'adjective', definition: 'Mild og tålmodig af sind' },
  { word: 'Samdrægtighed', pos: 'noun', definition: 'Fredelig enighed og sammenhold' },
  { word: 'Samhørighed', pos: 'noun', definition: 'Følelsen af at høre sammen' },
  { word: 'Samklang', pos: 'noun', definition: 'Harmonisk overensstemmelse' },
  { word: 'Sammenhold', pos: 'noun', definition: 'Trofast fællesskab der står sammen' },
  { word: 'Samvittighedsfuld', pos: 'adjective', definition: 'Grundig af hensyn til sin samvittighed' },
  { word: 'Sanddru', pos: 'adjective', definition: 'Som altid taler sandt' },
  { word: 'Sandfærdig', pos: 'adjective', definition: 'I overensstemmelse med sandheden' },
  { word: 'Sangbund', pos: 'noun', definition: 'Modtagelighed der får noget til at klinge' },
  { word: 'Sanselig', pos: 'adjective', definition: 'Rettet mod sansernes nydelse' },
  { word: 'Sart', pos: 'adjective', definition: 'Fin og let at såre' },
  { word: 'Selverkendelse', pos: 'noun', definition: 'Ærligt kendskab til egne styrker og svagheder' },
  { word: 'Selvhjulpen', pos: 'adjective', definition: 'I stand til at klare sig selv' },
  { word: 'Selvsagt', pos: 'adverb', definition: 'Naturligvis, som en selvfølge' },
  { word: 'Sindbillede', pos: 'noun', definition: 'Symbol der anskueliggør en tanke' },
  { word: 'Sindelag', pos: 'noun', definition: 'Grundholdningen i ens sind' },
  { word: 'Sindig', pos: 'adjective', definition: 'Rolig og eftertænksom, en jysk dyd' },
  { word: 'Sindsro', pos: 'noun', definition: 'Uforstyrret indre fred' },
  { word: 'Sirlig', pos: 'adjective', definition: 'Nydelig og omhyggeligt ordnet' },
  { word: 'Sitre', pos: 'verb', definition: 'Dirre fint af spænding eller bevægelse' },
  { word: 'Sjælefred', pos: 'noun', definition: 'Dyb og uforstyrret fred i sindet' },
  { word: 'Skabertrang', pos: 'noun', definition: 'Uimodståelig lyst til at skabe' },
  { word: 'Skam', pos: 'adverb', definition: 'Sandelig, bestemt, som i det er skam rigtigt' },
  { word: 'Skarpsindig', pos: 'adjective', definition: 'Med skarp og gennemtrængende forstand' },
  { word: 'Skatkammer', pos: 'noun', definition: 'Rigt gemmested for kostbarheder' },
  { word: 'Skelsættende', pos: 'adjective', definition: 'Så vigtig at den deler tiden i før og efter' },
  { word: 'Skikkelig', pos: 'adjective', definition: 'Fredelig og ordentlig' },
  { word: 'Skimte', pos: 'verb', definition: 'Se svagt og utydeligt' },
  { word: 'Skrøne', pos: 'noun', definition: 'Fantasifuld og harmløs løgnehistorie' },
  { word: 'Skumringstime', pos: 'noun', definition: 'Timen hvor dagen glider over i mørke' },
  { word: 'Skvulpe', pos: 'verb', definition: 'Slå i små bløde bølger' },
  { word: 'Skæbnetime', pos: 'noun', definition: 'Afgørende stund hvor alt står på spil' },
  { word: 'Skælmsk', pos: 'adjective', definition: 'Drilagtig med et glimt i øjet' },
  { word: 'Skæmte', pos: 'verb', definition: 'Spøge godmodigt, i ældre sprog' },
  { word: 'Skærmydsel', pos: 'noun', definition: 'Lille sammenstød uden alvorlige følger' },
  { word: 'Skønsom', pos: 'adjective', definition: 'Med god og afbalanceret dømmekraft' },
  { word: 'Slagfærdig', pos: 'adjective', definition: 'Hurtig til et rammende svar' },
  { word: 'Slentre', pos: 'verb', definition: 'Gå afslappet uden hastværk' },
  { word: 'Slumre', pos: 'verb', definition: 'Sove let; ligge gemt og uudnyttet' },
  { word: 'Smidig', pos: 'adjective', definition: 'Bøjelig og tilpasningsdygtig' },
  { word: 'Smilehul', pos: 'noun', definition: 'Lille fordybning i kinden når man smiler' },
  { word: 'Smægte', pos: 'verb', definition: 'Længes sygnende og lidenskabeligt' },
  { word: 'Snarere', pos: 'adverb', definition: 'Mere rigtigt, nærmere tværtimod' },
  { word: 'Snarrådig', pos: 'adjective', definition: 'Hurtig til at handle klogt i knibe' },
  { word: 'Snilde', pos: 'noun', definition: 'Praktisk opfindsomhed' },
  { word: 'Snurrig', pos: 'adjective', definition: 'Pudsig og lidt sær på en charmerende måde' },
  { word: 'Snusfornuft', pos: 'noun', definition: 'Jordnær og praktisk fornuft' },
  { word: 'Sober', pos: 'adjective', definition: 'Nøgtern, redelig og afdæmpet' },
  { word: 'Solbeskinnet', pos: 'adjective', definition: 'Badet i solens lys' },
  { word: 'Solstrejf', pos: 'noun', definition: 'Kort glimt af sol gennem skyerne' },
  { word: 'Sorgløs', pos: 'adjective', definition: 'Uden bekymringer i sindet' },
  { word: 'Spagfærdig', pos: 'adjective', definition: 'Stilfærdig og forsigtig i sin optræden' },
  { word: 'Spankulere', pos: 'verb', definition: 'Spadsere selvbevidst omkring' },
  { word: 'Spidsfindig', pos: 'adjective', definition: 'Udspekuleret fin i sine skelnen' },
  { word: 'Spilopmager', pos: 'noun', definition: 'En der elsker gale streger' },
  { word: 'Spirekraft', pos: 'noun', definition: 'Kraften til at vokse frem af næsten intet' },
  { word: 'Sprogblomst', pos: 'noun', definition: 'Ufrivilligt morsom sproglig fejl' },
  { word: 'Sprudlende', pos: 'adjective', definition: 'Boblende livlig og energisk' },
  { word: 'Sprælsk', pos: 'adjective', definition: 'Livlig og fuld af krudt' },
  { word: 'Spæd', pos: 'adjective', definition: 'Helt ny, fin og sart' },
  { word: 'Spørgelysten', pos: 'adjective', definition: 'Ivrig efter at stille spørgsmål' },
  { word: 'Standhaftig', pos: 'adjective', definition: 'Urokkelig når det gælder' },
  { word: 'Stedse', pos: 'adverb', definition: 'Altid og bestandigt, i ældre sprog' },
  { word: 'Stemningsfuld', pos: 'adjective', definition: 'Fyldt med atmosfære og stemning' },
  { word: 'Stilfærdig', pos: 'adjective', definition: 'Rolig og uden at gøre væsen af sig' },
  { word: 'Stilhed', pos: 'noun', definition: 'Fuldkommen fred for lyd og uro' },
  { word: 'Stilsikker', pos: 'adjective', definition: 'Med sikker fornemmelse for stil' },
  { word: 'Stiltiende', pos: 'adverb', definition: 'Uden at det siges højt' },
  { word: 'Stjerneklar', pos: 'adjective', definition: 'Med himlen fuld af synlige stjerner' },
  { word: 'Stjernestund', pos: 'noun', definition: 'Sjælden stund af ophøjet lykke' },
  { word: 'Storladen', pos: 'adjective', definition: 'Storslået og monumental' },
  { word: 'Storsind', pos: 'noun', definition: 'Ædelmodighed der ser stort på småting' },
  { word: 'Storslået', pos: 'adjective', definition: 'Imponerende i sin vælde' },
  { word: 'Stovt', pos: 'adjective', definition: 'Rolig, solid og pålidelig, i jysk sprog' },
  { word: 'Strabadser', pos: 'noun', definition: 'Hårde fysiske anstrengelser' },
  { word: 'Stræbsom', pos: 'adjective', definition: 'Flittig og målrettet i sit arbejde' },
  { word: 'Stund', pos: 'noun', definition: 'Kort og betydningsfuld tid' },
  { word: 'Særdeles', pos: 'adverb', definition: 'I høj grad' },
  { word: 'Sødme', pos: 'noun', definition: 'Blid og fyldig sød kvalitet' },
  { word: 'Sømmelig', pos: 'adjective', definition: 'Passende efter god skik' },
  { word: 'Søndagsbarn', pos: 'noun', definition: 'En som lykken altid følger' },
  { word: 'Sågar', pos: 'adverb', definition: 'Endda, oven i købet' },
  { word: 'Såmænd', pos: 'adverb', definition: 'Udtryk for afdæmpet og rolig forsikring' },
  { word: 'Taknemmelighed', pos: 'noun', definition: 'Varm følelse af tak' },
  { word: 'Taktfuld', pos: 'adjective', definition: 'Med fin fornemmelse for andres følelser' },
  { word: 'Tankefuld', pos: 'adjective', definition: 'Hensunken i stille tanker' },
  { word: 'Tanketorsk', pos: 'noun', definition: 'Ufrivillig tankefejl der giver et godt grin' },
  { word: 'Tankevækkende', pos: 'adjective', definition: 'Som sætter tanker i gang' },
  { word: 'Tapperhed', pos: 'noun', definition: 'Mod der holder stand i fare' },
  { word: 'Tidevand', pos: 'noun', definition: 'Havets regelmæssige stigen og falden' },
  { word: 'Tidløs', pos: 'adjective', definition: 'Uafhængig af tidens skiften og moder' },
  { word: 'Tidsfordriv', pos: 'noun', definition: 'Beskæftigelse for fornøjelsens skyld' },
  { word: 'Tidsånd', pos: 'noun', definition: 'Den herskende stemning i en tidsalder' },
  { word: 'Tilbageblik', pos: 'noun', definition: 'Eftertænksomt blik på det der var' },
  { word: 'Tilbøjelighed', pos: 'noun', definition: 'Naturlig hang til noget' },
  { word: 'Tilforladelig', pos: 'adjective', definition: 'Troværdig og til at stole på' },
  { word: 'Tilgivelse', pos: 'noun', definition: 'Det at slippe vreden og skænke fred' },
  { word: 'Tilkæmpe', pos: 'verb', definition: 'Vinde gennem sej og udholdende kamp' },
  { word: 'Tillidsfuld', pos: 'adjective', definition: 'Fuld af tro på andres gode vilje' },
  { word: 'Tilmed', pos: 'adverb', definition: 'Oven i købet' },
  { word: 'Tilsagn', pos: 'noun', definition: 'Bindende løfte om støtte' },
  { word: 'Tilskyndelse', pos: 'noun', definition: 'Indre eller ydre puf til handling' },
  { word: 'Tiltro', pos: 'noun', definition: 'Tillid til at nogen kan og vil' },
  { word: 'Tindre', pos: 'verb', definition: 'Stråle med levende, glimtende lys' },
  { word: 'Tjenstvillig', pos: 'adjective', definition: 'Altid parat til at hjælpe' },
  { word: 'Tommelfingerregel', pos: 'noun', definition: 'Enkel regel der som oftest holder' },
  { word: 'Toneangivende', pos: 'adjective', definition: 'Som sætter retningen for andre' },
  { word: 'Tonefald', pos: 'noun', definition: 'Den melodi stemmen taler med' },
  { word: 'Traktement', pos: 'noun', definition: 'Gæstfri beværtning med mad og drikke' },
  { word: 'Trivsel', pos: 'noun', definition: 'Det at have det godt og vokse' },
  { word: 'Trofasthed', pos: 'noun', definition: 'Ubrydelig loyalitet gennem tiden' },
  { word: 'Trolddom', pos: 'noun', definition: 'Magi og fortryllelse i folketroen' },
  { word: 'Troskyldig', pos: 'adjective', definition: 'Naivt tillidsfuld og uden bagtanker' },
  { word: 'Trumf', pos: 'noun', definition: 'Det stærkeste kort man har i baghånden' },
  { word: 'Tryghed', pos: 'noun', definition: 'Følelsen af at være i sikre hænder' },
  { word: 'Trædesten', pos: 'noun', definition: 'Skridt på vejen mod noget større' },
  { word: 'Trækfugl', pos: 'noun', definition: 'Fugl der rejser med årstiderne' },
  { word: 'Trøst', pos: 'noun', definition: 'Lindring af sorg og savn' },
  { word: 'Turde', pos: 'verb', definition: 'Have mod til' },
  { word: 'Tusindkunstner', pos: 'noun', definition: 'En der mestrer lidt af hvert' },
  { word: 'Tusmørke', pos: 'noun', definition: 'Halvmørket mellem dag og nat' },
  { word: 'Tvivlrådig', pos: 'adjective', definition: 'I splid med sig selv om valget' },
  { word: 'Tyngdepunkt', pos: 'noun', definition: 'Det sted hvor vægten samler sig' },
  { word: 'Tæft', pos: 'noun', definition: 'Fin næse for hvad der rører sig' },
  { word: 'Tænksom', pos: 'adjective', definition: 'Fordybet i stille eftertanke' },
  { word: 'Tøbrud', pos: 'noun', definition: 'Tidspunkt hvor is og kulde slipper sit tag' },
  { word: 'Tøjle', pos: 'verb', definition: 'Styre og holde i tømme' },
  { word: 'Tågeslør', pos: 'noun', definition: 'Tyndt lag tåge der blødgør konturerne' },
  { word: 'Tålmod', pos: 'noun', definition: 'Roen til at vente uden at klage' },
  { word: 'Uafladeligt', pos: 'adverb', definition: 'Uden ophør, igen og igen' },
  { word: 'Uanfægtet', pos: 'adjective', definition: 'Rolig og upåvirket af kritik og uro' },
  { word: 'Ubekymret', pos: 'adjective', definition: 'Fri for bekymring' },
  { word: 'Ubestikkelig', pos: 'adjective', definition: 'Umulig at købe eller påvirke' },
  { word: 'Udforske', pos: 'verb', definition: 'Undersøge nyt land og nye tanker' },
  { word: 'Udholdenhed', pos: 'noun', definition: 'Evnen til at blive ved når det gør ondt' },
  { word: 'Udlængsel', pos: 'noun', definition: 'Længsel efter at drage ud i verden' },
  { word: 'Udsyn', pos: 'noun', definition: 'Vidt blik ud over verden og tankerne' },
  { word: 'Udsøgt', pos: 'adjective', definition: 'Fint udvalgt af bedste kvalitet' },
  { word: 'Udtryksfuld', pos: 'adjective', definition: 'Rig på levende udtryk' },
  { word: 'Udve', pos: 'noun', definition: 'Længslen ud, modstykket til hjemve' },
  { word: 'Udvirke', pos: 'verb', definition: 'Få til at ske gennem sin indsats' },
  { word: 'Uegennyttig', pos: 'adjective', definition: 'Uden tanke for egen fordel' },
  { word: 'Uforbeholden', pos: 'adjective', definition: 'Hel og uden forbehold' },
  { word: 'Ufordærvet', pos: 'adjective', definition: 'Uspoleret og ren i sindet' },
  { word: 'Uforfærdet', pos: 'adjective', definition: 'Modig og uden frygt' },
  { word: 'Uforglemmelig', pos: 'adjective', definition: 'Umulig at glemme' },
  { word: 'Uforlignelig', pos: 'adjective', definition: 'Uden sidestykke' },
  { word: 'Ufortrøden', pos: 'adjective', definition: 'Ukuet og med uformindsket gejst' },
  { word: 'Ufortøvet', pos: 'adverb', definition: 'Straks og uden tøven' },
  { word: 'Uforvarende', pos: 'adverb', definition: 'Uden at ville det, ved et tilfælde' },
  { word: 'Uimodståelig', pos: 'adjective', definition: 'Umulig at stå for' },
  { word: 'Ukrænkelig', pos: 'adjective', definition: 'Hellig og urørlig' },
  { word: 'Ukuelig', pos: 'adjective', definition: 'Umulig at kue eller slå ned' },
  { word: 'Uladsiggørlig', pos: 'adjective', definition: 'Umulig at gennemføre' },
  { word: 'Ulastelig', pos: 'adjective', definition: 'Uden mindste fejl, om påklædning og vandel' },
  { word: 'Umage', pos: 'noun', definition: 'Den anstrengelse man gør sig med noget' },
  { word: 'Umiddelbarhed', pos: 'noun', definition: 'Frisk og utvungen naturlighed' },
  { word: 'Umistelig', pos: 'adjective', definition: 'Så dyrebar at den ikke kan undværes' },
  { word: 'Underfundig', pos: 'adjective', definition: 'Lunt og skjult vittig' },
  { word: 'Undertiden', pos: 'adverb', definition: 'Nu og da, sommetider' },
  { word: 'Undren', pos: 'noun', definition: 'Åben og spørgende forundring' },
  { word: 'Undse', pos: 'verb', definition: 'Genere sig af blufærdighed' },
  { word: 'Undseelse', pos: 'noun', definition: 'Blufærdig generthed' },
  { word: 'Undvære', pos: 'verb', definition: 'Klare sig uden' },
  { word: 'Uomtvistelig', pos: 'adjective', definition: 'Umulig at bestride' },
  { word: 'Uophørligt', pos: 'adverb', definition: 'Uden pause, hele tiden' },
  { word: 'Uransagelig', pos: 'adjective', definition: 'Umulig at udgrunde, om veje og årsager' },
  { word: 'Urkraft', pos: 'noun', definition: 'Oprindelig og utæmmet naturkraft' },
  { word: 'Urokkelig', pos: 'adjective', definition: 'Umulig at rokke i sin overbevisning' },
  { word: 'Urskov', pos: 'noun', definition: 'Uberørt og tæt oprindelig skov' },
  { word: 'Uselviskhed', pos: 'noun', definition: 'Det at sætte andre først' },
  { word: 'Uskyld', pos: 'noun', definition: 'Ren og skyldfri tilstand' },
  { word: 'Usnobbet', pos: 'adjective', definition: 'Fri for fine fornemmelser' },
  { word: 'Utrættelig', pos: 'adjective', definition: 'Som aldrig bliver træt af at kæmpe' },
  { word: 'Utvungen', pos: 'adjective', definition: 'Naturlig og fri i sin optræden' },
  { word: 'Uudgrundelig', pos: 'adjective', definition: 'Så dyb at den ikke kan loddes' },
  { word: 'Uudtømmelig', pos: 'adjective', definition: 'Som aldrig løber tør' },
  { word: 'Uvejr', pos: 'noun', definition: 'Voldsomt vejr med storm og regn' },
  { word: 'Uvilkårligt', pos: 'adverb', definition: 'Uden at man selv vil det, helt af sig selv' },
  { word: 'Uvurderlig', pos: 'adjective', definition: 'Så værdifuld at den ikke kan gøres op' },
  { word: 'Vandre', pos: 'verb', definition: 'Gå langt og længe, gerne i naturen' },
  { word: 'Varsom', pos: 'adjective', definition: 'Forsigtig og hensynsfuld' },
  { word: 'Varsomhed', pos: 'noun', definition: 'Nænsom forsigtighed' },
  { word: 'Vederhæftig', pos: 'adjective', definition: 'Pålidelig og sandfærdig' },
  { word: 'Vederkvæge', pos: 'verb', definition: 'Forfriske og give nye kræfter' },
  { word: 'Vedholdende', pos: 'adjective', definition: 'Udholdende uden at give op' },
  { word: 'Vedholdenhed', pos: 'noun', definition: 'Sejhed til at fortsætte trods modstand' },
  { word: 'Vejlede', pos: 'verb', definition: 'Lede på rette vej med råd og støtte' },
  { word: 'Vejrbidt', pos: 'adjective', definition: 'Mærket af vind og vejr' },
  { word: 'Velbefindende', pos: 'noun', definition: 'Tilstand af behag og sundhed' },
  { word: 'Velbevandret', pos: 'adjective', definition: 'Med solidt kendskab på et område' },
  { word: 'Velgerning', pos: 'noun', definition: 'God og gavmild handling' },
  { word: 'Velgørende', pos: 'adjective', definition: 'Behagelig og gavnlig; som gør godt' },
  { word: 'Velklang', pos: 'noun', definition: 'Skøn og harmonisk lyd' },
  { word: 'Velklingende', pos: 'adjective', definition: 'Behagelig for øret' },
  { word: 'Vellyd', pos: 'noun', definition: 'Lyd der er smuk at høre på' },
  { word: 'Veloplagt', pos: 'adjective', definition: 'Frisk og i strålende humør' },
  { word: 'Velovervejet', pos: 'adjective', definition: 'Grundigt gennemtænkt' },
  { word: 'Velsignet', pos: 'adjective', definition: 'Begunstiget af lykke og gode gaver' },
  { word: 'Veltalende', pos: 'adjective', definition: 'Sikker og overbevisende i sin tale' },
  { word: 'Velvilje', pos: 'noun', definition: 'Venlig indstilling og støtte' },
  { word: 'Vemod', pos: 'noun', definition: 'Stille, sorgblandet længsel' },
  { word: 'Vennesæl', pos: 'adjective', definition: 'Afholdt og omgivet af venner, i ældre sprog' },
  { word: 'Vennetjeneste', pos: 'noun', definition: 'Hjælpsom tjeneste gjort af venskab' },
  { word: 'Vid', pos: 'noun', definition: 'Skarp og legende intelligens' },
  { word: 'Videbegær', pos: 'noun', definition: 'Umættelig lyst til at lære' },
  { word: 'Vidsyn', pos: 'noun', definition: 'Vidt og tolerant udsyn' },
  { word: 'Vidtløftig', pos: 'adjective', definition: 'Omstændelig og udsvævende' },
  { word: 'Vidunder', pos: 'noun', definition: 'Noget så vidunderligt at man forundres' },
  { word: 'Vidunderlig', pos: 'adjective', definition: 'Helt igennem skøn og herlig' },
  { word: 'Viljestyrke', pos: 'noun', definition: 'Viljens kraft til at holde kursen' },
  { word: 'Vindpust', pos: 'noun', definition: 'Let og pludseligt pust af vind' },
  { word: 'Vindskibelig', pos: 'adjective', definition: 'Driftig og foretagsom, i ældre sprog' },
  { word: 'Vindstille', pos: 'noun', definition: 'Fuldkommen ro i luften' },
  { word: 'Virkelyst', pos: 'noun', definition: 'Lyst til at udrette noget' },
  { word: 'Vis', pos: 'adjective', definition: 'Dybt klog af erfaring' },
  { word: 'Visdom', pos: 'noun', definition: 'Dyb indsigt i livets sammenhænge' },
  { word: 'Vished', pos: 'noun', definition: 'Sikker viden uden tvivl' },
  { word: 'Visselig', pos: 'adverb', definition: 'Sandelig, i højtideligt sprog' },
  { word: 'Vital', pos: 'adjective', definition: 'Fuld af livskraft' },
  { word: 'Vitterligt', pos: 'adverb', definition: 'Beviseligt og sandt' },
  { word: 'Vove', pos: 'verb', definition: 'Turde sætte noget på spil' },
  { word: 'Vovemod', pos: 'noun', definition: 'Mod til at løbe en risiko' },
  { word: 'Vugge', pos: 'verb', definition: 'Gynge blidt fra side til side' },
  { word: 'Værdighed', pos: 'noun', definition: 'Rolig selvrespekt der aftvinger agtelse' },
  { word: 'Værdsætte', pos: 'verb', definition: 'Sætte ægte pris på' },
  { word: 'Værn', pos: 'noun', definition: 'Beskyttelse mod overlast' },
  { word: 'Værne', pos: 'verb', definition: 'Beskytte og passe godt på' },
  { word: 'Væver', pos: 'adjective', definition: 'Kvik, let og livlig' },
  { word: 'Våge', pos: 'verb', definition: 'Holde sig vågen for at passe på nogen' },
  { word: 'Vår', pos: 'noun', definition: 'Foråret, i poetisk sprog' },
  { word: 'Yde', pos: 'verb', definition: 'Give af sin kraft og kunnen' },
  { word: 'Ydmyg', pos: 'adjective', definition: 'Beskeden og uden selvhævdelse' },
  { word: 'Ydmyghed', pos: 'noun', definition: 'Beskedenhed over for det der er større end én selv' },
  { word: 'Yndefuld', pos: 'adjective', definition: 'Med let og fin gratie' },
  { word: 'Yndest', pos: 'noun', definition: 'Gunst og velvilje man nyder hos nogen' },
  { word: 'Yndig', pos: 'adjective', definition: 'Sødt og fint indtagende' },
  { word: 'Yppig', pos: 'adjective', definition: 'Frodig i former og vækst' },
  { word: 'Ytre', pos: 'verb', definition: 'Give udtryk for' },
  { word: 'Ædel', pos: 'adjective', definition: 'Af fornem og ren karakter' },
  { word: 'Ædelmodig', pos: 'adjective', definition: 'Storsindet og gavmild af hjertet' },
  { word: 'Ærbødig', pos: 'adjective', definition: 'Fuld af dyb respekt' },
  { word: 'Ærefuld', pos: 'adjective', definition: 'Som bringer hæder' },
  { word: 'Ærekær', pos: 'adjective', definition: 'Omhyggelig med sit gode navn og rygte' },
  { word: 'Æresord', pos: 'noun', definition: 'Løfte givet på sin ære' },
  { word: 'Æressag', pos: 'noun', definition: 'Sag man sætter sin ære i at klare' },
  { word: 'Ærinde', pos: 'noun', definition: 'Bestemt formål med at gå ud eller henvende sig' },
  { word: 'Ærlighed', pos: 'noun', definition: 'Sanddru og redelig adfærd' },
  { word: 'Ærværdig', pos: 'adjective', definition: 'Som indgyder respekt i kraft af alder og værdighed' },
  { word: 'Æselsøre', pos: 'noun', definition: 'Ombukket hjørne i en bogside' },
  { word: 'Ødsle', pos: 'verb', definition: 'Strø om sig med uden at spare' },
  { word: 'Øjensynligt', pos: 'adverb', definition: 'Efter alt at dømme, tilsyneladende' },
  { word: 'Øjenåbner', pos: 'noun', definition: 'Oplevelse der pludselig får en til at se klart' },
  { word: 'Ømhed', pos: 'noun', definition: 'Blid og kærlig omsorg' },
  { word: 'Ømhjertet', pos: 'adjective', definition: 'Let at røre og fuld af medfølelse' },
  { word: 'Ørkesløs', pos: 'adjective', definition: 'Uden mål, nytte og indhold' },
  { word: 'Øve', pos: 'verb', definition: 'Træne flittigt; udrette, som i at øve indflydelse' },
  { word: 'Åbenbaring', pos: 'noun', definition: 'Pludselig og overvældende indsigt' },
  { word: 'Åbenhjertig', pos: 'adjective', definition: 'Ærlig og åben om sine følelser' },
  { word: 'Ånd', pos: 'noun', definition: 'Det tænkende og skabende i mennesket' },
  { word: 'Åndfuld', pos: 'adjective', definition: 'Rig på vid og tankefuld elegance' },
  { word: 'Åndsnærværelse', pos: 'noun', definition: 'Snarrådig ro i det kritiske øjeblik' },
  { word: 'Årle', pos: 'adverb', definition: 'Tidligt om morgenen, i gammelt sprog' },
  { word: 'Årvågen', pos: 'adjective', definition: 'Vagtsomt opmærksom' },
];
