import type { WordEntry } from './types';

export const DE_DE_WORDS: WordEntry[] = [
  { word: 'Abendrot', pos: 'noun', definition: 'Rötlicher Schein des Himmels nach Sonnenuntergang' },
  { word: 'Abgebrüht', pos: 'adjective', definition: 'Durch Erfahrung unempfindlich und hartgesotten geworden' },
  { word: 'Abgeklärt', pos: 'adjective', definition: 'Durch Lebenserfahrung ruhig und gelassen geworden' },
  { word: 'Abgeschieden', pos: 'adjective', definition: 'Einsam und fern vom Trubel der Welt gelegen' },
  { word: 'Abgründig', pos: 'adjective', definition: 'Von unergründlicher, oft unheimlicher Tiefe' },
  { word: 'Abhandenkommen', pos: 'verb', definition: 'Verloren gehen, ohne dass man es merkt' },
  { word: 'Abkanzeln', pos: 'verb', definition: 'Jemanden scharf und herablassend zurechtweisen' },
  { word: 'Abstrus', pos: 'adjective', definition: 'Verworren und schwer verständlich' },
  { word: 'Absurd', pos: 'adjective', definition: 'Dem gesunden Menschenverstand völlig widersprechend' },
  { word: 'Abwägen', pos: 'verb', definition: 'Gründe und Gegengründe sorgfältig gegeneinander prüfen' },
  { word: 'Abwegig', pos: 'adjective', definition: 'Vom Naheliegenden weit entfernt, verfehlt' },
  { word: 'Achtsamkeit', pos: 'noun', definition: 'Bewusste, wertfreie Aufmerksamkeit für den Augenblick' },
  { word: 'Adäquat', pos: 'adjective', definition: 'Einer Sache angemessen und entsprechend' },
  { word: 'Adrett', pos: 'adjective', definition: 'Ordentlich, sauber und gefällig im Äußeren' },
  { word: 'Affront', pos: 'noun', definition: 'Offene Beleidigung oder bewusste Kränkung' },
  { word: 'Agil', pos: 'adjective', definition: 'Körperlich und geistig beweglich und rege' },
  { word: 'Ahnden', pos: 'verb', definition: 'Ein Vergehen oder Unrecht bestrafen' },
  { word: 'Akkurat', pos: 'adjective', definition: 'Sorgfältig, ordentlich und ganz genau' },
  { word: 'Akribisch', pos: 'adjective', definition: 'Mit äußerster Sorgfalt und Genauigkeit' },
  { word: 'Akzentuieren', pos: 'verb', definition: 'Etwas besonders betonen und hervorheben' },
  { word: 'Allegorie', pos: 'noun', definition: 'Bildhafte Darstellung eines abstrakten Begriffs' },
  { word: 'Allenthalben', pos: 'adverb', definition: 'Überall, an allen Orten zugleich' },
  { word: 'Altruismus', pos: 'noun', definition: 'Selbstlose Sorge um das Wohl anderer' },
  { word: 'Altweibersommer', pos: 'noun', definition: 'Milde Spätsommertage mit silbrig fliegenden Spinnfäden' },
  { word: 'Ambivalent', pos: 'adjective', definition: 'Von widersprüchlichen Gefühlen oder Wertungen zugleich geprägt' },
  { word: 'Anachronismus', pos: 'noun', definition: 'Etwas, das nicht mehr in seine Zeit passt' },
  { word: 'Analogie', pos: 'noun', definition: 'Entsprechung oder Ähnlichkeit zwischen verschiedenen Dingen' },
  { word: 'Anheimelnd', pos: 'adjective', definition: 'Vertraut, warm und behaglich wirkend' },
  { word: 'Anmut', pos: 'noun', definition: 'Natürliche Schönheit in Haltung und Bewegung' },
  { word: 'Anmutig', pos: 'adjective', definition: 'Von natürlicher Grazie und Lieblichkeit' },
  { word: 'Ansporn', pos: 'noun', definition: 'Innerer Antrieb, der zu Leistung beflügelt' },
  { word: 'Anstellig', pos: 'adjective', definition: 'Geschickt und gewandt bei praktischen Aufgaben' },
  { word: 'Antagonist', pos: 'noun', definition: 'Gegenspieler oder Vertreter des Gegensatzes' },
  { word: 'Antizipieren', pos: 'verb', definition: 'Etwas gedanklich vorwegnehmen' },
  { word: 'Apart', pos: 'adjective', definition: 'Von reizvoller, ungewöhnlicher Eleganz' },
  { word: 'Apathisch', pos: 'adjective', definition: 'Teilnahmslos und ohne innere Regung' },
  { word: 'Aplomb', pos: 'noun', definition: 'Selbstsicheres, nachdrückliches Auftreten' },
  { word: 'Apodiktisch', pos: 'adjective', definition: 'Keinen Widerspruch duldend, unumstößlich' },
  { word: 'Äquivalent', pos: 'adjective', definition: 'Gleichwertig und von gleicher Geltung' },
  { word: 'Arglos', pos: 'adjective', definition: 'Ohne Misstrauen und nichts Böses ahnend' },
  { word: 'Arkadisch', pos: 'adjective', definition: 'Ländlich-idyllisch wie in einem Hirtenparadies' },
  { word: 'Artikulieren', pos: 'verb', definition: 'Gedanken klar und deutlich in Worte fassen' },
  { word: 'Askese', pos: 'noun', definition: 'Enthaltsame, streng zurückgenommene Lebensführung' },
  { word: 'Ästhet', pos: 'noun', definition: 'Mensch mit ausgeprägtem Sinn für das Schöne' },
  { word: 'Ästhetisch', pos: 'adjective', definition: 'Dem Schönen und Geschmackvollen entsprechend' },
  { word: 'Ätherisch', pos: 'adjective', definition: 'Zart, vergeistigt und himmlisch leicht' },
  { word: 'Attitüde', pos: 'noun', definition: 'Innere Haltung oder einstudierte Pose' },
  { word: 'Audienz', pos: 'noun', definition: 'Feierlicher Empfang bei einer hochgestellten Persönlichkeit' },
  { word: 'Aufbegehren', pos: 'verb', definition: 'Sich empört gegen etwas auflehnen' },
  { word: 'Aufgeräumt', pos: 'adjective', definition: 'In heiterer, gelöster Stimmung' },
  { word: 'Aufmüpfig', pos: 'adjective', definition: 'Widerspenstig gegen Autorität aufbegehrend' },
  { word: 'Augenweide', pos: 'noun', definition: 'Anblick, der das Auge erfreut' },
  { word: 'Aura', pos: 'noun', definition: 'Besondere Ausstrahlung einer Person oder Sache' },
  { word: 'Ausgelassen', pos: 'adjective', definition: 'Übermütig fröhlich und unbeschwert' },
  { word: 'Ausgewogen', pos: 'adjective', definition: 'In einem harmonischen Gleichgewicht befindlich' },
  { word: 'Ausklügeln', pos: 'verb', definition: 'Etwas mit viel Scharfsinn ersinnen' },
  { word: 'Autark', pos: 'adjective', definition: 'Unabhängig und sich selbst genügend' },
  { word: 'Authentisch', pos: 'adjective', definition: 'Echt, glaubwürdig und unverfälscht' },
  { word: 'Avancieren', pos: 'verb', definition: 'Aufsteigen und zu etwas Höherem werden' },
  { word: 'Aversion', pos: 'noun', definition: 'Heftige innere Abneigung gegen etwas' },
  { word: 'Bagatelle', pos: 'noun', definition: 'Unbedeutende Kleinigkeit ohne großes Gewicht' },
  { word: 'Bagatellisieren', pos: 'verb', definition: 'Etwas als unwichtig herunterspielen' },
  { word: 'Balsam', pos: 'noun', definition: 'Wohltat, die Schmerz und Kummer lindert' },
  { word: 'Banause', pos: 'noun', definition: 'Mensch ohne Sinn für Kunst und Feinheit' },
  { word: 'Barmherzig', pos: 'adjective', definition: 'Voller Mitgefühl und tätiger Güte' },
  { word: 'Bauchgefühl', pos: 'noun', definition: 'Intuitive Ahnung jenseits aller Vernunftgründe' },
  { word: 'Bauernschläue', pos: 'noun', definition: 'Listige, praktische Gerissenheit' },
  { word: 'Beflügeln', pos: 'verb', definition: 'Jemanden beschwingen und zu Höherem anspornen' },
  { word: 'Befremdlich', pos: 'adjective', definition: 'Seltsam und auf irritierende Weise fremd' },
  { word: 'Behäbig', pos: 'adjective', definition: 'Breit, gemächlich und von träger Gemütlichkeit' },
  { word: 'Behaglich', pos: 'adjective', definition: 'Wohlig, gemütlich und voller Wärme' },
  { word: 'Behände', pos: 'adjective', definition: 'Flink, geschickt und leichtfüßig' },
  { word: 'Behelligen', pos: 'verb', definition: 'Jemanden ungebeten stören oder belästigen' },
  { word: 'Beherzigen', pos: 'verb', definition: 'Einen Rat aufnehmen und danach handeln' },
  { word: 'Beherzt', pos: 'adjective', definition: 'Mutig, entschlossen und ohne Zögern' },
  { word: 'Beklommen', pos: 'adjective', definition: 'Von banger Enge in der Brust erfüllt' },
  { word: 'Bekömmlich', pos: 'adjective', definition: 'Der Gesundheit zuträglich und gut verträglich' },
  { word: 'Bekunden', pos: 'verb', definition: 'Öffentlich und deutlich zum Ausdruck bringen' },
  { word: 'Belesen', pos: 'adjective', definition: 'Durch viel Lektüre umfassend gebildet' },
  { word: 'Beredt', pos: 'adjective', definition: 'Wortgewandt und ausdrucksstark' },
  { word: 'Beschaulich', pos: 'adjective', definition: 'Ruhig, besinnlich und ohne Hast' },
  { word: 'Beschwichtigen', pos: 'verb', definition: 'Jemanden beruhigen und besänftigen' },
  { word: 'Beseelt', pos: 'adjective', definition: 'Von innerem Leben und Empfindung erfüllt' },
  { word: 'Besonnen', pos: 'adjective', definition: 'Ruhig überlegend und umsichtig' },
  { word: 'Bestechend', pos: 'adjective', definition: 'Durch Qualität unmittelbar überzeugend' },
  { word: 'Bestrickend', pos: 'adjective', definition: 'Unwiderstehlich einnehmend und fesselnd' },
  { word: 'Betören', pos: 'verb', definition: 'Jemanden bezaubern und den Kopf verdrehen' },
  { word: 'Bewandert', pos: 'adjective', definition: 'Auf einem Gebiet kundig und erfahren' },
  { word: 'Bewerkstelligen', pos: 'verb', definition: 'Etwas Schwieriges geschickt zustande bringen' },
  { word: 'Bezaubernd', pos: 'adjective', definition: 'Auf märchenhafte Weise entzückend' },
  { word: 'Bezirzen', pos: 'verb', definition: 'Mit Charme umgarnen und verführen' },
  { word: 'Bigott', pos: 'adjective', definition: 'Scheinheilig und übertrieben frömmelnd' },
  { word: 'Bildschön', pos: 'adjective', definition: 'So schön, als wäre es gemalt' },
  { word: 'Bisweilen', pos: 'adverb', definition: 'Manchmal, hin und wieder' },
  { word: 'Bittersüß', pos: 'adjective', definition: 'Zugleich schmerzlich und beglückend' },
  { word: 'Blauäugig', pos: 'adjective', definition: 'Naiv und arglos vertrauensselig' },
  { word: 'Blümerant', pos: 'adjective', definition: 'Flau, schwindelig und unwohl zumute' },
  { word: 'Bodenständig', pos: 'adjective', definition: 'Fest verwurzelt und unprätentiös' },
  { word: 'Bonmot', pos: 'noun', definition: 'Geistreicher, treffender Ausspruch' },
  { word: 'Brachial', pos: 'adjective', definition: 'Mit roher Gewalt vorgehend' },
  { word: 'Brachliegen', pos: 'verb', definition: 'Ungenutzt bleiben trotz vorhandenen Potenzials' },
  { word: 'Bravour', pos: 'noun', definition: 'Meisterhafte Kühnheit in der Ausführung' },
  { word: 'Bredouille', pos: 'noun', definition: 'Missliche, verzwickte Lage' },
  { word: 'Brüskieren', pos: 'verb', definition: 'Jemanden schroff vor den Kopf stoßen' },
  { word: 'Bühnenreif', pos: 'adjective', definition: 'So gekonnt, dass es auf eine Bühne gehörte' },
  { word: 'Bukolisch', pos: 'adjective', definition: 'Das idyllische Hirten- und Landleben besingend' },
  { word: 'Changieren', pos: 'verb', definition: 'Zwischen Farben oder Bedeutungen schillernd wechseln' },
  { word: 'Charisma', pos: 'noun', definition: 'Besondere Ausstrahlungskraft, die Menschen gewinnt' },
  { word: 'Chimäre', pos: 'noun', definition: 'Trügerisches Hirngespinst ohne Wirklichkeit' },
  { word: 'Chuzpe', pos: 'noun', definition: 'Verblüffende, charmante Dreistigkeit' },
  { word: 'Clou', pos: 'noun', definition: 'Überraschender Höhe- und Kernpunkt einer Sache' },
  { word: 'Courage', pos: 'noun', definition: 'Beherzter Mut in schwieriger Lage' },
  { word: 'Couragiert', pos: 'adjective', definition: 'Mutig, beherzt und entschlossen' },
  { word: 'Credo', pos: 'noun', definition: 'Persönliches Bekenntnis und Leitsatz' },
  { word: 'Dahinschmelzen', pos: 'verb', definition: 'Vor Rührung oder Entzücken vergehen' },
  { word: 'Dämmerstunde', pos: 'noun', definition: 'Stille Stunde zwischen Tag und Nacht' },
  { word: 'Darben', pos: 'verb', definition: 'Not leiden und Mangel ertragen' },
  { word: 'Debakel', pos: 'noun', definition: 'Völliger, blamabler Zusammenbruch' },
  { word: 'Delikat', pos: 'adjective', definition: 'Fein und köstlich oder heikel zu behandeln' },
  { word: 'Demut', pos: 'noun', definition: 'Bescheidene Haltung ohne Selbstüberhebung' },
  { word: 'Demütig', pos: 'adjective', definition: 'Von bescheidener, ehrfürchtiger Gesinnung' },
  { word: 'Deplatziert', pos: 'adjective', definition: 'Am falschen Ort und unpassend' },
  { word: 'Dereinst', pos: 'adverb', definition: 'Irgendwann in ferner Zukunft' },
  { word: 'Desavouieren', pos: 'verb', definition: 'Jemanden bloßstellen und öffentlich brüskieren' },
  { word: 'Desiderat', pos: 'noun', definition: 'Etwas Fehlendes, dessen Ergänzung erwünscht ist' },
  { word: 'Despektierlich', pos: 'adjective', definition: 'Abschätzig und respektlos' },
  { word: 'Devot', pos: 'adjective', definition: 'Unterwürfig bis zur Selbstaufgabe' },
  { word: 'Dezent', pos: 'adjective', definition: 'Zurückhaltend, unaufdringlich und taktvoll' },
  { word: 'Dezidiert', pos: 'adjective', definition: 'Entschieden und mit Nachdruck vertreten' },
  { word: 'Diametral', pos: 'adjective', definition: 'Völlig entgegengesetzt' },
  { word: 'Dichotomie', pos: 'noun', definition: 'Strikte Zweiteilung ohne Zwischenstufen' },
  { word: 'Differenziert', pos: 'adjective', definition: 'Fein abgestuft und genau unterscheidend' },
  { word: 'Diffizil', pos: 'adjective', definition: 'Schwierig und heikel in der Handhabung' },
  { word: 'Diffus', pos: 'adjective', definition: 'Unscharf, zerstreut und ohne klare Kontur' },
  { word: 'Dilettantisch', pos: 'adjective', definition: 'Laienhaft und unfachmännisch' },
  { word: 'Diskrepanz', pos: 'noun', definition: 'Widersprüchliches Missverhältnis zwischen zwei Dingen' },
  { word: 'Diskret', pos: 'adjective', definition: 'Taktvoll verschwiegen und unaufdringlich' },
  { word: 'Disparat', pos: 'adjective', definition: 'Ungleichartig und nicht zusammenpassend' },
  { word: 'Distinguiert', pos: 'adjective', definition: 'Vornehm und betont kultiviert im Auftreten' },
  { word: 'Divergent', pos: 'adjective', definition: 'Auseinanderstrebend und voneinander abweichend' },
  { word: 'Dogmatisch', pos: 'adjective', definition: 'Starr an Lehrsätzen festhaltend' },
  { word: 'Doppelbödig', pos: 'adjective', definition: 'Mit verborgener zweiter Bedeutungsebene' },
  { word: 'Dräuen', pos: 'verb', definition: 'Drohend und unheilvoll bevorstehen' },
  { word: 'Dünkel', pos: 'noun', definition: 'Eingebildete Überheblichkeit' },
  { word: 'Durchtrieben', pos: 'adjective', definition: 'Gerissen und voller Schliche' },
  { word: 'Durchweg', pos: 'adverb', definition: 'Ausnahmslos, ohne Ausnahme' },
  { word: 'Ebenbürtig', pos: 'adjective', definition: 'An Rang und Können gleichwertig' },
  { word: 'Ebenmäßig', pos: 'adjective', definition: 'Von gleichmäßiger, harmonischer Form' },
  { word: 'Echauffieren', pos: 'verb', definition: 'Sich über etwas erhitzen und aufregen' },
  { word: 'Ehedem', pos: 'adverb', definition: 'Früher, in vergangenen Zeiten' },
  { word: 'Ehrerbietig', pos: 'adjective', definition: 'Von tiefem Respekt erfüllt' },
  { word: 'Ehrfurcht', pos: 'noun', definition: 'Scheue Hochachtung vor etwas Erhabenem' },
  { word: 'Eigenbrötler', pos: 'noun', definition: 'Wunderlicher Einzelgänger mit eigenen Wegen' },
  { word: 'Eigensinnig', pos: 'adjective', definition: 'Hartnäckig auf dem eigenen Willen beharrend' },
  { word: 'Eigenwillig', pos: 'adjective', definition: 'Von unverwechselbar eigener Prägung' },
  { word: 'Eilfertig', pos: 'adjective', definition: 'Übereifrig und vorschnell dienstbereit' },
  { word: 'Einerlei', pos: 'noun', definition: 'Eintönige Gleichförmigkeit des Alltags' },
  { word: 'Eingängig', pos: 'adjective', definition: 'Leicht fassbar und im Gedächtnis haftend' },
  { word: 'Einhellig', pos: 'adjective', definition: 'Völlig einmütig und ohne Gegenstimme' },
  { word: 'Einsilbig', pos: 'adjective', definition: 'Wortkarg und wenig mitteilsam' },
  { word: 'Einstweilen', pos: 'adverb', definition: 'Vorläufig, bis auf Weiteres' },
  { word: 'Eintracht', pos: 'noun', definition: 'Harmonisches Einvernehmen und Frieden' },
  { word: 'Einvernehmlich', pos: 'adjective', definition: 'In beiderseitigem Einverständnis geschehend' },
  { word: 'Elaboriert', pos: 'adjective', definition: 'Sorgfältig und differenziert ausgearbeitet' },
  { word: 'Elegie', pos: 'noun', definition: 'Wehmütig-klagendes Gedicht' },
  { word: 'Elegisch', pos: 'adjective', definition: 'Von sanfter Wehmut und Klage erfüllt' },
  { word: 'Eloquent', pos: 'adjective', definition: 'Redegewandt und sprachlich brillant' },
  { word: 'Eloquenz', pos: 'noun', definition: 'Gabe der gewandten, wirkungsvollen Rede' },
  { word: 'Eminent', pos: 'adjective', definition: 'Herausragend und von großer Bedeutung' },
  { word: 'Empathie', pos: 'noun', definition: 'Fähigkeit, sich in andere einzufühlen' },
  { word: 'Emphatisch', pos: 'adjective', definition: 'Mit Nachdruck und starkem Gefühl' },
  { word: 'Enigmatisch', pos: 'adjective', definition: 'Rätselhaft und geheimnisvoll' },
  { word: 'Entbehren', pos: 'verb', definition: 'Etwas schmerzlich vermissen müssen' },
  { word: 'Entrückt', pos: 'adjective', definition: 'Wie in eine andere Welt versetzt' },
  { word: 'Entschleunigen', pos: 'verb', definition: 'Das Lebenstempo bewusst verlangsamen' },
  { word: 'Entzücken', pos: 'noun', definition: 'Helle Freude und Begeisterung' },
  { word: 'Ephemer', pos: 'adjective', definition: 'Flüchtig und nur von kurzer Dauer' },
  { word: 'Epigone', pos: 'noun', definition: 'Unschöpferischer Nachahmer großer Vorbilder' },
  { word: 'Erbaulich', pos: 'adjective', definition: 'Dem Gemüt wohltuend und innerlich aufrichtend' },
  { word: 'Ergründen', pos: 'verb', definition: 'Einer Sache bis auf den Grund gehen' },
  { word: 'Erhaben', pos: 'adjective', definition: 'Von feierlicher, überwältigender Größe' },
  { word: 'Erhaschen', pos: 'verb', definition: 'Etwas Flüchtiges im letzten Moment erwischen' },
  { word: 'Erlesen', pos: 'adjective', definition: 'Ausgesucht fein und von erster Güte' },
  { word: 'Ermessen', pos: 'noun', definition: 'Freies Urteil nach eigenem Gutdünken' },
  { word: 'Erörtern', pos: 'verb', definition: 'Eine Frage eingehend besprechen' },
  { word: 'Erquicken', pos: 'verb', definition: 'Erfrischen und neu beleben' },
  { word: 'Erratisch', pos: 'adjective', definition: 'Regellos und unberechenbar verstreut' },
  { word: 'Ersinnen', pos: 'verb', definition: 'Sich etwas Neues ausdenken' },
  { word: 'Erwartungsfroh', pos: 'adjective', definition: 'Voller freudiger Spannung auf Kommendes' },
  { word: 'Esprit', pos: 'noun', definition: 'Sprühender, geistreicher Witz' },
  { word: 'Etepetete', pos: 'adjective', definition: 'Übertrieben fein und zimperlich' },
  { word: 'Euphemismus', pos: 'noun', definition: 'Beschönigende Umschreibung eines unangenehmen Sachverhalts' },
  { word: 'Euphorie', pos: 'noun', definition: 'Überschwängliches Hochgefühl' },
  { word: 'Evident', pos: 'adjective', definition: 'Offenkundig und unmittelbar einleuchtend' },
  { word: 'Evozieren', pos: 'verb', definition: 'Vorstellungen und Gefühle hervorrufen' },
  { word: 'Exaltiert', pos: 'adjective', definition: 'Übertrieben erregt und überspannt' },
  { word: 'Exorbitant', pos: 'adjective', definition: 'Jedes gewöhnliche Maß sprengend' },
  { word: 'Explizit', pos: 'adjective', definition: 'Ausdrücklich und unmissverständlich' },
  { word: 'Exquisit', pos: 'adjective', definition: 'Ausgesucht erlesen und vorzüglich' },
  { word: 'Extravagant', pos: 'adjective', definition: 'Betont ausgefallen und ungewöhnlich' },
  { word: 'Fabelhaft', pos: 'adjective', definition: 'So wunderbar wie aus einer Fabel' },
  { word: 'Fabulieren', pos: 'verb', definition: 'Fantasievoll und ausschmückend erzählen' },
  { word: 'Facettenreich', pos: 'adjective', definition: 'Viele Seiten und Schattierungen zeigend' },
  { word: 'Fadenscheinig', pos: 'adjective', definition: 'Als Vorwand leicht durchschaubar' },
  { word: 'Faible', pos: 'noun', definition: 'Besondere Vorliebe und Schwäche für etwas' },
  { word: 'Famos', pos: 'adjective', definition: 'Großartig und ausgezeichnet' },
  { word: 'Fatalismus', pos: 'noun', definition: 'Ergebenheit in ein unabwendbares Schicksal' },
  { word: 'Fauxpas', pos: 'noun', definition: 'Taktloser Verstoß gegen gesellschaftliche Formen' },
  { word: 'Federleicht', pos: 'adjective', definition: 'Leicht wie eine Feder, beinahe schwerelos' },
  { word: 'Feilschen', pos: 'verb', definition: 'Zäh und kleinlich um den Preis handeln' },
  { word: 'Feinfühlig', pos: 'adjective', definition: 'Mit zartem Gespür für andere' },
  { word: 'Feingeist', pos: 'noun', definition: 'Mensch von verfeinerter geistiger Kultur' },
  { word: 'Feinsinnig', pos: 'adjective', definition: 'Von zartem, empfindsamem Kunstverstand' },
  { word: 'Fernab', pos: 'adverb', definition: 'Weit entfernt vom Geschehen' },
  { word: 'Fernweh', pos: 'noun', definition: 'Sehnsucht nach fernen Ländern und Weiten' },
  { word: 'Fidel', pos: 'adjective', definition: 'Munter, lustig und gut aufgelegt' },
  { word: 'Filigran', pos: 'adjective', definition: 'Fein und zart wie kunstvolles Geflecht' },
  { word: 'Finesse', pos: 'noun', definition: 'Feine, raffinierte Kunstfertigkeit' },
  { word: 'Fingerspitzengefühl', pos: 'noun', definition: 'Feines Gespür im Umgang mit Menschen und Dingen' },
  { word: 'Firlefanz', pos: 'noun', definition: 'Überflüssiger Tand und Kram' },
  { word: 'Flanieren', pos: 'verb', definition: 'Gemächlich und schauend durch die Straßen schlendern' },
  { word: 'Flausen', pos: 'noun', definition: 'Törichte Launen und Hirngespinste' },
  { word: 'Flunkern', pos: 'verb', definition: 'Harmlos und schelmisch schwindeln' },
  { word: 'Folgerichtig', pos: 'adjective', definition: 'Logisch schlüssig aus dem Vorigen folgend' },
  { word: 'Forcieren', pos: 'verb', definition: 'Mit Nachdruck vorantreiben' },
  { word: 'Formvollendet', pos: 'adjective', definition: 'In der Form vollkommen und makellos' },
  { word: 'Fortan', pos: 'adverb', definition: 'Von nun an, künftig' },
  { word: 'Fragil', pos: 'adjective', definition: 'Zart, zerbrechlich und empfindlich' },
  { word: 'Frappant', pos: 'adjective', definition: 'Verblüffend und in die Augen springend' },
  { word: 'Freigeist', pos: 'noun', definition: 'Unabhängig denkender Mensch' },
  { word: 'Freimütig', pos: 'adjective', definition: 'Offen und ohne Scheu die Meinung sagend' },
  { word: 'Frenetisch', pos: 'adjective', definition: 'Rasend begeistert und stürmisch' },
  { word: 'Freudentaumel', pos: 'noun', definition: 'Rausch überschäumender Freude' },
  { word: 'Frohlocken', pos: 'verb', definition: 'Laut jubeln und triumphieren' },
  { word: 'Frohnatur', pos: 'noun', definition: 'Mensch von unverwüstlich heiterem Gemüt' },
  { word: 'Frotzeln', pos: 'verb', definition: 'Gutmütig spöttische Bemerkungen machen' },
  { word: 'Frugal', pos: 'adjective', definition: 'Einfach, karg und genügsam' },
  { word: 'Fuchsteufelswild', pos: 'adjective', definition: 'Vor Wut völlig außer sich' },
  { word: 'Fügung', pos: 'noun', definition: 'Schicksalhafte Verkettung der Umstände' },
  { word: 'Füllhorn', pos: 'noun', definition: 'Sinnbild überströmender Fülle und Gaben' },
  { word: 'Fulminant', pos: 'adjective', definition: 'Glänzend, mitreißend und von durchschlagender Wirkung' },
  { word: 'Fürderhin', pos: 'adverb', definition: 'Von jetzt an, in aller Zukunft' },
  { word: 'Furios', pos: 'adjective', definition: 'Stürmisch, wild und hinreißend' },
  { word: 'Galant', pos: 'adjective', definition: 'Höflich und zuvorkommend gegenüber anderen' },
  { word: 'Garstig', pos: 'adjective', definition: 'Böse, unfreundlich und abstoßend' },
  { word: 'Gebaren', pos: 'noun', definition: 'Auffälliges Verhalten und Auftreten' },
  { word: 'Gedankenverloren', pos: 'adjective', definition: 'Ganz in die eigenen Gedanken versunken' },
  { word: 'Gedeihen', pos: 'verb', definition: 'Sich prächtig entwickeln und wachsen' },
  { word: 'Gediegen', pos: 'adjective', definition: 'Solide, echt und von reiner Qualität' },
  { word: 'Geflissentlich', pos: 'adverb', definition: 'Mit Absicht und Bedacht, wohlweislich' },
  { word: 'Gefühlsduselei', pos: 'noun', definition: 'Übertriebene, unkritische Gefühlsseligkeit' },
  { word: 'Geheimniskrämer', pos: 'noun', definition: 'Jemand, der um alles ein Geheimnis macht' },
  { word: 'Geistesblitz', pos: 'noun', definition: 'Plötzlicher, genialer Einfall' },
  { word: 'Geistreich', pos: 'adjective', definition: 'Voller Witz und kluger Einfälle' },
  { word: 'Gelassenheit', pos: 'noun', definition: 'Innere Ruhe und Unerschütterlichkeit' },
  { word: 'Geleiten', pos: 'verb', definition: 'Jemanden schützend begleiten' },
  { word: 'Gemach', pos: 'adverb', definition: 'Nur langsam, ohne Hast' },
  { word: 'Gemächlich', pos: 'adjective', definition: 'Ruhig, langsam und ohne Eile' },
  { word: 'Gemütlichkeit', pos: 'noun', definition: 'Behagliche, warme und zwanglose Atmosphäre' },
  { word: 'Generös', pos: 'adjective', definition: 'Großzügig und freigebig' },
  { word: 'Genesen', pos: 'verb', definition: 'Von einer Krankheit gesund werden' },
  { word: 'Genügsam', pos: 'adjective', definition: 'Mit wenigem zufrieden' },
  { word: 'Geradlinig', pos: 'adjective', definition: 'Aufrichtig und ohne Umschweife' },
  { word: 'Gerissen', pos: 'adjective', definition: 'Schlau und mit allen Wassern gewaschen' },
  { word: 'Geruhsam', pos: 'adjective', definition: 'Friedlich still und erholsam' },
  { word: 'Gescheit', pos: 'adjective', definition: 'Klug und von wachem Verstand' },
  { word: 'Geschmeidig', pos: 'adjective', definition: 'Weich, biegsam und anpassungsfähig' },
  { word: 'Gestikulieren', pos: 'verb', definition: 'Lebhafte Gebärden mit den Händen machen' },
  { word: 'Gewieft', pos: 'adjective', definition: 'Durchtrieben schlau und erfahren' },
  { word: 'Gewitzt', pos: 'adjective', definition: 'Schlagfertig, pfiffig und clever' },
  { word: 'Glanzstück', pos: 'noun', definition: 'Herausragendes Prunk- und Meisterstück' },
  { word: 'Gleichmut', pos: 'noun', definition: 'Unerschütterliche Ruhe des Gemüts' },
  { word: 'Gleichwohl', pos: 'adverb', definition: 'Dennoch, trotz alledem' },
  { word: 'Glückselig', pos: 'adjective', definition: 'Von tiefem, vollkommenem Glück erfüllt' },
  { word: 'Gönnerhaft', pos: 'adjective', definition: 'Herablassend wohlwollend' },
  { word: 'Goutieren', pos: 'verb', definition: 'Etwas mit Wohlgefallen genießen und schätzen' },
  { word: 'Grandezza', pos: 'noun', definition: 'Würdevolle, vornehme Eleganz' },
  { word: 'Gravitätisch', pos: 'adjective', definition: 'Von gemessener, feierlicher Würde' },
  { word: 'Grazil', pos: 'adjective', definition: 'Zierlich, schlank und anmutig' },
  { word: 'Grobschlächtig', pos: 'adjective', definition: 'Derb, plump und ohne Feinheit' },
  { word: 'Groll', pos: 'noun', definition: 'Schwelender, verhaltener Zorn' },
  { word: 'Großmut', pos: 'noun', definition: 'Edle Hochherzigkeit gegenüber anderen' },
  { word: 'Grübeln', pos: 'verb', definition: 'Lange und quälend über etwas nachsinnen' },
  { word: 'Gütig', pos: 'adjective', definition: 'Von milder, wohlwollender Herzensgüte' },
  { word: 'Habseligkeiten', pos: 'noun', definition: 'Wenige, aber liebgewonnene Besitztümer' },
  { word: 'Hadern', pos: 'verb', definition: 'Mit dem Schicksal unzufrieden ringen' },
  { word: 'Hagestolz', pos: 'noun', definition: 'Eingefleischter, alternder Junggeselle' },
  { word: 'Halbherzig', pos: 'adjective', definition: 'Ohne rechte Überzeugung und Einsatz' },
  { word: 'Händeringend', pos: 'adverb', definition: 'Dringend und voller Verzweiflung' },
  { word: 'Hanebüchen', pos: 'adjective', definition: 'Unerhört und haarsträubend unsinnig' },
  { word: 'Harsch', pos: 'adjective', definition: 'Rau, schroff und unfreundlich' },
  { word: 'Hartgesotten', pos: 'adjective', definition: 'Abgebrüht und durch nichts zu erschüttern' },
  { word: 'Hausbacken', pos: 'adjective', definition: 'Bieder, langweilig und ohne Schwung' },
  { word: 'Hedonismus', pos: 'noun', definition: 'Streben nach Genuss als höchstem Gut' },
  { word: 'Hehr', pos: 'adjective', definition: 'Erhaben, heilig und ehrfurchtgebietend' },
  { word: 'Heimelig', pos: 'adjective', definition: 'Traut, geborgen und anheimelnd' },
  { word: 'Heiterkeit', pos: 'noun', definition: 'Unbeschwerte, helle Gemütsstimmung' },
  { word: 'Hemdsärmelig', pos: 'adjective', definition: 'Unkompliziert-pragmatisch und salopp' },
  { word: 'Herzensangelegenheit', pos: 'noun', definition: 'Sache, die einem zutiefst am Herzen liegt' },
  { word: 'Herzensgüte', pos: 'noun', definition: 'Tiefe, echte Güte des Wesens' },
  { word: 'Herzerwärmend', pos: 'adjective', definition: 'Das Herz mit Wärme und Freude erfüllend' },
  { word: 'Hienieden', pos: 'adverb', definition: 'Hier auf Erden, im Diesseits' },
  { word: 'Himmelhochjauchzend', pos: 'adjective', definition: 'Im Überschwang jubelnder Hochstimmung' },
  { word: 'Hingabe', pos: 'noun', definition: 'Selbstvergessene Aufopferung für eine Sache' },
  { word: 'Hingebungsvoll', pos: 'adjective', definition: 'Mit ganzer Seele bei der Sache' },
  { word: 'Hinlänglich', pos: 'adjective', definition: 'Ausreichend im nötigen Maße' },
  { word: 'Hinterfragen', pos: 'verb', definition: 'Etwas kritisch auf seine Gründe prüfen' },
  { word: 'Hintergründig', pos: 'adjective', definition: 'Mit verborgener, tieferer Bedeutung' },
  { word: 'Höchstselbst', pos: 'adverb', definition: 'In eigener Person, persönlich' },
  { word: 'Hochtrabend', pos: 'adjective', definition: 'Geschwollen und übertrieben anspruchsvoll im Ausdruck' },
  { word: 'Hoffnungsschimmer', pos: 'noun', definition: 'Erster schwacher Schein neuer Zuversicht' },
  { word: 'Hofieren', pos: 'verb', definition: 'Jemanden übertrieben umwerben und umschmeicheln' },
  { word: 'Honorig', pos: 'adjective', definition: 'Ehrenhaft und achtbar' },
  { word: 'Hörensagen', pos: 'noun', definition: 'Ungesichertes Wissen aus zweiter Hand' },
  { word: 'Huldigen', pos: 'verb', definition: 'Jemandem Verehrung und Ehre erweisen' },
  { word: 'Hybris', pos: 'noun', definition: 'Vermessene Selbstüberhebung' },
  { word: 'Idyll', pos: 'noun', definition: 'Bild friedvoll-heiler Abgeschiedenheit' },
  { word: 'Idyllisch', pos: 'adjective', definition: 'Friedlich-malerisch wie ein Idyll' },
  { word: 'Illuster', pos: 'adjective', definition: 'Glanzvoll, erlaucht und von erlesenem Ruf' },
  { word: 'Immanent', pos: 'adjective', definition: 'Innewohnend und im Wesen enthalten' },
  { word: 'Impertinent', pos: 'adjective', definition: 'Dreist, unverschämt und ungehörig' },
  { word: 'Implizit', pos: 'adjective', definition: 'Unausgesprochen mitenthalten' },
  { word: 'Imposant', pos: 'adjective', definition: 'Durch Größe und Erscheinung beeindruckend' },
  { word: 'Improvisieren', pos: 'verb', definition: 'Ohne Vorbereitung aus dem Stegreif gestalten' },
  { word: 'Inbrunst', pos: 'noun', definition: 'Glühende innere Hingabe' },
  { word: 'Indes', pos: 'adverb', definition: 'Unterdessen, währenddessen' },
  { word: 'Indifferent', pos: 'adjective', definition: 'Gleichgültig und ohne innere Anteilnahme' },
  { word: 'Infam', pos: 'adjective', definition: 'Niederträchtig und bösartig' },
  { word: 'Ingeniös', pos: 'adjective', definition: 'Erfinderisch, scharfsinnig und genial' },
  { word: 'Innehalten', pos: 'verb', definition: 'Mitten in der Bewegung kurz verharren' },
  { word: 'Innigkeit', pos: 'noun', definition: 'Tiefe, herzliche Verbundenheit' },
  { word: 'Insgeheim', pos: 'adverb', definition: 'Im Stillen, ohne dass andere es merken' },
  { word: 'Insinuieren', pos: 'verb', definition: 'Etwas unterschwellig andeuten und unterstellen' },
  { word: 'Inständig', pos: 'adjective', definition: 'Eindringlich und flehentlich' },
  { word: 'Integer', pos: 'adjective', definition: 'Unbestechlich und moralisch einwandfrei' },
  { word: 'Intuition', pos: 'noun', definition: 'Unmittelbares Erfassen ohne bewusstes Nachdenken' },
  { word: 'Irisierend', pos: 'adjective', definition: 'In Regenbogenfarben schillernd' },
  { word: 'Ironie', pos: 'noun', definition: 'Feiner Spott durch das Gegenteil des Gemeinten' },
  { word: 'Irrlichtern', pos: 'verb', definition: 'Unstet wie ein Irrlicht umhergeistern' },
  { word: 'Jäh', pos: 'adjective', definition: 'Plötzlich und unvermittelt hereinbrechend' },
  { word: 'Jauchzen', pos: 'verb', definition: 'Vor Freude laut aufjubeln' },
  { word: 'Jonglieren', pos: 'verb', definition: 'Geschickt mit mehreren Dingen zugleich hantieren' },
  { word: 'Jovial', pos: 'adjective', definition: 'Betont leutselig und gönnerhaft freundlich' },
  { word: 'Jubilieren', pos: 'verb', definition: 'Hell und freudig jubeln' },
  { word: 'Juwel', pos: 'noun', definition: 'Kostbarkeit von besonderem Wert' },
  { word: 'Kakophonie', pos: 'noun', definition: 'Misstönendes Durcheinander von Klängen' },
  { word: 'Kalkül', pos: 'noun', definition: 'Kühl abwägende Berechnung' },
  { word: 'Kapriole', pos: 'noun', definition: 'Übermütiger Luftsprung oder toller Einfall' },
  { word: 'Kapriziös', pos: 'adjective', definition: 'Launenhaft und eigenwillig' },
  { word: 'Karg', pos: 'adjective', definition: 'Spärlich, schmucklos und genügsam' },
  { word: 'Kathartisch', pos: 'adjective', definition: 'Seelisch reinigend und befreiend' },
  { word: 'Katzensprung', pos: 'noun', definition: 'Nur eine ganz kurze Entfernung' },
  { word: 'Kauzig', pos: 'adjective', definition: 'Wunderlich und liebenswert schrullig' },
  { word: 'Kess', pos: 'adjective', definition: 'Frech, flott und selbstbewusst' },
  { word: 'Klammheimlich', pos: 'adverb', definition: 'Ganz still und von niemandem bemerkt' },
  { word: 'Klangvoll', pos: 'adjective', definition: 'Voll und schön im Klang' },
  { word: 'Kleinod', pos: 'noun', definition: 'Kostbares kleines Schmuckstück' },
  { word: 'Knifflig', pos: 'adjective', definition: 'Verzwickt und schwierig zu lösen' },
  { word: 'Kokettieren', pos: 'verb', definition: 'Spielerisch mit den eigenen Reizen werben' },
  { word: 'Kokolores', pos: 'noun', definition: 'Unsinniges Gerede und Getue' },
  { word: 'Kolportieren', pos: 'verb', definition: 'Gerüchte und Behauptungen weiterverbreiten' },
  { word: 'Kompendium', pos: 'noun', definition: 'Knappes Nachschlagewerk des Wesentlichen' },
  { word: 'Kongenial', pos: 'adjective', definition: 'Geistig ebenbürtig und meisterhaft entsprechend' },
  { word: 'Konsterniert', pos: 'adjective', definition: 'Bestürzt und fassungslos' },
  { word: 'Kontemplation', pos: 'noun', definition: 'Versenkte, beschauliche Betrachtung' },
  { word: 'Konterkarieren', pos: 'verb', definition: 'Etwas gezielt durchkreuzen und vereiteln' },
  { word: 'Konziliant', pos: 'adjective', definition: 'Umgänglich, versöhnlich und entgegenkommend' },
  { word: 'Kopfkino', pos: 'noun', definition: 'Lebhafte Bilder der eigenen Vorstellungskraft' },
  { word: 'Koryphäe', pos: 'noun', definition: 'Anerkannte Größe ihres Fachs' },
  { word: 'Kosmopolit', pos: 'noun', definition: 'Weltbürger, überall zu Hause' },
  { word: 'Kredenzen', pos: 'verb', definition: 'Getränke oder Speisen feierlich anbieten' },
  { word: 'Kühn', pos: 'adjective', definition: 'Wagemutig und verwegen' },
  { word: 'Kulminieren', pos: 'verb', definition: 'Im Höhepunkt gipfeln' },
  { word: 'Kummerspeck', pos: 'noun', definition: 'Gewichtszunahme aus Kummer und Frust' },
  { word: 'Kunstfertig', pos: 'adjective', definition: 'Mit großem handwerklichem Geschick' },
  { word: 'Kurios', pos: 'adjective', definition: 'Merkwürdig, seltsam und zum Schmunzeln' },
  { word: 'Kurzerhand', pos: 'adverb', definition: 'Ohne Zögern und ohne viel Federlesens' },
  { word: 'Kurzweilig', pos: 'adjective', definition: 'Unterhaltsam, sodass die Zeit verfliegt' },
  { word: 'Labsal', pos: 'noun', definition: 'Wohltuende Erquickung für Leib und Seele' },
  { word: 'Lakonisch', pos: 'adjective', definition: 'Knapp, trocken und ohne viele Worte' },
  { word: 'Lamentieren', pos: 'verb', definition: 'Wortreich klagen und jammern' },
  { word: 'Landläufig', pos: 'adjective', definition: 'Allgemein üblich und verbreitet' },
  { word: 'Langmut', pos: 'noun', definition: 'Geduldige Nachsicht über lange Zeit' },
  { word: 'Lapidar', pos: 'adjective', definition: 'Kurz und bündig, von schlichter Wucht' },
  { word: 'Läppisch', pos: 'adjective', definition: 'Albern und lächerlich geringfügig' },
  { word: 'Lauschig', pos: 'adjective', definition: 'Gemütlich versteckt und traulich' },
  { word: 'Lavieren', pos: 'verb', definition: 'Sich geschickt zwischen Schwierigkeiten hindurchmanövrieren' },
  { word: 'Lebensbejahend', pos: 'adjective', definition: 'Dem Leben freudig zugewandt' },
  { word: 'Lebenskünstler', pos: 'noun', definition: 'Mensch, der aus allem das Beste macht' },
  { word: 'Leger', pos: 'adjective', definition: 'Ungezwungen und lässig' },
  { word: 'Leichtfüßig', pos: 'adjective', definition: 'Beschwingt und mühelos leicht im Gang' },
  { word: 'Leitmotiv', pos: 'noun', definition: 'Immer wiederkehrender prägender Grundgedanke' },
  { word: 'Lethargie', pos: 'noun', definition: 'Bleierne Trägheit und Teilnahmslosigkeit' },
  { word: 'Leutselig', pos: 'adjective', definition: 'Herablassend-freundlich und umgänglich' },
  { word: 'Lichtblick', pos: 'noun', definition: 'Erfreuliches Zeichen in trüber Lage' },
  { word: 'Lichtdurchflutet', pos: 'adjective', definition: 'Von hellem Licht ganz erfüllt' },
  { word: 'Liebäugeln', pos: 'verb', definition: 'Mit einem Gedanken wohlgefällig spielen' },
  { word: 'Liebreizend', pos: 'adjective', definition: 'Von zartem, gewinnendem Charme' },
  { word: 'Lodern', pos: 'verb', definition: 'Mit großer, heller Flamme brennen' },
  { word: 'Luftschloss', pos: 'noun', definition: 'Schöner, aber unerfüllbarer Wunschtraum' },
  { word: 'Lukullisch', pos: 'adjective', definition: 'Üppig und erlesen wie ein Festmahl' },
  { word: 'Lustwandeln', pos: 'verb', definition: 'Vergnügt und müßig umherspazieren' },
  { word: 'Luzide', pos: 'adjective', definition: 'Klar, hell und durchsichtig im Denken' },
  { word: 'Mäandern', pos: 'verb', definition: 'Sich in weiten Windungen dahinschlängeln' },
  { word: 'Makellos', pos: 'adjective', definition: 'Ohne jeden Fehler und Tadel' },
  { word: 'Malerisch', pos: 'adjective', definition: 'So schön, dass es ein Gemälde sein könnte' },
  { word: 'Manieriert', pos: 'adjective', definition: 'Gekünstelt und unnatürlich im Stil' },
  { word: 'Mannigfaltig', pos: 'adjective', definition: 'Vielfältig und reich an Formen' },
  { word: 'Marginal', pos: 'adjective', definition: 'Am Rande liegend und unbedeutend' },
  { word: 'Markant', pos: 'adjective', definition: 'Auffallend ausgeprägt und einprägsam' },
  { word: 'Martialisch', pos: 'adjective', definition: 'Kriegerisch grimmig und einschüchternd' },
  { word: 'Maßvoll', pos: 'adjective', definition: 'Das rechte Maß wahrend' },
  { word: 'Mäzen', pos: 'noun', definition: 'Großzügiger Förderer von Kunst und Kultur' },
  { word: 'Meisterhaft', pos: 'adjective', definition: 'Mit vollendetem Können ausgeführt' },
  { word: 'Melancholie', pos: 'noun', definition: 'Sanfte, versonnene Schwermut' },
  { word: 'Melodiös', pos: 'adjective', definition: 'Wohlklingend wie eine Melodie' },
  { word: 'Metapher', pos: 'noun', definition: 'Bildhafte Übertragung eines Ausdrucks' },
  { word: 'Mimose', pos: 'noun', definition: 'Überaus empfindlicher, leicht gekränkter Mensch' },
  { word: 'Minutiös', pos: 'adjective', definition: 'Bis in kleinste Einzelheiten genau' },
  { word: 'Mirakel', pos: 'noun', definition: 'Wunderbares, unerklärliches Ereignis' },
  { word: 'Mitnichten', pos: 'adverb', definition: 'Keineswegs, ganz und gar nicht' },
  { word: 'Mokieren', pos: 'verb', definition: 'Sich spöttisch über etwas lustig machen' },
  { word: 'Mondän', pos: 'adjective', definition: 'Elegant-weltläufig im großen Stil' },
  { word: 'Morbide', pos: 'adjective', definition: 'Dem Verfall zugeneigt und düster' },
  { word: 'Morgengrauen', pos: 'noun', definition: 'Erstes fahles Licht des anbrechenden Tages' },
  { word: 'Morgenmuffel', pos: 'noun', definition: 'Mensch, der morgens schwer in Gang kommt' },
  { word: 'Mundart', pos: 'noun', definition: 'Landschaftlich gefärbte Sprachform' },
  { word: 'Munkeln', pos: 'verb', definition: 'Heimlich und gerüchteweise reden' },
  { word: 'Müßiggang', pos: 'noun', definition: 'Genussvolles Nichtstun' },
  { word: 'Mutterseelenallein', pos: 'adjective', definition: 'Ganz und gar verlassen und allein' },
  { word: 'Mysterium', pos: 'noun', definition: 'Unergründliches Geheimnis' },
  { word: 'Nachgerade', pos: 'adverb', definition: 'Geradezu, mittlerweile wirklich' },
  { word: 'Nachhall', pos: 'noun', definition: 'Lange nachklingende Wirkung' },
  { word: 'Nachsinnen', pos: 'verb', definition: 'Still und gründlich über etwas nachdenken' },
  { word: 'Nächtens', pos: 'adverb', definition: 'Zur Nachtzeit, in nächtlicher Stunde' },
  { word: 'Namhaft', pos: 'adjective', definition: 'Bekannt und von gutem Ruf' },
  { word: 'Naseweis', pos: 'adjective', definition: 'Vorlaut und altklug' },
  { word: 'Nebulös', pos: 'adjective', definition: 'Verschwommen und undurchsichtig' },
  { word: 'Nesteln', pos: 'verb', definition: 'Mit unruhigen Fingern an etwas hantieren' },
  { word: 'Nestwärme', pos: 'noun', definition: 'Geborgenheit der familiären Umgebung' },
  { word: 'Nimbus', pos: 'noun', definition: 'Glanzvoller Ruf, der jemanden umgibt' },
  { word: 'Nimmermüde', pos: 'adjective', definition: 'Unermüdlich und ohne Erschöpfung' },
  { word: 'Nivellieren', pos: 'verb', definition: 'Unterschiede einebnen und ausgleichen' },
  { word: 'Nonchalance', pos: 'noun', definition: 'Lässige, unbekümmerte Eleganz' },
  { word: 'Nonchalant', pos: 'adjective', definition: 'Lässig-unbekümmert und souverän' },
  { word: 'Nonplusultra', pos: 'noun', definition: 'Das Unübertreffbare schlechthin' },
  { word: 'Nostalgie', pos: 'noun', definition: 'Wehmütige Sehnsucht nach Vergangenem' },
  { word: 'Notorisch', pos: 'adjective', definition: 'Allbekannt und unverbesserlich' },
  { word: 'Nuance', pos: 'noun', definition: 'Feiner, kaum merklicher Unterschied' },
  { word: 'Obendrein', pos: 'adverb', definition: 'Noch dazu, überdies' },
  { word: 'Obliegen', pos: 'verb', definition: 'Als Pflicht und Aufgabe zufallen' },
  { word: 'Obskur', pos: 'adjective', definition: 'Dunkel, zweifelhaft und undurchsichtig' },
  { word: 'Obsolet', pos: 'adjective', definition: 'Veraltet und nicht mehr gebräuchlich' },
  { word: 'Odyssee', pos: 'noun', definition: 'Lange Irrfahrt voller Abenteuer' },
  { word: 'Offenkundig', pos: 'adjective', definition: 'Für jedermann klar ersichtlich' },
  { word: 'Offerieren', pos: 'verb', definition: 'Förmlich und höflich anbieten' },
  { word: 'Ohnegleichen', pos: 'adjective', definition: 'Unvergleichlich, ohne Beispiel' },
  { word: 'Ohrwurm', pos: 'noun', definition: 'Melodie, die einem nicht aus dem Kopf geht' },
  { word: 'Oktroyieren', pos: 'verb', definition: 'Etwas gegen den Willen aufzwingen' },
  { word: 'Omnipräsent', pos: 'adjective', definition: 'Allgegenwärtig und überall anzutreffen' },
  { word: 'Opulent', pos: 'adjective', definition: 'Üppig, prachtvoll und verschwenderisch reich' },
  { word: 'Orakeln', pos: 'verb', definition: 'Dunkle, vieldeutige Andeutungen machen' },
  { word: 'Ostentativ', pos: 'adjective', definition: 'Betont zur Schau gestellt' },
  { word: 'Paradigma', pos: 'noun', definition: 'Grundlegendes Denkmuster einer Zeit' },
  { word: 'Paradox', pos: 'adjective', definition: 'Scheinbar widersinnig und doch wahr' },
  { word: 'Parlieren', pos: 'verb', definition: 'Leicht und gewandt plaudern' },
  { word: 'Partout', pos: 'adverb', definition: 'Um jeden Preis, unbedingt' },
  { word: 'Passion', pos: 'noun', definition: 'Große, hingebungsvolle Leidenschaft' },
  { word: 'Pathos', pos: 'noun', definition: 'Feierlich-leidenschaftliche Ergriffenheit' },
  { word: 'Patina', pos: 'noun', definition: 'Edler Hauch des Alters auf Oberflächen' },
  { word: 'Pedantisch', pos: 'adjective', definition: 'Übertrieben genau und kleinlich' },
  { word: 'Penibel', pos: 'adjective', definition: 'Peinlich genau und ordentlich' },
  { word: 'Perfide', pos: 'adjective', definition: 'Hinterhältig und niederträchtig' },
  { word: 'Perpetuieren', pos: 'verb', definition: 'Endlos fortsetzen und verewigen' },
  { word: 'Pfiffig', pos: 'adjective', definition: 'Schlau, findig und gewitzt' },
  { word: 'Philanthrop', pos: 'noun', definition: 'Menschenfreund mit tätiger Güte' },
  { word: 'Philosophieren', pos: 'verb', definition: 'Über Grundfragen des Lebens nachdenken' },
  { word: 'Pittoresk', pos: 'adjective', definition: 'Malerisch und wie fürs Bild geschaffen' },
  { word: 'Plädoyer', pos: 'noun', definition: 'Leidenschaftliche Rede für eine Sache' },
  { word: 'Plakativ', pos: 'adjective', definition: 'Auffällig vereinfacht und schlagwortartig' },
  { word: 'Plausibel', pos: 'adjective', definition: 'Einleuchtend und nachvollziehbar' },
  { word: 'Poesie', pos: 'noun', definition: 'Dichtkunst und aller Zauber des Poetischen' },
  { word: 'Poetisch', pos: 'adjective', definition: 'Voll dichterischem Zauber' },
  { word: 'Polyglott', pos: 'adjective', definition: 'Vieler Sprachen mächtig' },
  { word: 'Pompös', pos: 'adjective', definition: 'Prunkvoll bis zur Übertreibung' },
  { word: 'Postulieren', pos: 'verb', definition: 'Als Forderung oder Annahme aufstellen' },
  { word: 'Pragmatisch', pos: 'adjective', definition: 'Sachlich aufs Machbare gerichtet' },
  { word: 'Prägnant', pos: 'adjective', definition: 'Knapp und treffend auf den Punkt gebracht' },
  { word: 'Prämisse', pos: 'noun', definition: 'Voraussetzung, aus der gefolgert wird' },
  { word: 'Prangen', pos: 'verb', definition: 'Weithin sichtbar in voller Pracht stehen' },
  { word: 'Prekär', pos: 'adjective', definition: 'Heikel, unsicher und bedenklich' },
  { word: 'Profund', pos: 'adjective', definition: 'Tiefgründig und von gründlichem Wissen' },
  { word: 'Prosaisch', pos: 'adjective', definition: 'Nüchtern und ohne allen Zauber' },
  { word: 'Prosperieren', pos: 'verb', definition: 'Gedeihen und wirtschaftlich blühen' },
  { word: 'Putzmunter', pos: 'adjective', definition: 'Quicklebendig und hellwach' },
  { word: 'Querkopf', pos: 'noun', definition: 'Eigensinniger Mensch mit ganz eigenen Ansichten' },
  { word: 'Quicklebendig', pos: 'adjective', definition: 'Voller Leben und munterer Frische' },
  { word: 'Quintessenz', pos: 'noun', definition: 'Das Wesentliche als Kern der Sache' },
  { word: 'Quirlig', pos: 'adjective', definition: 'Lebhaft wuselig und voller Bewegung' },
  { word: 'Quittieren', pos: 'verb', definition: 'Etwas mit einer bestimmten Reaktion beantworten' },
  { word: 'Rabiat', pos: 'adjective', definition: 'Grob, rücksichtslos und gewaltsam' },
  { word: 'Rarität', pos: 'noun', definition: 'Seltenes, kostbares Stück' },
  { word: 'Räsonieren', pos: 'verb', definition: 'Wortreich urteilen und schwadronieren' },
  { word: 'Rastlos', pos: 'adjective', definition: 'Ohne Ruhe und ständig getrieben' },
  { word: 'Ratio', pos: 'noun', definition: 'Nüchtern abwägender Verstand' },
  { word: 'Raunen', pos: 'verb', definition: 'Geheimnisvoll leise murmeln' },
  { word: 'Redlich', pos: 'adjective', definition: 'Ehrlich, aufrichtig und rechtschaffen' },
  { word: 'Redselig', pos: 'adjective', definition: 'Gern und viel redend' },
  { word: 'Regsam', pos: 'adjective', definition: 'Geistig lebhaft und tätig' },
  { word: 'Rekapitulieren', pos: 'verb', definition: 'Das Wesentliche zusammenfassend wiederholen' },
  { word: 'Renitent', pos: 'adjective', definition: 'Widersetzlich und störrisch' },
  { word: 'Renommee', pos: 'noun', definition: 'Guter Ruf und öffentliches Ansehen' },
  { word: 'Resilienz', pos: 'noun', definition: 'Innere Widerstandskraft in Krisen' },
  { word: 'Resolut', pos: 'adjective', definition: 'Entschlossen und tatkräftig zupackend' },
  { word: 'Reüssieren', pos: 'verb', definition: 'Erfolg haben und sich durchsetzen' },
  { word: 'Reverenz', pos: 'noun', definition: 'Ehrerbietige Verbeugung oder Huldigung' },
  { word: 'Rhetorik', pos: 'noun', definition: 'Kunst der wirkungsvollen Rede' },
  { word: 'Rigoros', pos: 'adjective', definition: 'Streng, unerbittlich und durchgreifend' },
  { word: 'Ruchlos', pos: 'adjective', definition: 'Verrucht und ohne Gewissen' },
  { word: 'Rückgrat', pos: 'noun', definition: 'Innere Festigkeit und Charakterstärke' },
  { word: 'Ruhepol', pos: 'noun', definition: 'Mensch oder Ort vollkommener Gelassenheit' },
  { word: 'Rührselig', pos: 'adjective', definition: 'Übertrieben gefühlvoll und zu Tränen geneigt' },
  { word: 'Rüstig', pos: 'adjective', definition: 'Im Alter noch frisch und leistungsfähig' },
  { word: 'Sagenumwoben', pos: 'adjective', definition: 'Von Legenden und Mythen umrankt' },
  { word: 'Sakrosankt', pos: 'adjective', definition: 'Unantastbar und heilig' },
  { word: 'Salbungsvoll', pos: 'adjective', definition: 'Übertrieben feierlich im Ton' },
  { word: 'Salopp', pos: 'adjective', definition: 'Betont lässig und ungezwungen' },
  { word: 'Sanftmut', pos: 'noun', definition: 'Milde, friedfertige Gemütsart' },
  { word: 'Sanguinisch', pos: 'adjective', definition: 'Von heiter-lebhaftem Temperament' },
  { word: 'Sardonisch', pos: 'adjective', definition: 'Bitter höhnisch und grimmig spöttisch' },
  { word: 'Sattelfest', pos: 'adjective', definition: 'In einem Fach völlig sicher und beschlagen' },
  { word: 'Sattsam', pos: 'adverb', definition: 'Mehr als genug, bis zum Überdruss' },
  { word: 'Säuseln', pos: 'verb', definition: 'Leise und sanft rauschen oder flüstern' },
  { word: 'Schabernack', pos: 'noun', definition: 'Übermütiger, harmloser Streich' },
  { word: 'Schäkern', pos: 'verb', definition: 'Neckisch scherzen und flirten' },
  { word: 'Schalkhaft', pos: 'adjective', definition: 'Verschmitzt und neckisch aufgelegt' },
  { word: 'Scharfsinn', pos: 'noun', definition: 'Durchdringende Klarheit des Verstandes' },
  { word: 'Schelmisch', pos: 'adjective', definition: 'Spitzbübisch vergnügt' },
  { word: 'Schillernd', pos: 'adjective', definition: 'In wechselnden Farben glänzend und vieldeutig' },
  { word: 'Schlagfertig', pos: 'adjective', definition: 'Immer eine treffende Antwort bereit' },
  { word: 'Schlaraffenland', pos: 'noun', definition: 'Märchenland des mühelosen Überflusses' },
  { word: 'Schlendern', pos: 'verb', definition: 'Gemütlich und ziellos spazieren' },
  { word: 'Schlitzohr', pos: 'noun', definition: 'Gerissener, aber liebenswerter Schlaukopf' },
  { word: 'Schmachten', pos: 'verb', definition: 'Sehnsuchtsvoll verlangen und vergehen' },
  { word: 'Schmökern', pos: 'verb', definition: 'Genüsslich und versunken in Büchern lesen' },
  { word: 'Schmunzeln', pos: 'verb', definition: 'Still und vergnügt in sich hineinlächeln' },
  { word: 'Schnurstracks', pos: 'adverb', definition: 'Auf direktem Weg, ohne Umweg' },
  { word: 'Schöngeist', pos: 'noun', definition: 'Mensch mit feinem Sinn für Kunst und Literatur' },
  { word: 'Schwadronieren', pos: 'verb', definition: 'Großspurig und wortreich daherreden' },
  { word: 'Schwärmerisch', pos: 'adjective', definition: 'Voller überschwänglicher Begeisterung' },
  { word: 'Schwelgen', pos: 'verb', definition: 'Sich genussvoll einer Sache hingeben' },
  { word: 'Schwermut', pos: 'noun', definition: 'Tiefe, anhaltende Traurigkeit' },
  { word: 'Seelenverwandt', pos: 'adjective', definition: 'Im Innersten gleichgestimmt' },
  { word: 'Sehnsucht', pos: 'noun', definition: 'Inniges, schmerzliches Verlangen' },
  { word: 'Sehnsuchtsvoll', pos: 'adjective', definition: 'Von innigem Verlangen erfüllt' },
  { word: 'Seicht', pos: 'adjective', definition: 'Flach und ohne geistige Tiefe' },
  { word: 'Selbstironie', pos: 'noun', definition: 'Fähigkeit, über sich selbst zu schmunzeln' },
  { word: 'Selig', pos: 'adjective', definition: 'Von stillem, vollkommenem Glück erfüllt' },
  { word: 'Sentenz', pos: 'noun', definition: 'Knapper, einprägsamer Sinnspruch' },
  { word: 'Silberstreif', pos: 'noun', definition: 'Erstes Anzeichen der Besserung am Horizont' },
  { word: 'Sinnbild', pos: 'noun', definition: 'Anschauliches Symbol für etwas Abstraktes' },
  { word: 'Sinnieren', pos: 'verb', definition: 'Versunken vor sich hin grübeln' },
  { word: 'Sisyphusarbeit', pos: 'noun', definition: 'Mühsal ohne absehbares Ende' },
  { word: 'Skepsis', pos: 'noun', definition: 'Zweifelnde, prüfende Grundhaltung' },
  { word: 'Skurril', pos: 'adjective', definition: 'Verschroben komisch und bizarr' },
  { word: 'Sommerfrische', pos: 'noun', definition: 'Erholungsaufenthalt auf dem Lande im Sommer' },
  { word: 'Somnambul', pos: 'adjective', definition: 'Schlafwandlerisch sicher und entrückt' },
  { word: 'Sondieren', pos: 'verb', definition: 'Vorsichtig die Lage erkunden' },
  { word: 'Sonor', pos: 'adjective', definition: 'Voll, tief und wohlklingend' },
  { word: 'Souverän', pos: 'adjective', definition: 'Überlegen, sicher und gelassen' },
  { word: 'Sperrangelweit', pos: 'adverb', definition: 'Ganz und gar weit offen' },
  { word: 'Spitzbübisch', pos: 'adjective', definition: 'Verschmitzt wie ein kleiner Gauner' },
  { word: 'Spitzfindig', pos: 'adjective', definition: 'Übertrieben haarspalterisch scharfsinnig' },
  { word: 'Sporadisch', pos: 'adjective', definition: 'Nur vereinzelt und gelegentlich auftretend' },
  { word: 'Sprachgewalt', pos: 'noun', definition: 'Mächtige, mitreißende Ausdruckskraft' },
  { word: 'Stagnieren', pos: 'verb', definition: 'Zum Stillstand kommen' },
  { word: 'Standhaft', pos: 'adjective', definition: 'Fest und unbeirrbar bleibend' },
  { word: 'Sternenklar', pos: 'adjective', definition: 'Klar mit funkelndem Sternenhimmel' },
  { word: 'Sternstunde', pos: 'noun', definition: 'Schicksalhafter Augenblick großer Entscheidung' },
  { word: 'Stibitzen', pos: 'verb', definition: 'Etwas heimlich und schelmisch entwenden' },
  { word: 'Stichhaltig', pos: 'adjective', definition: 'Einer Prüfung standhaltend und überzeugend' },
  { word: 'Stilblüte', pos: 'noun', definition: 'Unfreiwillig komischer sprachlicher Fehlgriff' },
  { word: 'Stilvoll', pos: 'adjective', definition: 'Von sicherem, gutem Geschmack geprägt' },
  { word: 'Stimmungsvoll', pos: 'adjective', definition: 'Von dichter Atmosphäre erfüllt' },
  { word: 'Stoisch', pos: 'adjective', definition: 'Gleichmütig und unerschütterlich gelassen' },
  { word: 'Strahlkraft', pos: 'noun', definition: 'Weithin wirkende Anziehungs- und Leuchtkraft' },
  { word: 'Stringent', pos: 'adjective', definition: 'Logisch zwingend und schlüssig' },
  { word: 'Suada', pos: 'noun', definition: 'Wortreicher, unaufhaltsamer Redefluss' },
  { word: 'Sublim', pos: 'adjective', definition: 'Erhaben fein und nur dem Kenner zugänglich' },
  { word: 'Subtil', pos: 'adjective', definition: 'Fein, zart und kaum merklich' },
  { word: 'Süffisant', pos: 'adjective', definition: 'Selbstgefällig spöttisch lächelnd' },
  { word: 'Symbiose', pos: 'noun', definition: 'Enges Zusammenleben zu beiderseitigem Nutzen' },
  { word: 'Szenerie', pos: 'noun', definition: 'Stimmungsvolles Gesamtbild eines Schauplatzes' },
  { word: 'Tagtraum', pos: 'noun', definition: 'Wachträumerei voller Wunschbilder' },
  { word: 'Taktgefühl', pos: 'noun', definition: 'Feines Gespür für das Angemessene' },
  { word: 'Tändeln', pos: 'verb', definition: 'Verspielt und unernst mit etwas umgehen' },
  { word: 'Tatendrang', pos: 'noun', definition: 'Ungestümer Drang, etwas zu unternehmen' },
  { word: 'Taumeln', pos: 'verb', definition: 'Schwankend und benommen wanken' },
  { word: 'Tiefgründig', pos: 'adjective', definition: 'Von verborgenem Gedankenreichtum' },
  { word: 'Tingeln', pos: 'verb', definition: 'Mit kleinen Auftritten von Ort zu Ort ziehen' },
  { word: 'Tirilieren', pos: 'verb', definition: 'Hell und fröhlich wie ein Vogel singen' },
  { word: 'Tollkühn', pos: 'adjective', definition: 'Verwegen bis an den Rand des Leichtsinns' },
  { word: 'Torschlusspanik', pos: 'noun', definition: 'Angst, im Leben etwas endgültig zu verpassen' },
  { word: 'Tragweite', pos: 'noun', definition: 'Reichweite der Folgen einer Sache' },
  { word: 'Trällern', pos: 'verb', definition: 'Unbeschwert eine Melodie vor sich hin singen' },
  { word: 'Transzendent', pos: 'adjective', definition: 'Über die Grenzen der Erfahrung hinausgehend' },
  { word: 'Traumtänzer', pos: 'noun', definition: 'Weltfremd in eigenen Träumen lebender Mensch' },
  { word: 'Traumverloren', pos: 'adjective', definition: 'Ganz in Träume versunken' },
  { word: 'Treffsicher', pos: 'adjective', definition: 'Genau ins Ziel oder ins Schwarze treffend' },
  { word: 'Treuherzig', pos: 'adjective', definition: 'Arglos, ehrlich und vertrauensvoll' },
  { word: 'Tristesse', pos: 'noun', definition: 'Graue, trostlose Ödnis' },
  { word: 'Trübsinn', pos: 'noun', definition: 'Anhaltend gedrückte, düstere Stimmung' },
  { word: 'Trutzig', pos: 'adjective', definition: 'Wehrhaft stolz und unbeugsam' },
  { word: 'Tüfteln', pos: 'verb', definition: 'Geduldig an kniffligen Aufgaben arbeiten' },
  { word: 'Tunlichst', pos: 'adverb', definition: 'Möglichst, nach besten Kräften' },
  { word: 'Überaus', pos: 'adverb', definition: 'In hohem Maße, äußerst' },
  { word: 'Überdies', pos: 'adverb', definition: 'Außerdem, darüber hinaus' },
  { word: 'Übermut', pos: 'noun', definition: 'Ausgelassene, mutwillige Lebenslust' },
  { word: 'Überschwänglich', pos: 'adjective', definition: 'Im Gefühlsausdruck übersprudelnd' },
  { word: 'Ubiquitär', pos: 'adjective', definition: 'Überall verbreitet und anzutreffen' },
  { word: 'Umgarnen', pos: 'verb', definition: 'Mit List und Charme für sich einnehmen' },
  { word: 'Umsichtig', pos: 'adjective', definition: 'Alle Umstände klug bedenkend' },
  { word: 'Umtriebig', pos: 'adjective', definition: 'Rastlos geschäftig und unternehmungslustig' },
  { word: 'Unabdingbar', pos: 'adjective', definition: 'Unbedingt erforderlich' },
  { word: 'Unbändig', pos: 'adjective', definition: 'Wild und nicht zu zähmen' },
  { word: 'Unbedarft', pos: 'adjective', definition: 'Arglos und ohne Erfahrung' },
  { word: 'Unbeirrbar', pos: 'adjective', definition: 'Durch nichts vom Weg abzubringen' },
  { word: 'Unentwegt', pos: 'adverb', definition: 'Beharrlich immerfort und ohne Unterlass' },
  { word: 'Unergründlich', pos: 'adjective', definition: 'Bis auf den Grund nicht zu erfassen' },
  { word: 'Unerschrocken', pos: 'adjective', definition: 'Furchtlos auch in Gefahr' },
  { word: 'Unerschütterlich', pos: 'adjective', definition: 'Fest und durch nichts zu beirren' },
  { word: 'Ungestüm', pos: 'adjective', definition: 'Stürmisch drängend und wild' },
  { word: 'Unisono', pos: 'adverb', definition: 'Einstimmig und wie aus einem Munde' },
  { word: 'Unlängst', pos: 'adverb', definition: 'Vor kurzem, neulich' },
  { word: 'Unorthodox', pos: 'adjective', definition: 'Von gewohnten Wegen abweichend' },
  { word: 'Unverblümt', pos: 'adjective', definition: 'Geradeheraus und ohne Beschönigung' },
  { word: 'Unverfroren', pos: 'adjective', definition: 'Dreist und ohne jede Scham' },
  { word: 'Unversehens', pos: 'adverb', definition: 'Ganz plötzlich und unerwartet' },
  { word: 'Unwägbarkeit', pos: 'noun', definition: 'Nicht berechenbarer Unsicherheitsfaktor' },
  { word: 'Urgestein', pos: 'noun', definition: 'Altgediente, prägende Persönlichkeit' },
  { word: 'Urig', pos: 'adjective', definition: 'Ursprünglich, rustikal und originell' },
  { word: 'Usus', pos: 'noun', definition: 'Das allgemein Übliche und Gewohnte' },
  { word: 'Utopie', pos: 'noun', definition: 'Ideales, aber unerreichbares Zukunftsbild' },
  { word: 'Vehement', pos: 'adjective', definition: 'Heftig, ungestüm und mit Nachdruck' },
  { word: 'Verballhornen', pos: 'verb', definition: 'Ein Wort scherzhaft entstellen' },
  { word: 'Verbrämen', pos: 'verb', definition: 'Etwas Unangenehmes beschönigend verhüllen' },
  { word: 'Verfänglich', pos: 'adjective', definition: 'Heikel und leicht in Verlegenheit bringend' },
  { word: 'Vergänglichkeit', pos: 'noun', definition: 'Unaufhaltsames Dahinschwinden alles Irdischen' },
  { word: 'Vergebens', pos: 'adverb', definition: 'Ohne Erfolg, umsonst' },
  { word: 'Verheißungsvoll', pos: 'adjective', definition: 'Großes und Schönes versprechend' },
  { word: 'Verinnerlichen', pos: 'verb', definition: 'Sich etwas ganz zu eigen machen' },
  { word: 'Verklärt', pos: 'adjective', definition: 'In entrücktem Glanz erscheinend' },
  { word: 'Vermächtnis', pos: 'noun', definition: 'Hinterlassenes geistiges Erbe' },
  { word: 'Vermessen', pos: 'adjective', definition: 'Anmaßend kühn über das eigene Maß hinaus' },
  { word: 'Vernissage', pos: 'noun', definition: 'Festliche Eröffnung einer Kunstausstellung' },
  { word: 'Verschlimmbessern', pos: 'verb', definition: 'Durch gut gemeinte Eingriffe verschlechtern' },
  { word: 'Verschmitzt', pos: 'adjective', definition: 'Pfiffig-listig und liebenswert verschlagen' },
  { word: 'Verschroben', pos: 'adjective', definition: 'Wunderlich und seltsam eigenbrötlerisch' },
  { word: 'Versiert', pos: 'adjective', definition: 'Erfahren und bewandert in einer Sache' },
  { word: 'Versonnen', pos: 'adjective', definition: 'Träumerisch in Gedanken versunken' },
  { word: 'Vertrackt', pos: 'adjective', definition: 'Verzwickt und verwickelt kompliziert' },
  { word: 'Verträumt', pos: 'adjective', definition: 'Der Wirklichkeit sanft entrückt' },
  { word: 'Verve', pos: 'noun', definition: 'Mitreißender Schwung und Begeisterung' },
  { word: 'Verwegen', pos: 'adjective', definition: 'Kühn bis an die Grenze der Tollkühnheit' },
  { word: 'Verweilen', pos: 'verb', definition: 'An einem Ort bewusst länger bleiben' },
  { word: 'Verwunschen', pos: 'adjective', definition: 'Wie im Märchen verzaubert und entlegen' },
  { word: 'Verzückung', pos: 'noun', definition: 'Zustand höchster Entrückung und Freude' },
  { word: 'Vielsagend', pos: 'adjective', definition: 'Mehr andeutend als aussprechend' },
  { word: 'Vielschichtig', pos: 'adjective', definition: 'Aus vielen Bedeutungsebenen bestehend' },
  { word: 'Virtuos', pos: 'adjective', definition: 'Mit höchster technischer Meisterschaft' },
  { word: 'Visionär', pos: 'adjective', definition: 'Weit in die Zukunft vorausblickend' },
  { word: 'Volksmund', pos: 'noun', definition: 'Überlieferte Redeweise der einfachen Leute' },
  { word: 'Vollends', pos: 'adverb', definition: 'Ganz und gar, völlig' },
  { word: 'Vollmundig', pos: 'adjective', definition: 'Großspurig und viel versprechend' },
  { word: 'Vorbote', pos: 'noun', definition: 'Erstes Anzeichen kommender Ereignisse' },
  { word: 'Vorfreude', pos: 'noun', definition: 'Beglückende Erwartung eines schönen Ereignisses' },
  { word: 'Vortrefflich', pos: 'adjective', definition: 'Ausgezeichnet und über alles Lob erhaben' },
  { word: 'Vorwitzig', pos: 'adjective', definition: 'Neugierig-keck und etwas zu dreist' },
  { word: 'Wagemut', pos: 'noun', definition: 'Freudige Bereitschaft zum Wagnis' },
  { word: 'Wagnis', pos: 'noun', definition: 'Kühnes, riskantes Unterfangen' },
  { word: 'Wahlverwandtschaft', pos: 'noun', definition: 'Tiefe Verbundenheit aus freier Wahl' },
  { word: 'Wähnen', pos: 'verb', definition: 'Irrtümlich fest glauben' },
  { word: 'Waldeinsamkeit', pos: 'noun', definition: 'Stille, weltferne Einsamkeit des Waldes' },
  { word: 'Wanderlust', pos: 'noun', definition: 'Freude und Drang am Wandern' },
  { word: 'Wankelmut', pos: 'noun', definition: 'Unbeständigkeit im Wollen und Fühlen' },
  { word: 'Wehmut', pos: 'noun', definition: 'Sanfte Trauer über Vergangenes' },
  { word: 'Weitläufig', pos: 'adjective', definition: 'Ausgedehnt und großzügig angelegt' },
  { word: 'Weitsichtig', pos: 'adjective', definition: 'Kommende Entwicklungen klug bedenkend' },
  { word: 'Weltenbummler', pos: 'noun', definition: 'Unermüdlicher Reisender durch alle Länder' },
  { word: 'Weltgewandt', pos: 'adjective', definition: 'Sicher und geschliffen auf jedem Parkett' },
  { word: 'Weltschmerz', pos: 'noun', definition: 'Schwermut über die Unzulänglichkeit der Welt' },
  { word: 'Wesenszug', pos: 'noun', definition: 'Prägende Eigenschaft des Charakters' },
  { word: 'Wetteifern', pos: 'verb', definition: 'Sich mit anderen im Guten messen' },
  { word: 'Wettern', pos: 'verb', definition: 'Laut und heftig schimpfen' },
  { word: 'Widerhall', pos: 'noun', definition: 'Echo und aufgenommene Resonanz' },
  { word: 'Windschief', pos: 'adjective', definition: 'Schief und krumm verzogen' },
  { word: 'Wispern', pos: 'verb', definition: 'Ganz leise und geheimnisvoll flüstern' },
  { word: 'Wissbegierig', pos: 'adjective', definition: 'Voller Durst nach neuem Wissen' },
  { word: 'Wohlgemerkt', pos: 'adverb', definition: 'Das sei ausdrücklich betont' },
  { word: 'Wohlklang', pos: 'noun', definition: 'Angenehm harmonischer Klang' },
  { word: 'Wohlweislich', pos: 'adverb', definition: 'Aus gutem Grund und mit Bedacht' },
  { word: 'Wohlwollen', pos: 'noun', definition: 'Freundlich gesonnene Zuneigung' },
  { word: 'Wonne', pos: 'noun', definition: 'Tiefes, inniges Vergnügen' },
  { word: 'Wortgewandt', pos: 'adjective', definition: 'Geschickt und sicher im Ausdruck' },
  { word: 'Wortkarg', pos: 'adjective', definition: 'Nur wenige Worte machend' },
  { word: 'Wortwitz', pos: 'noun', definition: 'Geistreiches Spiel mit Worten' },
  { word: 'Wunderlich', pos: 'adjective', definition: 'Seltsam und schrullig geworden' },
  { word: 'Wundersam', pos: 'adjective', definition: 'Auf geheimnisvolle Weise erstaunlich' },
  { word: 'Zaghaft', pos: 'adjective', definition: 'Schüchtern zögernd und ängstlich' },
  { word: 'Zartbesaitet', pos: 'adjective', definition: 'Sehr empfindsam und leicht verletzlich' },
  { word: 'Zäsur', pos: 'noun', definition: 'Deutlicher Einschnitt in einem Verlauf' },
  { word: 'Zaudern', pos: 'verb', definition: 'Unschlüssig zögern und schwanken' },
  { word: 'Zeitgeist', pos: 'noun', definition: 'Denk- und Fühlweise einer Epoche' },
  { word: 'Zeitlebens', pos: 'adverb', definition: 'Das ganze Leben hindurch' },
  { word: 'Zeitvertreib', pos: 'noun', definition: 'Angenehme Beschäftigung gegen die Langeweile' },
  { word: 'Zelebrieren', pos: 'verb', definition: 'Etwas feierlich und genussvoll begehen' },
  { word: 'Zenit', pos: 'noun', definition: 'Höchster Punkt einer Entwicklung' },
  { word: 'Zerstreuung', pos: 'noun', definition: 'Leichte Unterhaltung und Ablenkung' },
  { word: 'Zetern', pos: 'verb', definition: 'Laut klagend schimpfen' },
  { word: 'Zierde', pos: 'noun', definition: 'Etwas, das schmückt und Ehre macht' },
  { word: 'Zugzwang', pos: 'noun', definition: 'Zwang, handeln zu müssen' },
  { word: 'Zuhauf', pos: 'adverb', definition: 'In großer Menge und Zahl' },
  { word: 'Zukunftsmusik', pos: 'noun', definition: 'Schöne Pläne in weiter Ferne' },
  { word: 'Zusehends', pos: 'adverb', definition: 'Sichtbar rasch, von Mal zu Mal mehr' },
  { word: 'Zuversicht', pos: 'noun', definition: 'Festes Vertrauen auf Gutes im Kommenden' },
  { word: 'Zuvorkommend', pos: 'adjective', definition: 'Aufmerksam höflich und gefällig' },
  { word: 'Zwanglos', pos: 'adjective', definition: 'Frei von Förmlichkeit' },
  { word: 'Zweisamkeit', pos: 'noun', definition: 'Trautes Beisammensein zu zweit' },
  { word: 'Zwiegespalten', pos: 'adjective', definition: 'Innerlich uneins zwischen zwei Neigungen' },
  { word: 'Zwiegespräch', pos: 'noun', definition: 'Vertrauliches Gespräch unter vier Augen' },
  { word: 'Zwielichtig', pos: 'adjective', definition: 'Undurchsichtig und von zweifelhaftem Ruf' },
  { word: 'Zynisch', pos: 'adjective', definition: 'Bitter spöttisch und ohne Achtung vor Gefühlen' },
];
