import type { WordEntry } from './types';

/**
 * en-US "Word of the Day" seed list — 732 entries (2 × 366) so the
 * selection cycle in word-of-day-data.ts covers two full years without
 * a repeat. Kept alphabetized: presentation order comes from the
 * year-seeded shuffle, so storage order is purely for maintenance
 * (duplicates land adjacent and diffs stay readable).
 */
export const EN_US_WORDS: WordEntry[] = [
  { word: 'Abate', pos: 'verb', definition: 'To become less intense or widespread' },
  { word: 'Aberration', pos: 'noun', definition: 'A departure from what is normal or expected' },
  { word: 'Abeyance', pos: 'noun', definition: 'A state of temporary disuse or suspension' },
  { word: 'Abscond', pos: 'verb', definition: 'To leave hurriedly and secretly, typically to avoid detection' },
  { word: 'Abstemious', pos: 'adjective', definition: 'Not self-indulgent, especially with food and drink' },
  { word: 'Abstruse', pos: 'adjective', definition: 'Difficult to understand; obscure' },
  { word: 'Accolade', pos: 'noun', definition: 'An award or privilege granted as special honor' },
  { word: 'Acerbic', pos: 'adjective', definition: 'Sharp and forthright in tone or wit' },
  { word: 'Acquiesce', pos: 'verb', definition: 'To accept something reluctantly but without protest' },
  { word: 'Acumen', pos: 'noun', definition: 'The ability to make good judgments and quick decisions' },
  { word: 'Adage', pos: 'noun', definition: 'A proverb or short statement expressing a general truth' },
  { word: 'Adamant', pos: 'adjective', definition: 'Refusing to be persuaded or to change one\'s mind' },
  { word: 'Adept', pos: 'adjective', definition: 'Very skilled or proficient at something' },
  { word: 'Admonish', pos: 'verb', definition: 'To warn or reprimand someone firmly but kindly' },
  { word: 'Adroit', pos: 'adjective', definition: 'Clever or skillful in using the hands or mind' },
  { word: 'Adulation', pos: 'noun', definition: 'Excessive admiration or praise' },
  { word: 'Aegis', pos: 'noun', definition: 'The protection, backing, or support of a person or thing' },
  { word: 'Aesthete', pos: 'noun', definition: 'A person with special appreciation of art and beauty' },
  { word: 'Affable', pos: 'adjective', definition: 'Friendly, good-natured, and easy to talk to' },
  { word: 'Affinity', pos: 'noun', definition: 'A natural liking for or attraction to something' },
  { word: 'Aggrandize', pos: 'verb', definition: 'To increase the power, status, or wealth of something' },
  { word: 'Akimbo', pos: 'adverb', definition: 'With hands on the hips and elbows turned outward' },
  { word: 'Alacrity', pos: 'noun', definition: 'Brisk and cheerful readiness' },
  { word: 'Albatross', pos: 'noun', definition: 'A burden that prevents success; a source of guilt' },
  { word: 'Alchemy', pos: 'noun', definition: 'A seemingly magical process of transformation or creation' },
  { word: 'Alfresco', pos: 'adverb', definition: 'In the open air; outdoors' },
  { word: 'Allay', pos: 'verb', definition: 'To diminish or put to rest fear, suspicion, or worry' },
  { word: 'Aloft', pos: 'adverb', definition: 'Up in or into the air; overhead' },
  { word: 'Altruism', pos: 'noun', definition: 'Selfless concern for the well-being of others' },
  { word: 'Amalgam', pos: 'noun', definition: 'A mixture or blend of different elements' },
  { word: 'Ambivalent', pos: 'adjective', definition: 'Having mixed feelings or contradictory ideas about something' },
  { word: 'Ameliorate', pos: 'verb', definition: 'To make something bad or unsatisfactory better' },
  { word: 'Amiable', pos: 'adjective', definition: 'Having a friendly and pleasant manner' },
  { word: 'Amorphous', pos: 'adjective', definition: 'Without a clearly defined shape or form' },
  { word: 'Anachronism', pos: 'noun', definition: 'Something that belongs to a different period of time' },
  { word: 'Anathema', pos: 'noun', definition: 'Something or someone that one vehemently dislikes' },
  { word: 'Anodyne', pos: 'adjective', definition: 'Unlikely to provoke offense; inoffensively bland' },
  { word: 'Antediluvian', pos: 'adjective', definition: 'Ridiculously old-fashioned; extremely ancient' },
  { word: 'Aphorism', pos: 'noun', definition: 'A pithy observation that contains a general truth' },
  { word: 'Aplomb', pos: 'noun', definition: 'Self-confidence or assurance, especially in a demanding situation' },
  { word: 'Apocryphal', pos: 'adjective', definition: 'Of doubtful authenticity, although widely circulated as true' },
  { word: 'Apogee', pos: 'noun', definition: 'The highest point in the development of something' },
  { word: 'Apotheosis', pos: 'noun', definition: 'The highest point or culmination; glorification' },
  { word: 'Apricity', pos: 'noun', definition: 'The warmth of the sun in winter' },
  { word: 'Arabesque', pos: 'noun', definition: 'An ornamental design of intertwined flowing lines' },
  { word: 'Arboreal', pos: 'adjective', definition: 'Living in or relating to trees' },
  { word: 'Arcane', pos: 'adjective', definition: 'Understood by few; mysterious or secret' },
  { word: 'Ardent', pos: 'adjective', definition: 'Enthusiastic or passionate' },
  { word: 'Ardor', pos: 'noun', definition: 'Enthusiasm or passion' },
  { word: 'Arduous', pos: 'adjective', definition: 'Involving strenuous effort; difficult and tiring' },
  { word: 'Argot', pos: 'noun', definition: 'The jargon or slang of a particular group' },
  { word: 'Ascendant', pos: 'adjective', definition: 'Rising in power or influence' },
  { word: 'Ascetic', pos: 'adjective', definition: 'Characterized by severe self-discipline and abstention' },
  { word: 'Assiduous', pos: 'adjective', definition: 'Showing great care, attention, and effort' },
  { word: 'Assuage', pos: 'verb', definition: 'To make an unpleasant feeling less intense' },
  { word: 'Astute', pos: 'adjective', definition: 'Having the ability to accurately assess situations to one\'s advantage' },
  { word: 'Atavistic', pos: 'adjective', definition: 'Relating to something ancient or ancestral' },
  { word: 'Atelier', pos: 'noun', definition: 'A workshop or studio, especially of an artist or designer' },
  { word: 'Attenuate', pos: 'verb', definition: 'To reduce the force, effect, or value of something' },
  { word: 'Audacious', pos: 'adjective', definition: 'Showing a willingness to take surprisingly bold risks' },
  { word: 'Aurora', pos: 'noun', definition: 'The dawn; a natural display of colored light in the sky' },
  { word: 'Auspicious', pos: 'adjective', definition: 'Indicating a good chance of success; favorable' },
  { word: 'Austere', pos: 'adjective', definition: 'Severe or strict in manner; markedly simple' },
  { word: 'Avarice', pos: 'noun', definition: 'Extreme greed for wealth or material gain' },
  { word: 'Avuncular', pos: 'adjective', definition: 'Kind and friendly toward a younger person, like an uncle' },
  { word: 'Awry', pos: 'adverb', definition: 'Away from the expected course; amiss' },
  { word: 'Azure', pos: 'adjective', definition: 'Bright blue in color, like a cloudless sky' },
  { word: 'Badinage', pos: 'noun', definition: 'Humorous or witty conversation' },
  { word: 'Balustrade', pos: 'noun', definition: 'A railing supported by ornamental posts' },
  { word: 'Bask', pos: 'verb', definition: 'To revel in and make the most of something pleasing' },
  { word: 'Bastion', pos: 'noun', definition: 'An institution or place that strongly defends a principle' },
  { word: 'Beatific', pos: 'adjective', definition: 'Feeling or expressing blissful happiness' },
  { word: 'Beguile', pos: 'verb', definition: 'To charm or enchant, sometimes deceptively' },
  { word: 'Behemoth', pos: 'noun', definition: 'Something enormous in size or power' },
  { word: 'Beholden', pos: 'adjective', definition: 'Owing thanks or a debt for a service or favor' },
  { word: 'Belie', pos: 'verb', definition: 'To fail to give a true impression of something' },
  { word: 'Bellwether', pos: 'noun', definition: 'Something that leads or indicates a trend' },
  { word: 'Benediction', pos: 'noun', definition: 'The utterance of a blessing' },
  { word: 'Benefactor', pos: 'noun', definition: 'A person who gives help, especially financial, to a cause' },
  { word: 'Benevolent', pos: 'adjective', definition: 'Well-meaning and kindly' },
  { word: 'Bequeath', pos: 'verb', definition: 'To pass something on or leave it to someone' },
  { word: 'Bereft', pos: 'adjective', definition: 'Deprived of or lacking something' },
  { word: 'Beseech', pos: 'verb', definition: 'To ask someone urgently and fervently' },
  { word: 'Bespoke', pos: 'adjective', definition: 'Made to order for a particular customer' },
  { word: 'Bibliophile', pos: 'noun', definition: 'A person who collects or greatly loves books' },
  { word: 'Blithe', pos: 'adjective', definition: 'Showing a casual and cheerful indifference' },
  { word: 'Bombastic', pos: 'adjective', definition: 'High-sounding but with little meaning; inflated' },
  { word: 'Bonhomie', pos: 'noun', definition: 'Cheerful friendliness; geniality' },
  { word: 'Bosky', pos: 'adjective', definition: 'Covered by trees or bushes; wooded' },
  { word: 'Bountiful', pos: 'adjective', definition: 'Given or giving generously; abundant' },
  { word: 'Bravado', pos: 'noun', definition: 'A bold manner intended to impress or intimidate' },
  { word: 'Bravura', pos: 'noun', definition: 'Great technical skill and brilliance in a performance' },
  { word: 'Brio', pos: 'noun', definition: 'Vigor or vivacity of style or performance' },
  { word: 'Brusque', pos: 'adjective', definition: 'Abrupt or offhand in speech or manner' },
  { word: 'Bucolic', pos: 'adjective', definition: 'Relating to the pleasant aspects of the countryside' },
  { word: 'Bulwark', pos: 'noun', definition: 'A defensive wall; a person or thing that protects' },
  { word: 'Buoyant', pos: 'adjective', definition: 'Cheerful and optimistic; able to stay afloat' },
  { word: 'Burgeon', pos: 'verb', definition: 'To begin to grow or increase rapidly; flourish' },
  { word: 'Burnish', pos: 'verb', definition: 'To polish something until it shines; to enhance' },
  { word: 'Byzantine', pos: 'adjective', definition: 'Excessively complicated and detailed' },
  { word: 'Cacophony', pos: 'noun', definition: 'A harsh, discordant mixture of sounds' },
  { word: 'Cadence', pos: 'noun', definition: 'A rhythmic flow of sounds or words' },
  { word: 'Cajole', pos: 'verb', definition: 'To persuade someone by sustained coaxing or flattery' },
  { word: 'Callow', pos: 'adjective', definition: 'Inexperienced and immature' },
  { word: 'Camaraderie', pos: 'noun', definition: 'Mutual trust and friendship among people who spend time together' },
  { word: 'Candor', pos: 'noun', definition: 'The quality of being open and honest; frankness' },
  { word: 'Canny', pos: 'adjective', definition: 'Having or showing shrewdness, especially in practical matters' },
  { word: 'Capacious', pos: 'adjective', definition: 'Having a lot of space inside; roomy' },
  { word: 'Capitulate', pos: 'verb', definition: 'To cease to resist; to surrender' },
  { word: 'Capricious', pos: 'adjective', definition: 'Given to sudden and unaccountable changes of mood' },
  { word: 'Cardinal', pos: 'adjective', definition: 'Of the greatest importance; fundamental' },
  { word: 'Carouse', pos: 'verb', definition: 'To drink alcohol and enjoy oneself with others noisily' },
  { word: 'Cascade', pos: 'noun', definition: 'A small waterfall, or a succession of stages' },
  { word: 'Castigate', pos: 'verb', definition: 'To reprimand someone severely' },
  { word: 'Catalyst', pos: 'noun', definition: 'Something that precipitates an event or change' },
  { word: 'Catharsis', pos: 'noun', definition: 'The release of pent-up emotions, bringing relief' },
  { word: 'Cavalcade', pos: 'noun', definition: 'A formal procession of people on horseback or in vehicles' },
  { word: 'Cavort', pos: 'verb', definition: 'To jump or dance around excitedly' },
  { word: 'Celerity', pos: 'noun', definition: 'Swiftness of movement' },
  { word: 'Celestial', pos: 'adjective', definition: 'Belonging or relating to the sky or heavens' },
  { word: 'Cerulean', pos: 'adjective', definition: 'Deep sky blue in color' },
  { word: 'Chagrin', pos: 'noun', definition: 'Distress caused by having failed or been humiliated' },
  { word: 'Chicanery', pos: 'noun', definition: 'The use of trickery to achieve a purpose' },
  { word: 'Chimera', pos: 'noun', definition: 'A thing hoped for but illusory or impossible to achieve' },
  { word: 'Chivalrous', pos: 'adjective', definition: 'Courteous and gallant, especially toward others in need' },
  { word: 'Chrysalis', pos: 'noun', definition: 'A transitional state of growth or development' },
  { word: 'Circumspect', pos: 'adjective', definition: 'Wary and unwilling to take risks; cautious' },
  { word: 'Citadel', pos: 'noun', definition: 'A fortress protecting a city; a stronghold' },
  { word: 'Clairvoyant', pos: 'adjective', definition: 'Having perception beyond the ordinary senses' },
  { word: 'Clandestine', pos: 'adjective', definition: 'Kept secret or done secretively' },
  { word: 'Clarion', pos: 'adjective', definition: 'Loud and clear, like a rallying call' },
  { word: 'Clemency', pos: 'noun', definition: 'Mercy or lenience shown toward an offender' },
  { word: 'Cloister', pos: 'verb', definition: 'To seclude or shut away from the world' },
  { word: 'Coalesce', pos: 'verb', definition: 'To come together to form one mass or whole' },
  { word: 'Cogent', pos: 'adjective', definition: 'Clear, logical, and convincing' },
  { word: 'Cogitate', pos: 'verb', definition: 'To think deeply about something; meditate' },
  { word: 'Colloquial', pos: 'adjective', definition: 'Used in ordinary or familiar conversation' },
  { word: 'Colossus', pos: 'noun', definition: 'A person or thing of enormous size or importance' },
  { word: 'Comity', pos: 'noun', definition: 'Courtesy and considerate behavior toward others' },
  { word: 'Commensurate', pos: 'adjective', definition: 'Corresponding in size or degree; in proportion' },
  { word: 'Compendium', pos: 'noun', definition: 'A collection of concise but detailed information' },
  { word: 'Conciliatory', pos: 'adjective', definition: 'Intended to placate or pacify' },
  { word: 'Concomitant', pos: 'adjective', definition: 'Naturally accompanying or associated' },
  { word: 'Confluence', pos: 'noun', definition: 'The junction of two rivers; a coming together' },
  { word: 'Congenial', pos: 'adjective', definition: 'Pleasant because suited to one\'s taste or nature' },
  { word: 'Connoisseur', pos: 'noun', definition: 'An expert judge in matters of taste' },
  { word: 'Consecrate', pos: 'verb', definition: 'To make or declare something sacred' },
  { word: 'Consonance', pos: 'noun', definition: 'Agreement or compatibility between things' },
  { word: 'Constellation', pos: 'noun', definition: 'A group of associated or similar things' },
  { word: 'Consummate', pos: 'adjective', definition: 'Showing supreme mastery or skill' },
  { word: 'Contemplative', pos: 'adjective', definition: 'Expressing or involving prolonged thought' },
  { word: 'Contretemps', pos: 'noun', definition: 'A minor dispute or an unforeseen mishap' },
  { word: 'Contrite', pos: 'adjective', definition: 'Feeling or expressing remorse' },
  { word: 'Conundrum', pos: 'noun', definition: 'A confusing and difficult problem or question' },
  { word: 'Convivial', pos: 'adjective', definition: 'Friendly, lively, and enjoyable' },
  { word: 'Copacetic', pos: 'adjective', definition: 'In excellent order; completely satisfactory' },
  { word: 'Copious', pos: 'adjective', definition: 'Abundant in supply or quantity' },
  { word: 'Cornucopia', pos: 'noun', definition: 'An abundant supply of good things' },
  { word: 'Coruscate', pos: 'verb', definition: 'To flash or sparkle with light' },
  { word: 'Cosmopolitan', pos: 'adjective', definition: 'At home in and familiar with many different countries and cultures' },
  { word: 'Cosset', pos: 'verb', definition: 'To care for and protect in an overindulgent way' },
  { word: 'Coterie', pos: 'noun', definition: 'A small group of people with shared interests' },
  { word: 'Countenance', pos: 'noun', definition: 'A person\'s face or facial expression' },
  { word: 'Crepuscular', pos: 'adjective', definition: 'Relating to or resembling twilight' },
  { word: 'Crescendo', pos: 'noun', definition: 'A progressive increase in intensity, reaching a climax' },
  { word: 'Cryptic', pos: 'adjective', definition: 'Having a meaning that is mysterious or obscure' },
  { word: 'Culminate', pos: 'verb', definition: 'To reach a climax or point of highest development' },
  { word: 'Cultivate', pos: 'verb', definition: 'To try to develop or improve a quality or skill' },
  { word: 'Cynosure', pos: 'noun', definition: 'A person or thing that is the center of attention' },
  { word: 'Dalliance', pos: 'noun', definition: 'A casual romantic or brief involvement with something' },
  { word: 'Dapple', pos: 'verb', definition: 'To mark with spots of color, light, or shade' },
  { word: 'Dauntless', pos: 'adjective', definition: 'Showing fearlessness and determination' },
  { word: 'Dearth', pos: 'noun', definition: 'A scarcity or lack of something' },
  { word: 'Debonair', pos: 'adjective', definition: 'Confident, stylish, and charming' },
  { word: 'Decorous', pos: 'adjective', definition: 'In keeping with good taste and propriety' },
  { word: 'Decorum', pos: 'noun', definition: 'Behavior in keeping with good taste and propriety' },
  { word: 'Defenestration', pos: 'noun', definition: 'The act of throwing someone or something out of a window' },
  { word: 'Deference', pos: 'noun', definition: 'Humble submission and respect' },
  { word: 'Deft', pos: 'adjective', definition: 'Neatly skillful and quick in movement' },
  { word: 'Deleterious', pos: 'adjective', definition: 'Causing harm or damage' },
  { word: 'Deliberate', pos: 'verb', definition: 'To engage in long and careful consideration' },
  { word: 'Delineate', pos: 'verb', definition: 'To describe or portray something precisely' },
  { word: 'Deluge', pos: 'noun', definition: 'A great flood; an overwhelming quantity of something' },
  { word: 'Demarcate', pos: 'verb', definition: 'To set the boundaries or limits of something' },
  { word: 'Demure', pos: 'adjective', definition: 'Reserved, modest, and shy' },
  { word: 'Denizen', pos: 'noun', definition: 'An inhabitant or occupant of a particular place' },
  { word: 'Denouement', pos: 'noun', definition: 'The final resolution of a story or situation' },
  { word: 'Desultory', pos: 'adjective', definition: 'Lacking a plan, purpose, or enthusiasm' },
  { word: 'Dexterous', pos: 'adjective', definition: 'Showing skill, especially with the hands' },
  { word: 'Diaphanous', pos: 'adjective', definition: 'Light, delicate, and translucent' },
  { word: 'Diatribe', pos: 'noun', definition: 'A forceful and bitter verbal attack' },
  { word: 'Dichotomy', pos: 'noun', definition: 'A division or contrast between two opposed things' },
  { word: 'Didactic', pos: 'adjective', definition: 'Intended to teach or instruct' },
  { word: 'Diffident', pos: 'adjective', definition: 'Modest or shy from a lack of self-confidence' },
  { word: 'Dilettante', pos: 'noun', definition: 'A person who cultivates an interest without real commitment' },
  { word: 'Diligent', pos: 'adjective', definition: 'Showing care and conscientiousness in work or duties' },
  { word: 'Discern', pos: 'verb', definition: 'To perceive or recognize something clearly' },
  { word: 'Disparate', pos: 'adjective', definition: 'Essentially different in kind; not comparable' },
  { word: 'Dissemble', pos: 'verb', definition: 'To conceal one\'s true motives or feelings' },
  { word: 'Dissonance', pos: 'noun', definition: 'A lack of harmony or agreement' },
  { word: 'Dovetail', pos: 'verb', definition: 'To fit or combine together neatly' },
  { word: 'Draconian', pos: 'adjective', definition: 'Excessively harsh and severe, especially of laws' },
  { word: 'Dulcet', pos: 'adjective', definition: 'Sweet and soothing to hear' },
  { word: 'Duplicity', pos: 'noun', definition: 'Deceitfulness; double-dealing' },
  { word: 'Dynamo', pos: 'noun', definition: 'An extremely energetic person' },
  { word: 'Ebullient', pos: 'adjective', definition: 'Cheerful and full of energy' },
  { word: 'Eclectic', pos: 'adjective', definition: 'Deriving ideas or style from a broad range of sources' },
  { word: 'Edify', pos: 'verb', definition: 'To instruct or improve someone morally or intellectually' },
  { word: 'Effervescent', pos: 'adjective', definition: 'Vivacious and enthusiastic; bubbling' },
  { word: 'Efficacious', pos: 'adjective', definition: 'Successful in producing a desired result' },
  { word: 'Effulgent', pos: 'adjective', definition: 'Shining brightly; radiant' },
  { word: 'Effusive', pos: 'adjective', definition: 'Expressing feelings of approval in an unrestrained way' },
  { word: 'Egalitarian', pos: 'adjective', definition: 'Believing in the equality of all people' },
  { word: 'Elan', pos: 'noun', definition: 'Energy, style, and enthusiasm' },
  { word: 'Elation', pos: 'noun', definition: 'Great happiness and exhilaration' },
  { word: 'Elegiac', pos: 'adjective', definition: 'Wistfully mournful, especially for what is past' },
  { word: 'Elegy', pos: 'noun', definition: 'A poem of serious reflection, typically a lament for the dead' },
  { word: 'Elixir', pos: 'noun', definition: 'A magical or medicinal potion; a remedy' },
  { word: 'Eloquent', pos: 'adjective', definition: 'Fluent or persuasive in speaking or writing' },
  { word: 'Elucidate', pos: 'verb', definition: 'To make something clear; to explain' },
  { word: 'Emanate', pos: 'verb', definition: 'To issue or spread out from a source' },
  { word: 'Embellish', pos: 'verb', definition: 'To make more attractive by adding decorative details' },
  { word: 'Embolden', pos: 'verb', definition: 'To give someone the courage or confidence to act' },
  { word: 'Eminent', pos: 'adjective', definition: 'Famous and respected within a particular sphere' },
  { word: 'Empirical', pos: 'adjective', definition: 'Based on observation or experience rather than theory' },
  { word: 'Emulate', pos: 'verb', definition: 'To match or surpass by imitation' },
  { word: 'Enamor', pos: 'verb', definition: 'To fill with a feeling of love or admiration' },
  { word: 'Enclave', pos: 'noun', definition: 'A distinct territory or group enclosed within a larger one' },
  { word: 'Encomium', pos: 'noun', definition: 'A speech or piece of writing that praises highly' },
  { word: 'Enervate', pos: 'verb', definition: 'To drain of energy or vitality' },
  { word: 'Engender', pos: 'verb', definition: 'To cause or give rise to a feeling or condition' },
  { word: 'Enigmatic', pos: 'adjective', definition: 'Difficult to interpret or understand; mysterious' },
  { word: 'Enliven', pos: 'verb', definition: 'To make something more entertaining or interesting' },
  { word: 'Ennui', pos: 'noun', definition: 'Listlessness arising from a lack of excitement' },
  { word: 'Enthrall', pos: 'verb', definition: 'To capture the fascinated attention of someone' },
  { word: 'Ephemeral', pos: 'adjective', definition: 'Lasting for a very short time' },
  { word: 'Epicure', pos: 'noun', definition: 'A person who takes particular pleasure in fine food and drink' },
  { word: 'Epiphany', pos: 'noun', definition: 'A moment of sudden and great revelation' },
  { word: 'Epitome', pos: 'noun', definition: 'A perfect example of a quality or type' },
  { word: 'Equanimity', pos: 'noun', definition: 'Mental calmness and composure in a difficult situation' },
  { word: 'Equinox', pos: 'noun', definition: 'The time when day and night are of equal length' },
  { word: 'Equipoise', pos: 'noun', definition: 'A state of balance between opposing forces' },
  { word: 'Equivocate', pos: 'verb', definition: 'To use ambiguous language to conceal the truth' },
  { word: 'Erstwhile', pos: 'adjective', definition: 'Former; of a previous time' },
  { word: 'Erudite', pos: 'adjective', definition: 'Having or showing great knowledge or learning' },
  { word: 'Eschew', pos: 'verb', definition: 'To deliberately avoid or abstain from' },
  { word: 'Esoteric', pos: 'adjective', definition: 'Intended for or understood by only a small group' },
  { word: 'Espouse', pos: 'verb', definition: 'To adopt or support a cause or belief' },
  { word: 'Esprit', pos: 'noun', definition: 'Liveliness of mind and expression; wit' },
  { word: 'Estimable', pos: 'adjective', definition: 'Worthy of great respect' },
  { word: 'Ethereal', pos: 'adjective', definition: 'Extremely delicate and light, seeming heavenly' },
  { word: 'Euphonious', pos: 'adjective', definition: 'Pleasing to the ear' },
  { word: 'Euphoria', pos: 'noun', definition: 'A feeling of intense excitement and happiness' },
  { word: 'Evanescent', pos: 'adjective', definition: 'Soon passing out of sight or memory; fleeting' },
  { word: 'Evince', pos: 'verb', definition: 'To reveal the presence of a quality or feeling' },
  { word: 'Evocative', pos: 'adjective', definition: 'Bringing strong images or feelings to mind' },
  { word: 'Exalt', pos: 'verb', definition: 'To hold in very high regard; to praise' },
  { word: 'Exemplary', pos: 'adjective', definition: 'Serving as a desirable model; outstanding' },
  { word: 'Exhilarate', pos: 'verb', definition: 'To make someone feel very happy and animated' },
  { word: 'Exigent', pos: 'adjective', definition: 'Pressing; demanding immediate attention' },
  { word: 'Exonerate', pos: 'verb', definition: 'To absolve from blame' },
  { word: 'Expedient', pos: 'adjective', definition: 'Convenient and practical, if perhaps improper' },
  { word: 'Exquisite', pos: 'adjective', definition: 'Extremely beautiful and delicate' },
  { word: 'Extemporize', pos: 'verb', definition: 'To compose or perform without preparation; improvise' },
  { word: 'Extol', pos: 'verb', definition: 'To praise enthusiastically' },
  { word: 'Exuberant', pos: 'adjective', definition: 'Filled with lively energy and excitement' },
  { word: 'Fabulist', pos: 'noun', definition: 'A teller of tales; a composer of fables' },
  { word: 'Facetious', pos: 'adjective', definition: 'Treating serious issues with deliberately inappropriate humor' },
  { word: 'Fanfare', pos: 'noun', definition: 'A showy display or celebratory flourish' },
  { word: 'Fastidious', pos: 'adjective', definition: 'Very attentive to accuracy and detail' },
  { word: 'Fathom', pos: 'verb', definition: 'To understand after much thought' },
  { word: 'Fecund', pos: 'adjective', definition: 'Highly fertile; producing much new growth' },
  { word: 'Felicity', pos: 'noun', definition: 'Intense happiness; the ability to find fitting expression' },
  { word: 'Fervent', pos: 'adjective', definition: 'Having or displaying passionate intensity' },
  { word: 'Festoon', pos: 'verb', definition: 'To adorn with chains, garlands, or decorations' },
  { word: 'Fidelity', pos: 'noun', definition: 'Faithfulness; the degree of exactness of a copy' },
  { word: 'Filigree', pos: 'noun', definition: 'Delicate ornamental work of fine wire or lines' },
  { word: 'Finesse', pos: 'noun', definition: 'Refined delicacy and skill in handling a situation' },
  { word: 'Firmament', pos: 'noun', definition: 'The heavens or the sky' },
  { word: 'Flabbergast', pos: 'verb', definition: 'To surprise someone greatly; astonish' },
  { word: 'Flourish', pos: 'verb', definition: 'To grow or develop in a healthy, vigorous way' },
  { word: 'Foible', pos: 'noun', definition: 'A minor weakness or eccentricity in character' },
  { word: 'Foray', pos: 'noun', definition: 'A brief attempt to become involved in a new activity' },
  { word: 'Forbearance', pos: 'noun', definition: 'Patient self-control and restraint' },
  { word: 'Formidable', pos: 'adjective', definition: 'Inspiring respect through being impressively capable' },
  { word: 'Fortitude', pos: 'noun', definition: 'Courage in pain or adversity' },
  { word: 'Fortuitous', pos: 'adjective', definition: 'Happening by a lucky chance' },
  { word: 'Frisson', pos: 'noun', definition: 'A sudden thrill of excitement or fear' },
  { word: 'Frolic', pos: 'verb', definition: 'To play and move about cheerfully' },
  { word: 'Fruition', pos: 'noun', definition: 'The point at which a plan or project is realized' },
  { word: 'Fugacious', pos: 'adjective', definition: 'Tending to disappear; fleeting' },
  { word: 'Furtive', pos: 'adjective', definition: 'Attempting to avoid notice; secretive' },
  { word: 'Gallant', pos: 'adjective', definition: 'Brave and heroic; courteously attentive' },
  { word: 'Galvanize', pos: 'verb', definition: 'To shock or excite someone into taking action' },
  { word: 'Gambol', pos: 'verb', definition: 'To run or jump about playfully' },
  { word: 'Garner', pos: 'verb', definition: 'To gather or collect something, especially approval' },
  { word: 'Garrulous', pos: 'adjective', definition: 'Excessively talkative, especially on trivial matters' },
  { word: 'Germane', pos: 'adjective', definition: 'Relevant to a subject under consideration' },
  { word: 'Gilded', pos: 'adjective', definition: 'Covered thinly with gold; wealthy and privileged' },
  { word: 'Gingerly', pos: 'adverb', definition: 'In a careful or cautious manner' },
  { word: 'Glean', pos: 'verb', definition: 'To gather information or material bit by bit' },
  { word: 'Gloaming', pos: 'noun', definition: 'Twilight; dusk' },
  { word: 'Gossamer', pos: 'noun', definition: 'Something very light, thin, and insubstantial' },
  { word: 'Grandeur', pos: 'noun', definition: 'Splendor and impressiveness, especially of appearance' },
  { word: 'Grandiloquent', pos: 'adjective', definition: 'Pompous or extravagant in language or style' },
  { word: 'Gravitas', pos: 'noun', definition: 'Dignity, seriousness, or solemnity of manner' },
  { word: 'Gregarious', pos: 'adjective', definition: 'Fond of company; sociable' },
  { word: 'Guile', pos: 'noun', definition: 'Sly or cunning intelligence' },
  { word: 'Gumption', pos: 'noun', definition: 'Shrewd, spirited initiative and resourcefulness' },
  { word: 'Gusto', pos: 'noun', definition: 'Enjoyment and enthusiasm in doing something' },
  { word: 'Halcyon', pos: 'adjective', definition: 'Denoting a period of time that was idyllically happy and peaceful' },
  { word: 'Hale', pos: 'adjective', definition: 'Strong and healthy, especially in old age' },
  { word: 'Hallowed', pos: 'adjective', definition: 'Made holy; greatly revered' },
  { word: 'Harbinger', pos: 'noun', definition: 'A person or thing that signals the approach of another' },
  { word: 'Haven', pos: 'noun', definition: 'A place of safety or refuge' },
  { word: 'Headlong', pos: 'adverb', definition: 'With reckless haste; head first' },
  { word: 'Hearten', pos: 'verb', definition: 'To make more cheerful or confident' },
  { word: 'Hegemony', pos: 'noun', definition: 'Leadership or dominance over others' },
  { word: 'Herculean', pos: 'adjective', definition: 'Requiring great strength or effort' },
  { word: 'Heterodox', pos: 'adjective', definition: 'Not conforming with accepted standards or beliefs' },
  { word: 'Heuristic', pos: 'adjective', definition: 'Enabling a person to discover or learn for themselves' },
  { word: 'Heyday', pos: 'noun', definition: 'The period of a person\'s or thing\'s greatest success' },
  { word: 'Hiatus', pos: 'noun', definition: 'A pause or gap in a sequence or process' },
  { word: 'Hinterland', pos: 'noun', definition: 'The remote areas of a region away from cities' },
  { word: 'Histrionic', pos: 'adjective', definition: 'Overly theatrical or melodramatic' },
  { word: 'Holistic', pos: 'adjective', definition: 'Considering the whole rather than just the parts' },
  { word: 'Homage', pos: 'noun', definition: 'Special honor or respect shown publicly' },
  { word: 'Hone', pos: 'verb', definition: 'To refine or perfect a skill over time' },
  { word: 'Hubris', pos: 'noun', definition: 'Excessive pride or self-confidence' },
  { word: 'Husbandry', pos: 'noun', definition: 'Careful management and conservation of resources' },
  { word: 'Hyperbole', pos: 'noun', definition: 'Exaggerated statements not meant to be taken literally' },
  { word: 'Iconoclast', pos: 'noun', definition: 'A person who attacks cherished beliefs or institutions' },
  { word: 'Idyllic', pos: 'adjective', definition: 'Extremely happy, peaceful, or picturesque' },
  { word: 'Ignominious', pos: 'adjective', definition: 'Deserving or causing public disgrace' },
  { word: 'Illustrious', pos: 'adjective', definition: 'Well known, respected, and admired for past achievements' },
  { word: 'Imbue', pos: 'verb', definition: 'To inspire or permeate with a feeling or quality' },
  { word: 'Immaculate', pos: 'adjective', definition: 'Perfectly clean, neat, or free from flaw' },
  { word: 'Immutable', pos: 'adjective', definition: 'Unchanging over time; unable to be changed' },
  { word: 'Impassioned', pos: 'adjective', definition: 'Filled with or showing great emotion' },
  { word: 'Impeccable', pos: 'adjective', definition: 'In accordance with the highest standards; faultless' },
  { word: 'Imperturbable', pos: 'adjective', definition: 'Unable to be upset or excited; calm' },
  { word: 'Impervious', pos: 'adjective', definition: 'Unable to be affected or penetrated' },
  { word: 'Impetus', pos: 'noun', definition: 'The force that makes something happen or move' },
  { word: 'Impish', pos: 'adjective', definition: 'Inclined to do slightly naughty things for fun; mischievous' },
  { word: 'Implacable', pos: 'adjective', definition: 'Unable to be appeased or placated' },
  { word: 'Impresario', pos: 'noun', definition: 'An organizer of concerts, plays, or grand ventures' },
  { word: 'Impromptu', pos: 'adjective', definition: 'Done without being planned or rehearsed' },
  { word: 'Incandescent', pos: 'adjective', definition: 'Emitting light as a result of being heated; passionate' },
  { word: 'Incantation', pos: 'noun', definition: 'A series of words said as a magic spell or charm' },
  { word: 'Inchoate', pos: 'adjective', definition: 'Just begun and not fully formed' },
  { word: 'Incisive', pos: 'adjective', definition: 'Intelligently analytical and clear-thinking' },
  { word: 'Incognito', pos: 'adverb', definition: 'With one\'s true identity concealed' },
  { word: 'Incongruous', pos: 'adjective', definition: 'Out of place; not in harmony with the surroundings' },
  { word: 'Indefatigable', pos: 'adjective', definition: 'Persisting tirelessly' },
  { word: 'Indelible', pos: 'adjective', definition: 'Making marks or memories that cannot be removed' },
  { word: 'Indomitable', pos: 'adjective', definition: 'Impossible to subdue or defeat' },
  { word: 'Ineffable', pos: 'adjective', definition: 'Too great or extreme to be expressed in words' },
  { word: 'Inexorable', pos: 'adjective', definition: 'Impossible to stop or prevent' },
  { word: 'Infuse', pos: 'verb', definition: 'To fill or pervade with a quality' },
  { word: 'Ingenuity', pos: 'noun', definition: 'The quality of being clever, original, and inventive' },
  { word: 'Ingenuous', pos: 'adjective', definition: 'Innocent, candid, and unsuspecting' },
  { word: 'Inimitable', pos: 'adjective', definition: 'So good or unique as to be impossible to copy' },
  { word: 'Inkling', pos: 'noun', definition: 'A slight knowledge or vague suspicion of something' },
  { word: 'Innate', pos: 'adjective', definition: 'Inborn; existing naturally from birth' },
  { word: 'Inquisitive', pos: 'adjective', definition: 'Eager for knowledge; curious' },
  { word: 'Insatiable', pos: 'adjective', definition: 'Impossible to satisfy' },
  { word: 'Inscrutable', pos: 'adjective', definition: 'Impossible to understand or interpret' },
  { word: 'Insouciant', pos: 'adjective', definition: 'Showing a casual lack of concern; carefree' },
  { word: 'Interlude', pos: 'noun', definition: 'An intervening period of time; a pause' },
  { word: 'Intrepid', pos: 'adjective', definition: 'Fearless and adventurous' },
  { word: 'Intrinsic', pos: 'adjective', definition: 'Belonging naturally; essential to the thing itself' },
  { word: 'Inure', pos: 'verb', definition: 'To accustom someone to something unpleasant' },
  { word: 'Inveterate', pos: 'adjective', definition: 'Having a long-established and unlikely-to-change habit' },
  { word: 'Invigorate', pos: 'verb', definition: 'To give strength or energy to' },
  { word: 'Irascible', pos: 'adjective', definition: 'Easily made angry; hot-tempered' },
  { word: 'Iridescent', pos: 'adjective', definition: 'Showing luminous colors that change when seen from different angles' },
  { word: 'Jaunty', pos: 'adjective', definition: 'Having a lively, cheerful, and self-confident manner' },
  { word: 'Jocular', pos: 'adjective', definition: 'Fond of or characterized by joking; humorous' },
  { word: 'Jovial', pos: 'adjective', definition: 'Cheerful and friendly' },
  { word: 'Jubilant', pos: 'adjective', definition: 'Feeling or expressing great happiness and triumph' },
  { word: 'Judicious', pos: 'adjective', definition: 'Having or showing good judgment' },
  { word: 'Juggernaut', pos: 'noun', definition: 'A huge, powerful, and overwhelming force' },
  { word: 'Juxtapose', pos: 'verb', definition: 'To place close together for contrasting effect' },
  { word: 'Kaleidoscope', pos: 'noun', definition: 'A constantly changing pattern or sequence of elements' },
  { word: 'Keepsake', pos: 'noun', definition: 'A small item kept in memory of the person who gave it' },
  { word: 'Kindle', pos: 'verb', definition: 'To arouse or inspire an emotion or feeling' },
  { word: 'Kinetic', pos: 'adjective', definition: 'Relating to or resulting from motion; energetic' },
  { word: 'Kismet', pos: 'noun', definition: 'Destiny; fate' },
  { word: 'Knack', pos: 'noun', definition: 'An acquired or natural skill at performing a task' },
  { word: 'Kudos', pos: 'noun', definition: 'Praise and honor received for an achievement' },
  { word: 'Labyrinthine', pos: 'adjective', definition: 'Like a labyrinth; irregular and twisting' },
  { word: 'Lachrymose', pos: 'adjective', definition: 'Tearful or given to weeping; inducing tears' },
  { word: 'Lackadaisical', pos: 'adjective', definition: 'Lacking enthusiasm and determination' },
  { word: 'Laconic', pos: 'adjective', definition: 'Using very few words' },
  { word: 'Lagniappe', pos: 'noun', definition: 'Something given as a bonus or unexpected gift' },
  { word: 'Lambent', pos: 'adjective', definition: 'Glowing or flickering with a soft radiance' },
  { word: 'Languid', pos: 'adjective', definition: 'Pleasantly relaxed and unhurried' },
  { word: 'Largesse', pos: 'noun', definition: 'Generosity in bestowing money or gifts' },
  { word: 'Lark', pos: 'noun', definition: 'Something done for fun, especially something mischievous' },
  { word: 'Lassitude', pos: 'noun', definition: 'A state of physical or mental weariness' },
  { word: 'Laudable', pos: 'adjective', definition: 'Deserving praise and commendation' },
  { word: 'Legerdemain', pos: 'noun', definition: 'Skillful use of one\'s hands in conjuring; trickery' },
  { word: 'Levity', pos: 'noun', definition: 'The treatment of a serious matter with humor' },
  { word: 'Lexicon', pos: 'noun', definition: 'The vocabulary of a person, language, or field' },
  { word: 'Lilt', pos: 'noun', definition: 'A characteristic rising and falling of the voice' },
  { word: 'Liminal', pos: 'adjective', definition: 'Occupying a position at, or on both sides of, a threshold' },
  { word: 'Limpid', pos: 'adjective', definition: 'Completely clear and transparent' },
  { word: 'Lionize', pos: 'verb', definition: 'To treat someone as a celebrity' },
  { word: 'Lissome', pos: 'adjective', definition: 'Thin, supple, and graceful' },
  { word: 'Lithe', pos: 'adjective', definition: 'Moving with graceful, flexible ease' },
  { word: 'Lodestar', pos: 'noun', definition: 'A star used for guidance; a source of inspiration' },
  { word: 'Loquacious', pos: 'adjective', definition: 'Tending to talk a great deal' },
  { word: 'Lucid', pos: 'adjective', definition: 'Expressed clearly; easy to understand' },
  { word: 'Luminous', pos: 'adjective', definition: 'Full of or shedding light; bright or shining' },
  { word: 'Luster', pos: 'noun', definition: 'A gentle sheen or soft glow; distinction' },
  { word: 'Luxuriant', pos: 'adjective', definition: 'Rich and profuse in growth; lush' },
  { word: 'Lyrical', pos: 'adjective', definition: 'Expressing emotion in an imaginative and beautiful way' },
  { word: 'Maelstrom', pos: 'noun', definition: 'A powerful whirlpool; a situation of confused movement' },
  { word: 'Magnanimous', pos: 'adjective', definition: 'Generous or forgiving, especially toward a rival' },
  { word: 'Malaise', pos: 'noun', definition: 'A general feeling of discomfort or unease' },
  { word: 'Malleable', pos: 'adjective', definition: 'Easily shaped; adaptable' },
  { word: 'Manifold', pos: 'adjective', definition: 'Many and various' },
  { word: 'Marvel', pos: 'verb', definition: 'To be filled with wonder or astonishment' },
  { word: 'Maudlin', pos: 'adjective', definition: 'Self-pityingly or tearfully sentimental' },
  { word: 'Maverick', pos: 'noun', definition: 'An unorthodox or independent-minded person' },
  { word: 'Meander', pos: 'verb', definition: 'To follow a winding course; to wander aimlessly' },
  { word: 'Medley', pos: 'noun', definition: 'A varied mixture of people or things' },
  { word: 'Mellifluous', pos: 'adjective', definition: 'Sweet or musical; pleasant to hear' },
  { word: 'Melodious', pos: 'adjective', definition: 'Pleasant-sounding; tuneful' },
  { word: 'Memento', pos: 'noun', definition: 'An object kept as a reminder of a person or event' },
  { word: 'Mercurial', pos: 'adjective', definition: 'Subject to sudden or unpredictable changes of mood' },
  { word: 'Meritorious', pos: 'adjective', definition: 'Deserving reward or praise' },
  { word: 'Meticulous', pos: 'adjective', definition: 'Showing great attention to detail; very careful and precise' },
  { word: 'Mettle', pos: 'noun', definition: 'A person\'s ability to cope well with difficulties; spirit' },
  { word: 'Mien', pos: 'noun', definition: 'A person\'s look or manner, indicating their mood' },
  { word: 'Milieu', pos: 'noun', definition: 'A person\'s social environment' },
  { word: 'Mirth', pos: 'noun', definition: 'Amusement, especially as expressed in laughter' },
  { word: 'Mitigate', pos: 'verb', definition: 'To make something bad less severe or serious' },
  { word: 'Mnemonic', pos: 'noun', definition: 'A device such as a pattern that aids memory' },
  { word: 'Modicum', pos: 'noun', definition: 'A small quantity of something desirable' },
  { word: 'Mollify', pos: 'verb', definition: 'To appease the anger or anxiety of someone' },
  { word: 'Mosaic', pos: 'noun', definition: 'A combination of diverse elements forming a coherent whole' },
  { word: 'Moxie', pos: 'noun', definition: 'Force of character, determination, or nerve' },
  { word: 'Multifarious', pos: 'adjective', definition: 'Having many varied parts or aspects' },
  { word: 'Munificent', pos: 'adjective', definition: 'More generous than is usual or necessary' },
  { word: 'Muse', pos: 'verb', definition: 'To consider something thoughtfully' },
  { word: 'Myriad', pos: 'noun', definition: 'A countless or extremely great number' },
  { word: 'Nadir', pos: 'noun', definition: 'The lowest point in fortunes; rock bottom' },
  { word: 'Nascent', pos: 'adjective', definition: 'Just coming into existence and beginning to develop' },
  { word: 'Nebulous', pos: 'adjective', definition: 'In the form of a cloud; unclear or vague' },
  { word: 'Nefarious', pos: 'adjective', definition: 'Wicked, villainous, or criminal' },
  { word: 'Neologism', pos: 'noun', definition: 'A newly coined word or expression' },
  { word: 'Nimble', pos: 'adjective', definition: 'Quick and light in movement or action' },
  { word: 'Nocturne', pos: 'noun', definition: 'A dreamy musical piece evocative of night' },
  { word: 'Nonchalant', pos: 'adjective', definition: 'Feeling or appearing casually calm and relaxed' },
  { word: 'Nonpareil', pos: 'adjective', definition: 'Having no match or equal; unrivaled' },
  { word: 'Nostalgia', pos: 'noun', definition: 'A sentimental longing for the past' },
  { word: 'Nourish', pos: 'verb', definition: 'To keep a feeling or belief alive; to sustain with food' },
  { word: 'Nuance', pos: 'noun', definition: 'A subtle difference in meaning, expression, or tone' },
  { word: 'Numinous', pos: 'adjective', definition: 'Having a strong spiritual or mystical quality' },
  { word: 'Oasis', pos: 'noun', definition: 'A pleasant or peaceful area in the midst of a difficult place' },
  { word: 'Obdurate', pos: 'adjective', definition: 'Stubbornly refusing to change one\'s opinion' },
  { word: 'Obfuscate', pos: 'verb', definition: 'To make something unclear or unintelligible' },
  { word: 'Obsequious', pos: 'adjective', definition: 'Obedient or attentive to an excessive degree' },
  { word: 'Obviate', pos: 'verb', definition: 'To remove a need or difficulty; to prevent' },
  { word: 'Odyssey', pos: 'noun', definition: 'A long and eventful journey or experience' },
  { word: 'Oeuvre', pos: 'noun', definition: 'The complete body of work of an artist or writer' },
  { word: 'Officious', pos: 'adjective', definition: 'Asserting authority in an annoyingly domineering way' },
  { word: 'Omniscient', pos: 'adjective', definition: 'Knowing everything' },
  { word: 'Onerous', pos: 'adjective', definition: 'Involving a burdensome amount of effort' },
  { word: 'Onomatopoeia', pos: 'noun', definition: 'A word formed from the sound it describes' },
  { word: 'Opalescent', pos: 'adjective', definition: 'Showing varying colors like an opal' },
  { word: 'Opine', pos: 'verb', definition: 'To hold and state as one\'s opinion' },
  { word: 'Opportune', pos: 'adjective', definition: 'Occurring at an especially convenient time' },
  { word: 'Opulent', pos: 'adjective', definition: 'Ostentatiously rich and luxurious' },
  { word: 'Ornate', pos: 'adjective', definition: 'Elaborately decorated' },
  { word: 'Oscillate', pos: 'verb', definition: 'To move back and forth between states or positions' },
  { word: 'Ostensible', pos: 'adjective', definition: 'Stated or appearing to be true, but not necessarily so' },
  { word: 'Ostentatious', pos: 'adjective', definition: 'Designed to impress or attract notice; showy' },
  { word: 'Overture', pos: 'noun', definition: 'An introduction to something more substantial; an opening move' },
  { word: 'Palatial', pos: 'adjective', definition: 'Resembling a palace; spacious and splendid' },
  { word: 'Palimpsest', pos: 'noun', definition: 'Something reused but still bearing traces of its earlier form' },
  { word: 'Palpable', pos: 'adjective', definition: 'So intense as to seem almost touchable' },
  { word: 'Panacea', pos: 'noun', definition: 'A solution or remedy for all difficulties' },
  { word: 'Panache', pos: 'noun', definition: 'Flamboyant confidence of style or manner' },
  { word: 'Pantheon', pos: 'noun', definition: 'A group of particularly respected or important people' },
  { word: 'Paradigm', pos: 'noun', definition: 'A typical example, pattern, or model of something' },
  { word: 'Paragon', pos: 'noun', definition: 'A model of excellence; a perfect example' },
  { word: 'Paramount', pos: 'adjective', definition: 'More important than anything else; supreme' },
  { word: 'Parsimonious', pos: 'adjective', definition: 'Extremely unwilling to spend money or use resources' },
  { word: 'Pastiche', pos: 'noun', definition: 'A work that imitates the style of another artist or period' },
  { word: 'Pathos', pos: 'noun', definition: 'A quality that evokes pity or sadness' },
  { word: 'Patina', pos: 'noun', definition: 'A surface sheen acquired with age or use' },
  { word: 'Paucity', pos: 'noun', definition: 'The presence of something in only small amounts; scarcity' },
  { word: 'Peccadillo', pos: 'noun', definition: 'A small, relatively unimportant offense or sin' },
  { word: 'Pell-mell', pos: 'adverb', definition: 'In a confused, rushed, or disorderly manner' },
  { word: 'Pellucid', pos: 'adjective', definition: 'Translucently clear; easily understood' },
  { word: 'Penchant', pos: 'noun', definition: 'A strong or habitual liking for something' },
  { word: 'Pensive', pos: 'adjective', definition: 'Engaged in deep or serious thought' },
  { word: 'Penumbra', pos: 'noun', definition: 'A partial shadow between full shadow and full light' },
  { word: 'Percolate', pos: 'verb', definition: 'To spread gradually through an area or group' },
  { word: 'Peregrinate', pos: 'verb', definition: 'To travel or wander from place to place' },
  { word: 'Perennial', pos: 'adjective', definition: 'Lasting for a long or apparently infinite time; enduring' },
  { word: 'Perfunctory', pos: 'adjective', definition: 'Carried out with minimum effort or reflection' },
  { word: 'Peripatetic', pos: 'adjective', definition: 'Traveling from place to place, especially for work' },
  { word: 'Perspicacious', pos: 'adjective', definition: 'Having a ready insight into things; shrewd' },
  { word: 'Pertinacious', pos: 'adjective', definition: 'Holding firmly to an opinion or course of action' },
  { word: 'Petrichor', pos: 'noun', definition: 'The pleasant smell of earth after rain' },
  { word: 'Philanthropy', pos: 'noun', definition: 'The desire to promote the welfare of others; generosity' },
  { word: 'Phlegmatic', pos: 'adjective', definition: 'Having an unemotional and calm disposition' },
  { word: 'Pinnacle', pos: 'noun', definition: 'The most successful point; the culmination' },
  { word: 'Piquant', pos: 'adjective', definition: 'Pleasantly stimulating to the mind; agreeably sharp in taste' },
  { word: 'Pique', pos: 'verb', definition: 'To stimulate interest or curiosity' },
  { word: 'Pithy', pos: 'adjective', definition: 'Concise and forcefully expressive' },
  { word: 'Placate', pos: 'verb', definition: 'To make someone less angry or hostile' },
  { word: 'Placid', pos: 'adjective', definition: 'Not easily upset or excited; calm and peaceful' },
  { word: 'Platitude', pos: 'noun', definition: 'A remark used too often to be interesting or thoughtful' },
  { word: 'Plaudit', pos: 'noun', definition: 'An expression of praise or approval' },
  { word: 'Plethora', pos: 'noun', definition: 'A large or excessive amount of something' },
  { word: 'Pluck', pos: 'noun', definition: 'Spirited and determined courage' },
  { word: 'Poignant', pos: 'adjective', definition: 'Evoking a keen sense of sadness or regret' },
  { word: 'Poise', pos: 'noun', definition: 'Graceful and elegant bearing; composure' },
  { word: 'Polymath', pos: 'noun', definition: 'A person of wide-ranging knowledge or learning' },
  { word: 'Portent', pos: 'noun', definition: 'A sign or warning that something significant is likely to happen' },
  { word: 'Portmanteau', pos: 'noun', definition: 'A word blending the sounds and meanings of two others' },
  { word: 'Pragmatic', pos: 'adjective', definition: 'Dealing with things sensibly and realistically' },
  { word: 'Precipice', pos: 'noun', definition: 'A very steep rock face; the brink of a dangerous situation' },
  { word: 'Precocious', pos: 'adjective', definition: 'Having developed abilities at an earlier age than usual' },
  { word: 'Predilection', pos: 'noun', definition: 'A preference or special liking for something' },
  { word: 'Prescient', pos: 'adjective', definition: 'Having knowledge of events before they take place' },
  { word: 'Pristine', pos: 'adjective', definition: 'In its original condition; unspoiled' },
  { word: 'Probity', pos: 'noun', definition: 'The quality of having strong moral principles; honesty' },
  { word: 'Proclivity', pos: 'noun', definition: 'A tendency to choose or do something regularly' },
  { word: 'Prodigious', pos: 'adjective', definition: 'Remarkably or impressively great in extent or degree' },
  { word: 'Prolific', pos: 'adjective', definition: 'Producing much fruit, foliage, or many works' },
  { word: 'Propensity', pos: 'noun', definition: 'An inclination or natural tendency to behave in a certain way' },
  { word: 'Propinquity', pos: 'noun', definition: 'The state of being close to someone or something' },
  { word: 'Propitious', pos: 'adjective', definition: 'Giving or indicating a good chance of success' },
  { word: 'Prosaic', pos: 'adjective', definition: 'Lacking poetic beauty; commonplace' },
  { word: 'Protean', pos: 'adjective', definition: 'Tending to change frequently; versatile' },
  { word: 'Provenance', pos: 'noun', definition: 'The place of origin or earliest known history of something' },
  { word: 'Prowess', pos: 'noun', definition: 'Skill or expertise in a particular activity' },
  { word: 'Prudent', pos: 'adjective', definition: 'Acting with care and thought for the future' },
  { word: 'Puckish', pos: 'adjective', definition: 'Playful, especially in a mischievous way' },
  { word: 'Pulchritude', pos: 'noun', definition: 'Physical beauty' },
  { word: 'Punctilious', pos: 'adjective', definition: 'Showing great attention to detail or correct behavior' },
  { word: 'Quaff', pos: 'verb', definition: 'To drink something heartily' },
  { word: 'Quandary', pos: 'noun', definition: 'A state of perplexity or uncertainty over what to do' },
  { word: 'Quell', pos: 'verb', definition: 'To put an end to something, typically by force; to calm' },
  { word: 'Quiescent', pos: 'adjective', definition: 'In a state of inactivity or dormancy' },
  { word: 'Quietude', pos: 'noun', definition: 'A state of stillness, calmness, and quiet' },
  { word: 'Quintessential', pos: 'adjective', definition: 'Representing the most perfect example of a quality' },
  { word: 'Quixotic', pos: 'adjective', definition: 'Exceedingly idealistic; unrealistic and impractical' },
  { word: 'Quotidian', pos: 'adjective', definition: 'Of or occurring every day; ordinary' },
  { word: 'Raconteur', pos: 'noun', definition: 'A person who tells anecdotes in a skillful and amusing way' },
  { word: 'Radiant', pos: 'adjective', definition: 'Sending out light; glowing with joy or health' },
  { word: 'Rambunctious', pos: 'adjective', definition: 'Uncontrollably exuberant; boisterous' },
  { word: 'Rapport', pos: 'noun', definition: 'A close and harmonious relationship with mutual understanding' },
  { word: 'Rapprochement', pos: 'noun', definition: 'A resumption of harmonious relations' },
  { word: 'Rapt', pos: 'adjective', definition: 'Completely fascinated or absorbed' },
  { word: 'Rarefied', pos: 'adjective', definition: 'Distant from the lives of ordinary people; esoteric' },
  { word: 'Recalcitrant', pos: 'adjective', definition: 'Having an obstinately uncooperative attitude' },
  { word: 'Recondite', pos: 'adjective', definition: 'Little known; dealing with profound or obscure subject matter' },
  { word: 'Redolent', pos: 'adjective', definition: 'Strongly reminiscent or suggestive of something; fragrant' },
  { word: 'Refulgent', pos: 'adjective', definition: 'Shining brightly; radiant and gleaming' },
  { word: 'Regal', pos: 'adjective', definition: 'Of, resembling, or fit for a monarch; magnificent' },
  { word: 'Regale', pos: 'verb', definition: 'To entertain or amuse with talk or a feast' },
  { word: 'Rejuvenate', pos: 'verb', definition: 'To make someone or something feel younger or more vital' },
  { word: 'Renaissance', pos: 'noun', definition: 'A revival of or renewed interest in something' },
  { word: 'Renown', pos: 'noun', definition: 'The condition of being known and honored widely; fame' },
  { word: 'Repartee', pos: 'noun', definition: 'Conversation characterized by quick, witty comments' },
  { word: 'Repertoire', pos: 'noun', definition: 'A stock of skills or works that a person is able to perform' },
  { word: 'Replete', pos: 'adjective', definition: 'Filled or well-supplied with something' },
  { word: 'Repose', pos: 'noun', definition: 'A state of rest, sleep, or tranquility' },
  { word: 'Resilient', pos: 'adjective', definition: 'Able to recover quickly from difficulties' },
  { word: 'Resolute', pos: 'adjective', definition: 'Admirably purposeful, determined, and unwavering' },
  { word: 'Resonant', pos: 'adjective', definition: 'Deep, clear, and continuing to sound; evoking memories' },
  { word: 'Respite', pos: 'noun', definition: 'A short period of rest or relief from something difficult' },
  { word: 'Resplendent', pos: 'adjective', definition: 'Impressive and attractive; brilliant' },
  { word: 'Reticent', pos: 'adjective', definition: 'Not revealing one\'s thoughts or feelings readily' },
  { word: 'Revere', pos: 'verb', definition: 'To feel deep respect or admiration for something' },
  { word: 'Reverie', pos: 'noun', definition: 'A state of being pleasantly lost in one\'s thoughts' },
  { word: 'Rhapsodize', pos: 'verb', definition: 'To speak or write about something with great enthusiasm' },
  { word: 'Riparian', pos: 'adjective', definition: 'Relating to or situated on the banks of a river' },
  { word: 'Riposte', pos: 'noun', definition: 'A quick, clever reply to an insult or criticism' },
  { word: 'Risible', pos: 'adjective', definition: 'Provoking laughter' },
  { word: 'Rollicking', pos: 'adjective', definition: 'Exuberantly lively and amusing' },
  { word: 'Ruminate', pos: 'verb', definition: 'To think deeply about something' },
  { word: 'Rustic', pos: 'adjective', definition: 'Relating to the countryside; charmingly simple' },
  { word: 'Sagacious', pos: 'adjective', definition: 'Having keen judgment; wise' },
  { word: 'Salient', pos: 'adjective', definition: 'Most noticeable or important' },
  { word: 'Salubrious', pos: 'adjective', definition: 'Health-giving; healthy' },
  { word: 'Salutary', pos: 'adjective', definition: 'Producing good effects; beneficial' },
  { word: 'Sanctuary', pos: 'noun', definition: 'A place of refuge or safety' },
  { word: 'Sanguine', pos: 'adjective', definition: 'Optimistic or positive, especially in a difficult situation' },
  { word: 'Sapient', pos: 'adjective', definition: 'Wise, or attempting to appear wise' },
  { word: 'Sardonic', pos: 'adjective', definition: 'Grimly mocking or cynical' },
  { word: 'Sartorial', pos: 'adjective', definition: 'Relating to tailoring, clothes, or style of dress' },
  { word: 'Satiate', pos: 'verb', definition: 'To satisfy fully' },
  { word: 'Saunter', pos: 'verb', definition: 'To walk in a slow, relaxed manner' },
  { word: 'Savant', pos: 'noun', definition: 'A learned person, especially with detailed knowledge in a field' },
  { word: 'Savor', pos: 'verb', definition: 'To enjoy something completely, especially by dwelling on it' },
  { word: 'Scintilla', pos: 'noun', definition: 'A tiny trace or spark of a quality or feeling' },
  { word: 'Scintillate', pos: 'verb', definition: 'To emit flashes of light; to sparkle' },
  { word: 'Scrupulous', pos: 'adjective', definition: 'Diligent, thorough, and extremely attentive to detail' },
  { word: 'Sedulous', pos: 'adjective', definition: 'Showing dedication and diligence' },
  { word: 'Sempiternal', pos: 'adjective', definition: 'Eternal and unchanging; everlasting' },
  { word: 'Seraphic', pos: 'adjective', definition: 'Characteristic of an angel; blissfully serene' },
  { word: 'Serenade', pos: 'noun', definition: 'A piece of music performed in someone\'s honor' },
  { word: 'Serendipity', pos: 'noun', definition: 'The occurrence of events by chance in a happy way' },
  { word: 'Serene', pos: 'adjective', definition: 'Calm, peaceful, and untroubled' },
  { word: 'Shimmer', pos: 'verb', definition: 'To shine with a soft, tremulous light' },
  { word: 'Shrewd', pos: 'adjective', definition: 'Having sharp powers of judgment; astute' },
  { word: 'Sinuous', pos: 'adjective', definition: 'Having many curves and turns; graceful and supple' },
  { word: 'Skulduggery', pos: 'noun', definition: 'Underhanded or unscrupulous behavior; trickery' },
  { word: 'Sojourn', pos: 'noun', definition: 'A temporary stay in a place' },
  { word: 'Solace', pos: 'noun', definition: 'Comfort or consolation in a time of distress' },
  { word: 'Solicitous', pos: 'adjective', definition: 'Showing interest or concern for someone\'s well-being' },
  { word: 'Soliloquy', pos: 'noun', definition: 'The act of speaking one\'s thoughts aloud when alone' },
  { word: 'Solstice', pos: 'noun', definition: 'The time when the sun reaches its highest or lowest point' },
  { word: 'Somnolent', pos: 'adjective', definition: 'Sleepy; drowsy; inducing drowsiness' },
  { word: 'Sonorous', pos: 'adjective', definition: 'Imposingly deep and full in sound' },
  { word: 'Soporific', pos: 'adjective', definition: 'Tending to induce drowsiness or sleep' },
  { word: 'Spellbind', pos: 'verb', definition: 'To hold the complete attention of someone as if by magic' },
  { word: 'Splendor', pos: 'noun', definition: 'Magnificent and grand appearance' },
  { word: 'Sprightly', pos: 'adjective', definition: 'Lively and full of energy' },
  { word: 'Spry', pos: 'adjective', definition: 'Active and lively, especially despite advancing age' },
  { word: 'Spurious', pos: 'adjective', definition: 'Not being what it purports to be; false' },
  { word: 'Stalwart', pos: 'adjective', definition: 'Loyal, reliable, and hardworking' },
  { word: 'Steadfast', pos: 'adjective', definition: 'Resolutely firm and unwavering' },
  { word: 'Stoic', pos: 'adjective', definition: 'Enduring hardship without showing feelings or complaining' },
  { word: 'Stratagem', pos: 'noun', definition: 'A plan or scheme intended to outwit an opponent' },
  { word: 'Suave', pos: 'adjective', definition: 'Charming, confident, and elegant in manner' },
  { word: 'Sublime', pos: 'adjective', definition: 'Of outstanding spiritual or intellectual worth' },
  { word: 'Succinct', pos: 'adjective', definition: 'Briefly and clearly expressed' },
  { word: 'Sumptuous', pos: 'adjective', definition: 'Splendid and expensive-looking; luxurious' },
  { word: 'Superfluous', pos: 'adjective', definition: 'Unnecessary, especially through being more than enough' },
  { word: 'Supplant', pos: 'verb', definition: 'To supersede and replace something' },
  { word: 'Supple', pos: 'adjective', definition: 'Bending and moving easily and gracefully; flexible' },
  { word: 'Surfeit', pos: 'noun', definition: 'An excessive amount of something' },
  { word: 'Surreptitious', pos: 'adjective', definition: 'Kept secret, especially because it would not be approved of' },
  { word: 'Susurrus', pos: 'noun', definition: 'A whispering or rustling sound' },
  { word: 'Svelte', pos: 'adjective', definition: 'Slender and elegant' },
  { word: 'Sycophant', pos: 'noun', definition: 'A person who flatters someone important for personal gain' },
  { word: 'Sylvan', pos: 'adjective', definition: 'Relating to woods; wooded and pleasant' },
  { word: 'Symbiosis', pos: 'noun', definition: 'A mutually beneficial relationship between different groups' },
  { word: 'Tableau', pos: 'noun', definition: 'A striking or vivid scene or picture' },
  { word: 'Tacit', pos: 'adjective', definition: 'Understood or implied without being stated' },
  { word: 'Taciturn', pos: 'adjective', definition: 'Reserved or uncommunicative in speech' },
  { word: 'Talisman', pos: 'noun', definition: 'An object thought to have magic powers and bring good luck' },
  { word: 'Tantalize', pos: 'verb', definition: 'To torment or tease with something unobtainable' },
  { word: 'Tapestry', pos: 'noun', definition: 'An intricate combination of things woven together' },
  { word: 'Temerity', pos: 'noun', definition: 'Excessive confidence or boldness; audacity' },
  { word: 'Tempestuous', pos: 'adjective', definition: 'Characterized by strong and turbulent emotion' },
  { word: 'Tenacious', pos: 'adjective', definition: 'Holding firmly to something; persistent' },
  { word: 'Tenet', pos: 'noun', definition: 'A principle or belief held as true by a group' },
  { word: 'Terse', pos: 'adjective', definition: 'Sparing in the use of words; abrupt' },
  { word: 'Tessellate', pos: 'verb', definition: 'To fit shapes together in a pattern with no gaps' },
  { word: 'Thrive', pos: 'verb', definition: 'To grow, develop, or prosper vigorously' },
  { word: 'Timbre', pos: 'noun', definition: 'The distinctive character or quality of a sound or voice' },
  { word: 'Torpor', pos: 'noun', definition: 'A state of physical or mental inactivity; lethargy' },
  { word: 'Tranquil', pos: 'adjective', definition: 'Free from disturbance; calm' },
  { word: 'Transcendent', pos: 'adjective', definition: 'Beyond or above the range of normal experience' },
  { word: 'Transfix', pos: 'verb', definition: 'To cause someone to become motionless with wonder' },
  { word: 'Transient', pos: 'adjective', definition: 'Lasting only for a short time; impermanent' },
  { word: 'Transmute', pos: 'verb', definition: 'To change in form, nature, or substance' },
  { word: 'Trenchant', pos: 'adjective', definition: 'Vigorous or incisive in expression or style' },
  { word: 'Trepidation', pos: 'noun', definition: 'A feeling of fear about something that may happen' },
  { word: 'Trove', pos: 'noun', definition: 'A store of valuable or delightful things' },
  { word: 'Tutelage', pos: 'noun', definition: 'Protection of or authority over someone; instruction' },
  { word: 'Ubiquitous', pos: 'adjective', definition: 'Present, appearing, or found everywhere' },
  { word: 'Umbrage', pos: 'noun', definition: 'Offense or annoyance at what someone has done' },
  { word: 'Unctuous', pos: 'adjective', definition: 'Excessively or ingratiatingly flattering' },
  { word: 'Undaunted', pos: 'adjective', definition: 'Not discouraged by difficulty, danger, or disappointment' },
  { word: 'Undulate', pos: 'verb', definition: 'To move with a smooth wavelike motion' },
  { word: 'Unequivocal', pos: 'adjective', definition: 'Leaving no doubt; unambiguous' },
  { word: 'Unflappable', pos: 'adjective', definition: 'Having unshakable composure; calm in a crisis' },
  { word: 'Unfurl', pos: 'verb', definition: 'To spread out from a rolled or folded state' },
  { word: 'Urbane', pos: 'adjective', definition: 'Courteous and refined in manner; suave' },
  { word: 'Utopia', pos: 'noun', definition: 'An imagined place where everything is perfect' },
  { word: 'Vacillate', pos: 'verb', definition: 'To waver between different opinions or actions' },
  { word: 'Vagary', pos: 'noun', definition: 'An unexpected and inexplicable change in a situation' },
  { word: 'Valiant', pos: 'adjective', definition: 'Possessing or showing courage and determination' },
  { word: 'Valor', pos: 'noun', definition: 'Great courage in the face of danger' },
  { word: 'Vanguard', pos: 'noun', definition: 'A group of people leading the way in new developments' },
  { word: 'Variegated', pos: 'adjective', definition: 'Exhibiting different colors, especially in irregular patches' },
  { word: 'Vaunted', pos: 'adjective', definition: 'Praised or boasted about, often excessively' },
  { word: 'Vehement', pos: 'adjective', definition: 'Showing strong feeling; forceful or passionate' },
  { word: 'Venerable', pos: 'adjective', definition: 'Accorded great respect because of age, wisdom, or character' },
  { word: 'Veracity', pos: 'noun', definition: 'Conformity to facts; truthfulness' },
  { word: 'Verdant', pos: 'adjective', definition: 'Green with grass or other rich vegetation' },
  { word: 'Verisimilitude', pos: 'noun', definition: 'The appearance of being true or real' },
  { word: 'Veritable', pos: 'adjective', definition: 'Used for emphasis, often metaphorically; genuine' },
  { word: 'Vernacular', pos: 'noun', definition: 'The everyday language spoken by ordinary people' },
  { word: 'Vernal', pos: 'adjective', definition: 'Relating to or occurring in the spring' },
  { word: 'Vertiginous', pos: 'adjective', definition: 'Causing dizziness; extremely high or steep' },
  { word: 'Verve', pos: 'noun', definition: 'Vigor, spirit, and enthusiasm' },
  { word: 'Vestige', pos: 'noun', definition: 'A trace of something that once existed' },
  { word: 'Vibrant', pos: 'adjective', definition: 'Full of energy and enthusiasm; bright and striking' },
  { word: 'Vicarious', pos: 'adjective', definition: 'Experienced through the feelings or actions of another' },
  { word: 'Vignette', pos: 'noun', definition: 'A brief, evocative description or scene' },
  { word: 'Vim', pos: 'noun', definition: 'Energy and enthusiasm' },
  { word: 'Vindicate', pos: 'verb', definition: 'To clear of blame or suspicion; to justify' },
  { word: 'Virtuoso', pos: 'noun', definition: 'A person highly skilled in an artistic pursuit' },
  { word: 'Visage', pos: 'noun', definition: 'A person\'s face, with reference to its expression' },
  { word: 'Visceral', pos: 'adjective', definition: 'Relating to deep inward feelings rather than intellect' },
  { word: 'Vista', pos: 'noun', definition: 'A pleasing view; a mental picture of future possibilities' },
  { word: 'Vivacious', pos: 'adjective', definition: 'Attractively lively and animated' },
  { word: 'Vociferous', pos: 'adjective', definition: 'Expressing opinions loudly and forcefully' },
  { word: 'Volition', pos: 'noun', definition: 'The faculty or power of using one\'s own will' },
  { word: 'Voluble', pos: 'adjective', definition: 'Speaking fluently, readily, and at length' },
  { word: 'Voracious', pos: 'adjective', definition: 'Having a very eager approach to an activity; ravenous' },
  { word: 'Wanderlust', pos: 'noun', definition: 'A strong desire to travel and explore the world' },
  { word: 'Wane', pos: 'verb', definition: 'To decrease in vigor, power, or extent' },
  { word: 'Wellspring', pos: 'noun', definition: 'An original and bountiful source of something' },
  { word: 'Wheedle', pos: 'verb', definition: 'To use flattery or coaxing to persuade someone' },
  { word: 'Whet', pos: 'verb', definition: 'To sharpen a tool; to stimulate desire or interest' },
  { word: 'Whimsical', pos: 'adjective', definition: 'Playfully quaint or fanciful' },
  { word: 'Wily', pos: 'adjective', definition: 'Skilled at gaining an advantage, especially deceitfully' },
  { word: 'Winsome', pos: 'adjective', definition: 'Attractive or appealing in a fresh, innocent way' },
  { word: 'Wistful', pos: 'adjective', definition: 'Having a feeling of vague or regretful longing' },
  { word: 'Wizened', pos: 'adjective', definition: 'Shriveled or wrinkled with age' },
  { word: 'Wonderment', pos: 'noun', definition: 'A state of awed admiration or respect' },
  { word: 'Wry', pos: 'adjective', definition: 'Using dry, mocking humor' },
  { word: 'Yearn', pos: 'verb', definition: 'To have an intense feeling of longing for something' },
  { word: 'Yen', pos: 'noun', definition: 'A longing or yearning for something' },
  { word: 'Yonder', pos: 'adverb', definition: 'At some distance in the direction indicated; over there' },
  { word: 'Zeal', pos: 'noun', definition: 'Great energy or enthusiasm for a cause or objective' },
  { word: 'Zeitgeist', pos: 'noun', definition: 'The defining spirit or mood of a particular period' },
  { word: 'Zenith', pos: 'noun', definition: 'The highest point reached; the peak or culmination' },
  { word: 'Zephyr', pos: 'noun', definition: 'A soft, gentle breeze' },
  { word: 'Zest', pos: 'noun', definition: 'Great enthusiasm and energy; piquancy' },
];
