import type { WordEntry } from './types';

export const ES_ES_WORDS: WordEntry[] = [
  { word: 'Abigarrado', pos: 'adjective', definition: 'De muchos colores o elementos mezclados sin concierto' },
  { word: 'Abismal', pos: 'adjective', definition: 'Enorme y profundo como un abismo' },
  { word: 'Abnegación', pos: 'noun', definition: 'Sacrificio voluntario de los propios intereses por los demás' },
  { word: 'Abnegado', pos: 'adjective', definition: 'Que se sacrifica por los demás sin esperar nada a cambio' },
  { word: 'Abrumador', pos: 'adjective', definition: 'Que agobia por su magnitud o intensidad' },
  { word: 'Absorto', pos: 'adjective', definition: 'Completamente concentrado en un pensamiento, ajeno a lo demás' },
  { word: 'Abstruso', pos: 'adjective', definition: 'Difícil de comprender, reservado a entendimientos profundos' },
  { word: 'Acaecer', pos: 'verb', definition: 'Suceder, producirse un hecho' },
  { word: 'Acaso', pos: 'adverb', definition: 'Quizá, tal vez' },
  { word: 'Acechar', pos: 'verb', definition: 'Observar a escondidas aguardando el momento oportuno' },
  { word: 'Acendrado', pos: 'adjective', definition: 'Puro y sin mancha, depurado de todo defecto' },
  { word: 'Acervo', pos: 'noun', definition: 'Conjunto de bienes o valores culturales acumulados por tradición' },
  { word: 'Aciago', pos: 'adjective', definition: 'Desgraciado, de mal agüero o funesto presagio' },
  { word: 'Acicate', pos: 'noun', definition: 'Estímulo que incita a emprender o continuar algo' },
  { word: 'Acompasado', pos: 'adjective', definition: 'Que sigue un ritmo regular y armonioso' },
  { word: 'Acongojar', pos: 'verb', definition: 'Causar aflicción o angustia profunda' },
  { word: 'Acrisolado', pos: 'adjective', definition: 'Depurado y probado, como el oro en el crisol' },
  { word: 'Acuciar', pos: 'verb', definition: 'Apremiar con urgencia o estimular con insistencia' },
  { word: 'Adalid', pos: 'noun', definition: 'Caudillo o defensor destacado de una causa' },
  { word: 'Adamantino', pos: 'adjective', definition: 'Duro y brillante como el diamante' },
  { word: 'Adrede', pos: 'adverb', definition: 'De forma deliberada, a propósito' },
  { word: 'Adusto', pos: 'adjective', definition: 'Serio y severo en el trato, poco expresivo' },
  { word: 'Aflorar', pos: 'verb', definition: 'Salir a la superficie algo que estaba oculto' },
  { word: 'Agasajar', pos: 'verb', definition: 'Tratar a alguien con atenciones, regalos y muestras de afecto' },
  { word: 'Agazapado', pos: 'adjective', definition: 'Escondido y al acecho, esperando el momento oportuno' },
  { word: 'Agorero', pos: 'adjective', definition: 'Que predice males o anuncia desdichas' },
  { word: 'Agreste', pos: 'adjective', definition: 'Áspero y silvestre, propio del campo sin cultivar' },
  { word: 'Aguzar', pos: 'verb', definition: 'Afinar los sentidos o el ingenio para percibir mejor' },
  { word: 'Ahínco', pos: 'noun', definition: 'Empeño y esfuerzo grande con que se hace algo' },
  { word: 'Ahondar', pos: 'verb', definition: 'Profundizar en algo hasta llegar a su fondo' },
  { word: 'Airoso', pos: 'adjective', definition: 'Que sale de una dificultad con éxito y elegancia' },
  { word: 'Alabastrino', pos: 'adjective', definition: 'Blanco y translúcido como el alabastro' },
  { word: 'Albergar', pos: 'verb', definition: 'Dar cobijo o guardar dentro de sí una esperanza' },
  { word: 'Albor', pos: 'noun', definition: 'Comienzo o primera luz de algo que despunta' },
  { word: 'Alborada', pos: 'noun', definition: 'Amanecer, tiempo en que despunta el día' },
  { word: 'Alborozo', pos: 'noun', definition: 'Alegría extraordinaria que se manifiesta con gestos y voces' },
  { word: 'Albur', pos: 'noun', definition: 'Azar o contingencia a la que se confía un resultado' },
  { word: 'Alcurnia', pos: 'noun', definition: 'Ascendencia noble o linaje ilustre de una familia' },
  { word: 'Aledaño', pos: 'adjective', definition: 'Contiguo, situado junto a un lugar' },
  { word: 'Alegoría', pos: 'noun', definition: 'Representación simbólica de una idea mediante figuras' },
  { word: 'Aletargar', pos: 'verb', definition: 'Producir un sopor profundo que adormece la actividad' },
  { word: 'Algarabía', pos: 'noun', definition: 'Griterío confuso de voces alegres' },
  { word: 'Alharaca', pos: 'noun', definition: 'Demostración exagerada de un sentimiento' },
  { word: 'Aliciente', pos: 'noun', definition: 'Atractivo o incentivo que anima a hacer algo' },
  { word: 'Allende', pos: 'adverb', definition: 'Más allá, de la parte de allá' },
  { word: 'Almibarado', pos: 'adjective', definition: 'Excesivamente dulce o meloso en el trato o el lenguaje' },
  { word: 'Altivez', pos: 'noun', definition: 'Orgullo que lleva a sentirse superior a los demás' },
  { word: 'Altruismo', pos: 'noun', definition: 'Diligencia en procurar el bien ajeno aun a costa del propio' },
  { word: 'Alusivo', pos: 'adjective', definition: 'Que hace referencia indirecta a algo' },
  { word: 'Amainar', pos: 'verb', definition: 'Perder fuerza el viento, la lluvia o un ánimo exaltado' },
  { word: 'Ambages', pos: 'noun', definition: 'Rodeos de palabras para no decir algo directamente' },
  { word: 'Ambrosía', pos: 'noun', definition: 'Manjar delicioso, digno de los dioses' },
  { word: 'Amedrentar', pos: 'verb', definition: 'Infundir miedo para intimidar a alguien' },
  { word: 'Ameno', pos: 'adjective', definition: 'Grato y placentero por su variedad y encanto' },
  { word: 'Amilanar', pos: 'verb', definition: 'Acobardar, hacer perder el ánimo o la resolución' },
  { word: 'Anacrónico', pos: 'adjective', definition: 'Que no corresponde a la época en que se sitúa' },
  { word: 'Anegar', pos: 'verb', definition: 'Inundar o cubrir por completo de agua' },
  { word: 'Anhelo', pos: 'noun', definition: 'Deseo vehemente y profundo de algo' },
  { word: 'Anodino', pos: 'adjective', definition: 'Insustancial, que carece de interés o gracia' },
  { word: 'Antaño', pos: 'adverb', definition: 'En tiempos pasados, antiguamente' },
  { word: 'Añejo', pos: 'adjective', definition: 'Que ha mejorado o madurado con el paso de los años' },
  { word: 'Añoranza', pos: 'noun', definition: 'Nostalgia por algo o alguien ausente' },
  { word: 'Apacible', pos: 'adjective', definition: 'Manso y tranquilo, de trato agradable' },
  { word: 'Apaciblemente', pos: 'adverb', definition: 'Con dulzura y sosiego, sin sobresalto' },
  { word: 'Apaciguar', pos: 'verb', definition: 'Calmar, poner en paz los ánimos alterados' },
  { word: 'Apesadumbrado', pos: 'adjective', definition: 'Afligido por una pena o pesar hondo' },
  { word: 'Aplomo', pos: 'noun', definition: 'Serenidad y seguridad en la manera de actuar' },
  { word: 'Apócrifo', pos: 'adjective', definition: 'Falso o de autenticidad dudosa' },
  { word: 'Apogeo', pos: 'noun', definition: 'Punto culminante de esplendor de un proceso' },
  { word: 'Apoteosis', pos: 'noun', definition: 'Momento culminante de exaltación y grandeza' },
  { word: 'Aquiescencia', pos: 'noun', definition: 'Consentimiento o conformidad con algo' },
  { word: 'Arcano', pos: 'noun', definition: 'Secreto profundo y muy reservado' },
  { word: 'Ardid', pos: 'noun', definition: 'Artificio ingenioso empleado para lograr un fin' },
  { word: 'Arduo', pos: 'adjective', definition: 'Muy difícil, que exige gran esfuerzo' },
  { word: 'Argucia', pos: 'noun', definition: 'Argumento falso presentado con ingenio' },
  { word: 'Arrebol', pos: 'noun', definition: 'Color rojizo de las nubes iluminadas por el sol' },
  { word: 'Arrobamiento', pos: 'noun', definition: 'Éxtasis o embelesamiento que enajena los sentidos' },
  { word: 'Asaz', pos: 'adverb', definition: 'Bastante, en gran medida' },
  { word: 'Asiduo', pos: 'adjective', definition: 'Frecuente, constante y perseverante' },
  { word: 'Ataviar', pos: 'verb', definition: 'Vestir y adornar con esmero' },
  { word: 'Atávico', pos: 'adjective', definition: 'Heredado de los antepasados remotos' },
  { word: 'Atenuar', pos: 'verb', definition: 'Disminuir la fuerza o intensidad de algo' },
  { word: 'Atesorar', pos: 'verb', definition: 'Guardar algo valioso con cuidado y aprecio' },
  { word: 'Atisbar', pos: 'verb', definition: 'Observar con disimulo o vislumbrar apenas' },
  { word: 'Atolladero', pos: 'noun', definition: 'Situación difícil de la que cuesta salir' },
  { word: 'Atribulado', pos: 'adjective', definition: 'Afligido por penas o tribulaciones' },
  { word: 'Audaz', pos: 'adjective', definition: 'Atrevido, que actúa sin temor al riesgo' },
  { word: 'Augurio', pos: 'noun', definition: 'Señal que anuncia algo venidero' },
  { word: 'Austero', pos: 'adjective', definition: 'Sobrio y sencillo, sin adornos ni excesos' },
  { word: 'Avatar', pos: 'noun', definition: 'Vicisitud o cambio de fortuna en el curso de la vida' },
  { word: 'Avezado', pos: 'adjective', definition: 'Experimentado y curtido en una actividad' },
  { word: 'Ávido', pos: 'adjective', definition: 'Que desea algo con ansia e intensidad' },
  { word: 'Avistar', pos: 'verb', definition: 'Alcanzar a ver algo a lo lejos' },
  { word: 'Azaroso', pos: 'adjective', definition: 'Sujeto al azar, lleno de riesgos e imprevistos' },
  { word: 'Baladí', pos: 'adjective', definition: 'Insignificante, de poca importancia' },
  { word: 'Balbucear', pos: 'verb', definition: 'Hablar con pronunciación vacilante y entrecortada' },
  { word: 'Baluarte', pos: 'noun', definition: 'Defensa firme o amparo de una causa' },
  { word: 'Barruntar', pos: 'verb', definition: 'Presentir algo por indicios o señales' },
  { word: 'Beatífico', pos: 'adjective', definition: 'Que refleja placidez y serenidad plenas' },
  { word: 'Beldad', pos: 'noun', definition: 'Belleza extraordinaria, hermosura notable' },
  { word: 'Benevolencia', pos: 'noun', definition: 'Buena voluntad y simpatía hacia las personas' },
  { word: 'Benévolo', pos: 'adjective', definition: 'Que tiene buena voluntad e indulgencia' },
  { word: 'Bienaventurado', pos: 'adjective', definition: 'Feliz y afortunado, digno de dicha' },
  { word: 'Bisoño', pos: 'adjective', definition: 'Nuevo e inexperto en un oficio o actividad' },
  { word: 'Bizarro', pos: 'adjective', definition: 'Valiente, generoso y de gallarda presencia' },
  { word: 'Bonanza', pos: 'noun', definition: 'Tiempo sereno y próspero tras la adversidad' },
  { word: 'Bonhomía', pos: 'noun', definition: 'Afabilidad, sencillez y bondad en el carácter' },
  { word: 'Bosquejar', pos: 'verb', definition: 'Trazar los rasgos generales de una idea u obra' },
  { word: 'Boyante', pos: 'adjective', definition: 'Que goza de fortuna y prosperidad creciente' },
  { word: 'Bravura', pos: 'noun', definition: 'Valentía y fiereza ante el peligro' },
  { word: 'Brío', pos: 'noun', definition: 'Energía, ánimo y resolución al actuar' },
  { word: 'Bruma', pos: 'noun', definition: 'Niebla ligera, especialmente la que se forma sobre el mar' },
  { word: 'Brumoso', pos: 'adjective', definition: 'Cubierto de niebla, confuso y poco claro' },
  { word: 'Bruñir', pos: 'verb', definition: 'Sacar brillo a una superficie puliéndola' },
  { word: 'Bucólico', pos: 'adjective', definition: 'Que evoca la vida idílica del campo' },
  { word: 'Bullicio', pos: 'noun', definition: 'Ruido y rumor de mucha gente en movimiento' },
  { word: 'Cabalmente', pos: 'adverb', definition: 'De manera completa y exacta' },
  { word: 'Cadencia', pos: 'noun', definition: 'Ritmo armonioso y acompasado de sonidos o movimientos' },
  { word: 'Calidez', pos: 'noun', definition: 'Cordialidad y afecto en el trato' },
  { word: 'Cándido', pos: 'adjective', definition: 'Sencillo e ingenuo, sin malicia ni doblez' },
  { word: 'Candor', pos: 'noun', definition: 'Sinceridad e inocencia sin doblez' },
  { word: 'Candoroso', pos: 'adjective', definition: 'Ingenuo y puro, sin malicia alguna' },
  { word: 'Capcioso', pos: 'adjective', definition: 'Que encierra engaño bajo apariencia de verdad' },
  { word: 'Cariz', pos: 'noun', definition: 'Aspecto que presenta un asunto o situación' },
  { word: 'Cautivar', pos: 'verb', definition: 'Atraer irresistiblemente la atención o el afecto' },
  { word: 'Cauto', pos: 'adjective', definition: 'Que actúa con precaución y prudencia' },
  { word: 'Cavilar', pos: 'verb', definition: 'Pensar en algo con intensidad y detenimiento' },
  { word: 'Caviloso', pos: 'adjective', definition: 'Dado a darle vueltas a los pensamientos con inquietud' },
  { word: 'Celaje', pos: 'noun', definition: 'Aspecto del cielo surcado de nubes tenues y coloridas' },
  { word: 'Celeridad', pos: 'noun', definition: 'Rapidez y prontitud en el movimiento o la ejecución' },
  { word: 'Cenit', pos: 'noun', definition: 'Punto más alto o momento de apogeo' },
  { word: 'Centellear', pos: 'verb', definition: 'Despedir destellos vivos e intermitentes' },
  { word: 'Ceñudo', pos: 'adjective', definition: 'Que frunce el ceño en señal de enfado o gravedad' },
  { word: 'Cercenar', pos: 'verb', definition: 'Cortar o recortar algo disminuyéndolo' },
  { word: 'Certero', pos: 'adjective', definition: 'Acertado y seguro, que da en el blanco' },
  { word: 'Certidumbre', pos: 'noun', definition: 'Conocimiento seguro y claro de algo' },
  { word: 'Cicatero', pos: 'adjective', definition: 'Mezquino, que escatima lo que podría dar' },
  { word: 'Cimentar', pos: 'verb', definition: 'Asentar los fundamentos firmes de algo' },
  { word: 'Circunloquio', pos: 'noun', definition: 'Rodeo de palabras para expresar algo' },
  { word: 'Circunspecto', pos: 'adjective', definition: 'Comedido y prudente, que guarda decoro' },
  { word: 'Clarividencia', pos: 'noun', definition: 'Facultad de comprender y discernir con lucidez' },
  { word: 'Claudicar', pos: 'verb', definition: 'Ceder o rendirse abandonando un empeño' },
  { word: 'Clemencia', pos: 'noun', definition: 'Compasión y moderación al impartir justicia' },
  { word: 'Colmar', pos: 'verb', definition: 'Llenar hasta rebosar, satisfacer plenamente' },
  { word: 'Colosal', pos: 'adjective', definition: 'De proporciones o cualidades extraordinarias' },
  { word: 'Comedido', pos: 'adjective', definition: 'Moderado y cortés en palabras y acciones' },
  { word: 'Compendio', pos: 'noun', definition: 'Exposición breve de lo esencial de una materia' },
  { word: 'Complaciente', pos: 'adjective', definition: 'Que procura agradar y satisfacer a los demás' },
  { word: 'Conciliábulo', pos: 'noun', definition: 'Reunión secreta para tratar algo que se quiere ocultar' },
  { word: 'Concisión', pos: 'noun', definition: 'Brevedad y economía de palabras al expresarse' },
  { word: 'Conciso', pos: 'adjective', definition: 'Que expresa mucho con pocas palabras' },
  { word: 'Confabular', pos: 'verb', definition: 'Ponerse de acuerdo en secreto para un fin' },
  { word: 'Congoja', pos: 'noun', definition: 'Angustia y aflicción intensas del ánimo' },
  { word: 'Conmiseración', pos: 'noun', definition: 'Compasión ante la desgracia ajena' },
  { word: 'Conmovedor', pos: 'adjective', definition: 'Que emociona y enternece profundamente' },
  { word: 'Connivencia', pos: 'noun', definition: 'Complicidad tolerante con una falta ajena' },
  { word: 'Consternación', pos: 'noun', definition: 'Abatimiento profundo causado por algo doloroso' },
  { word: 'Contemplativo', pos: 'adjective', definition: 'Dado a la observación serena y meditativa' },
  { word: 'Contingencia', pos: 'noun', definition: 'Suceso posible pero incierto' },
  { word: 'Contrito', pos: 'adjective', definition: 'Arrepentido sinceramente de una falta' },
  { word: 'Contumaz', pos: 'adjective', definition: 'Obstinado en mantener un error' },
  { word: 'Convite', pos: 'noun', definition: 'Banquete o festejo al que se invita' },
  { word: 'Copioso', pos: 'adjective', definition: 'Abundante, cuantioso en extremo' },
  { word: 'Cordura', pos: 'noun', definition: 'Prudencia y buen juicio' },
  { word: 'Corolario', pos: 'noun', definition: 'Consecuencia que se deduce naturalmente de lo dicho' },
  { word: 'Coruscante', pos: 'adjective', definition: 'Que brilla o resplandece con destellos' },
  { word: 'Cotejar', pos: 'verb', definition: 'Comparar cosas entre sí para apreciar sus diferencias' },
  { word: 'Crepitar', pos: 'verb', definition: 'Producir chasquidos repetidos, como la leña al arder' },
  { word: 'Crepuscular', pos: 'adjective', definition: 'Propio de la media luz del atardecer' },
  { word: 'Crepúsculo', pos: 'noun', definition: 'Claridad tenue entre el día y la noche' },
  { word: 'Cristalino', pos: 'adjective', definition: 'Claro y transparente como el cristal' },
  { word: 'Cuantioso', pos: 'adjective', definition: 'Grande en cantidad o número' },
  { word: 'Cuita', pos: 'noun', definition: 'Pena, aflicción o trabajo que se padece' },
  { word: 'Culmen', pos: 'noun', definition: 'Punto más alto o momento cumbre' },
  { word: 'Cúmulo', pos: 'noun', definition: 'Gran acumulación de cosas juntas' },
  { word: 'Dádiva', pos: 'noun', definition: 'Regalo que se entrega gratuitamente, con generosidad' },
  { word: 'Deambular', pos: 'verb', definition: 'Andar sin rumbo fijo, pasear sin destino' },
  { word: 'Dechado', pos: 'noun', definition: 'Ejemplo o modelo digno de imitarse' },
  { word: 'Declive', pos: 'noun', definition: 'Decadencia o pérdida progresiva de fuerza' },
  { word: 'Deleite', pos: 'noun', definition: 'Placer intenso del ánimo o de los sentidos' },
  { word: 'Deleznable', pos: 'adjective', definition: 'Despreciable, de poco valor o consistencia' },
  { word: 'Demudado', pos: 'adjective', definition: 'Con el rostro alterado por una emoción súbita' },
  { word: 'Denodado', pos: 'adjective', definition: 'Esforzado y valeroso, que no escatima empeño' },
  { word: 'Denostar', pos: 'verb', definition: 'Injuriar gravemente de palabra' },
  { word: 'Denuedo', pos: 'noun', definition: 'Valor y energía con que se acomete algo' },
  { word: 'Deparar', pos: 'verb', definition: 'Ofrecer o presentar algo el destino o la ocasión' },
  { word: 'Desasosiego', pos: 'noun', definition: 'Inquietud que impide la calma del ánimo' },
  { word: 'Desazón', pos: 'noun', definition: 'Malestar interior, inquietud sin causa precisa' },
  { word: 'Desdén', pos: 'noun', definition: 'Indiferencia despectiva hacia algo o alguien' },
  { word: 'Desentrañar', pos: 'verb', definition: 'Penetrar lo más oculto y dificultoso de un asunto' },
  { word: 'Desidia', pos: 'noun', definition: 'Negligencia y abandono por falta de interés' },
  { word: 'Deslumbrar', pos: 'verb', definition: 'Impresionar vivamente por la belleza o el brillo' },
  { word: 'Desparpajo', pos: 'noun', definition: 'Desenvoltura y soltura al hablar o actuar' },
  { word: 'Despuntar', pos: 'verb', definition: 'Empezar a brotar el día o a distinguirse alguien por su talento' },
  { word: 'Destello', pos: 'noun', definition: 'Resplandor vivo y fugaz de luz' },
  { word: 'Desvelo', pos: 'noun', definition: 'Cuidado y esfuerzo puestos con esmero en algo' },
  { word: 'Devaneo', pos: 'noun', definition: 'Distracción pasajera o amorío sin propósito serio' },
  { word: 'Diáfano', pos: 'adjective', definition: 'Claro y transparente, que deja pasar la luz' },
  { word: 'Diatriba', pos: 'noun', definition: 'Discurso o escrito violento e injurioso contra algo' },
  { word: 'Dicha', pos: 'noun', definition: 'Felicidad plena, suerte venturosa' },
  { word: 'Dicharachero', pos: 'adjective', definition: 'Que conversa con gracia, ocurrente y animado' },
  { word: 'Diestramente', pos: 'adverb', definition: 'Con habilidad y destreza' },
  { word: 'Dilapidar', pos: 'verb', definition: 'Malgastar bienes o recursos sin medida' },
  { word: 'Dilecto', pos: 'adjective', definition: 'Amado con especial predilección' },
  { word: 'Diligente', pos: 'adjective', definition: 'Cuidadoso y rápido en hacer lo que debe' },
  { word: 'Dilucidar', pos: 'verb', definition: 'Aclarar un asunto confuso hasta hacerlo comprensible' },
  { word: 'Dirimir', pos: 'verb', definition: 'Resolver una controversia o desacuerdo' },
  { word: 'Discernir', pos: 'verb', definition: 'Distinguir con el juicio una cosa de otra' },
  { word: 'Díscolo', pos: 'adjective', definition: 'Indócil, rebelde a la autoridad o la norma' },
  { word: 'Discurrir', pos: 'verb', definition: 'Reflexionar sobre algo, o fluir el tiempo y las aguas' },
  { word: 'Diseminar', pos: 'verb', definition: 'Esparcir algo por lugares diversos' },
  { word: 'Disquisición', pos: 'noun', definition: 'Examen minucioso o digresión erudita sobre un tema' },
  { word: 'Distendido', pos: 'adjective', definition: 'Relajado, sin tensión ni formalidad' },
  { word: 'Divagar', pos: 'verb', definition: 'Apartarse del asunto dejando vagar el pensamiento' },
  { word: 'Doblez', pos: 'noun', definition: 'Hipocresía, falsedad en el modo de actuar' },
  { word: 'Docto', pos: 'adjective', definition: 'Que posee amplios conocimientos adquiridos con estudio' },
  { word: 'Donaire', pos: 'noun', definition: 'Gracia y gallardía al hablar o moverse' },
  { word: 'Doquier', pos: 'adverb', definition: 'En cualquier parte, por todas partes' },
  { word: 'Dubitativo', pos: 'adjective', definition: 'Que muestra o implica duda' },
  { word: 'Ducho', pos: 'adjective', definition: 'Experimentado y hábil en una materia' },
  { word: 'Duende', pos: 'noun', definition: 'Encanto misterioso e inefable de una persona o arte' },
  { word: 'Ecuánime', pos: 'adjective', definition: 'Imparcial y sereno en el juicio' },
  { word: 'Ecuanimidad', pos: 'noun', definition: 'Serenidad e imparcialidad de ánimo constante' },
  { word: 'Edificante', pos: 'adjective', definition: 'Que da buen ejemplo e inspira virtud' },
  { word: 'Efeméride', pos: 'noun', definition: 'Acontecimiento notable que se recuerda en su aniversario' },
  { word: 'Efervescente', pos: 'adjective', definition: 'Agitado y vivaz, en plena ebullición de ánimo' },
  { word: 'Efigie', pos: 'noun', definition: 'Imagen o representación de una persona' },
  { word: 'Efímero', pos: 'adjective', definition: 'Que dura poco tiempo, pasajero' },
  { word: 'Efusivo', pos: 'adjective', definition: 'Que expresa afecto con intensidad y calidez' },
  { word: 'Égida', pos: 'noun', definition: 'Protección o amparo bajo el que alguien actúa' },
  { word: 'Elocuencia', pos: 'noun', definition: 'Facultad de hablar de modo eficaz para conmover o persuadir' },
  { word: 'Elocuente', pos: 'adjective', definition: 'Que persuade o conmueve con la palabra' },
  { word: 'Elucubrar', pos: 'verb', definition: 'Imaginar o reflexionar con empeño, a veces sin fundamento' },
  { word: 'Emanar', pos: 'verb', definition: 'Desprenderse o proceder de algo como de su origen' },
  { word: 'Embaucar', pos: 'verb', definition: 'Engañar aprovechando la ingenuidad ajena' },
  { word: 'Embelesar', pos: 'verb', definition: 'Cautivar los sentidos hasta suspender el ánimo' },
  { word: 'Embeleso', pos: 'noun', definition: 'Estado de quien queda absorto por el encanto de algo' },
  { word: 'Embriagador', pos: 'adjective', definition: 'Que enajena y deleita los sentidos' },
  { word: 'Enardecer', pos: 'verb', definition: 'Avivar una pasión o el ánimo de alguien' },
  { word: 'Encandilar', pos: 'verb', definition: 'Deslumbrar o despertar admiración fascinada' },
  { word: 'Encauzar', pos: 'verb', definition: 'Dirigir algo por el buen camino' },
  { word: 'Encomiable', pos: 'adjective', definition: 'Digno de alabanza y reconocimiento' },
  { word: 'Encomio', pos: 'noun', definition: 'Alabanza encarecida de los méritos de alguien' },
  { word: 'Encumbrado', pos: 'adjective', definition: 'Elevado a una posición alta o distinguida' },
  { word: 'Endeble', pos: 'adjective', definition: 'Débil, de poca resistencia o consistencia' },
  { word: 'Enigmático', pos: 'adjective', definition: 'Misterioso, difícil de descifrar o comprender' },
  { word: 'Enjundia', pos: 'noun', definition: 'Sustancia e importancia de fondo que tiene algo' },
  { word: 'Enjuto', pos: 'adjective', definition: 'Delgado y seco de carnes' },
  { word: 'Enmendar', pos: 'verb', definition: 'Corregir un error o reparar un daño' },
  { word: 'Ensalzar', pos: 'verb', definition: 'Alabar y engrandecer los méritos de alguien' },
  { word: 'Ensimismado', pos: 'adjective', definition: 'Abstraído en los propios pensamientos' },
  { word: 'Ensoñación', pos: 'noun', definition: 'Fantasía o ilusión en la que se deja vagar la mente' },
  { word: 'Entelequia', pos: 'noun', definition: 'Cosa irreal que solo existe en la imaginación' },
  { word: 'Entereza', pos: 'noun', definition: 'Firmeza de ánimo ante la adversidad' },
  { word: 'Entrañable', pos: 'adjective', definition: 'Íntimo y muy querido, cercano al corazón' },
  { word: 'Entresijo', pos: 'noun', definition: 'Aspecto oculto o interioridad de un asunto' },
  { word: 'Entrever', pos: 'verb', definition: 'Ver confusamente o conjeturar algo por indicios' },
  { word: 'Epifanía', pos: 'noun', definition: 'Manifestación o revelación súbita que ilumina la comprensión' },
  { word: 'Epítome', pos: 'noun', definition: 'Resumen o expresión máxima y ejemplar de algo' },
  { word: 'Equidad', pos: 'noun', definition: 'Justicia que da a cada uno lo que merece' },
  { word: 'Erial', pos: 'noun', definition: 'Tierra sin cultivar ni labrar' },
  { word: 'Erigir', pos: 'verb', definition: 'Fundar o levantar algo con solemnidad' },
  { word: 'Errabundo', pos: 'adjective', definition: 'Que vaga de una parte a otra sin asiento fijo' },
  { word: 'Errante', pos: 'adjective', definition: 'Que anda de un lugar a otro sin domicilio estable' },
  { word: 'Erudito', pos: 'adjective', definition: 'Instruido en profundidad en diversas materias' },
  { word: 'Escarmiento', pos: 'noun', definition: 'Lección severa que enseña a no reincidir' },
  { word: 'Escrutar', pos: 'verb', definition: 'Examinar con atención minuciosa y penetrante' },
  { word: 'Escudriñar', pos: 'verb', definition: 'Examinar con minuciosidad hasta el último rincón' },
  { word: 'Escueto', pos: 'adjective', definition: 'Conciso y despojado de todo adorno' },
  { word: 'Esgrimir', pos: 'verb', definition: 'Emplear un argumento o razón como arma' },
  { word: 'Esmero', pos: 'noun', definition: 'Sumo cuidado puesto en hacer algo bien' },
  { word: 'Espejismo', pos: 'noun', definition: 'Ilusión que hace ver lo que en realidad no existe' },
  { word: 'Espolear', pos: 'verb', definition: 'Estimular con viveza para que se actúe' },
  { word: 'Esquivo', pos: 'adjective', definition: 'Huidizo, que rehúye el trato o el contacto' },
  { word: 'Estentóreo', pos: 'adjective', definition: 'De voz muy fuerte y retumbante' },
  { word: 'Estoicismo', pos: 'noun', definition: 'Fortaleza serena ante la adversidad' },
  { word: 'Estoico', pos: 'adjective', definition: 'Que soporta las desgracias con entereza imperturbable' },
  { word: 'Estrépito', pos: 'noun', definition: 'Ruido grande y aparatoso' },
  { word: 'Estridente', pos: 'adjective', definition: 'Agudo y chirriante, que molesta por su exceso' },
  { word: 'Etéreo', pos: 'adjective', definition: 'Sutil e intangible, como del cielo' },
  { word: 'Eufonía', pos: 'noun', definition: 'Sonoridad agradable de las palabras' },
  { word: 'Evanescente', pos: 'adjective', definition: 'Que se desvanece como el humo' },
  { word: 'Evocar', pos: 'verb', definition: 'Traer algo a la memoria o a la imaginación' },
  { word: 'Exacerbar', pos: 'verb', definition: 'Agravar o avivar una pasión o molestia' },
  { word: 'Exangüe', pos: 'adjective', definition: 'Agotado, sin fuerzas ni aliento' },
  { word: 'Exhortar', pos: 'verb', definition: 'Animar con razones a hacer algo' },
  { word: 'Exiguo', pos: 'adjective', definition: 'Escaso, insuficiente en cantidad' },
  { word: 'Eximio', pos: 'adjective', definition: 'Excelente, de calidad sobresaliente' },
  { word: 'Exordio', pos: 'noun', definition: 'Introducción que prepara el ánimo del oyente' },
  { word: 'Expedito', pos: 'adjective', definition: 'Libre de estorbos, pronto para actuar' },
  { word: 'Exuberante', pos: 'adjective', definition: 'Abundante y frondoso en extremo' },
  { word: 'Exultante', pos: 'adjective', definition: 'Que muestra una alegría desbordante' },
  { word: 'Falaz', pos: 'adjective', definition: 'Engañoso, que induce a error con apariencia de verdad' },
  { word: 'Fárrago', pos: 'noun', definition: 'Conjunto desordenado y confuso de cosas o ideas' },
  { word: 'Fastuoso', pos: 'adjective', definition: 'De lujo y ostentación deslumbrantes' },
  { word: 'Fatuo', pos: 'adjective', definition: 'Presuntuoso y vano, sin fundamento para serlo' },
  { word: 'Faz', pos: 'noun', definition: 'Rostro o superficie visible de algo' },
  { word: 'Febril', pos: 'adjective', definition: 'Agitado e intenso, como movido por la fiebre' },
  { word: 'Fecundo', pos: 'adjective', definition: 'Que produce con abundancia, fértil en frutos u obras' },
  { word: 'Fehaciente', pos: 'adjective', definition: 'Que prueba algo de forma indudable' },
  { word: 'Feraz', pos: 'adjective', definition: 'Dicho de la tierra, muy fértil y productiva' },
  { word: 'Férreo', pos: 'adjective', definition: 'Duro y tenaz como el hierro' },
  { word: 'Ferviente', pos: 'adjective', definition: 'Que siente o muestra un entusiasmo ardiente' },
  { word: 'Fervientemente', pos: 'adverb', definition: 'Con ardor y devoción intensos' },
  { word: 'Fervor', pos: 'noun', definition: 'Entusiasmo ardiente y devoto por algo' },
  { word: 'Festín', pos: 'noun', definition: 'Banquete espléndido y celebración abundante' },
  { word: 'Fidedigno', pos: 'adjective', definition: 'Digno de fe y de crédito' },
  { word: 'Filantropía', pos: 'noun', definition: 'Amor al género humano expresado en obras generosas' },
  { word: 'Filigrana', pos: 'noun', definition: 'Obra de delicadeza y primor exquisitos' },
  { word: 'Flamante', pos: 'adjective', definition: 'Nuevo y reluciente, recién estrenado' },
  { word: 'Flemático', pos: 'adjective', definition: 'Imperturbable, de calma que nada altera' },
  { word: 'Fogoso', pos: 'adjective', definition: 'Ardiente e impetuoso en el sentir o el actuar' },
  { word: 'Fortuito', pos: 'adjective', definition: 'Que sucede por casualidad, sin previsión' },
  { word: 'Fragor', pos: 'noun', definition: 'Ruido estruendoso, como el de la batalla o la tormenta' },
  { word: 'Fraguar', pos: 'verb', definition: 'Idear y dar forma a un plan o proyecto' },
  { word: 'Franquear', pos: 'verb', definition: 'Abrir paso, dejar libre el camino' },
  { word: 'Frenesí', pos: 'noun', definition: 'Exaltación violenta y apasionada del ánimo' },
  { word: 'Frondoso', pos: 'adjective', definition: 'Abundante en hojas y ramas' },
  { word: 'Frugal', pos: 'adjective', definition: 'Moderado y sencillo en la comida y el gasto' },
  { word: 'Fruición', pos: 'noun', definition: 'Goce intenso con que se disfruta algo' },
  { word: 'Fugaz', pos: 'adjective', definition: 'Que dura un instante y desaparece veloz' },
  { word: 'Fugazmente', pos: 'adverb', definition: 'De manera breve y pasajera, por un instante' },
  { word: 'Fulgor', pos: 'noun', definition: 'Resplandor brillante y vivo' },
  { word: 'Fulgurante', pos: 'adjective', definition: 'Que brilla o avanza con la rapidez del relámpago' },
  { word: 'Furtivo', pos: 'adjective', definition: 'Hecho a escondidas, sin ser visto' },
  { word: 'Fútil', pos: 'adjective', definition: 'De escasa importancia o sustancia' },
  { word: 'Galante', pos: 'adjective', definition: 'Atento y cortés, especialmente con las damas' },
  { word: 'Gallardamente', pos: 'adverb', definition: 'Con elegancia, valor y bizarría' },
  { word: 'Gallardía', pos: 'noun', definition: 'Elegancia y valentía en el porte y el ánimo' },
  { word: 'Garbo', pos: 'noun', definition: 'Gracia y desenvoltura al moverse o actuar' },
  { word: 'Garboso', pos: 'adjective', definition: 'Que se mueve con gracia, gallardía y soltura' },
  { word: 'Gélido', pos: 'adjective', definition: 'Helado, extremadamente frío' },
  { word: 'Gentil', pos: 'adjective', definition: 'Amable y cortés, de trato exquisito' },
  { word: 'Germinar', pos: 'verb', definition: 'Comenzar a brotar y desarrollarse algo' },
  { word: 'Gesta', pos: 'noun', definition: 'Hazaña memorable digna de ser cantada' },
  { word: 'Gestar', pos: 'verb', definition: 'Preparar o desarrollar algo hasta su nacimiento' },
  { word: 'Gozo', pos: 'noun', definition: 'Alegría honda que llena el ánimo' },
  { word: 'Grácil', pos: 'adjective', definition: 'Sutil, delicado y ligero en su forma' },
  { word: 'Grandilocuente', pos: 'adjective', definition: 'Que habla con solemnidad excesiva y afectada' },
  { word: 'Gregario', pos: 'adjective', definition: 'Que sigue al grupo sin criterio propio' },
  { word: 'Guarecer', pos: 'verb', definition: 'Acoger o dar refugio contra un peligro' },
  { word: 'Hálito', pos: 'noun', definition: 'Aliento suave o soplo tenue de vida' },
  { word: 'Hastío', pos: 'noun', definition: 'Tedio profundo, cansancio del ánimo' },
  { word: 'Hedonismo', pos: 'noun', definition: 'Búsqueda del placer como fin supremo de la vida' },
  { word: 'Heraldo', pos: 'noun', definition: 'Mensajero que anuncia algo venidero' },
  { word: 'Hercúleo', pos: 'adjective', definition: 'De fuerza descomunal, digna de Hércules' },
  { word: 'Hermético', pos: 'adjective', definition: 'Impenetrable, cerrado a toda comprensión' },
  { word: 'Hidalguía', pos: 'noun', definition: 'Nobleza y generosidad de ánimo' },
  { word: 'Hierático', pos: 'adjective', definition: 'De solemnidad rígida que no deja traslucir emoción' },
  { word: 'Hilvanar', pos: 'verb', definition: 'Enlazar ideas o palabras con soltura y coherencia' },
  { word: 'Hito', pos: 'noun', definition: 'Acontecimiento que marca un punto clave en un desarrollo' },
  { word: 'Hogaño', pos: 'adverb', definition: 'En este año o en la época presente' },
  { word: 'Holgadamente', pos: 'adverb', definition: 'Con amplitud y desahogo, sin apuros' },
  { word: 'Holgura', pos: 'noun', definition: 'Amplitud y desahogo, bienestar sin estrecheces' },
  { word: 'Hondura', pos: 'noun', definition: 'Profundidad de algo, en especial del pensamiento' },
  { word: 'Horadar', pos: 'verb', definition: 'Atravesar algo de parte a parte haciendo un agujero' },
  { word: 'Hosco', pos: 'adjective', definition: 'Áspero e intratable en el gesto y el trato' },
  { word: 'Hospitalario', pos: 'adjective', definition: 'Que acoge con generosidad y agrado a los demás' },
  { word: 'Huraño', pos: 'adjective', definition: 'Que rehúye el trato y la compañía de la gente' },
  { word: 'Idílico', pos: 'adjective', definition: 'Encantador y apacible como un sueño pastoril' },
  { word: 'Idiosincrasia', pos: 'noun', definition: 'Modo de ser distintivo de una persona o colectividad' },
  { word: 'Ignoto', pos: 'adjective', definition: 'Desconocido, aún no descubierto' },
  { word: 'Ilación', pos: 'noun', definition: 'Enlace lógico y ordenado de las ideas' },
  { word: 'Imberbe', pos: 'adjective', definition: 'Joven al que aún no le ha salido la barba' },
  { word: 'Imbuir', pos: 'verb', definition: 'Infundir en el ánimo una idea o sentimiento' },
  { word: 'Impasible', pos: 'adjective', definition: 'Que no muestra ni deja traslucir emoción alguna' },
  { word: 'Impávido', pos: 'adjective', definition: 'Sereno ante el peligro, sin asomo de temor' },
  { word: 'Imperecedero', pos: 'adjective', definition: 'Que no perece, inmortal en el recuerdo' },
  { word: 'Impertérrito', pos: 'adjective', definition: 'Que nada logra intimidar ni alterar' },
  { word: 'Ímpetu', pos: 'noun', definition: 'Fuerza y energía con que se acomete algo' },
  { word: 'Impoluto', pos: 'adjective', definition: 'Limpio y sin mancha alguna' },
  { word: 'Imponderable', pos: 'adjective', definition: 'Que no puede medirse ni preverse' },
  { word: 'Impregnar', pos: 'verb', definition: 'Empapar o penetrar algo por completo' },
  { word: 'Ímprobo', pos: 'adjective', definition: 'Dicho de un esfuerzo, enorme y continuado' },
  { word: 'Impronta', pos: 'noun', definition: 'Huella o sello característico que algo deja' },
  { word: 'Inasible', pos: 'adjective', definition: 'Que no se puede asir ni atrapar' },
  { word: 'Inaudito', pos: 'adjective', definition: 'Nunca oído, sorprendente por insólito' },
  { word: 'Incauto', pos: 'adjective', definition: 'Que actúa sin cautela ni malicia, fácil de engañar' },
  { word: 'Incipiente', pos: 'adjective', definition: 'Que apenas empieza a manifestarse' },
  { word: 'Inclemencia', pos: 'noun', definition: 'Rigor severo, especialmente del tiempo atmosférico' },
  { word: 'Incólume', pos: 'adjective', definition: 'Sano y sin daño alguno tras un percance' },
  { word: 'Inconmensurable', pos: 'adjective', definition: 'Tan grande que no puede medirse' },
  { word: 'Indeleble', pos: 'adjective', definition: 'Que no se puede borrar ni quitar' },
  { word: 'Indolencia', pos: 'noun', definition: 'Apatía que rehúye el esfuerzo y el cuidado' },
  { word: 'Indolente', pos: 'adjective', definition: 'Perezoso, insensible al esfuerzo y al deber' },
  { word: 'Indómito', pos: 'adjective', definition: 'Que no se deja domar ni someter' },
  { word: 'Inefable', pos: 'adjective', definition: 'Tan sublime que no puede expresarse con palabras' },
  { word: 'Ineluctable', pos: 'adjective', definition: 'Contra lo que no se puede luchar, inevitable' },
  { word: 'Inescrutable', pos: 'adjective', definition: 'Que no se puede averiguar ni penetrar' },
  { word: 'Inexorable', pos: 'adjective', definition: 'Que no se deja vencer por ruegos, implacable' },
  { word: 'Inexorablemente', pos: 'adverb', definition: 'De forma implacable e inevitable' },
  { word: 'Infatigable', pos: 'adjective', definition: 'Incapaz de cansarse o rendirse' },
  { word: 'Ingente', pos: 'adjective', definition: 'Muy grande, de magnitud extraordinaria' },
  { word: 'Inhóspito', pos: 'adjective', definition: 'Poco acogedor, incómodo para ser habitado' },
  { word: 'Inmarcesible', pos: 'adjective', definition: 'Que no puede marchitarse' },
  { word: 'Inmutable', pos: 'adjective', definition: 'Que no cambia ni puede cambiar' },
  { word: 'Inopia', pos: 'noun', definition: 'Ignorancia de lo que ocurre alrededor' },
  { word: 'Inopinadamente', pos: 'adverb', definition: 'De forma inesperada, sin haberlo previsto' },
  { word: 'Inquebrantable', pos: 'adjective', definition: 'Que persiste sin quebrarse ni ceder' },
  { word: 'Insigne', pos: 'adjective', definition: 'Célebre y distinguido por sus méritos' },
  { word: 'Insólito', pos: 'adjective', definition: 'Raro y desacostumbrado, fuera de lo común' },
  { word: 'Insondable', pos: 'adjective', definition: 'De profundidad imposible de alcanzar o comprender' },
  { word: 'Intachable', pos: 'adjective', definition: 'Sin falta ni defecto que reprochar' },
  { word: 'Interludio', pos: 'noun', definition: 'Pausa o intervalo entre dos momentos' },
  { word: 'Intrépido', pos: 'adjective', definition: 'Que no teme el peligro y lo afronta con arrojo' },
  { word: 'Intrincado', pos: 'adjective', definition: 'Enredado y complicado, difícil de desentrañar' },
  { word: 'Inusitado', pos: 'adjective', definition: 'No habitual, extraordinario por infrecuente' },
  { word: 'Irisado', pos: 'adjective', definition: 'Que brilla con los colores del arco iris' },
  { word: 'Irradiar', pos: 'verb', definition: 'Despedir luz, calor o influencia en todas direcciones' },
  { word: 'Itinerante', pos: 'adjective', definition: 'Que va de un lugar a otro sin sede fija' },
  { word: 'Jactancia', pos: 'noun', definition: 'Alabanza presuntuosa de uno mismo' },
  { word: 'Jalonar', pos: 'verb', definition: 'Marcar el curso de algo con hitos señalados' },
  { word: 'Jarana', pos: 'noun', definition: 'Diversión bulliciosa y festiva' },
  { word: 'Jocoso', pos: 'adjective', definition: 'Gracioso, festivo y dado a la broma' },
  { word: 'Jolgorio', pos: 'noun', definition: 'Regocijo ruidoso y celebración animada' },
  { word: 'Jovial', pos: 'adjective', definition: 'Alegre, festivo y de buen humor' },
  { word: 'Júbilo', pos: 'noun', definition: 'Alegría intensa que se manifiesta con signos exteriores' },
  { word: 'Jubiloso', pos: 'adjective', definition: 'Lleno de una alegría que desborda' },
  { word: 'Juicioso', pos: 'adjective', definition: 'Que obra con madurez y buen juicio' },
  { word: 'Lacónico', pos: 'adjective', definition: 'Breve y conciso en el hablar o escribir' },
  { word: 'Ladino', pos: 'adjective', definition: 'Astuto y sagaz para lograr sus propósitos' },
  { word: 'Lánguidamente', pos: 'adverb', definition: 'Con suavidad decaída y sin vigor' },
  { word: 'Languidecer', pos: 'verb', definition: 'Perder vigor, ánimo o lozanía poco a poco' },
  { word: 'Lánguido', pos: 'adjective', definition: 'Débil y decaído, falto de energía' },
  { word: 'Lapidario', pos: 'adjective', definition: 'Dicho de una frase, concisa y digna de grabarse en piedra' },
  { word: 'Largueza', pos: 'noun', definition: 'Generosidad en dar sin reparo' },
  { word: 'Lasitud', pos: 'noun', definition: 'Cansancio y falta de fuerzas' },
  { word: 'Latente', pos: 'adjective', definition: 'Oculto pero presente, a la espera de manifestarse' },
  { word: 'Laudable', pos: 'adjective', definition: 'Digno de alabanza' },
  { word: 'Lenitivo', pos: 'noun', definition: 'Aquello que suaviza o alivia un padecimiento' },
  { word: 'Letargo', pos: 'noun', definition: 'Sopor profundo, suspensión prolongada de la actividad' },
  { word: 'Levedad', pos: 'noun', definition: 'Ligereza suave, cualidad de lo que apenas pesa' },
  { word: 'Libérrimo', pos: 'adjective', definition: 'Absolutamente libre, sin traba alguna' },
  { word: 'Lid', pos: 'noun', definition: 'Combate o disputa en que se contiende' },
  { word: 'Liviano', pos: 'adjective', definition: 'Ligero de peso o de poca gravedad' },
  { word: 'Loable', pos: 'adjective', definition: 'Que merece elogio y reconocimiento' },
  { word: 'Locuaz', pos: 'adjective', definition: 'Que habla mucho y con desenvoltura' },
  { word: 'Longevo', pos: 'adjective', definition: 'Que alcanza una edad muy avanzada' },
  { word: 'Lontananza', pos: 'noun', definition: 'Lejanía, término más distante de lo que se ve' },
  { word: 'Lozano', pos: 'adjective', definition: 'De frescura, verdor y vigor juveniles' },
  { word: 'Lucidez', pos: 'noun', definition: 'Claridad de razonamiento y comprensión' },
  { word: 'Lúcido', pos: 'adjective', definition: 'Claro en el razonamiento y la expresión' },
  { word: 'Luctuoso', pos: 'adjective', definition: 'Triste y digno de llanto' },
  { word: 'Lustre', pos: 'noun', definition: 'Brillo o esplendor que realza y distingue' },
  { word: 'Magnanimidad', pos: 'noun', definition: 'Grandeza de ánimo para perdonar y dar con generosidad' },
  { word: 'Magnánimo', pos: 'adjective', definition: 'De ánimo grande y generoso, inclinado a perdonar' },
  { word: 'Majestuoso', pos: 'adjective', definition: 'De grandeza imponente que inspira admiración' },
  { word: 'Malograr', pos: 'verb', definition: 'Frustrar algo antes de que llegue a su plenitud' },
  { word: 'Mancillar', pos: 'verb', definition: 'Manchar la honra o la buena fama' },
  { word: 'Mansamente', pos: 'adverb', definition: 'Con suavidad y sosiego, sin brusquedad' },
  { word: 'Mansedumbre', pos: 'noun', definition: 'Suavidad y docilidad apacible del carácter' },
  { word: 'Maquinar', pos: 'verb', definition: 'Tramar algo oculta y arteramente' },
  { word: 'Marchito', pos: 'adjective', definition: 'Ajado, que ha perdido la frescura y lozanía' },
  { word: 'Mecenas', pos: 'noun', definition: 'Protector generoso de artistas y sabios' },
  { word: 'Meditabundo', pos: 'adjective', definition: 'Absorto en profunda meditación' },
  { word: 'Melancolía', pos: 'noun', definition: 'Tristeza suave y sosegada, de causa imprecisa' },
  { word: 'Melifluo', pos: 'adjective', definition: 'Dulce y suave en exceso, como la miel' },
  { word: 'Menester', pos: 'noun', definition: 'Necesidad, ocupación o quehacer propio' },
  { word: 'Menguar', pos: 'verb', definition: 'Disminuir o irse reduciendo poco a poco' },
  { word: 'Menoscabo', pos: 'noun', definition: 'Daño o merma en el valor o la estima de algo' },
  { word: 'Mesura', pos: 'noun', definition: 'Moderación y compostura en el actuar' },
  { word: 'Meticuloso', pos: 'adjective', definition: 'Que actúa con minuciosidad y esmero extremos' },
  { word: 'Miríada', pos: 'noun', definition: 'Cantidad inmensa e incontable de cosas' },
  { word: 'Mitigar', pos: 'verb', definition: 'Suavizar o aplacar la dureza de algo' },
  { word: 'Modorra', pos: 'noun', definition: 'Somnolencia pesada que entorpece los sentidos' },
  { word: 'Mohíno', pos: 'adjective', definition: 'Triste, disgustado y de mal talante' },
  { word: 'Mordaz', pos: 'adjective', definition: 'Que critica con ingenio afilado e hiriente' },
  { word: 'Morriña', pos: 'noun', definition: 'Nostalgia de la tierra propia y de los suyos' },
  { word: 'Mortecino', pos: 'adjective', definition: 'Apagado, de luz o vitalidad casi extinguida' },
  { word: 'Mudanza', pos: 'noun', definition: 'Cambio o inconstancia en el ánimo o la fortuna' },
  { word: 'Munificencia', pos: 'noun', definition: 'Generosidad espléndida en dar' },
  { word: 'Murmullo', pos: 'noun', definition: 'Rumor suave y continuado de voces o aguas' },
  { word: 'Musitar', pos: 'verb', definition: 'Susurrar o hablar entre dientes, apenas audible' },
  { word: 'Mustio', pos: 'adjective', definition: 'Marchito y lánguido, o triste sin brillo' },
  { word: 'Nadería', pos: 'noun', definition: 'Cosa de poquísima importancia o valor' },
  { word: 'Nefando', pos: 'adjective', definition: 'Tan indigno que no puede mencionarse sin repugnancia' },
  { word: 'Nefasto', pos: 'adjective', definition: 'Funesto, que trae desgracia o resulta muy malo' },
  { word: 'Nimiedad', pos: 'noun', definition: 'Pequeñez insignificante que no merece atención' },
  { word: 'Nimio', pos: 'adjective', definition: 'Insignificante, de mínima importancia' },
  { word: 'Nítidamente', pos: 'adverb', definition: 'Con claridad y limpieza perfectas' },
  { word: 'Nítido', pos: 'adjective', definition: 'Limpio, claro y bien definido' },
  { word: 'Noctámbulo', pos: 'adjective', definition: 'Que gusta de vivir y andar de noche' },
  { word: 'Novel', pos: 'adjective', definition: 'Que se inicia en una actividad, principiante' },
  { word: 'Numen', pos: 'noun', definition: 'Inspiración creadora del artista o poeta' },
  { word: 'Obcecado', pos: 'adjective', definition: 'Cegado por una idea fija que no admite razones' },
  { word: 'Obnubilar', pos: 'verb', definition: 'Nublar el entendimiento o la razón' },
  { word: 'Obsequioso', pos: 'adjective', definition: 'Excesivamente atento y dispuesto a complacer' },
  { word: 'Ocaso', pos: 'noun', definition: 'Puesta del sol o declive final de algo' },
  { word: 'Ocurrente', pos: 'adjective', definition: 'Ingenioso, de respuestas agudas e inesperadas' },
  { word: 'Ofuscar', pos: 'verb', definition: 'Turbar la razón o confundir las ideas' },
  { word: 'Ojeriza', pos: 'noun', definition: 'Antipatía persistente hacia alguien' },
  { word: 'Omnisciente', pos: 'adjective', definition: 'Que lo sabe y lo conoce todo' },
  { word: 'Onírico', pos: 'adjective', definition: 'Propio de los sueños o semejante a ellos' },
  { word: 'Opalescente', pos: 'adjective', definition: 'De reflejos irisados y lechosos como el ópalo' },
  { word: 'Oprobio', pos: 'noun', definition: 'Deshonra pública y vergonzosa' },
  { word: 'Opulencia', pos: 'noun', definition: 'Abundancia y riqueza extremas' },
  { word: 'Oráculo', pos: 'noun', definition: 'Respuesta o persona cuya palabra se tiene por sabia e infalible' },
  { word: 'Orfebrería', pos: 'noun', definition: 'Arte de labrar con primor metales preciosos' },
  { word: 'Orondo', pos: 'adjective', definition: 'Satisfecho y ufano de sí mismo' },
  { word: 'Oropel', pos: 'noun', definition: 'Apariencia brillante pero de escaso valor' },
  { word: 'Osadía', pos: 'noun', definition: 'Atrevimiento audaz, resolución sin miedo' },
  { word: 'Ostensible', pos: 'adjective', definition: 'Manifiesto, patente a la vista de todos' },
  { word: 'Ostracismo', pos: 'noun', definition: 'Exclusión o apartamiento del trato y la vida pública' },
  { word: 'Otear', pos: 'verb', definition: 'Escudriñar el horizonte desde un lugar alto' },
  { word: 'Otrora', pos: 'adverb', definition: 'En otro tiempo, antiguamente' },
  { word: 'Pábulo', pos: 'noun', definition: 'Alimento o motivo que aviva un rumor o pasión' },
  { word: 'Paladín', pos: 'noun', definition: 'Defensor esforzado de una causa noble' },
  { word: 'Palmario', pos: 'adjective', definition: 'Claro, evidente y manifiesto' },
  { word: 'Panacea', pos: 'noun', definition: 'Remedio que se supone capaz de curarlo todo' },
  { word: 'Parabién', pos: 'noun', definition: 'Felicitación que se da por un éxito' },
  { word: 'Paradisíaco', pos: 'adjective', definition: 'Delicioso y placentero como el paraíso' },
  { word: 'Parangón', pos: 'noun', definition: 'Comparación que mide algo con lo mejor' },
  { word: 'Parcamente', pos: 'adverb', definition: 'Con sobriedad y escasez de palabras' },
  { word: 'Parco', pos: 'adjective', definition: 'Sobrio y moderado, escaso en palabras' },
  { word: 'Parsimonia', pos: 'noun', definition: 'Calma y lentitud deliberadas en el actuar' },
  { word: 'Pasmoso', pos: 'adjective', definition: 'Que causa asombro y admiración extremos' },
  { word: 'Pátina', pos: 'noun', definition: 'Tono suave que el tiempo deposita sobre las cosas' },
  { word: 'Paulatinamente', pos: 'adverb', definition: 'Poco a poco, de manera gradual' },
  { word: 'Paulatino', pos: 'adjective', definition: 'Que procede o se produce lentamente, por grados' },
  { word: 'Perdurable', pos: 'adjective', definition: 'Que dura mucho tiempo o para siempre' },
  { word: 'Peregrino', pos: 'adjective', definition: 'Extraño, singular y pocas veces visto' },
  { word: 'Perenne', pos: 'adjective', definition: 'Continuo e incesante, que no muere' },
  { word: 'Perentorio', pos: 'adjective', definition: 'Urgente y que no admite demora' },
  { word: 'Pergeñar', pos: 'verb', definition: 'Trazar o disponer algo con cierta habilidad' },
  { word: 'Pericia', pos: 'noun', definition: 'Habilidad y destreza adquiridas con la experiencia' },
  { word: 'Periplo', pos: 'noun', definition: 'Viaje largo, por lo común con regreso al punto de partida' },
  { word: 'Pernicioso', pos: 'adjective', definition: 'Gravemente dañoso y perjudicial' },
  { word: 'Perorata', pos: 'noun', definition: 'Discurso largo y pesado, inoportuno para quien lo oye' },
  { word: 'Perspicacia', pos: 'noun', definition: 'Agudeza para percibir lo que a otros se les escapa' },
  { word: 'Perspicaz', pos: 'adjective', definition: 'De entendimiento agudo y penetrante' },
  { word: 'Pertinaz', pos: 'adjective', definition: 'Obstinado y persistente, que no cede' },
  { word: 'Pesadumbre', pos: 'noun', definition: 'Pesar hondo que aflige el ánimo' },
  { word: 'Pesaroso', pos: 'adjective', definition: 'Apenado y arrepentido por algo' },
  { word: 'Pétreo', pos: 'adjective', definition: 'De piedra o duro e inconmovible como ella' },
  { word: 'Pintoresco', pos: 'adjective', definition: 'Peculiar y vistoso, digno de ser pintado' },
  { word: 'Plácidamente', pos: 'adverb', definition: 'Con sosiego y tranquilidad gratas' },
  { word: 'Placidez', pos: 'noun', definition: 'Sosiego y calma apacibles' },
  { word: 'Plácido', pos: 'adjective', definition: 'Sosegado y grato, sin perturbación' },
  { word: 'Plausible', pos: 'adjective', definition: 'Digno de aplauso o admisible por atendible' },
  { word: 'Plegaria', pos: 'noun', definition: 'Súplica ferviente y humilde' },
  { word: 'Plenitud', pos: 'noun', definition: 'Punto de máxima intensidad o perfección de algo' },
  { word: 'Pléyade', pos: 'noun', definition: 'Grupo de personas ilustres que brillan en una misma época' },
  { word: 'Ponderar', pos: 'verb', definition: 'Sopesar con cuidado o alabar encarecidamente' },
  { word: 'Ponzoña', pos: 'noun', definition: 'Veneno o influencia dañina y corruptora' },
  { word: 'Portento', pos: 'noun', definition: 'Persona o cosa admirable por sus cualidades extraordinarias' },
  { word: 'Portentoso', pos: 'adjective', definition: 'Singular y extraordinario, que causa admiración' },
  { word: 'Postrero', pos: 'adjective', definition: 'Último en una serie u orden' },
  { word: 'Preclaro', pos: 'adjective', definition: 'Ilustre y digno de admiración por sus méritos' },
  { word: 'Prestamente', pos: 'adverb', definition: 'Con prontitud y diligencia' },
  { word: 'Presteza', pos: 'noun', definition: 'Prontitud y diligencia en hacer algo' },
  { word: 'Primoroso', pos: 'adjective', definition: 'Hecho con delicadeza, esmero y perfección' },
  { word: 'Prístino', pos: 'adjective', definition: 'Original y puro, tal como fue en su primer estado' },
  { word: 'Probidad', pos: 'noun', definition: 'Honradez e integridad intachables' },
  { word: 'Proceloso', pos: 'adjective', definition: 'Tormentoso y agitado, lleno de borrascas' },
  { word: 'Prodigar', pos: 'verb', definition: 'Dar con abundancia y generosidad' },
  { word: 'Prodigioso', pos: 'adjective', definition: 'Maravilloso, que excede lo natural' },
  { word: 'Proeza', pos: 'noun', definition: 'Hazaña de gran valor o esfuerzo' },
  { word: 'Prolífico', pos: 'adjective', definition: 'Que produce obras o frutos en abundancia' },
  { word: 'Prolijo', pos: 'adjective', definition: 'Extenso y detallado hasta el exceso' },
  { word: 'Propicio', pos: 'adjective', definition: 'Favorable para que algo suceda o se logre' },
  { word: 'Prosaico', pos: 'adjective', definition: 'Vulgar y falto de elevación, sin poesía' },
  { word: 'Proverbial', pos: 'adjective', definition: 'Muy conocido de todos, como un proverbio' },
  { word: 'Pujante', pos: 'adjective', definition: 'Que crece o avanza con fuerza y vigor' },
  { word: 'Pujanza', pos: 'noun', definition: 'Fuerza vigorosa con que algo crece o se impulsa' },
  { word: 'Pulcritud', pos: 'noun', definition: 'Esmero extremo en la limpieza y el cuidado' },
  { word: 'Pulcro', pos: 'adjective', definition: 'Aseado, esmerado y cuidado hasta el detalle' },
  { word: 'Pulular', pos: 'verb', definition: 'Abundar y bullir en un lugar personas o cosas' },
  { word: 'Pundonor', pos: 'noun', definition: 'Amor propio que impulsa a quedar bien ante los demás' },
  { word: 'Pusilánime', pos: 'adjective', definition: 'Falto de ánimo y valor para afrontar retos' },
  { word: 'Quebranto', pos: 'noun', definition: 'Pérdida o daño grande, aflicción honda' },
  { word: 'Quedamente', pos: 'adverb', definition: 'En voz baja, con suavidad silenciosa' },
  { word: 'Quejumbroso', pos: 'adjective', definition: 'Que se lamenta con frecuencia y tono plañidero' },
  { word: 'Querencia', pos: 'noun', definition: 'Apego al lugar donde uno se ha criado o se siente seguro' },
  { word: 'Quietud', pos: 'noun', definition: 'Sosiego y reposo sin movimiento ni ruido' },
  { word: 'Quimera', pos: 'noun', definition: 'Ilusión imposible que se persigue como real' },
  { word: 'Quimérico', pos: 'adjective', definition: 'Fabuloso e irrealizable, propio de la fantasía' },
  { word: 'Quisquilloso', pos: 'adjective', definition: 'Que se ofende o repara en pequeñeces' },
  { word: 'Raigambre', pos: 'noun', definition: 'Conjunto de raíces y tradiciones que dan firmeza a algo' },
  { word: 'Raudal', pos: 'noun', definition: 'Abundancia que fluye con ímpetu, como agua desbordada' },
  { word: 'Raudo', pos: 'adjective', definition: 'Rápido, veloz y precipitado' },
  { word: 'Rebosante', pos: 'adjective', definition: 'Tan lleno que desborda' },
  { word: 'Recabar', pos: 'verb', definition: 'Conseguir algo mediante súplicas o gestiones' },
  { word: 'Recalcitrante', pos: 'adjective', definition: 'Obstinado en la resistencia, reacio a cambiar' },
  { word: 'Recatado', pos: 'adjective', definition: 'Modesto y prudente en el comportamiento' },
  { word: 'Recio', pos: 'adjective', definition: 'Fuerte, robusto y de firme temple' },
  { word: 'Recodo', pos: 'noun', definition: 'Ángulo o vuelta cerrada de un camino o río' },
  { word: 'Recóndito', pos: 'adjective', definition: 'Muy escondido, reservado y oculto' },
  { word: 'Redimir', pos: 'verb', definition: 'Librar de una pena, esclavitud o mala situación' },
  { word: 'Refulgente', pos: 'adjective', definition: 'Que emite un resplandor brillante' },
  { word: 'Refulgir', pos: 'verb', definition: 'Resplandecer con brillo intenso' },
  { word: 'Regazo', pos: 'noun', definition: 'Cobijo amoroso que acoge y ampara' },
  { word: 'Regocijo', pos: 'noun', definition: 'Alegría expansiva que se celebra y comparte' },
  { word: 'Relente', pos: 'noun', definition: 'Humedad fresca de las noches serenas' },
  { word: 'Remanso', pos: 'noun', definition: 'Lugar de calma donde se detiene la corriente' },
  { word: 'Remembranza', pos: 'noun', definition: 'Recuerdo que se trae a la memoria con nostalgia' },
  { word: 'Rememorar', pos: 'verb', definition: 'Recordar con detenimiento algo pasado' },
  { word: 'Remozar', pos: 'verb', definition: 'Dar aspecto nuevo y lozano a algo' },
  { word: 'Rencilla', pos: 'noun', definition: 'Riña menor que deja resentimiento' },
  { word: 'Renombre', pos: 'noun', definition: 'Fama y celebridad ganadas por los méritos' },
  { word: 'Reposado', pos: 'adjective', definition: 'Sosegado, tranquilo y sin prisa' },
  { word: 'Requiebro', pos: 'noun', definition: 'Piropo o palabra galante para halagar' },
  { word: 'Resarcir', pos: 'verb', definition: 'Compensar un daño, perjuicio o agravio' },
  { word: 'Resiliencia', pos: 'noun', definition: 'Capacidad de sobreponerse a la adversidad' },
  { word: 'Resquicio', pos: 'noun', definition: 'Abertura pequeña o pequeña ocasión que se ofrece' },
  { word: 'Retahíla', pos: 'noun', definition: 'Serie larga de cosas que se suceden sin orden' },
  { word: 'Reticente', pos: 'adjective', definition: 'Reservado y desconfiado, que calla parte de lo que piensa' },
  { word: 'Retozar', pos: 'verb', definition: 'Saltar y corretear alegremente en señal de júbilo' },
  { word: 'Rezagado', pos: 'adjective', definition: 'Que se queda atrás respecto de los demás' },
  { word: 'Rezumar', pos: 'verb', definition: 'Dejar escapar un líquido o una cualidad por los poros' },
  { word: 'Rielar', pos: 'verb', definition: 'Brillar con luz trémula, como la luna sobre el agua' },
  { word: 'Risueño', pos: 'adjective', definition: 'Que muestra risa en el semblante, favorable y alegre' },
  { word: 'Rocambolesco', pos: 'adjective', definition: 'Extraordinario y enrevesado hasta lo inverosímil' },
  { word: 'Rozagante', pos: 'adjective', definition: 'Vistoso, saludable y de aspecto satisfecho' },
  { word: 'Rutilante', pos: 'adjective', definition: 'Que brilla y resplandece como un astro' },
  { word: 'Sagacidad', pos: 'noun', definition: 'Astucia y agudeza para prever y advertir' },
  { word: 'Sagaz', pos: 'adjective', definition: 'Avisado y astuto, que prevé con agudeza' },
  { word: 'Sagazmente', pos: 'adverb', definition: 'Con astucia y penetración' },
  { word: 'Sazón', pos: 'noun', definition: 'Punto de madurez o momento oportuno de algo' },
  { word: 'Sedoso', pos: 'adjective', definition: 'Suave al tacto como la seda' },
  { word: 'Sempiterno', pos: 'adjective', definition: 'Que durará siempre, sin fin' },
  { word: 'Señero', pos: 'adjective', definition: 'Único y sin par, que destaca solo' },
  { word: 'Serendipia', pos: 'noun', definition: 'Hallazgo valioso que ocurre por casualidad afortunada' },
  { word: 'Sesudo', pos: 'adjective', definition: 'Juicioso, profundo y reflexivo' },
  { word: 'Sibarita', pos: 'noun', definition: 'Persona de gustos refinados dada a los placeres exquisitos' },
  { word: 'Sibilino', pos: 'adjective', definition: 'Misterioso y de sentido oculto, como los oráculos' },
  { word: 'Sigilo', pos: 'noun', definition: 'Silencio y secreto cuidadosos con que se hace algo' },
  { word: 'Sigilosamente', pos: 'adverb', definition: 'En silencio y sin ser advertido' },
  { word: 'Sino', pos: 'noun', definition: 'Destino o fuerza que parece regir la vida' },
  { word: 'Sinsabor', pos: 'noun', definition: 'Pesar o disgusto que amarga el ánimo' },
  { word: 'Sobrecogedor', pos: 'adjective', definition: 'Que sorprende e intimida por su intensidad' },
  { word: 'Sobremanera', pos: 'adverb', definition: 'Muchísimo, más allá de toda medida' },
  { word: 'Sobremesa', pos: 'noun', definition: 'Tiempo de conversación que sigue a la comida compartida' },
  { word: 'Socarrón', pos: 'adjective', definition: 'Burlón con disimulo e ironía tranquila' },
  { word: 'Socavar', pos: 'verb', definition: 'Debilitar algo minando su base' },
  { word: 'Solaz', pos: 'noun', definition: 'Descanso placentero y esparcimiento del ánimo' },
  { word: 'Solícito', pos: 'adjective', definition: 'Diligente y atento en el cuidado de los demás' },
  { word: 'Soliloquio', pos: 'noun', definition: 'Reflexión en voz alta y a solas consigo mismo' },
  { word: 'Somero', pos: 'adjective', definition: 'Superficial, hecho por encima y sin detenimiento' },
  { word: 'Sopesar', pos: 'verb', definition: 'Examinar con cuidado el pro y el contra de algo' },
  { word: 'Sopor', pos: 'noun', definition: 'Adormecimiento pesado de los sentidos' },
  { word: 'Sortilegio', pos: 'noun', definition: 'Hechizo o encanto que parece obra de magia' },
  { word: 'Sosegadamente', pos: 'adverb', definition: 'Con calma y tranquilidad reposadas' },
  { word: 'Sosegado', pos: 'adjective', definition: 'Quieto, pacífico y sin agitación' },
  { word: 'Sosiego', pos: 'noun', definition: 'Quietud y serenidad del ánimo' },
  { word: 'Soslayar', pos: 'verb', definition: 'Evitar una dificultad pasando de lado' },
  { word: 'Súbitamente', pos: 'adverb', definition: 'De repente, sin aviso previo' },
  { word: 'Sublime', pos: 'adjective', definition: 'De elevación y belleza que sobrecogen' },
  { word: 'Sucinto', pos: 'adjective', definition: 'Breve y resumido en lo esencial' },
  { word: 'Suntuoso', pos: 'adjective', definition: 'De gran lujo, magnificencia y coste' },
  { word: 'Superfluo', pos: 'adjective', definition: 'Innecesario, que sobra por no hacer falta' },
  { word: 'Surcar', pos: 'verb', definition: 'Atravesar un medio dejando estela, como la nave el mar' },
  { word: 'Sutileza', pos: 'noun', definition: 'Finura delicada de ingenio o de matiz' },
  { word: 'Sutilmente', pos: 'adverb', definition: 'Con delicadeza apenas perceptible' },
  { word: 'Tácitamente', pos: 'adverb', definition: 'Sin expresarlo con palabras, de modo sobreentendido' },
  { word: 'Tácito', pos: 'adjective', definition: 'Que se entiende sin necesidad de decirse' },
  { word: 'Taciturno', pos: 'adjective', definition: 'Callado y melancólico, poco dado a hablar' },
  { word: 'Talante', pos: 'noun', definition: 'Disposición de ánimo con que se hace o recibe algo' },
  { word: 'Talismán', pos: 'noun', definition: 'Objeto al que se atribuye poder protector' },
  { word: 'Tañer', pos: 'verb', definition: 'Tocar un instrumento de cuerda o una campana' },
  { word: 'Templanza', pos: 'noun', definition: 'Moderación serena en los apetitos y pasiones' },
  { word: 'Temple', pos: 'noun', definition: 'Fortaleza serena para afrontar dificultades' },
  { word: 'Tenacidad', pos: 'noun', definition: 'Firmeza persistente en un propósito' },
  { word: 'Tenaz', pos: 'adjective', definition: 'Firme y persistente en un propósito' },
  { word: 'Tenazmente', pos: 'adverb', definition: 'Con persistencia firme que no se rinde' },
  { word: 'Tenue', pos: 'adjective', definition: 'Delicado, débil y sutil' },
  { word: 'Tenuemente', pos: 'adverb', definition: 'Con suavidad débil y delicada' },
  { word: 'Terso', pos: 'adjective', definition: 'Liso, limpio y resplandeciente' },
  { word: 'Tersura', pos: 'noun', definition: 'Lisura suave y limpia de una superficie' },
  { word: 'Tertulia', pos: 'noun', definition: 'Reunión habitual para conversar sobre temas diversos' },
  { word: 'Tesitura', pos: 'noun', definition: 'Circunstancia o situación en que alguien se halla' },
  { word: 'Tesón', pos: 'noun', definition: 'Constancia firme y empeñosa en lo que se emprende' },
  { word: 'Titánico', pos: 'adjective', definition: 'Desmesurado, de esfuerzo o proporciones gigantescas' },
  { word: 'Titilar', pos: 'verb', definition: 'Centellear con leve temblor, como las estrellas' },
  { word: 'Torbellino', pos: 'noun', definition: 'Remolino impetuoso de viento o de sucesos' },
  { word: 'Tórrido', pos: 'adjective', definition: 'Muy ardiente, de calor sofocante' },
  { word: 'Tortuoso', pos: 'adjective', definition: 'Lleno de vueltas y rodeos, poco directo' },
  { word: 'Trajín', pos: 'noun', definition: 'Ajetreo de idas y venidas incesantes' },
  { word: 'Traslucir', pos: 'verb', definition: 'Dejarse ver o adivinar algo a través de indicios' },
  { word: 'Trémulo', pos: 'adjective', definition: 'Que tiembla ligeramente, como la luz de una vela' },
  { word: 'Trepidante', pos: 'adjective', definition: 'Agitado y veloz, que no da tregua' },
  { word: 'Tribulación', pos: 'noun', definition: 'Congoja o adversidad que aflige el ánimo' },
  { word: 'Trocar', pos: 'verb', definition: 'Cambiar una cosa por otra, transformar' },
  { word: 'Trovador', pos: 'noun', definition: 'Poeta que componía y cantaba versos de amor' },
  { word: 'Truculento', pos: 'adjective', definition: 'Que sobrecoge por su crudeza excesiva' },
  { word: 'Ubérrimo', pos: 'adjective', definition: 'Extraordinariamente fértil y abundante' },
  { word: 'Ubicuo', pos: 'adjective', definition: 'Que parece estar presente en todas partes a la vez' },
  { word: 'Ufanamente', pos: 'adverb', definition: 'Con orgullo y satisfacción visibles' },
  { word: 'Ufano', pos: 'adjective', definition: 'Satisfecho y orgulloso de sí o de lo suyo' },
  { word: 'Ulterior', pos: 'adjective', definition: 'Que sucede o se dice después de algo' },
  { word: 'Umbral', pos: 'noun', definition: 'Paso de entrada o comienzo de algo nuevo' },
  { word: 'Umbrío', pos: 'adjective', definition: 'Sombreado, donde apenas llega el sol' },
  { word: 'Urdir', pos: 'verb', definition: 'Tramar con cautela un plan o intriga' },
  { word: 'Utopía', pos: 'noun', definition: 'Ideal perfecto pero irrealizable' },
  { word: 'Vagar', pos: 'verb', definition: 'Andar por diversos lugares sin rumbo determinado' },
  { word: 'Vanagloria', pos: 'noun', definition: 'Presunción vana por los propios méritos' },
  { word: 'Vasto', pos: 'adjective', definition: 'Muy extenso o muy grande' },
  { word: 'Vaticinio', pos: 'noun', definition: 'Predicción o anuncio de lo que ha de venir' },
  { word: 'Vehemencia', pos: 'noun', definition: 'Ímpetu apasionado con que se siente o dice algo' },
  { word: 'Vehemente', pos: 'adjective', definition: 'Que siente o se expresa con pasión impetuosa' },
  { word: 'Veladamente', pos: 'adverb', definition: 'De manera encubierta, sin decirlo abiertamente' },
  { word: 'Veleidad', pos: 'noun', definition: 'Capricho inconstante, deseo pasajero' },
  { word: 'Venerable', pos: 'adjective', definition: 'Digno de respeto profundo por su edad o virtud' },
  { word: 'Venerar', pos: 'verb', definition: 'Sentir y mostrar respeto profundo por alguien o algo' },
  { word: 'Ventura', pos: 'noun', definition: 'Felicidad, buena suerte o azar favorable' },
  { word: 'Venturoso', pos: 'adjective', definition: 'Afortunado, que trae o goza de felicidad' },
  { word: 'Verbigracia', pos: 'adverb', definition: 'Por ejemplo, para ilustrar lo dicho' },
  { word: 'Vergel', pos: 'noun', definition: 'Huerto florido y frondoso, jardín deleitoso' },
  { word: 'Vernáculo', pos: 'adjective', definition: 'Propio del país o lugar de origen, en especial la lengua' },
  { word: 'Verosímil', pos: 'adjective', definition: 'Creíble por tener apariencia de verdad' },
  { word: 'Vestigio', pos: 'noun', definition: 'Huella o señal que queda de algo pasado' },
  { word: 'Vetusto', pos: 'adjective', definition: 'Muy viejo y anticuado, marcado por los años' },
  { word: 'Vicisitud', pos: 'noun', definition: 'Alternancia de sucesos prósperos y adversos' },
  { word: 'Vilipendiar', pos: 'verb', definition: 'Despreciar o tratar con indignidad a alguien' },
  { word: 'Virtuosismo', pos: 'noun', definition: 'Dominio extraordinario de la técnica de un arte' },
  { word: 'Vislumbrar', pos: 'verb', definition: 'Ver algo apenas, o conjeturarlo por leves indicios' },
  { word: 'Vivaz', pos: 'adjective', definition: 'De ingenio agudo y vitalidad pronta' },
  { word: 'Vocinglero', pos: 'adjective', definition: 'Que habla muy alto y sin sustancia' },
  { word: 'Voluble', pos: 'adjective', definition: 'De ánimo cambiante e inconstante' },
  { word: 'Voluptuoso', pos: 'adjective', definition: 'Que inclina o se entrega a los placeres de los sentidos' },
  { word: 'Vorágine', pos: 'noun', definition: 'Remolino impetuoso que arrastra cuanto alcanza' },
  { word: 'Yermo', pos: 'adjective', definition: 'Despoblado e inhabitado, sin cultivo' },
  { word: 'Yerro', pos: 'noun', definition: 'Equivocación o falta cometida por descuido' },
  { word: 'Yuxtaponer', pos: 'verb', definition: 'Poner una cosa junto a otra sin nexo que las una' },
  { word: 'Zafio', pos: 'adjective', definition: 'Tosco e inculto en los modales' },
  { word: 'Zaguán', pos: 'noun', definition: 'Espacio cubierto a la entrada de una casa' },
  { word: 'Zaherir', pos: 'verb', definition: 'Mortificar a alguien con reproches o burlas' },
  { word: 'Zalamería', pos: 'noun', definition: 'Halago empalagoso hecho para ganarse a alguien' },
  { word: 'Zanjar', pos: 'verb', definition: 'Resolver de manera definitiva una dificultad' },
  { word: 'Zarandear', pos: 'verb', definition: 'Sacudir o mover a alguien o algo con energía' },
  { word: 'Zascandil', pos: 'noun', definition: 'Persona enredadora, informal y de poco asiento' },
  { word: 'Zozobra', pos: 'noun', definition: 'Inquietud angustiosa ante un peligro o incertidumbre' },
  { word: 'Zurcir', pos: 'verb', definition: 'Coser con puntadas finas la rotura de un tejido' },
];
