import type { WordEntry } from './types';

/**
 * fr-FR "Word of the Day" seed list — 732 entries (2 × 366) so the
 * selection cycle in word-of-day-data.ts covers two full years without
 * a repeat. Kept alphabetized (accents folded for ordering):
 * presentation order comes from the year-seeded shuffle, so storage
 * order is purely for maintenance.
 */
export const FR_FR_WORDS: WordEntry[] = [
  { word: 'Abasourdir', pos: 'verb', definition: 'Étourdir par un grand bruit ou stupéfier profondément' },
  { word: 'Abhorrer', pos: 'verb', definition: 'Avoir en horreur, détester au plus haut point' },
  { word: 'Abnégation', pos: 'noun', definition: 'Sacrifice volontaire de soi au profit des autres' },
  { word: 'Abscons', pos: 'adjective', definition: 'Difficile à comprendre, obscur pour le lecteur' },
  { word: 'Absoudre', pos: 'verb', definition: 'Pardonner une faute, en délier son auteur' },
  { word: 'Acabit', pos: 'noun', definition: 'Nature ou qualité, souvent avec nuance péjorative' },
  { word: 'Acariâtre', pos: 'adjective', definition: 'De caractère grincheux et difficile à vivre' },
  { word: 'Accalmie', pos: 'noun', definition: 'Calme momentané après une période agitée' },
  { word: 'Accort', pos: 'adjective', definition: 'Aimable, gracieux et avenant' },
  { word: 'Acerbe', pos: 'adjective', definition: 'Mordant et blessant dans le propos' },
  { word: 'Acmé', pos: 'noun', definition: 'Point culminant, sommet du développement' },
  { word: 'Acuité', pos: 'noun', definition: 'Finesse de perception ou intensité aiguë' },
  { word: 'Adamantin', pos: 'adjective', definition: 'Qui a la dureté ou le brillant du diamant' },
  { word: 'Admonester', pos: 'verb', definition: 'Réprimander sévèrement mais sans sanction' },
  { word: 'Aduler', pos: 'verb', definition: 'Témoigner une admiration excessive et flatteuse' },
  { word: 'Affable', pos: 'adjective', definition: 'Qui accueille autrui avec douceur et bienveillance' },
  { word: 'Affres', pos: 'noun', definition: 'Angoisses profondes, tourments extrêmes' },
  { word: 'Agapes', pos: 'noun', definition: 'Festin joyeux partagé entre amis' },
  { word: 'Agreste', pos: 'adjective', definition: 'Qui a le charme rustique de la campagne' },
  { word: 'Aguerrir', pos: 'verb', definition: 'Endurcir par des épreuves répétées' },
  { word: 'Ahurissant', pos: 'adjective', definition: 'Qui frappe de stupeur tant il surprend' },
  { word: 'Alacrité', pos: 'noun', definition: 'Vivacité joyeuse et entraînante' },
  { word: 'Alambiqué', pos: 'adjective', definition: 'Compliqué et contourné à l\'excès' },
  { word: 'Albâtre', pos: 'noun', definition: 'Pierre translucide symbole de blancheur parfaite' },
  { word: 'Alcôve', pos: 'noun', definition: 'Renfoncement intime abritant un lit' },
  { word: 'Alentour', pos: 'adverb', definition: 'Dans les environs, tout autour' },
  { word: 'Allégorie', pos: 'noun', definition: 'Représentation concrète d\'une idée abstraite' },
  { word: 'Allègrement', pos: 'adverb', definition: 'Avec entrain et vivacité joyeuse' },
  { word: 'Allégresse', pos: 'noun', definition: 'Joie vive qui se manifeste ouvertement' },
  { word: 'Altier', pos: 'adjective', definition: 'Qui a une fierté noble et hautaine' },
  { word: 'Altruisme', pos: 'noun', definition: 'Disposition à se soucier du bien des autres' },
  { word: 'Ambivalent', pos: 'adjective', definition: 'Qui réunit deux aspects ou sentiments opposés' },
  { word: 'Ambroisie', pos: 'noun', definition: 'Nourriture des dieux, mets exquis' },
  { word: 'Amène', pos: 'adjective', definition: 'Agréable, courtois et plein de douceur' },
  { word: 'Aménité', pos: 'noun', definition: 'Amabilité pleine de charme et de douceur' },
  { word: 'Amphigourique', pos: 'adjective', definition: 'Confus et embrouillé jusqu\'au ridicule' },
  { word: 'Anachorète', pos: 'noun', definition: 'Ermite retiré du monde pour méditer' },
  { word: 'Anfractuosité', pos: 'noun', definition: 'Creux profond et irrégulier dans la roche' },
  { word: 'Anodin', pos: 'adjective', definition: 'Sans importance ni danger, insignifiant' },
  { word: 'Antédiluvien', pos: 'adjective', definition: 'Extrêmement ancien, démodé depuis longtemps' },
  { word: 'Antienne', pos: 'noun', definition: 'Refrain répété inlassablement' },
  { word: 'Apaiser', pos: 'verb', definition: 'Ramener au calme, adoucir une douleur' },
  { word: 'Apanage', pos: 'noun', definition: 'Privilège exclusif propre à quelqu\'un' },
  { word: 'Aphorisme', pos: 'noun', definition: 'Formule brève résumant une vérité' },
  { word: 'Apocryphe', pos: 'adjective', definition: 'Dont l\'authenticité est douteuse' },
  { word: 'Apogée', pos: 'noun', definition: 'Point le plus élevé, sommet de la gloire' },
  { word: 'Apologue', pos: 'noun', definition: 'Court récit dont se dégage une morale' },
  { word: 'Aporie', pos: 'noun', definition: 'Contradiction insoluble dans un raisonnement' },
  { word: 'Apothéose', pos: 'noun', definition: 'Triomphe final, consécration éclatante' },
  { word: 'Âpre', pos: 'adjective', definition: 'Rude au goût ou dur dans la lutte' },
  { word: 'Aquilon', pos: 'noun', definition: 'Vent du nord, froid et violent, cher aux poètes' },
  { word: 'Arabesque', pos: 'noun', definition: 'Ligne ornementale aux courbes entrelacées' },
  { word: 'Arcane', pos: 'noun', definition: 'Secret réservé aux initiés' },
  { word: 'Ardeur', pos: 'noun', definition: 'Énergie vive et enthousiaste mise dans une action' },
  { word: 'Argutie', pos: 'noun', definition: 'Raisonnement subtil mais creux, chicane verbale' },
  { word: 'Assidûment', pos: 'adverb', definition: 'Avec une régularité constante et appliquée' },
  { word: 'Atavique', pos: 'adjective', definition: 'Hérité des ancêtres lointains' },
  { word: 'Atermoiement', pos: 'noun', definition: 'Action de remettre sans cesse à plus tard' },
  { word: 'Atrabilaire', pos: 'adjective', definition: 'D\'humeur sombre et irascible' },
  { word: 'Attenant', pos: 'adjective', definition: 'Qui touche, contigu à autre chose' },
  { word: 'Aubade', pos: 'noun', definition: 'Concert donné à l\'aube sous les fenêtres' },
  { word: 'Auguste', pos: 'adjective', definition: 'Qui inspire un respect solennel' },
  { word: 'Auspices', pos: 'noun', definition: 'Circonstances qui laissent présager la suite' },
  { word: 'Austère', pos: 'adjective', definition: 'Sévère et dépouillé, sans ornement ni plaisir' },
  { word: 'Autarcie', pos: 'noun', definition: 'État de qui se suffit à soi-même' },
  { word: 'Avanie', pos: 'noun', definition: 'Affront public, humiliation infligée' },
  { word: 'Avenant', pos: 'adjective', definition: 'Qui plaît par sa grâce et sa bonne mine' },
  { word: 'Axiome', pos: 'noun', definition: 'Vérité admise sans démonstration' },
  { word: 'Azur', pos: 'noun', definition: 'Bleu clair et lumineux du ciel' },
  { word: 'Badin', pos: 'adjective', definition: 'Qui plaisante avec une gaieté légère' },
  { word: 'Badinage', pos: 'noun', definition: 'Propos léger et enjoué, jeu spirituel' },
  { word: 'Bagatelle', pos: 'noun', definition: 'Chose futile et sans importance' },
  { word: 'Baguenauder', pos: 'verb', definition: 'Se promener en flânant, sans occupation sérieuse' },
  { word: 'Balbutier', pos: 'verb', definition: 'Articuler avec hésitation, parler confusément' },
  { word: 'Baliverne', pos: 'noun', definition: 'Propos futile et sans fondement' },
  { word: 'Balsamique', pos: 'adjective', definition: 'Qui exhale un parfum doux et apaisant' },
  { word: 'Barguigner', pos: 'verb', definition: 'Hésiter longuement avant de se décider' },
  { word: 'Bariolé', pos: 'adjective', definition: 'Couvert de couleurs vives et variées' },
  { word: 'Baroque', pos: 'adjective', definition: 'D\'une irrégularité étrange et exubérante' },
  { word: 'Batifoler', pos: 'verb', definition: 'Jouer et folâtrer avec insouciance' },
  { word: 'Béatitude', pos: 'noun', definition: 'Bonheur parfait et serein' },
  { word: 'Bénin', pos: 'adjective', definition: 'Sans gravité, doux et inoffensif' },
  { word: 'Besogneux', pos: 'adjective', definition: 'Qui travaille durement pour un maigre profit' },
  { word: 'Bienveillance', pos: 'noun', definition: 'Disposition favorable et indulgente envers autrui' },
  { word: 'Billevesée', pos: 'noun', definition: 'Idée creuse, propos vide de sens' },
  { word: 'Blafard', pos: 'adjective', definition: 'D\'une pâleur terne et sans éclat' },
  { word: 'Bonhomie', pos: 'noun', definition: 'Simplicité aimable et bon enfant' },
  { word: 'Boréal', pos: 'adjective', definition: 'Propre aux régions du grand Nord' },
  { word: 'Boudoir', pos: 'noun', definition: 'Petit salon élégant et intime' },
  { word: 'Bougon', pos: 'adjective', definition: 'Qui grommelle son mécontentement sans méchanceté' },
  { word: 'Bourgeonner', pos: 'verb', definition: 'Se couvrir de bourgeons, promettre la floraison' },
  { word: 'Bourlinguer', pos: 'verb', definition: 'Voyager beaucoup en menant une vie aventureuse' },
  { word: 'Brasier', pos: 'noun', definition: 'Feu ardent aux braises incandescentes' },
  { word: 'Bravache', pos: 'adjective', definition: 'Qui affiche un courage de façade' },
  { word: 'Bravoure', pos: 'noun', definition: 'Courage éclatant au cœur du danger' },
  { word: 'Brocarder', pos: 'verb', definition: 'Railler par des moqueries piquantes' },
  { word: 'Bruine', pos: 'noun', definition: 'Pluie très fine et froide qui tombe lentement' },
  { word: 'Bruissement', pos: 'noun', definition: 'Murmure léger et confus, comme celui des feuilles' },
  { word: 'Bucolique', pos: 'adjective', definition: 'Qui évoque la douceur de la vie champêtre' },
  { word: 'Burlesque', pos: 'adjective', definition: 'D\'un comique extravagant et outré' },
  { word: 'Byzantin', pos: 'adjective', definition: 'D\'une complication excessive et oiseuse' },
  { word: 'Cabotin', pos: 'noun', definition: 'Comédien qui cherche à se faire remarquer' },
  { word: 'Cacophonie', pos: 'noun', definition: 'Mélange discordant de sons désagréables' },
  { word: 'Caduc', pos: 'adjective', definition: 'Qui a cessé d\'être valable ou actuel' },
  { word: 'Cajoler', pos: 'verb', definition: 'Entourer de tendresse et de paroles douces' },
  { word: 'Calembour', pos: 'noun', definition: 'Jeu de mots fondé sur une ressemblance de sons' },
  { word: 'Calfeutrer', pos: 'verb', definition: 'Boucher les fentes pour se protéger du froid' },
  { word: 'Calligraphie', pos: 'noun', definition: 'Art de former une écriture élégante' },
  { word: 'Candeur', pos: 'noun', definition: 'Pureté naïve et confiante de l\'âme' },
  { word: 'Candide', pos: 'adjective', definition: 'D\'une innocence pure et sans détour' },
  { word: 'Capiteux', pos: 'adjective', definition: 'Qui monte à la tête et enivre les sens' },
  { word: 'Captieux', pos: 'adjective', definition: 'Qui cherche à tromper par de faux raisonnements' },
  { word: 'Carmin', pos: 'noun', definition: 'Rouge éclatant et profond' },
  { word: 'Cartésien', pos: 'adjective', definition: 'Qui raisonne avec méthode et logique' },
  { word: 'Casanier', pos: 'adjective', definition: 'Qui aime rester chez soi' },
  { word: 'Céans', pos: 'adverb', definition: 'Ici même, dans cette maison' },
  { word: 'Célérité', pos: 'noun', definition: 'Rapidité dans l\'exécution' },
  { word: 'Cénacle', pos: 'noun', definition: 'Cercle restreint de personnes partageant les mêmes idées' },
  { word: 'Chafouin', pos: 'adjective', definition: 'À la mine sournoise et rusée' },
  { word: 'Chamarré', pos: 'adjective', definition: 'Orné de couleurs éclatantes et surchargées' },
  { word: 'Chanceler', pos: 'verb', definition: 'Vaciller sur ses bases, menacer de tomber' },
  { word: 'Charivari', pos: 'noun', definition: 'Tapage joyeux et désordonné' },
  { word: 'Chatoyant', pos: 'adjective', definition: 'Qui brille de reflets changeants' },
  { word: 'Chenu', pos: 'adjective', definition: 'Blanchi par le grand âge' },
  { word: 'Chimère', pos: 'noun', definition: 'Rêve irréalisable, illusion séduisante' },
  { word: 'Chuchotis', pos: 'noun', definition: 'Léger bruit de voix qui chuchotent' },
  { word: 'Circonlocution', pos: 'noun', definition: 'Manière détournée de dire les choses' },
  { word: 'Circonspect', pos: 'adjective', definition: 'Qui agit avec prudence et réflexion' },
  { word: 'Ciseler', pos: 'verb', definition: 'Travailler avec un soin minutieux du détail' },
  { word: 'Clairsemé', pos: 'adjective', definition: 'Répandu de façon éparse et peu dense' },
  { word: 'Clapoter', pos: 'verb', definition: 'Faire un léger bruit de vagues qui se croisent' },
  { word: 'Clémence', pos: 'noun', definition: 'Indulgence de qui pourrait punir' },
  { word: 'Cocagne', pos: 'noun', definition: 'Pays imaginaire où tout abonde' },
  { word: 'Coi', pos: 'adjective', definition: 'Silencieux et immobile de saisissement' },
  { word: 'Commensal', pos: 'noun', definition: 'Compagnon de table habituel' },
  { word: 'Componction', pos: 'noun', definition: 'Gravité affectée et cérémonieuse' },
  { word: 'Concis', pos: 'adjective', definition: 'Qui exprime beaucoup en peu de mots' },
  { word: 'Concorde', pos: 'noun', definition: 'Bonne entente et paix entre les personnes' },
  { word: 'Confins', pos: 'noun', definition: 'Limites extrêmes d\'un territoire' },
  { word: 'Conjecture', pos: 'noun', definition: 'Supposition fondée sur des indices incomplets' },
  { word: 'Connivence', pos: 'noun', definition: 'Entente secrète et complice' },
  { word: 'Contempler', pos: 'verb', definition: 'Regarder longuement avec admiration' },
  { word: 'Contrition', pos: 'noun', definition: 'Regret sincère d\'une faute commise' },
  { word: 'Copieusement', pos: 'adverb', definition: 'En grande abondance' },
  { word: 'Coquecigrue', pos: 'noun', definition: 'Absurdité, chose chimérique et sans valeur' },
  { word: 'Coruscant', pos: 'adjective', definition: 'Qui brille avec éclat, étincelant' },
  { word: 'Cosmopolite', pos: 'adjective', definition: 'Ouvert à toutes les cultures du monde' },
  { word: 'Courroux', pos: 'noun', definition: 'Colère noble et véhémente' },
  { word: 'Courtois', pos: 'adjective', definition: 'D\'une politesse raffinée et élégante' },
  { word: 'Crépiter', pos: 'verb', definition: 'Faire une suite de petits bruits secs' },
  { word: 'Crépuscule', pos: 'noun', definition: 'Lumière déclinante entre le jour et la nuit' },
  { word: 'Cristallin', pos: 'adjective', definition: 'Pur et clair comme le cristal' },
  { word: 'Cryptique', pos: 'adjective', definition: 'Dont le sens demeure caché, énigmatique' },
  { word: 'Dantesque', pos: 'adjective', definition: 'D\'une démesure grandiose et effrayante' },
  { word: 'Déambuler', pos: 'verb', definition: 'Marcher sans but précis, au gré de sa fantaisie' },
  { word: 'Débonnaire', pos: 'adjective', definition: 'D\'une bonté paisible et sans façon' },
  { word: 'Débusquer', pos: 'verb', definition: 'Faire sortir de sa cachette' },
  { word: 'Déceler', pos: 'verb', definition: 'Découvrir ce qui était caché ou peu visible' },
  { word: 'Déconcertant', pos: 'adjective', definition: 'Qui surprend au point de faire perdre contenance' },
  { word: 'Décorum', pos: 'noun', definition: 'Ensemble des convenances et du cérémonial' },
  { word: 'Dédale', pos: 'noun', definition: 'Enchevêtrement de chemins où l\'on se perd' },
  { word: 'Déférence', pos: 'noun', definition: 'Respect marqué par des égards particuliers' },
  { word: 'Délectable', pos: 'adjective', definition: 'Qui procure un plaisir exquis' },
  { word: 'Délétère', pos: 'adjective', definition: 'Qui nuit sournoisement, corrupteur' },
  { word: 'Déliquescence', pos: 'noun', definition: 'Décadence progressive, décomposition lente' },
  { word: 'Dénouement', pos: 'noun', definition: 'Manière dont se résout une intrigue' },
  { word: 'Dépaysement', pos: 'noun', definition: 'Sentiment étrange et charmant du changement de cadre' },
  { word: 'Derechef', pos: 'adverb', definition: 'Une nouvelle fois, encore une fois' },
  { word: 'Dérisoire', pos: 'adjective', definition: 'Si insignifiant qu\'il prête à sourire' },
  { word: 'Désaltérer', pos: 'verb', definition: 'Apaiser la soif' },
  { word: 'Désinvolture', pos: 'noun', definition: 'Liberté un peu insolente dans les manières' },
  { word: 'Dessein', pos: 'noun', definition: 'Projet mûrement formé, intention profonde' },
  { word: 'Dessiller', pos: 'verb', definition: 'Ouvrir les yeux de quelqu\'un sur la vérité' },
  { word: 'Désuet', pos: 'adjective', definition: 'Passé de mode, au charme un peu ancien' },
  { word: 'Diaphane', pos: 'adjective', definition: 'Qui laisse filtrer la lumière sans être transparent' },
  { word: 'Diatribe', pos: 'noun', definition: 'Critique violente et injurieuse' },
  { word: 'Digression', pos: 'noun', definition: 'Développement qui s\'écarte du sujet' },
  { word: 'Dilettante', pos: 'noun', definition: 'Personne qui pratique un art pour le seul plaisir' },
  { word: 'Diligent', pos: 'adjective', definition: 'Qui agit avec zèle, soin et promptitude' },
  { word: 'Disert', pos: 'adjective', definition: 'Qui parle avec aisance et élégance' },
  { word: 'Dispendieux', pos: 'adjective', definition: 'Qui exige une grande dépense' },
  { word: 'Dithyrambique', pos: 'adjective', definition: 'D\'un enthousiasme excessif dans la louange' },
  { word: 'Dodeliner', pos: 'verb', definition: 'Balancer doucement la tête' },
  { word: 'Dolent', pos: 'adjective', definition: 'Qui exprime une plainte douce et languissante' },
  { word: 'Doucereux', pos: 'adjective', definition: 'D\'une douceur affectée et hypocrite' },
  { word: 'Draconien', pos: 'adjective', definition: 'D\'une sévérité extrême et inflexible' },
  { word: 'Dulcinée', pos: 'noun', definition: 'Femme aimée et idéalisée, par plaisanterie tendre' },
  { word: 'Duplicité', pos: 'noun', definition: 'Caractère de qui joue double jeu' },
  { word: 'Ébaubi', pos: 'adjective', definition: 'Frappé d\'un étonnement qui laisse bouche bée' },
  { word: 'Éblouir', pos: 'verb', definition: 'Frapper la vue ou l\'esprit par un vif éclat' },
  { word: 'Ébouriffant', pos: 'adjective', definition: 'Extraordinaire au point de décoiffer' },
  { word: 'Écarlate', pos: 'adjective', definition: 'D\'un rouge éclatant et vif' },
  { word: 'Écarquiller', pos: 'verb', definition: 'Ouvrir les yeux tout grands de surprise' },
  { word: 'Éclectique', pos: 'adjective', definition: 'Qui puise avec goût dans des genres variés' },
  { word: 'Éclore', pos: 'verb', definition: 'Naître en s\'ouvrant, comme une fleur ou une idée' },
  { word: 'Écrin', pos: 'noun', definition: 'Coffret précieux, cadre qui met en valeur' },
  { word: 'Édénique', pos: 'adjective', definition: 'Digne du paradis terrestre' },
  { word: 'Édifiant', pos: 'adjective', definition: 'Qui porte à la vertu par son exemple' },
  { word: 'Effluve', pos: 'noun', definition: 'Émanation subtile qui se dégage des corps' },
  { word: 'Effronté', pos: 'adjective', definition: 'D\'une audace insolente et sans honte' },
  { word: 'Égayer', pos: 'verb', definition: 'Rendre gai, animer d\'une note joyeuse' },
  { word: 'Égérie', pos: 'noun', definition: 'Inspiratrice d\'un artiste ou d\'un créateur' },
  { word: 'Élégamment', pos: 'adverb', definition: 'Avec grâce et distinction' },
  { word: 'Élégiaque', pos: 'adjective', definition: 'Empreint d\'une mélancolie tendre et poétique' },
  { word: 'Éloge', pos: 'noun', definition: 'Discours qui célèbre les mérites de quelqu\'un' },
  { word: 'Éloquence', pos: 'noun', definition: 'Art de toucher et de convaincre par la parole' },
  { word: 'Élucubration', pos: 'noun', definition: 'Théorie laborieuse et extravagante' },
  { word: 'Émaner', pos: 'verb', definition: 'Se dégager, provenir comme une émanation' },
  { word: 'Embaumer', pos: 'verb', definition: 'Remplir l\'air d\'une odeur suave' },
  { word: 'Embellie', pos: 'noun', definition: 'Amélioration passagère, éclaircie bienvenue' },
  { word: 'Emberlificoter', pos: 'verb', definition: 'Embrouiller quelqu\'un pour mieux le tromper' },
  { word: 'Embruns', pos: 'noun', definition: 'Fine pluie marine soulevée par les vagues' },
  { word: 'Émérite', pos: 'adjective', definition: 'D\'une compétence éprouvée par une longue pratique' },
  { word: 'Émerveiller', pos: 'verb', definition: 'Remplir d\'un étonnement admiratif' },
  { word: 'Empyrée', pos: 'noun', definition: 'Partie la plus haute du ciel, séjour des dieux' },
  { word: 'Enchanteur', pos: 'adjective', definition: 'Qui séduit comme par magie' },
  { word: 'Enjôler', pos: 'verb', definition: 'Séduire par des paroles flatteuses et habiles' },
  { word: 'Enjoué', pos: 'adjective', definition: 'D\'une gaieté aimable et légère' },
  { word: 'Enluminure', pos: 'noun', definition: 'Ornement peint des manuscrits anciens' },
  { word: 'Ensorceler', pos: 'verb', definition: 'Captiver comme par un sortilège' },
  { word: 'Entêtant', pos: 'adjective', definition: 'Qui monte à la tête et ne vous quitte plus' },
  { word: 'Éperdument', pos: 'adverb', definition: 'Avec une passion folle et sans mesure' },
  { word: 'Éphémère', pos: 'adjective', definition: 'Qui ne dure qu\'un temps très bref' },
  { word: 'Épicurien', pos: 'adjective', definition: 'Qui recherche les plaisirs avec raffinement' },
  { word: 'Épigone', pos: 'noun', definition: 'Successeur sans originalité d\'un grand créateur' },
  { word: 'Épiphanie', pos: 'noun', definition: 'Révélation soudaine et lumineuse' },
  { word: 'Épistolaire', pos: 'adjective', definition: 'Relatif à l\'art de la correspondance' },
  { word: 'Épris', pos: 'adjective', definition: 'Saisi de passion pour quelqu\'un ou quelque chose' },
  { word: 'Équanimité', pos: 'noun', definition: 'Égalité d\'humeur, sérénité constante' },
  { word: 'Ergoter', pos: 'verb', definition: 'Chicaner sur des détails insignifiants' },
  { word: 'Errance', pos: 'noun', definition: 'Voyage sans but fixe, vagabondage rêveur' },
  { word: 'Érudit', pos: 'adjective', definition: 'D\'un savoir vaste et approfondi' },
  { word: 'Escamoter', pos: 'verb', definition: 'Faire disparaître avec une adresse de prestidigitateur' },
  { word: 'Escarpé', pos: 'adjective', definition: 'En pente raide, difficile à gravir' },
  { word: 'Ésotérique', pos: 'adjective', definition: 'Réservé aux seuls initiés' },
  { word: 'Espiègle', pos: 'adjective', definition: 'D\'une malice vive et sans méchanceté' },
  { word: 'Esquisser', pos: 'verb', definition: 'Tracer les premières lignes, ébaucher' },
  { word: 'Estival', pos: 'adjective', definition: 'Propre à la saison chaude' },
  { word: 'Éthéré', pos: 'adjective', definition: 'D\'une pureté légère et presque immatérielle' },
  { word: 'Étinceler', pos: 'verb', definition: 'Briller de mille feux' },
  { word: 'Étreinte', pos: 'noun', definition: 'Action de serrer dans ses bras' },
  { word: 'Euphonie', pos: 'noun', definition: 'Harmonie agréable de sons qui se suivent' },
  { word: 'Évanescent', pos: 'adjective', definition: 'Qui s\'efface et disparaît comme une fumée' },
  { word: 'Exalter', pos: 'verb', definition: 'Élever très haut, enflammer l\'enthousiasme' },
  { word: 'Exaucer', pos: 'verb', definition: 'Accueillir favorablement un vœu ou une prière' },
  { word: 'Exégèse', pos: 'noun', definition: 'Interprétation savante d\'un texte' },
  { word: 'Exhorter', pos: 'verb', definition: 'Encourager vivement par la parole' },
  { word: 'Expier', pos: 'verb', definition: 'Réparer une faute par la peine subie' },
  { word: 'Exquis', pos: 'adjective', definition: 'D\'une délicatesse rare et raffinée' },
  { word: 'Extatique', pos: 'adjective', definition: 'Transporté par un ravissement intense' },
  { word: 'Exubérant', pos: 'adjective', definition: 'Qui déborde de vitalité et de fantaisie' },
  { word: 'Facétieux', pos: 'adjective', definition: 'Porté à la plaisanterie malicieuse' },
  { word: 'Faconde', pos: 'noun', definition: 'Abondance de paroles, éloquence facile' },
  { word: 'Fadaise', pos: 'noun', definition: 'Propos plat et insignifiant' },
  { word: 'Falot', pos: 'adjective', definition: 'Terne et effacé, sans relief' },
  { word: 'Famélique', pos: 'adjective', definition: 'Amaigri par la faim' },
  { word: 'Fantasmagorie', pos: 'noun', definition: 'Spectacle fantastique et irréel' },
  { word: 'Fantasque', pos: 'adjective', definition: 'Sujet à des caprices imprévisibles' },
  { word: 'Faraud', pos: 'adjective', definition: 'Qui affiche une fierté un peu fanfaronne' },
  { word: 'Fastueux', pos: 'adjective', definition: 'D\'un luxe éclatant et somptueux' },
  { word: 'Fat', pos: 'adjective', definition: 'Content de soi jusqu\'au ridicule' },
  { word: 'Fébrile', pos: 'adjective', definition: 'D\'une agitation nerveuse et impatiente' },
  { word: 'Féerie', pos: 'noun', definition: 'Spectacle d\'une beauté merveilleuse' },
  { word: 'Félicité', pos: 'noun', definition: 'Bonheur suprême et sans mélange' },
  { word: 'Féru', pos: 'adjective', definition: 'Passionné avec érudition pour un domaine' },
  { word: 'Ferveur', pos: 'noun', definition: 'Ardeur enthousiaste et profonde' },
  { word: 'Festoyer', pos: 'verb', definition: 'Faire bombance dans la joie' },
  { word: 'Fielleux', pos: 'adjective', definition: 'Plein d\'une amertume malveillante' },
  { word: 'Flagorner', pos: 'verb', definition: 'Flatter bassement et avec insistance' },
  { word: 'Flamboyant', pos: 'adjective', definition: 'Qui jette des éclats de flamme' },
  { word: 'Flâner', pos: 'verb', definition: 'Se promener sans hâte, au hasard du plaisir' },
  { word: 'Flegme', pos: 'noun', definition: 'Calme imperturbable en toute circonstance' },
  { word: 'Fleurer', pos: 'verb', definition: 'Répandre une odeur agréable' },
  { word: 'Florilège', pos: 'noun', definition: 'Recueil de morceaux choisis' },
  { word: 'Foisonner', pos: 'verb', definition: 'Abonder, se multiplier avec profusion' },
  { word: 'Folâtrer', pos: 'verb', definition: 'Jouer et batifoler gaiement' },
  { word: 'Fougue', pos: 'noun', definition: 'Élan impétueux et passionné' },
  { word: 'Fourbe', pos: 'adjective', definition: 'Qui trompe avec une ruse perfide' },
  { word: 'Fourmiller', pos: 'verb', definition: 'Grouiller en grand nombre' },
  { word: 'Fragrance', pos: 'noun', definition: 'Parfum subtil et agréable' },
  { word: 'Frasque', pos: 'noun', definition: 'Écart de conduite plein de panache' },
  { word: 'Fredonner', pos: 'verb', definition: 'Chanter à mi-voix, sans articuler' },
  { word: 'Frémir', pos: 'verb', definition: 'Être agité d\'un léger tremblement d\'émotion' },
  { word: 'Friand', pos: 'adjective', definition: 'Qui apprécie particulièrement une chose' },
  { word: 'Frimas', pos: 'noun', definition: 'Brouillard glacé qui givre les paysages' },
  { word: 'Frisquet', pos: 'adjective', definition: 'Légèrement froid, un peu vif' },
  { word: 'Frivole', pos: 'adjective', definition: 'Léger et futile, sans profondeur' },
  { word: 'Frugal', pos: 'adjective', definition: 'Simple et sobre, qui se contente de peu' },
  { word: 'Fugace', pos: 'adjective', definition: 'Qui passe et disparaît rapidement' },
  { word: 'Fulgurance', pos: 'noun', definition: 'Éclat soudain et brillant, trait de génie' },
  { word: 'Fuligineux', pos: 'adjective', definition: 'Noirci comme par la suie, obscur' },
  { word: 'Funambule', pos: 'noun', definition: 'Acrobate qui marche sur un fil tendu' },
  { word: 'Furtivement', pos: 'adverb', definition: 'À la dérobée, sans se faire remarquer' },
  { word: 'Fustiger', pos: 'verb', definition: 'Critiquer avec une grande sévérité' },
  { word: 'Galant', pos: 'adjective', definition: 'D\'une courtoisie empressée envers les dames' },
  { word: 'Galimatias', pos: 'noun', definition: 'Discours confus et inintelligible' },
  { word: 'Gambader', pos: 'verb', definition: 'Sauter joyeusement en tous sens' },
  { word: 'Gargantuesque', pos: 'adjective', definition: 'D\'un appétit ou d\'une ampleur démesurés' },
  { word: 'Gazouillis', pos: 'noun', definition: 'Chant léger et confus des oiseaux' },
  { word: 'Gemme', pos: 'noun', definition: 'Pierre précieuse à l\'état brut' },
  { word: 'Girouette', pos: 'noun', definition: 'Personne qui change sans cesse d\'avis' },
  { word: 'Glaner', pos: 'verb', definition: 'Recueillir çà et là des bribes précieuses' },
  { word: 'Gloriole', pos: 'noun', definition: 'Vanité tirée de petites choses' },
  { word: 'Goguenard', pos: 'adjective', definition: 'D\'une moquerie narquoise et bon enfant' },
  { word: 'Gouailleur', pos: 'adjective', definition: 'D\'une raillerie populaire et insolente' },
  { word: 'Goulûment', pos: 'adverb', definition: 'Avec une avidité gourmande' },
  { word: 'Gracile', pos: 'adjective', definition: 'Mince et délicat avec élégance' },
  { word: 'Grandiloquent', pos: 'adjective', definition: 'D\'une emphase pompeuse et théâtrale' },
  { word: 'Grisant', pos: 'adjective', definition: 'Qui exalte et enivre légèrement' },
  { word: 'Grivois', pos: 'adjective', definition: 'D\'une gaieté licencieuse mais sans vulgarité' },
  { word: 'Grommeler', pos: 'verb', definition: 'Protester à voix basse entre ses dents' },
  { word: 'Guilleret', pos: 'adjective', definition: 'D\'une gaieté vive et insouciante' },
  { word: 'Hâbleur', pos: 'adjective', definition: 'Qui se vante avec exagération' },
  { word: 'Hagard', pos: 'adjective', definition: 'Au regard égaré par la peur ou la fatigue' },
  { word: 'Harangue', pos: 'noun', definition: 'Discours solennel adressé à une assemblée' },
  { word: 'Hardiesse', pos: 'noun', definition: 'Audace assurée qui brave les obstacles' },
  { word: 'Hâtivement', pos: 'adverb', definition: 'Avec une précipitation excessive' },
  { word: 'Hédonisme', pos: 'noun', definition: 'Doctrine qui fait du plaisir le bien suprême' },
  { word: 'Hermétique', pos: 'adjective', definition: 'Impénétrable, fermé à toute compréhension' },
  { word: 'Hiématal', pos: 'adjective', definition: 'Relatif à la saison froide' },
  { word: 'Hiératique', pos: 'adjective', definition: 'D\'une majesté figée et solennelle' },
  { word: 'Hirsute', pos: 'adjective', definition: 'Aux cheveux en désordre et touffus' },
  { word: 'Historiette', pos: 'noun', definition: 'Petit récit plaisant et anecdotique' },
  { word: 'Homérique', pos: 'adjective', definition: 'D\'une ampleur épique et mémorable' },
  { word: 'Horripiler', pos: 'verb', definition: 'Agacer au plus haut point' },
  { word: 'Houleux', pos: 'adjective', definition: 'Agité de mouvements tumultueux' },
  { word: 'Humer', pos: 'verb', definition: 'Aspirer pour sentir un parfum ou un air' },
  { word: 'Hurluberlu', pos: 'noun', definition: 'Personne extravagante et étourdie' },
  { word: 'Hyperbole', pos: 'noun', definition: 'Exagération expressive du langage' },
  { word: 'Iconoclaste', pos: 'adjective', definition: 'Qui brise les traditions établies' },
  { word: 'Idoine', pos: 'adjective', definition: 'Parfaitement approprié à la situation' },
  { word: 'Idylle', pos: 'noun', definition: 'Amour tendre et naïf, romance charmante' },
  { word: 'Ignominie', pos: 'noun', definition: 'Déshonneur extrême, action infâme' },
  { word: 'Illico', pos: 'adverb', definition: 'Immédiatement, sur-le-champ' },
  { word: 'Immaculé', pos: 'adjective', definition: 'D\'une pureté sans la moindre tache' },
  { word: 'Immarcescible', pos: 'adjective', definition: 'Qui ne peut se flétrir ni se faner' },
  { word: 'Immémorial', pos: 'adjective', definition: 'Si ancien que la mémoire en est perdue' },
  { word: 'Impalpable', pos: 'adjective', definition: 'Si fin ou si léger que le toucher ne le saisit pas' },
  { word: 'Impassible', pos: 'adjective', definition: 'Qui ne laisse paraître aucune émotion' },
  { word: 'Impavide', pos: 'adjective', definition: 'Que rien ne peut effrayer' },
  { word: 'Impécunieux', pos: 'adjective', definition: 'Qui manque d\'argent' },
  { word: 'Impérieux', pos: 'adjective', definition: 'Qui commande avec autorité, pressant' },
  { word: 'Impétueux', pos: 'adjective', definition: 'D\'une fougue violente et rapide' },
  { word: 'Implacable', pos: 'adjective', definition: 'Que rien ne peut fléchir ni apaiser' },
  { word: 'Impondérable', pos: 'noun', definition: 'Élément imprévisible qui déjoue les calculs' },
  { word: 'Impromptu', pos: 'adjective', definition: 'Improvisé sur le moment, sans préparation' },
  { word: 'Impunément', pos: 'adverb', definition: 'Sans subir de punition ni de dommage' },
  { word: 'Inanité', pos: 'noun', definition: 'Caractère vain et vide de sens' },
  { word: 'Incandescent', pos: 'adjective', definition: 'Rendu lumineux à force de chaleur' },
  { word: 'Incantation', pos: 'noun', definition: 'Formule chantée aux pouvoirs magiques' },
  { word: 'Incessamment', pos: 'adverb', definition: 'Très prochainement, sans délai' },
  { word: 'Incognito', pos: 'adverb', definition: 'Sans être reconnu, sous une identité cachée' },
  { word: 'Incommensurable', pos: 'adjective', definition: 'Si vaste qu\'aucune mesure ne le contient' },
  { word: 'Incunable', pos: 'noun', definition: 'Livre imprimé aux origines de l\'imprimerie' },
  { word: 'Indicible', pos: 'adjective', definition: 'Si intense que les mots ne peuvent le dire' },
  { word: 'Indolent', pos: 'adjective', definition: 'D\'une nonchalance molle et paisible' },
  { word: 'Inébranlable', pos: 'adjective', definition: 'Que rien ne peut faire fléchir' },
  { word: 'Ineffable', pos: 'adjective', definition: 'Trop sublime pour être exprimé par des mots' },
  { word: 'Inéluctable', pos: 'adjective', definition: 'Que rien ne permet d\'éviter' },
  { word: 'Inénarrable', pos: 'adjective', definition: 'Si cocasse qu\'on ne peut le raconter sans rire' },
  { word: 'Ineptie', pos: 'noun', definition: 'Sottise absurde, propos stupide' },
  { word: 'Inextricable', pos: 'adjective', definition: 'Si embrouillé qu\'on ne peut le démêler' },
  { word: 'Infime', pos: 'adjective', definition: 'Extrêmement petit, minuscule' },
  { word: 'Ingambe', pos: 'adjective', definition: 'Alerte et vif malgré son âge' },
  { word: 'Ingénu', pos: 'adjective', definition: 'D\'une innocence franche et confiante' },
  { word: 'Inique', pos: 'adjective', definition: 'D\'une injustice criante' },
  { word: 'Inlassablement', pos: 'adverb', definition: 'Sans jamais se lasser ni faiblir' },
  { word: 'Inopiné', pos: 'adjective', definition: 'Qui survient sans avoir été prévu' },
  { word: 'Inopinément', pos: 'adverb', definition: 'De façon soudaine et imprévue' },
  { word: 'Insatiable', pos: 'adjective', definition: 'Dont le désir ne peut être comblé' },
  { word: 'Insidieusement', pos: 'adverb', definition: 'De manière sournoise et progressive' },
  { word: 'Insigne', pos: 'adjective', definition: 'Remarquable entre tous, éclatant' },
  { word: 'Insolite', pos: 'adjective', definition: 'Qui étonne par son étrangeté inhabituelle' },
  { word: 'Insondable', pos: 'adjective', definition: 'Si profond que nul ne peut en toucher le fond' },
  { word: 'Instamment', pos: 'adverb', definition: 'Avec une insistance pressante' },
  { word: 'Intarissable', pos: 'adjective', definition: 'Qui ne s\'épuise jamais, inépuisable' },
  { word: 'Intègre', pos: 'adjective', definition: 'D\'une honnêteté absolue et incorruptible' },
  { word: 'Intempestif', pos: 'adjective', definition: 'Qui survient à contretemps' },
  { word: 'Interlope', pos: 'adjective', definition: 'D\'une légalité douteuse, équivoque' },
  { word: 'Interstice', pos: 'noun', definition: 'Très petit espace vide entre deux choses' },
  { word: 'Intrépide', pos: 'adjective', definition: 'Qui ne tremble devant aucun danger' },
  { word: 'Inusité', pos: 'adjective', definition: 'Dont on ne se sert plus, rare et surprenant' },
  { word: 'Irascible', pos: 'adjective', definition: 'Prompt à la colère' },
  { word: 'Iridescent', pos: 'adjective', definition: 'Aux reflets irisés comme un arc-en-ciel' },
  { word: 'Irrévérencieux', pos: 'adjective', definition: 'Qui manque de respect avec insolence' },
  { word: 'Ivresse', pos: 'noun', definition: 'Exaltation qui transporte hors de soi' },
  { word: 'Jacasser', pos: 'verb', definition: 'Bavarder bruyamment et sans arrêt' },
  { word: 'Jactance', pos: 'noun', definition: 'Vantardise arrogante et bavarde' },
  { word: 'Jadis', pos: 'adverb', definition: 'Dans un passé lointain, autrefois' },
  { word: 'Jaser', pos: 'verb', definition: 'Bavarder avec malice, faire des commérages' },
  { word: 'Jouvence', pos: 'noun', definition: 'Jeunesse retrouvée, source de renouveau' },
  { word: 'Jovial', pos: 'adjective', definition: 'D\'une gaieté franche et communicative' },
  { word: 'Jubilatoire', pos: 'adjective', definition: 'Qui procure une joie intense et exultante' },
  { word: 'Jubiler', pos: 'verb', definition: 'Éprouver une joie intense et triomphante' },
  { word: 'Judicieux', pos: 'adjective', definition: 'Qui témoigne d\'un jugement sûr' },
  { word: 'Juvénile', pos: 'adjective', definition: 'Qui a la fraîcheur de la jeunesse' },
  { word: 'Kaléidoscope', pos: 'noun', definition: 'Succession changeante d\'images colorées' },
  { word: 'Labyrinthique', pos: 'adjective', definition: 'Aux détours si nombreux qu\'on s\'y égare' },
  { word: 'Laconique', pos: 'adjective', definition: 'Qui dit beaucoup en très peu de mots' },
  { word: 'Lambiner', pos: 'verb', definition: 'Agir avec une lenteur nonchalante' },
  { word: 'Lancinant', pos: 'adjective', definition: 'Qui revient sans cesse et obsède' },
  { word: 'Langoureux', pos: 'adjective', definition: 'Empreint d\'une tendre et rêveuse mélancolie' },
  { word: 'Languissamment', pos: 'adverb', definition: 'Avec une douceur alanguie et rêveuse' },
  { word: 'Lapidaire', pos: 'adjective', definition: 'D\'une concision frappante et définitive' },
  { word: 'Larmoyant', pos: 'adjective', definition: 'D\'une tristesse appuyée jusqu\'aux larmes' },
  { word: 'Latent', pos: 'adjective', definition: 'Présent mais encore caché, qui couve' },
  { word: 'Laudatif', pos: 'adjective', definition: 'Qui exprime la louange' },
  { word: 'Lénifiant', pos: 'adjective', definition: 'Qui apaise et adoucit' },
  { word: 'Léonin', pos: 'adjective', definition: 'Qui réserve la part du lion, inégal' },
  { word: 'Lestement', pos: 'adverb', definition: 'Avec agilité et légèreté' },
  { word: 'Léthargie', pos: 'noun', definition: 'Engourdissement profond et prolongé' },
  { word: 'Liesse', pos: 'noun', definition: 'Joie collective et débordante' },
  { word: 'Limbes', pos: 'noun', definition: 'État vague et indécis, entre-deux flou' },
  { word: 'Liminaire', pos: 'adjective', definition: 'Placé au seuil, en ouverture' },
  { word: 'Limpide', pos: 'adjective', definition: 'D\'une clarté parfaite et transparente' },
  { word: 'Lisière', pos: 'noun', definition: 'Bordure où la forêt rencontre la plaine' },
  { word: 'Loquace', pos: 'adjective', definition: 'Qui parle volontiers et abondamment' },
  { word: 'Louvoyer', pos: 'verb', definition: 'Avancer par détours pour éviter les obstacles' },
  { word: 'Lubie', pos: 'noun', definition: 'Caprice soudain et extravagant' },
  { word: 'Ludique', pos: 'adjective', definition: 'Relatif au jeu et au plaisir de jouer' },
  { word: 'Lugubre', pos: 'adjective', definition: 'D\'une tristesse sombre et funèbre' },
  { word: 'Luminescence', pos: 'noun', definition: 'Lumière douce émise sans chaleur' },
  { word: 'Luxuriant', pos: 'adjective', definition: 'D\'une abondance végétale exubérante' },
  { word: 'Lyrique', pos: 'adjective', definition: 'Qui exprime les émotions avec exaltation' },
  { word: 'Machiavélique', pos: 'adjective', definition: 'D\'une ruse perfide et calculée' },
  { word: 'Maelström', pos: 'noun', definition: 'Tourbillon puissant qui engloutit tout' },
  { word: 'Magnanime', pos: 'adjective', definition: 'D\'une générosité noble envers les vaincus' },
  { word: 'Magnificence', pos: 'noun', definition: 'Splendeur fastueuse et éclatante' },
  { word: 'Magnifier', pos: 'verb', definition: 'Célébrer en donnant plus de grandeur' },
  { word: 'Manichéen', pos: 'adjective', definition: 'Qui oppose sans nuance le bien et le mal' },
  { word: 'Mansarde', pos: 'noun', definition: 'Chambre nichée sous les toits' },
  { word: 'Mansuétude', pos: 'noun', definition: 'Douceur indulgente et patiente' },
  { word: 'Marivaudage', pos: 'noun', definition: 'Badinage galant et raffiné' },
  { word: 'Marmonner', pos: 'verb', definition: 'Murmurer entre ses dents de façon indistincte' },
  { word: 'Marmoréen', pos: 'adjective', definition: 'Qui a la blancheur froide du marbre' },
  { word: 'Matois', pos: 'adjective', definition: 'Rusé sous des dehors de bonhomie' },
  { word: 'Maussade', pos: 'adjective', definition: 'D\'une humeur triste et renfrognée' },
  { word: 'Méandre', pos: 'noun', definition: 'Détour sinueux, comme celui des rivières' },
  { word: 'Médusé', pos: 'adjective', definition: 'Pétrifié de stupeur' },
  { word: 'Mélancolie', pos: 'noun', definition: 'Tristesse douce et rêveuse, sans cause précise' },
  { word: 'Mélodieux', pos: 'adjective', definition: 'Dont le son est doux et harmonieux' },
  { word: 'Mercantile', pos: 'adjective', definition: 'Uniquement soucieux du gain' },
  { word: 'Méridional', pos: 'adjective', definition: 'Du Midi, baigné de soleil du Sud' },
  { word: 'Méticuleux', pos: 'adjective', definition: 'Attentif aux moindres détails' },
  { word: 'Mielleux', pos: 'adjective', definition: 'D\'une douceur affectée et fausse' },
  { word: 'Mièvre', pos: 'adjective', definition: 'D\'une grâce fade et affectée' },
  { word: 'Mirifique', pos: 'adjective', definition: 'Merveilleux jusqu\'à sembler trop beau' },
  { word: 'Miroiter', pos: 'verb', definition: 'Renvoyer la lumière en reflets changeants' },
  { word: 'Missive', pos: 'noun', definition: 'Lettre écrite et envoyée' },
  { word: 'Mitonner', pos: 'verb', definition: 'Préparer longuement et avec amour' },
  { word: 'Modique', pos: 'adjective', definition: 'De faible valeur, peu élevé' },
  { word: 'Moiré', pos: 'adjective', definition: 'Aux reflets ondoyants et changeants' },
  { word: 'Mordoré', pos: 'adjective', definition: 'D\'un brun chaud aux reflets dorés' },
  { word: 'Morgue', pos: 'noun', definition: 'Arrogance méprisante et hautaine' },
  { word: 'Morose', pos: 'adjective', definition: 'D\'une humeur sombre et chagrine' },
  { word: 'Moult', pos: 'adverb', definition: 'Beaucoup, en grande quantité, à la mode ancienne' },
  { word: 'Munificence', pos: 'noun', definition: 'Générosité fastueuse et grandiose' },
  { word: 'Musarder', pos: 'verb', definition: 'Perdre son temps à des riens agréables' },
  { word: 'Mutin', pos: 'adjective', definition: 'D\'une espièglerie charmante et taquine' },
  { word: 'Myriade', pos: 'noun', definition: 'Quantité innombrable' },
  { word: 'Nacré', pos: 'adjective', definition: 'Aux reflets doux et irisés de la nacre' },
  { word: 'Naguère', pos: 'adverb', definition: 'Il y a peu de temps, récemment encore' },
  { word: 'Narquois', pos: 'adjective', definition: 'D\'une moquerie fine et malicieuse' },
  { word: 'Nébuleux', pos: 'adjective', definition: 'Vague et confus comme un nuage' },
  { word: 'Néfaste', pos: 'adjective', definition: 'Qui porte malheur, funeste' },
  { word: 'Néophyte', pos: 'noun', definition: 'Nouveau venu plein de zèle dans une pratique' },
  { word: 'Nimber', pos: 'verb', definition: 'Entourer d\'un halo de lumière' },
  { word: 'Nonchalance', pos: 'noun', definition: 'Lenteur indolente et gracieuse' },
  { word: 'Nonobstant', pos: 'adverb', definition: 'Malgré cela, cependant' },
  { word: 'Nostalgie', pos: 'noun', definition: 'Regret tendre du temps passé ou du pays perdu' },
  { word: 'Notoire', pos: 'adjective', definition: 'Connu de tous, manifeste' },
  { word: 'Novateur', pos: 'adjective', definition: 'Qui ouvre des voies nouvelles' },
  { word: 'Nuitamment', pos: 'adverb', definition: 'Pendant la nuit, à la faveur de la nuit' },
  { word: 'Nyctalope', pos: 'adjective', definition: 'Capable de voir dans la nuit' },
  { word: 'Oasis', pos: 'noun', definition: 'Havre de fraîcheur au milieu de l\'aridité' },
  { word: 'Objurgation', pos: 'noun', definition: 'Remontrance pressante pour dissuader' },
  { word: 'Obligeamment', pos: 'adverb', definition: 'Avec une serviabilité aimable' },
  { word: 'Obséquieux', pos: 'adjective', definition: 'D\'une politesse servile et excessive' },
  { word: 'Obsolète', pos: 'adjective', definition: 'Sorti de l\'usage, dépassé' },
  { word: 'Occire', pos: 'verb', definition: 'Tuer, dans la langue des anciens récits' },
  { word: 'Odyssée', pos: 'noun', definition: 'Long voyage riche en aventures' },
  { word: 'Offusquer', pos: 'verb', definition: 'Choquer et froisser la sensibilité' },
  { word: 'Oisiveté', pos: 'noun', definition: 'État de qui vit sans rien faire' },
  { word: 'Olibrius', pos: 'noun', definition: 'Personnage extravagant au comportement étrange' },
  { word: 'Ombrageux', pos: 'adjective', definition: 'Prompt à se vexer, susceptible' },
  { word: 'Omniscient', pos: 'adjective', definition: 'Qui sait toutes choses' },
  { word: 'Onctueux', pos: 'adjective', definition: 'D\'une douceur veloutée et moelleuse' },
  { word: 'Ondoyer', pos: 'verb', definition: 'Onduler souplement comme les blés au vent' },
  { word: 'Onirique', pos: 'adjective', definition: 'Qui appartient au monde des rêves' },
  { word: 'Opalescent', pos: 'adjective', definition: 'Aux reflets laiteux et irisés de l\'opale' },
  { word: 'Opiniâtre', pos: 'adjective', definition: 'D\'une ténacité que rien ne décourage' },
  { word: 'Opportun', pos: 'adjective', definition: 'Qui vient exactement au bon moment' },
  { word: 'Opportunément', pos: 'adverb', definition: 'Au moment le plus favorable' },
  { word: 'Opprobre', pos: 'noun', definition: 'Honte publique et infamante' },
  { word: 'Opulent', pos: 'adjective', definition: 'D\'une richesse abondante et généreuse' },
  { word: 'Orée', pos: 'noun', definition: 'Bord d\'un bois, seuil de la forêt' },
  { word: 'Oripeaux', pos: 'noun', definition: 'Vêtements au faux clinquant, défroque voyante' },
  { word: 'Ostensiblement', pos: 'adverb', definition: 'De façon voyante, pour être bien vu' },
  { word: 'Ostentatoire', pos: 'adjective', definition: 'Étalé avec une insistance vaniteuse' },
  { word: 'Ourdir', pos: 'verb', definition: 'Tramer en secret un complot' },
  { word: 'Outrecuidance', pos: 'noun', definition: 'Confiance en soi arrogante et présomptueuse' },
  { word: 'Palabres', pos: 'noun', definition: 'Discussions longues et interminables' },
  { word: 'Palimpseste', pos: 'noun', definition: 'Manuscrit effacé puis réécrit, aux couches superposées' },
  { word: 'Palinodie', pos: 'noun', definition: 'Revirement complet d\'opinion' },
  { word: 'Palpiter', pos: 'verb', definition: 'Battre et frémir d\'émotion ou de vie' },
  { word: 'Panacée', pos: 'noun', definition: 'Remède supposé guérir tous les maux' },
  { word: 'Panache', pos: 'noun', definition: 'Éclat brillant et brave qui force l\'admiration' },
  { word: 'Pantagruélique', pos: 'adjective', definition: 'Digne d\'un appétit de géant' },
  { word: 'Pantois', pos: 'adjective', definition: 'Suffoqué de surprise, interdit' },
  { word: 'Parangon', pos: 'noun', definition: 'Modèle parfait, exemple accompli' },
  { word: 'Parcimonie', pos: 'noun', definition: 'Épargne minutieuse, distribution au compte-gouttes' },
  { word: 'Pastoral', pos: 'adjective', definition: 'Qui évoque la vie paisible des bergers' },
  { word: 'Patibulaire', pos: 'adjective', definition: 'À la mine inquiétante de mauvais garçon' },
  { word: 'Patine', pos: 'noun', definition: 'Douceur que le temps dépose sur les choses' },
  { word: 'Pavoiser', pos: 'verb', definition: 'Afficher une fierté triomphante' },
  { word: 'Peaufiner', pos: 'verb', definition: 'Parfaire avec un soin minutieux' },
  { word: 'Pécuniaire', pos: 'adjective', definition: 'Relatif à l\'argent' },
  { word: 'Pénombre', pos: 'noun', definition: 'Demi-jour doux entre ombre et lumière' },
  { word: 'Pérégrination', pos: 'noun', definition: 'Long voyage aux étapes nombreuses' },
  { word: 'Péremptoire', pos: 'adjective', definition: 'Qui tranche sans admettre de réplique' },
  { word: 'Perfide', pos: 'adjective', definition: 'Qui trahit la confiance avec fourberie' },
  { word: 'Pernicieux', pos: 'adjective', definition: 'Nuisible de façon insidieuse' },
  { word: 'Pérorer', pos: 'verb', definition: 'Discourir longuement avec suffisance' },
  { word: 'Perspicace', pos: 'adjective', definition: 'Qui perçoit ce qui échappe aux autres' },
  { word: 'Pétillant', pos: 'adjective', definition: 'Qui brille de vivacité et de gaieté' },
  { word: 'Pétrichor', pos: 'noun', definition: 'Odeur de la terre après la pluie' },
  { word: 'Philanthrope', pos: 'noun', definition: 'Personne qui œuvre au bien de ses semblables' },
  { word: 'Philistin', pos: 'noun', definition: 'Personne fermée aux choses de l\'esprit' },
  { word: 'Phosphorescent', pos: 'adjective', definition: 'Qui luit doucement dans l\'obscurité' },
  { word: 'Picaresque', pos: 'adjective', definition: 'Riche en aventures de héros vagabonds' },
  { word: 'Pittoresque', pos: 'adjective', definition: 'Qui charme par son originalité imagée' },
  { word: 'Placide', pos: 'adjective', definition: 'D\'un calme doux que rien ne trouble' },
  { word: 'Placidement', pos: 'adverb', definition: 'Avec un calme imperturbable' },
  { word: 'Pléthore', pos: 'noun', definition: 'Abondance excessive, surabondance' },
  { word: 'Poindre', pos: 'verb', definition: 'Commencer à paraître, comme le jour qui se lève' },
  { word: 'Polisson', pos: 'adjective', definition: 'Espiègle et un peu effronté' },
  { word: 'Poltron', pos: 'adjective', definition: 'Qui manque de courage devant le danger' },
  { word: 'Pondéré', pos: 'adjective', definition: 'D\'un jugement équilibré et mesuré' },
  { word: 'Posément', pos: 'adverb', definition: 'Avec calme et mesure, sans hâte' },
  { word: 'Potentat', pos: 'noun', definition: 'Souverain absolu, homme tout-puissant' },
  { word: 'Pragmatique', pos: 'adjective', definition: 'Tourné vers l\'action efficace et concrète' },
  { word: 'Préambule', pos: 'noun', definition: 'Entrée en matière qui précède le sujet' },
  { word: 'Précepte', pos: 'noun', definition: 'Règle de conduite tirée de la sagesse' },
  { word: 'Prestance', pos: 'noun', definition: 'Allure imposante et élégante' },
  { word: 'Preste', pos: 'adjective', definition: 'Rapide et agile dans ses mouvements' },
  { word: 'Prestement', pos: 'adverb', definition: 'Avec rapidité et agilité' },
  { word: 'Prévenance', pos: 'noun', definition: 'Attention délicate qui devance les désirs' },
  { word: 'Primesautier', pos: 'adjective', definition: 'Qui agit de premier mouvement, spontané' },
  { word: 'Probité', pos: 'noun', definition: 'Honnêteté scrupuleuse et droite' },
  { word: 'Prodigalité', pos: 'noun', definition: 'Générosité dépensière et sans compter' },
  { word: 'Prodigieux', pos: 'adjective', definition: 'Extraordinaire au point de tenir du prodige' },
  { word: 'Profusion', pos: 'noun', definition: 'Grande abondance déversée sans mesure' },
  { word: 'Prolixe', pos: 'adjective', definition: 'Trop long et diffus dans ses propos' },
  { word: 'Promontoire', pos: 'noun', definition: 'Avancée de terre élevée dominant la mer' },
  { word: 'Promptement', pos: 'adverb', definition: 'Sans tarder, avec célérité' },
  { word: 'Prosaïque', pos: 'adjective', definition: 'Terre à terre, dépourvu de poésie' },
  { word: 'Providentiel', pos: 'adjective', definition: 'Qui arrive à point nommé comme un secours du ciel' },
  { word: 'Puéril', pos: 'adjective', definition: 'D\'un enfantillage peu digne d\'un adulte' },
  { word: 'Pugnace', pos: 'adjective', definition: 'Combatif, qui aime la lutte' },
  { word: 'Pusillanime', pos: 'adjective', definition: 'Qui manque de courage et craint le risque' },
  { word: 'Quérir', pos: 'verb', definition: 'Aller chercher, dans la langue ancienne' },
  { word: 'Quidam', pos: 'noun', definition: 'Individu quelconque dont on tait le nom' },
  { word: 'Quiétude', pos: 'noun', definition: 'Tranquillité paisible et sans inquiétude' },
  { word: 'Quintessence', pos: 'noun', definition: 'Ce qu\'il y a de plus pur et de plus raffiné' },
  { word: 'Quolibet', pos: 'noun', definition: 'Plaisanterie moqueuse lancée à quelqu\'un' },
  { word: 'Rabelaisien', pos: 'adjective', definition: 'D\'une verve truculente et joyeusement excessive' },
  { word: 'Radieux', pos: 'adjective', definition: 'Qui rayonne de lumière ou de bonheur' },
  { word: 'Radoter', pos: 'verb', definition: 'Répéter sans cesse les mêmes propos' },
  { word: 'Raffoler', pos: 'verb', definition: 'Aimer à la folie' },
  { word: 'Ragaillardir', pos: 'verb', definition: 'Redonner force et bonne humeur' },
  { word: 'Ramage', pos: 'noun', definition: 'Chant des oiseaux dans les feuillages' },
  { word: 'Rasséréner', pos: 'verb', definition: 'Ramener au calme et à la sérénité' },
  { word: 'Ratiociner', pos: 'verb', definition: 'Raisonner de façon interminable et pointilleuse' },
  { word: 'Ravissement', pos: 'noun', definition: 'Émerveillement qui transporte de joie' },
  { word: 'Recueillement', pos: 'noun', definition: 'Concentration silencieuse et méditative' },
  { word: 'Rédhibitoire', pos: 'adjective', definition: 'Qui constitue un obstacle absolu' },
  { word: 'Réfractaire', pos: 'adjective', definition: 'Qui refuse de se soumettre' },
  { word: 'Regimber', pos: 'verb', definition: 'Résister en se cabrant contre la contrainte' },
  { word: 'Rémanent', pos: 'adjective', definition: 'Qui persiste après la disparition de sa cause' },
  { word: 'Réminiscence', pos: 'noun', definition: 'Souvenir vague qui remonte à la mémoire' },
  { word: 'Renâcler', pos: 'verb', definition: 'Rechigner à la tâche avec mauvaise volonté' },
  { word: 'Rengaine', pos: 'noun', definition: 'Refrain répété jusqu\'à la lassitude' },
  { word: 'Requinquer', pos: 'verb', definition: 'Redonner des forces et de l\'entrain' },
  { word: 'Rescousse', pos: 'noun', definition: 'Secours porté à qui est en difficulté' },
  { word: 'Résilience', pos: 'noun', definition: 'Capacité à se reconstruire après les épreuves' },
  { word: 'Résurgence', pos: 'noun', definition: 'Réapparition de ce qui semblait disparu' },
  { word: 'Retors', pos: 'adjective', definition: 'Rusé et plein de détours malins' },
  { word: 'Retrouvailles', pos: 'noun', definition: 'Joie de se revoir après une longue séparation' },
  { word: 'Rêvasser', pos: 'verb', definition: 'Laisser flotter son esprit en rêveries vagues' },
  { word: 'Revêche', pos: 'adjective', definition: 'D\'un abord rude et peu aimable' },
  { word: 'Révérence', pos: 'noun', definition: 'Profond respect mêlé de crainte admirative' },
  { word: 'Rêverie', pos: 'noun', definition: 'Pensée vagabonde où l\'esprit se laisse aller' },
  { word: 'Rhapsodie', pos: 'noun', definition: 'Composition libre aux accents populaires' },
  { word: 'Ribambelle', pos: 'noun', definition: 'Longue suite joyeuse et nombreuse' },
  { word: 'Rieur', pos: 'adjective', definition: 'Qui aime rire et exprime la gaieté' },
  { word: 'Ripaille', pos: 'noun', definition: 'Repas abondant et joyeux, festin' },
  { word: 'Roboratif', pos: 'adjective', definition: 'Qui redonne force et vigueur' },
  { word: 'Rocambolesque', pos: 'adjective', definition: 'Plein de rebondissements invraisemblables' },
  { word: 'Rogue', pos: 'adjective', definition: 'D\'une arrogance froide et dédaigneuse' },
  { word: 'Romanesque', pos: 'adjective', definition: 'Digne des aventures et passions des romans' },
  { word: 'Roublard', pos: 'adjective', definition: 'Habile à ruser pour son profit' },
  { word: 'Rougeoyer', pos: 'verb', definition: 'Prendre des teintes rouges et changeantes' },
  { word: 'Rouspéter', pos: 'verb', definition: 'Protester en bougonnant' },
  { word: 'Rubicond', pos: 'adjective', definition: 'Au visage rouge et florissant' },
  { word: 'Rutilant', pos: 'adjective', definition: 'D\'un éclat vif et brillant' },
  { word: 'Sacerdoce', pos: 'noun', definition: 'Mission exigeante accomplie avec dévouement' },
  { word: 'Sagacité', pos: 'noun', definition: 'Finesse pénétrante du jugement' },
  { word: 'Saltimbanque', pos: 'noun', definition: 'Artiste ambulant des places publiques' },
  { word: 'Salutaire', pos: 'adjective', definition: 'Qui fait du bien, bénéfique' },
  { word: 'Sarabande', pos: 'noun', definition: 'Farandole bruyante et désordonnée' },
  { word: 'Sardonique', pos: 'adjective', definition: 'D\'une moquerie amère et méchante' },
  { word: 'Satiété', pos: 'noun', definition: 'État de qui a été comblé au-delà du désir' },
  { word: 'Satiné', pos: 'adjective', definition: 'Doux et lustré comme le satin' },
  { word: 'Saugrenu', pos: 'adjective', definition: 'D\'une bizarrerie absurde et inattendue' },
  { word: 'Savoureux', pos: 'adjective', definition: 'Qui a une saveur riche et délicieuse' },
  { word: 'Scabreux', pos: 'adjective', definition: 'Délicat à aborder, risqué et osé' },
  { word: 'Scélérat', pos: 'noun', definition: 'Bandit capable des pires forfaits' },
  { word: 'Sciemment', pos: 'adverb', definition: 'En toute connaissance de cause' },
  { word: 'Scintiller', pos: 'verb', definition: 'Briller par éclats tremblotants' },
  { word: 'Scrupuleux', pos: 'adjective', definition: 'D\'une exactitude morale minutieuse' },
  { word: 'Séculaire', pos: 'adjective', definition: 'Qui existe depuis des siècles' },
  { word: 'Séditieux', pos: 'adjective', definition: 'Qui pousse à la révolte' },
  { word: 'Sémillant', pos: 'adjective', definition: 'D\'une vivacité pétillante et joyeuse' },
  { word: 'Sempiternel', pos: 'adjective', definition: 'Qui revient sans fin, à la longue lassant' },
  { word: 'Sentencieux', pos: 'adjective', definition: 'Qui parle par maximes avec gravité affectée' },
  { word: 'Séraphique', pos: 'adjective', definition: 'D\'une pureté angélique et céleste' },
  { word: 'Sérendipité', pos: 'noun', definition: 'Art de faire des découvertes heureuses par hasard' },
  { word: 'Sérénité', pos: 'noun', definition: 'Paix intérieure calme et confiante' },
  { word: 'Sibyllin', pos: 'adjective', definition: 'Dont le sens reste mystérieux et énigmatique' },
  { word: 'Sidéral', pos: 'adjective', definition: 'Relatif aux astres et aux espaces célestes' },
  { word: 'Sidérer', pos: 'verb', definition: 'Frapper de stupeur, laisser sans réaction' },
  { word: 'Sinécure', pos: 'noun', definition: 'Emploi bien payé qui demande peu de travail' },
  { word: 'Soliloque', pos: 'noun', definition: 'Discours que se tient une personne seule' },
  { word: 'Sollicitude', pos: 'noun', definition: 'Attention affectueuse et soucieuse du bien-être' },
  { word: 'Sommeiller', pos: 'verb', definition: 'Dormir légèrement, rester en attente' },
  { word: 'Somnolent', pos: 'adjective', definition: 'À demi endormi, engourdi de sommeil' },
  { word: 'Somptueux', pos: 'adjective', definition: 'D\'une magnificence luxueuse' },
  { word: 'Songeur', pos: 'adjective', definition: 'Perdu dans une rêverie pensive' },
  { word: 'Soporifique', pos: 'adjective', definition: 'Si ennuyeux qu\'il endort' },
  { word: 'Sortilège', pos: 'noun', definition: 'Charme magique aux effets mystérieux' },
  { word: 'Soubresaut', pos: 'noun', definition: 'Mouvement brusque et involontaire' },
  { word: 'Soupirant', pos: 'noun', definition: 'Amoureux qui courtise avec assiduité' },
  { word: 'Sournois', pos: 'adjective', definition: 'Qui dissimule ses intentions malveillantes' },
  { word: 'Spartiate', pos: 'adjective', definition: 'D\'une austérité rigoureuse et disciplinée' },
  { word: 'Spleen', pos: 'noun', definition: 'Mélancolie vague et sans cause' },
  { word: 'Sporadique', pos: 'adjective', definition: 'Qui apparaît çà et là, de façon irrégulière' },
  { word: 'Stoïque', pos: 'adjective', definition: 'Qui supporte la douleur sans se plaindre' },
  { word: 'Suave', pos: 'adjective', definition: 'D\'une douceur exquise et caressante' },
  { word: 'Subodorer', pos: 'verb', definition: 'Pressentir, deviner ce qui se trame' },
  { word: 'Subrepticement', pos: 'adverb', definition: 'En cachette, de manière furtive' },
  { word: 'Succinct', pos: 'adjective', definition: 'Dit en peu de mots, bref' },
  { word: 'Succulent', pos: 'adjective', definition: 'D\'une saveur délicieuse' },
  { word: 'Supplique', pos: 'noun', definition: 'Demande humble et insistante' },
  { word: 'Suranné', pos: 'adjective', definition: 'D\'un autre âge, au charme vieillot' },
  { word: 'Surseoir', pos: 'verb', definition: 'Remettre à plus tard, différer' },
  { word: 'Susurrer', pos: 'verb', definition: 'Murmurer doucement à voix légère' },
  { word: 'Sybarite', pos: 'noun', definition: 'Personne qui cultive le raffinement des plaisirs' },
  { word: 'Sycophante', pos: 'noun', definition: 'Délateur flatteur et fourbe' },
  { word: 'Sylvestre', pos: 'adjective', definition: 'Qui appartient à la forêt' },
  { word: 'Tacitement', pos: 'adverb', definition: 'Sans être exprimé, de manière sous-entendue' },
  { word: 'Taciturne', pos: 'adjective', definition: 'Qui parle peu et reste volontiers silencieux' },
  { word: 'Tanguer', pos: 'verb', definition: 'Balancer comme un navire sur la houle' },
  { word: 'Tapageur', pos: 'adjective', definition: 'Qui cherche à attirer bruyamment le regard' },
  { word: 'Taquin', pos: 'adjective', definition: 'Qui aime agacer gentiment pour rire' },
  { word: 'Tarabiscoté', pos: 'adjective', definition: 'Surchargé de détails compliqués' },
  { word: 'Tarir', pos: 'verb', definition: 'Cesser de couler, épuiser une source' },
  { word: 'Tatillon', pos: 'adjective', definition: 'Attaché aux petits détails avec excès' },
  { word: 'Téméraire', pos: 'adjective', definition: 'D\'une audace imprudente et hardie' },
  { word: 'Tempérance', pos: 'noun', definition: 'Modération dans les plaisirs et les désirs' },
  { word: 'Tempétueux', pos: 'adjective', definition: 'Agité de violentes tempêtes' },
  { word: 'Tenace', pos: 'adjective', definition: 'Qui ne renonce jamais, persévérant' },
  { word: 'Ténèbres', pos: 'noun', definition: 'Obscurité profonde et inquiétante' },
  { word: 'Ténu', pos: 'adjective', definition: 'D\'une finesse extrême, à peine perceptible' },
  { word: 'Tergiverser', pos: 'verb', definition: 'User de détours pour éviter de se décider' },
  { word: 'Thaumaturge', pos: 'noun', definition: 'Faiseur de miracles' },
  { word: 'Thuriféraire', pos: 'noun', definition: 'Flatteur qui encense un puissant' },
  { word: 'Timoré', pos: 'adjective', definition: 'Trop craintif pour oser entreprendre' },
  { word: 'Tintamarre', pos: 'noun', definition: 'Vacarme assourdissant et discordant' },
  { word: 'Tintinnabuler', pos: 'verb', definition: 'Sonner comme un grelot ou une clochette' },
  { word: 'Titanesque', pos: 'adjective', definition: 'D\'une ampleur digne des titans' },
  { word: 'Tonitruant', pos: 'adjective', definition: 'D\'une voix éclatante comme le tonnerre' },
  { word: 'Torpeur', pos: 'noun', definition: 'Engourdissement lourd du corps et de l\'esprit' },
  { word: 'Tortueux', pos: 'adjective', definition: 'Plein de détours sinueux ou de ruses' },
  { word: 'Tourbillonner', pos: 'verb', definition: 'Tournoyer rapidement en spirales' },
  { word: 'Tournoyer', pos: 'verb', definition: 'Tourner sur soi en décrivant des cercles' },
  { word: 'Tramontane', pos: 'noun', definition: 'Vent froid du nord qui souffle vers la mer' },
  { word: 'Transcender', pos: 'verb', definition: 'Dépasser et élever au-delà des limites' },
  { word: 'Translucide', pos: 'adjective', definition: 'Qui laisse passer la lumière en la voilant' },
  { word: 'Trépidant', pos: 'adjective', definition: 'D\'un rythme vif et haletant' },
  { word: 'Truculent', pos: 'adjective', definition: 'D\'une verve haute en couleur et savoureuse' },
  { word: 'Truisme', pos: 'noun', definition: 'Vérité si évidente qu\'elle va sans dire' },
  { word: 'Tumultueux', pos: 'adjective', definition: 'Plein d\'agitation bruyante et désordonnée' },
  { word: 'Turpitude', pos: 'noun', definition: 'Conduite honteuse et ignoble' },
  { word: 'Tutélaire', pos: 'adjective', definition: 'Qui protège comme une divinité bienveillante' },
  { word: 'Ubiquité', pos: 'noun', definition: 'Don d\'être présent partout à la fois' },
  { word: 'Ubuesque', pos: 'adjective', definition: 'D\'un absurde grotesque et dérisoire' },
  { word: 'Uchronie', pos: 'noun', definition: 'Histoire réinventée à partir d\'un passé modifié' },
  { word: 'Unisson', pos: 'noun', definition: 'Accord parfait des voix ou des cœurs' },
  { word: 'Urbanité', pos: 'noun', definition: 'Politesse raffinée et courtoise' },
  { word: 'Utopie', pos: 'noun', definition: 'Idéal séduisant mais irréalisable' },
  { word: 'Vacarme', pos: 'noun', definition: 'Grand bruit confus et assourdissant' },
  { word: 'Vagabonder', pos: 'verb', definition: 'Errer librement, sans itinéraire fixé' },
  { word: 'Vaillamment', pos: 'adverb', definition: 'Avec un courage brave et déterminé' },
  { word: 'Vaillance', pos: 'noun', definition: 'Courage brave devant le danger ou la tâche' },
  { word: 'Valeureux', pos: 'adjective', definition: 'Plein de bravoure et de mérite' },
  { word: 'Vaniteux', pos: 'adjective', definition: 'Rempli d\'une fierté frivole et étalée' },
  { word: 'Vaticiner', pos: 'verb', definition: 'Prophétiser avec une emphase déraisonnable' },
  { word: 'Véhément', pos: 'adjective', definition: 'D\'une ardeur impétueuse et passionnée' },
  { word: 'Velléité', pos: 'noun', definition: 'Intention hésitante jamais suivie d\'effet' },
  { word: 'Velouté', pos: 'adjective', definition: 'Doux au toucher ou au goût comme du velours' },
  { word: 'Vénérable', pos: 'adjective', definition: 'Digne du respect dû au grand âge ou à la sagesse' },
  { word: 'Verbeux', pos: 'adjective', definition: 'Qui noie sa pensée dans trop de mots' },
  { word: 'Verdoyant', pos: 'adjective', definition: 'Couvert d\'une végétation bien verte' },
  { word: 'Vernal', pos: 'adjective', definition: 'Propre au printemps' },
  { word: 'Vertigineux', pos: 'adjective', definition: 'Si haut ou si rapide qu\'il donne le vertige' },
  { word: 'Vespéral', pos: 'adjective', definition: 'Propre au soir et à sa lumière déclinante' },
  { word: 'Vétille', pos: 'noun', definition: 'Détail insignifiant dont on fait grand cas' },
  { word: 'Vétuste', pos: 'adjective', definition: 'Détérioré par le temps, vieilli' },
  { word: 'Vigie', pos: 'noun', definition: 'Guetteur attentif posté en observation' },
  { word: 'Vilipender', pos: 'verb', definition: 'Dénoncer comme méprisable, traîner plus bas que terre' },
  { word: 'Vindicatif', pos: 'adjective', definition: 'Porté à la vengeance' },
  { word: 'Virevolter', pos: 'verb', definition: 'Tournoyer avec légèreté et vivacité' },
  { word: 'Virtuose', pos: 'noun', definition: 'Artiste d\'une habileté technique éblouissante' },
  { word: 'Vivace', pos: 'adjective', definition: 'D\'une vitalité durable et résistante' },
  { word: 'Vivifiant', pos: 'adjective', definition: 'Qui ranime les forces et donne de la vigueur' },
  { word: 'Vociférer', pos: 'verb', definition: 'Crier avec colère et véhémence' },
  { word: 'Volubile', pos: 'adjective', definition: 'Qui parle vite et avec abondance' },
  { word: 'Volupté', pos: 'noun', definition: 'Plaisir intense des sens ou de l\'esprit' },
  { word: 'Vorace', pos: 'adjective', definition: 'D\'un appétit dévorant et insatiable' },
  { word: 'Zélateur', pos: 'noun', definition: 'Partisan animé d\'un zèle ardent' },
  { word: 'Zénith', pos: 'noun', definition: 'Point culminant du ciel ou de la réussite' },
  { word: 'Zéphyr', pos: 'noun', definition: 'Vent doux et léger, brise agréable' },
];
