import type { WordEntry } from './types';

export const NL_NL_WORDS: WordEntry[] = [
  { word: 'Aandachtig', pos: 'adjective', definition: 'Met volle en zorgvuldige aandacht' },
  { word: 'Aandenken', pos: 'noun', definition: 'Voorwerp dat de herinnering aan iets of iemand levend houdt' },
  { word: 'Aandoenlijk', pos: 'adjective', definition: 'Vertedering of ontroering opwekkend' },
  { word: 'Aangrijpend', pos: 'adjective', definition: 'Diepe emotie teweegbrengend' },
  { word: 'Aanminnig', pos: 'adjective', definition: 'Lieftallig en innemend' },
  { word: 'Aanschouwelijk', pos: 'adjective', definition: 'Beeldend en duidelijk voorstelbaar' },
  { word: 'Aanschouwen', pos: 'verb', definition: 'Met aandacht bekijken' },
  { word: 'Aanstonds', pos: 'adverb', definition: 'Zo dadelijk, over korte tijd' },
  { word: 'Aanvallig', pos: 'adjective', definition: 'Bekoorlijk en lieftallig van voorkomen' },
  { word: 'Abuis', pos: 'noun', definition: 'Vergissing of misverstand' },
  { word: 'Accuraat', pos: 'adjective', definition: 'Nauwkeurig en zorgvuldig' },
  { word: 'Achteloos', pos: 'adjective', definition: 'Zonder aandacht of zorg gedaan' },
  { word: 'Achtenswaardig', pos: 'adjective', definition: 'Respect en waardering verdienend' },
  { word: 'Adagium', pos: 'noun', definition: 'Kernachtige spreuk of gezegde' },
  { word: 'Adembenemend', pos: 'adjective', definition: 'Zo indrukwekkend dat het de adem beneemt' },
  { word: 'Affectie', pos: 'noun', definition: 'Warme genegenheid' },
  { word: 'Affiniteit', pos: 'noun', definition: 'Natuurlijke verwantschap of aantrekking' },
  { word: 'Afgunst', pos: 'noun', definition: 'Wrevel over andermans geluk of voorspoed' },
  { word: 'Aimabel', pos: 'adjective', definition: 'Beminnelijk en innemend in de omgang' },
  { word: 'Allengs', pos: 'adverb', definition: 'Gaandeweg, langzamerhand' },
  { word: 'Allure', pos: 'noun', definition: 'Voorname uitstraling en stijl' },
  { word: 'Alom', pos: 'adverb', definition: 'Overal, aan alle kanten' },
  { word: 'Altruïsme', pos: 'noun', definition: 'Onbaatzuchtige zorg voor het welzijn van anderen' },
  { word: 'Ambachtelijk', pos: 'adjective', definition: 'Met traditioneel handwerk en vakmanschap vervaardigd' },
  { word: 'Ambivalentie', pos: 'noun', definition: 'Tegenstrijdigheid van gevoelens die tegelijk bestaan' },
  { word: 'Amechtig', pos: 'adjective', definition: 'Buiten adem, hijgend van inspanning' },
  { word: 'Amoureus', pos: 'adjective', definition: 'Verliefd, de liefde betreffend' },
  { word: 'Ampel', pos: 'adjective', definition: 'Uitvoerig en ruimschoots' },
  { word: 'Amper', pos: 'adverb', definition: 'Nauwelijks, ternauwernood' },
  { word: 'Anekdote', pos: 'noun', definition: 'Kort en treffend verhaal uit het werkelijke leven' },
  { word: 'Animo', pos: 'noun', definition: 'Zin en enthousiasme om iets te ondernemen' },
  { word: 'Apert', pos: 'adjective', definition: 'Duidelijk en onmiskenbaar' },
  { word: 'Aplomb', pos: 'noun', definition: 'Zelfverzekerd en gedecideerd optreden' },
  { word: 'Apotheose', pos: 'noun', definition: 'Schitterend hoogtepunt of slotstuk' },
  { word: 'Arcadisch', pos: 'adjective', definition: 'Landelijk en idyllisch als een herdersgedicht' },
  { word: 'Archaïsch', pos: 'adjective', definition: 'Uit een ver verleden stammend' },
  { word: 'Argeloos', pos: 'adjective', definition: 'Zonder achterdocht, onschuldig van aard' },
  { word: 'Argwaan', pos: 'noun', definition: 'Vermoeden dat een ander kwaad in de zin heeft' },
  { word: 'Aroma', pos: 'noun', definition: 'Fijne, kenmerkende geur' },
  { word: 'Asgrauw', pos: 'adjective', definition: 'Vaal en grijs als as' },
  { word: 'Atelier', pos: 'noun', definition: 'Werkplaats van een kunstenaar' },
  { word: 'Attentie', pos: 'noun', definition: 'Klein blijk van aandacht en zorgzaamheid' },
  { word: 'Aubade', pos: 'noun', definition: 'Muzikale hulde gebracht in de vroege ochtend' },
  { word: 'Authentiek', pos: 'adjective', definition: 'Echt, onvervalst en oorspronkelijk' },
  { word: 'Autonoom', pos: 'adjective', definition: 'Zelfstandig en onafhankelijk handelend' },
  { word: 'Avondrood', pos: 'noun', definition: 'Rode gloed aan de westelijke hemel na zonsondergang' },
  { word: 'Avontuur', pos: 'noun', definition: 'Spannende onderneming met onzekere afloop' },
  { word: 'Azuur', pos: 'noun', definition: 'Heldere hemelsblauwe kleur' },
  { word: 'Bakermat', pos: 'noun', definition: 'Plaats waar iets is ontstaan of vandaan komt' },
  { word: 'Balsem', pos: 'noun', definition: 'Verzachtend middel, ook figuurlijk voor troost' },
  { word: 'Balsturig', pos: 'adjective', definition: 'Koppig en weerspannig' },
  { word: 'Barmhartigheid', pos: 'noun', definition: 'Mildheid en mededogen voor wie lijdt' },
  { word: 'Barok', pos: 'adjective', definition: 'Overdadig versierd en weelderig van vorm' },
  { word: 'Beamen', pos: 'verb', definition: 'Instemmend bevestigen wat een ander zegt' },
  { word: 'Bedaard', pos: 'adjective', definition: 'Rustig en kalm van aard' },
  { word: 'Bedachtzaam', pos: 'adjective', definition: 'Rustig nadenkend voor men handelt' },
  { word: 'Bedaren', pos: 'verb', definition: 'Tot rust komen of brengen' },
  { word: 'Bedeesd', pos: 'adjective', definition: 'Verlegen en stil van optreden' },
  { word: 'Bedevaart', pos: 'noun', definition: 'Vrome tocht naar een heilige plaats' },
  { word: 'Bedisselen', pos: 'verb', definition: 'Handig en op eigen wijze regelen' },
  { word: 'Bedrijvig', pos: 'adjective', definition: 'Vol levendige activiteit' },
  { word: 'Beduusd', pos: 'adjective', definition: 'Verbaasd en even uit het veld geslagen' },
  { word: 'Bedwelmend', pos: 'adjective', definition: 'De zinnen verdovend en benevelend' },
  { word: 'Beeldschoon', pos: 'adjective', definition: 'Buitengewoon mooi om te zien' },
  { word: 'Beeldspraak', pos: 'noun', definition: 'Figuurlijk taalgebruik met beelden en vergelijkingen' },
  { word: 'Befaamd', pos: 'adjective', definition: 'Wijd en zijd beroemd' },
  { word: 'Begeesterd', pos: 'adjective', definition: 'Vervuld van vurig enthousiasme' },
  { word: 'Begenadigd', pos: 'adjective', definition: 'Met uitzonderlijk talent gezegend' },
  { word: 'Beginsel', pos: 'noun', definition: 'Grondregel waarop denken of handelen rust' },
  { word: 'Behaaglijk', pos: 'adjective', definition: 'Aangenaam warm en comfortabel aanvoelend' },
  { word: 'Behendigheid', pos: 'noun', definition: 'Vlugheid en vaardigheid van beweging' },
  { word: 'Behoedzaam', pos: 'adjective', definition: 'Voorzichtig en waakzaam te werk gaand' },
  { word: 'Beklijven', pos: 'verb', definition: 'Blijvend indruk maken en in de herinnering voortleven' },
  { word: 'Bekoorlijk', pos: 'adjective', definition: 'Aantrekkelijk door charme en lieflijkheid' },
  { word: 'Bekoren', pos: 'verb', definition: 'Door charme aantrekken en behagen' },
  { word: 'Belezenheid', pos: 'noun', definition: 'Grote kennis verworven door veel lezen' },
  { word: 'Beminnelijk', pos: 'adjective', definition: 'Innemend en gemakkelijk lief te hebben' },
  { word: 'Beminnen', pos: 'verb', definition: 'Liefhebben met tederheid' },
  { word: 'Benard', pos: 'adjective', definition: 'Hachelijk en beklemmend' },
  { word: 'Benevelen', pos: 'verb', definition: 'Het heldere denken zacht vertroebelen' },
  { word: 'Beogen', pos: 'verb', definition: 'Als doel voor ogen hebben' },
  { word: 'Bepeinzen', pos: 'verb', definition: 'Stil en diep overdenken' },
  { word: 'Berusting', pos: 'noun', definition: 'Kalme aanvaarding van wat niet te veranderen is' },
  { word: 'Betoverend', pos: 'adjective', definition: 'Zo mooi dat het als magie aanvoelt' },
  { word: 'Bevallig', pos: 'adjective', definition: 'Sierlijk en gracieus van bewegen' },
  { word: 'Bevlogenheid', pos: 'noun', definition: 'Hartstochtelijke geestdrift voor een zaak' },
  { word: 'Bewieroken', pos: 'verb', definition: 'Overdadig en uitbundig prijzen' },
  { word: 'Bewogen', pos: 'adjective', definition: 'Vol emotie en innerlijke beroering' },
  { word: 'Bezadigd', pos: 'adjective', definition: 'Kalm en evenwichtig door levenservaring' },
  { word: 'Bezield', pos: 'adjective', definition: 'Vervuld van innerlijk vuur en overtuiging' },
  { word: 'Bezinnen', pos: 'verb', definition: 'Rustig nadenken over de diepere betekenis' },
  { word: 'Bezonken', pos: 'adjective', definition: 'Doordacht en tot rijpheid gekomen' },
  { word: 'Bijkans', pos: 'adverb', definition: 'Bijna, nagenoeg' },
  { word: 'Bijwijlen', pos: 'adverb', definition: 'Nu en dan, soms' },
  { word: 'Binnenpret', pos: 'noun', definition: 'Stil plezier om iets dat alleen jij weet' },
  { word: 'Blakend', pos: 'adjective', definition: 'Stralend van gezondheid en energie' },
  { word: 'Blijmoedig', pos: 'adjective', definition: 'Opgewekt en welgemoed van aard' },
  { word: 'Blikvanger', pos: 'noun', definition: 'Iets dat meteen alle aandacht trekt' },
  { word: 'Bloemrijk', pos: 'adjective', definition: 'Rijk aan sierlijke beelden en woorden' },
  { word: 'Bloesem', pos: 'noun', definition: 'Bloeiende bloemen aan een boom of struik' },
  { word: 'Boekenwurm', pos: 'noun', definition: 'Iemand die verzot is op lezen' },
  { word: 'Boezemvriend', pos: 'noun', definition: 'Allerbeste en meest vertrouwde vriend' },
  { word: 'Bourgondisch', pos: 'adjective', definition: 'Genietend van het goede leven, van eten en drinken' },
  { word: 'Bovenaards', pos: 'adjective', definition: 'Zo mooi dat het niet van deze wereld lijkt' },
  { word: 'Bovenal', pos: 'adverb', definition: 'Vooral, meer dan al het andere' },
  { word: 'Branie', pos: 'noun', definition: 'Overmoedige durf en lef' },
  { word: 'Bravoure', pos: 'noun', definition: 'Zwierige durf in optreden' },
  { word: 'Breekbaar', pos: 'adjective', definition: 'Teer en kwetsbaar' },
  { word: 'Brille', pos: 'noun', definition: 'Schittering van geest en talent' },
  { word: 'Broos', pos: 'adjective', definition: 'Teer en licht te beschadigen' },
  { word: 'Bruisen', pos: 'verb', definition: 'Sprankelend borrelen van leven en energie' },
  { word: 'Buitenissig', pos: 'adjective', definition: 'Ongewoon en excentriek' },
  { word: 'Buitenkans', pos: 'noun', definition: 'Onverwacht gelukkig voordeel' },
  { word: 'Cadans', pos: 'noun', definition: 'Regelmatig, wiegend ritme' },
  { word: 'Capricieus', pos: 'adjective', definition: 'Grillig en wispelturig' },
  { word: 'Cerebraal', pos: 'adjective', definition: 'Sterk op het verstand gericht' },
  { word: 'Charisma', pos: 'noun', definition: 'Bijzondere persoonlijke uitstraling die anderen aantrekt' },
  { word: 'Charme', pos: 'noun', definition: 'Innemende bekoorlijkheid' },
  { word: 'Charmeren', pos: 'verb', definition: 'Voor zich innemen door charme' },
  { word: 'Chic', pos: 'adjective', definition: 'Elegant en stijlvol' },
  { word: 'Clementie', pos: 'noun', definition: 'Mildheid en genade in het oordeel' },
  { word: 'Compassie', pos: 'noun', definition: 'Diep meegevoel met het lijden van anderen' },
  { word: 'Consciëntieus', pos: 'adjective', definition: 'Uiterst nauwgezet en plichtsgetrouw' },
  { word: 'Contemplatie', pos: 'noun', definition: 'Stille, diepe beschouwing' },
  { word: 'Coulant', pos: 'adjective', definition: 'Inschikkelijk en soepel in het tegemoetkomen' },
  { word: 'Cru', pos: 'adjective', definition: 'Hard en onverbloemd' },
  { word: 'Cryptisch', pos: 'adjective', definition: 'Raadselachtig en verhuld geformuleerd' },
  { word: 'Culinair', pos: 'adjective', definition: 'De verfijnde kookkunst betreffend' },
  { word: 'Curieus', pos: 'adjective', definition: 'Merkwaardig en nieuwsgierigheid wekkend' },
  { word: 'Dadendrang', pos: 'noun', definition: 'Sterke drang om te handelen en te ondernemen' },
  { word: 'Dagdromen', pos: 'verb', definition: 'Wakend wegzinken in fantasieën' },
  { word: 'Dageraad', pos: 'noun', definition: 'Het eerste ochtendlicht bij het aanbreken van de dag' },
  { word: 'Danig', pos: 'adverb', definition: 'In hoge mate, zeer' },
  { word: 'Dartel', pos: 'adjective', definition: 'Speels en uitgelaten' },
  { word: 'Dartelen', pos: 'verb', definition: 'Vrolijk en speels rondspringen' },
  { word: 'Dauw', pos: 'noun', definition: 'Fijne vochtdruppels die zich in de nacht op planten afzetten' },
  { word: 'Deemoed', pos: 'noun', definition: 'Nederige bescheidenheid' },
  { word: 'Deftig', pos: 'adjective', definition: 'Voornaam en statig' },
  { word: 'Degelijk', pos: 'adjective', definition: 'Solide en betrouwbaar van kwaliteit' },
  { word: 'Deinen', pos: 'verb', definition: 'Zacht op en neer wiegen als golven' },
  { word: 'Delicaat', pos: 'adjective', definition: 'Fijn en teer, met zorg te behandelen' },
  { word: 'Denkbeeldig', pos: 'adjective', definition: 'Alleen in de verbeelding bestaand' },
  { word: 'Deugd', pos: 'noun', definition: 'Morele voortreffelijkheid' },
  { word: 'Devoot', pos: 'adjective', definition: 'Vroom en toegewijd' },
  { word: 'Dichterlijk', pos: 'adjective', definition: 'Poëtisch van taal en verbeelding' },
  { word: 'Diepgang', pos: 'noun', definition: 'Ernst en inhoudelijke rijkdom' },
  { word: 'Diepzinnig', pos: 'adjective', definition: 'Van grote gedachtediepte' },
  { word: 'Dierbaar', pos: 'adjective', definition: 'Innig geliefd en na aan het hart' },
  { word: 'Discretie', pos: 'noun', definition: 'Tact en gepaste terughoudendheid' },
  { word: 'Doldriest', pos: 'adjective', definition: 'Roekeloos overmoedig' },
  { word: 'Dolen', pos: 'verb', definition: 'Zonder vast doel ronddwalen' },
  { word: 'Doorgronden', pos: 'verb', definition: 'Tot de kern van iets doordringen' },
  { word: 'Doorleefd', pos: 'adjective', definition: 'Getekend en verrijkt door levenservaring' },
  { word: 'Doortastend', pos: 'adjective', definition: 'Krachtig en zonder aarzelen optredend' },
  { word: 'Doorwrocht', pos: 'adjective', definition: 'Grondig en met zorg uitgewerkt' },
  { word: 'Doorzettingsvermogen', pos: 'noun', definition: 'Kracht om vol te houden bij tegenslag' },
  { word: 'Driest', pos: 'adjective', definition: 'Vermetel en brutaal van durf' },
  { word: 'Dromerig', pos: 'adjective', definition: 'Half in gedachten en mijmeringen verzonken' },
  { word: 'Duiden', pos: 'verb', definition: 'Betekenis geven aan iets' },
  { word: 'Duizelingwekkend', pos: 'adjective', definition: 'Zo groots dat het duizelt' },
  { word: 'Dwarrelen', pos: 'verb', definition: 'Licht en zwevend in kringen naar beneden vallen' },
  { word: 'Dwepen', pos: 'verb', definition: 'Overdreven vurig vereren' },
  { word: 'Edelmoedigheid', pos: 'noun', definition: 'Grootse onbaatzuchtigheid van hart' },
  { word: 'Eensklaps', pos: 'adverb', definition: 'Plotseling, onverhoeds' },
  { word: 'Eerbied', pos: 'noun', definition: 'Diep respect en ontzag' },
  { word: 'Eerbiedigen', pos: 'verb', definition: 'Met eerbied behandelen en ontzien' },
  { word: 'Eerbiedwaardig', pos: 'adjective', definition: 'Ontzag afdwingend door ouderdom of waardigheid' },
  { word: 'Efemeer', pos: 'adjective', definition: 'Van korte duur, vluchtig als een dag' },
  { word: 'Eigenheid', pos: 'noun', definition: 'Datgene wat iemand onmiskenbaar zichzelf maakt' },
  { word: 'Eigenzinnig', pos: 'adjective', definition: 'Vasthoudend aan de eigen koers en opvattingen' },
  { word: 'Elan', pos: 'noun', definition: 'Geestdriftige zwier en energie' },
  { word: 'Elegie', pos: 'noun', definition: 'Weemoedig klaaggedicht' },
  { word: 'Eloquentie', pos: 'noun', definition: 'Meeslepende welsprekendheid' },
  { word: 'Empathie', pos: 'noun', definition: 'Vermogen zich in de gevoelens van anderen te verplaatsen' },
  { word: 'Engelengeduld', pos: 'noun', definition: 'Onuitputtelijk geduld' },
  { word: 'Enigma', pos: 'noun', definition: 'Raadsel dat zich moeilijk laat doorgronden' },
  { word: 'Epifanie', pos: 'noun', definition: 'Plotseling helder inzicht' },
  { word: 'Erbarmen', pos: 'noun', definition: 'Diep medelijden en ontferming' },
  { word: 'Erfgoed', pos: 'noun', definition: 'Wat van vorige generaties is overgeleverd' },
  { word: 'Erudiet', pos: 'adjective', definition: 'Van grote geleerdheid en brede ontwikkeling' },
  { word: 'Esprit', pos: 'noun', definition: 'Sprankelende geestigheid' },
  { word: 'Esthetisch', pos: 'adjective', definition: 'Op schoonheid gericht' },
  { word: 'Etherisch', pos: 'adjective', definition: 'IJl en vluchtig als uit een andere wereld' },
  { word: 'Euforie', pos: 'noun', definition: 'Overweldigend gevoel van geluk' },
  { word: 'Evenwicht', pos: 'noun', definition: 'Toestand van rust en balans' },
  { word: 'Excelleren', pos: 'verb', definition: 'Uitblinken boven allen' },
  { word: 'Extatisch', pos: 'adjective', definition: 'In vervoering van intense vreugde' },
  { word: 'Fabelachtig', pos: 'adjective', definition: 'Zo bijzonder dat het haast onwerkelijk lijkt' },
  { word: 'Fascineren', pos: 'verb', definition: 'Onweerstaanbaar boeien' },
  { word: 'Feeëriek', pos: 'adjective', definition: 'Sprookjesachtig betoverend' },
  { word: 'Fenomenaal', pos: 'adjective', definition: 'Buitengewoon indrukwekkend' },
  { word: 'Fierheid', pos: 'noun', definition: 'Trotse, zelfbewuste waardigheid' },
  { word: 'Fijnbesnaard', pos: 'adjective', definition: 'Gevoelig en verfijnd van gemoed' },
  { word: 'Fijngevoelig', pos: 'adjective', definition: 'Met veel tact voor andermans gevoelens' },
  { word: 'Filosoferen', pos: 'verb', definition: 'Bespiegelend nadenken over de grote vragen' },
  { word: 'Finesse', pos: 'noun', definition: 'Verfijnd gevoel voor subtiele details' },
  { word: 'Flair', pos: 'noun', definition: 'Natuurlijke zwier en handigheid' },
  { word: 'Flaneren', pos: 'verb', definition: 'Ontspannen wandelen om te zien en gezien te worden' },
  { word: 'Flonkeren', pos: 'verb', definition: 'Levendig schitteren als sterren' },
  { word: 'Florissant', pos: 'adjective', definition: 'Bloeiend en voorspoedig' },
  { word: 'Fluweelzacht', pos: 'adjective', definition: 'Zacht als fluweel' },
  { word: 'Fonkelen', pos: 'verb', definition: 'Helder en levendig glinsteren' },
  { word: 'Formidabel', pos: 'adjective', definition: 'Ontzagwekkend groots' },
  { word: 'Fortuinlijk', pos: 'adjective', definition: 'Door het geluk begunstigd' },
  { word: 'Frank', pos: 'adjective', definition: 'Vrijmoedig en onbevangen' },
  { word: 'Furore', pos: 'noun', definition: 'Opzienbarend succes dat ophef maakt' },
  { word: 'Gaandeweg', pos: 'adverb', definition: 'Langzamerhand, stap voor stap' },
  { word: 'Galant', pos: 'adjective', definition: 'Hoffelijk en voorkomend in de omgang' },
  { word: 'Gastvrijheid', pos: 'noun', definition: 'Hartelijke ontvangst van gasten' },
  { word: 'Geanimeerd', pos: 'adjective', definition: 'Levendig en opgewekt van sfeer' },
  { word: 'Geborgenheid', pos: 'noun', definition: 'Gevoel van veilige, warme beschutting' },
  { word: 'Gedachtegoed', pos: 'noun', definition: 'Geheel van ideeën en opvattingen' },
  { word: 'Gedecideerd', pos: 'adjective', definition: 'Vastberaden en zonder aarzeling' },
  { word: 'Gedegen', pos: 'adjective', definition: 'Grondig en van degelijke kwaliteit' },
  { word: 'Gedenkwaardig', pos: 'adjective', definition: 'Waard om lang herinnerd te worden' },
  { word: 'Gedienstig', pos: 'adjective', definition: 'Bereidwillig om anderen van dienst te zijn' },
  { word: 'Gedistingeerd', pos: 'adjective', definition: 'Voornaam en verfijnd van voorkomen' },
  { word: 'Gedrevenheid', pos: 'noun', definition: 'Vurige innerlijke motivatie' },
  { word: 'Geestdrift', pos: 'noun', definition: 'Vurig enthousiasme' },
  { word: 'Geestig', pos: 'adjective', definition: 'Op een fijne manier grappig en gevat' },
  { word: 'Geestrijk', pos: 'adjective', definition: 'Sprankelend van vernuft en humor' },
  { word: 'Geestverwant', pos: 'noun', definition: 'Iemand die denkt en voelt zoals jij' },
  { word: 'Gelaat', pos: 'noun', definition: 'Het gezicht, in verheven taal' },
  { word: 'Gelaten', pos: 'adjective', definition: 'Kalm berustend in wat komt' },
  { word: 'Geliefkoosd', pos: 'adjective', definition: 'Met voorliefde gekozen, favoriet' },
  { word: 'Gelukzaligheid', pos: 'noun', definition: 'Toestand van volmaakt geluk' },
  { word: 'Gemoedelijk', pos: 'adjective', definition: 'Ontspannen, hartelijk en zonder plichtplegingen' },
  { word: 'Gemoedsrust', pos: 'noun', definition: 'Innerlijke kalmte en vrede' },
  { word: 'Genereus', pos: 'adjective', definition: 'Gul en royaal van geest' },
  { word: 'Genoeglijk', pos: 'adjective', definition: 'Aangenaam en behaaglijk van sfeer' },
  { word: 'Geraffineerd', pos: 'adjective', definition: 'Verfijnd en vernuftig uitgedacht' },
  { word: 'Gerenommeerd', pos: 'adjective', definition: 'Met een gevestigde goede naam' },
  { word: 'Gerieflijk', pos: 'adjective', definition: 'Comfortabel en aangenaam ingericht' },
  { word: 'Gestaag', pos: 'adjective', definition: 'Rustig en zonder onderbreken doorgaand' },
  { word: 'Getijde', pos: 'noun', definition: 'Het ritmisch rijzen en dalen van de zee' },
  { word: 'Gevat', pos: 'adjective', definition: 'Snel en raak van repliek' },
  { word: 'Gewetensvol', pos: 'adjective', definition: 'Handelend naar een zorgvuldig geweten' },
  { word: 'Gewiekst', pos: 'adjective', definition: 'Slim en handig in het benutten van kansen' },
  { word: 'Gezelligheid', pos: 'noun', definition: 'Knus en warm samenzijn waar geen vertaling voor bestaat' },
  { word: 'Gezwind', pos: 'adverb', definition: 'Snel en vlot, in verheven taal' },
  { word: 'Glansrijk', pos: 'adjective', definition: 'Schitterend en met groot succes' },
  { word: 'Glinsteren', pos: 'verb', definition: 'Licht weerkaatsen in kleine schitteringen' },
  { word: 'Gloed', pos: 'noun', definition: 'Warme, zachte uitstraling van licht' },
  { word: 'Gloedvol', pos: 'adjective', definition: 'Warm en vurig van toon' },
  { word: 'Gloren', pos: 'verb', definition: 'Zwak beginnen te lichten, zoals de dageraad' },
  { word: 'Glunderen', pos: 'verb', definition: 'Stralen van stille tevredenheid' },
  { word: 'Goedertieren', pos: 'adjective', definition: 'Mild en genadig gezind' },
  { word: 'Goedgemutst', pos: 'adjective', definition: 'In een opgewekte stemming' },
  { word: 'Goedlachs', pos: 'adjective', definition: 'Snel en graag lachend' },
  { word: 'Gonzen', pos: 'verb', definition: 'Zoemen van bedrijvigheid' },
  { word: 'Grandioos', pos: 'adjective', definition: 'Groots en overweldigend' },
  { word: 'Gratie', pos: 'noun', definition: 'Sierlijke elegantie van beweging' },
  { word: 'Grif', pos: 'adverb', definition: 'Vlot en zonder aarzelen' },
  { word: 'Grillig', pos: 'adjective', definition: 'Onvoorspelbaar veranderlijk' },
  { word: 'Grootmoedig', pos: 'adjective', definition: 'Edel van hart, zonder wrok' },
  { word: 'Grossieren', pos: 'verb', definition: 'In ruime mate bezitten of leveren' },
  { word: 'Guitig', pos: 'adjective', definition: 'Ondeugend en schalks op een innemende manier' },
  { word: 'Gul', pos: 'adjective', definition: 'Royaal in het geven' },
  { word: 'Hachelijk', pos: 'adjective', definition: 'Riskant en vol gevaar' },
  { word: 'Halsstarrig', pos: 'adjective', definition: 'Koppig volhardend in het eigen standpunt' },
  { word: 'Handreiking', pos: 'noun', definition: 'Behulpzaam gebaar om een ander tegemoet te komen' },
  { word: 'Harmonieus', pos: 'adjective', definition: 'In fraaie onderlinge samenklank' },
  { word: 'Hartendief', pos: 'noun', definition: 'Iemand die meteen ieders hart steelt' },
  { word: 'Hartgrondig', pos: 'adverb', definition: 'Uit de grond van het hart, volkomen' },
  { word: 'Hartstocht', pos: 'noun', definition: 'Vurige, allesoverheersende passie' },
  { word: 'Hartverwarmend', pos: 'adjective', definition: 'Weldadig voor het gemoed' },
  { word: 'Heilzaam', pos: 'adjective', definition: 'Goed voor gezondheid en welzijn' },
  { word: 'Heimwee', pos: 'noun', definition: 'Verlangend gemis naar huis of naar vroeger' },
  { word: 'Hekelen', pos: 'verb', definition: 'Scherp bespotten en bekritiseren' },
  { word: 'Hemels', pos: 'adjective', definition: 'Zalig als in de hemel' },
  { word: 'Her en der', pos: 'adverb', definition: 'Verspreid op verschillende plaatsen' },
  { word: 'Herademen', pos: 'verb', definition: 'Opgelucht weer vrij ademhalen' },
  { word: 'Herbergzaam', pos: 'adjective', definition: 'Gastvrij beschutting biedend' },
  { word: 'Herfsttij', pos: 'noun', definition: 'De tijd van de herfst, ook figuurlijk de nadagen' },
  { word: 'Hermetisch', pos: 'adjective', definition: 'Volkomen afgesloten, ook ondoorgrondelijk' },
  { word: 'Heroïsch', pos: 'adjective', definition: 'Heldhaftig en moedig' },
  { word: 'Herrijzen', pos: 'verb', definition: 'Opnieuw oprijzen na verval' },
  { word: 'Hersenspinsel', pos: 'noun', definition: 'Denkbeeld dat alleen in de eigen fantasie bestaat' },
  { word: 'Heuglijk', pos: 'adjective', definition: 'Vreugdevol om te gedenken' },
  { word: 'Hoffelijkheid', pos: 'noun', definition: 'Beleefdheid met ouderwetse gratie' },
  { word: 'Hoogdravend', pos: 'adjective', definition: 'Gezwollen en plechtig van taal' },
  { word: 'Hoogstaand', pos: 'adjective', definition: 'Van hoog moreel gehalte' },
  { word: 'Hoogzomer', pos: 'noun', definition: 'Het warme hart van de zomer' },
  { word: 'Hoopvol', pos: 'adjective', definition: 'Vervuld van hoop en verwachting' },
  { word: 'Houvast', pos: 'noun', definition: 'Iets om steun aan te ontlenen' },
  { word: 'Hovenier', pos: 'noun', definition: 'Tuinman, in verzorgde taal' },
  { word: 'Huiselijk', pos: 'adjective', definition: 'Knus en vertrouwd als thuis' },
  { word: 'Huiveringwekkend', pos: 'adjective', definition: 'Rillingen van ontzag of angst oproepend' },
  { word: 'Hulde', pos: 'noun', definition: 'Eerbewijs vol bewondering' },
  { word: 'Hummel', pos: 'noun', definition: 'Klein, aandoenlijk kind' },
  { word: 'Hunkeren', pos: 'verb', definition: 'Intens verlangen naar iets' },
  { word: 'Ideëel', pos: 'adjective', definition: 'Op idealen gericht, niet op eigenbelang' },
  { word: 'Idylle', pos: 'noun', definition: 'Tafereel van landelijke, ongestoorde vrede' },
  { word: 'Idyllisch', pos: 'adjective', definition: 'Lieflijk en vredig als een idylle' },
  { word: 'Iel', pos: 'adjective', definition: 'Tenger en fijn van bouw' },
  { word: 'Ietwat', pos: 'adverb', definition: 'Enigszins, een klein beetje' },
  { word: 'IJl', pos: 'adjective', definition: 'Dun, teer en vluchtig als lucht' },
  { word: 'IJverig', pos: 'adjective', definition: 'Vlijtig en met toewijding werkend' },
  { word: 'IJzersterk', pos: 'adjective', definition: 'Buitengewoon sterk en overtuigend' },
  { word: 'Illuster', pos: 'adjective', definition: 'Doorluchtig en beroemd' },
  { word: 'Immens', pos: 'adjective', definition: 'Onmetelijk groot' },
  { word: 'Immer', pos: 'adverb', definition: 'Altijd, te allen tijde' },
  { word: 'Impressie', pos: 'noun', definition: 'Indruk die iets op de geest maakt' },
  { word: 'Inborst', pos: 'noun', definition: 'Iemands innerlijke aard' },
  { word: 'Indachtig', pos: 'adjective', definition: 'In gedachten houdend, gedenkend' },
  { word: 'Ingenieus', pos: 'adjective', definition: 'Vernuftig bedacht' },
  { word: 'Ingetogen', pos: 'adjective', definition: 'Sober en beheerst' },
  { word: 'Ingoed', pos: 'adjective', definition: 'Door en door goedhartig' },
  { word: 'Inkeer', pos: 'noun', definition: 'Bezinning en terugkeer tot zichzelf' },
  { word: 'Innemend', pos: 'adjective', definition: 'Meteen sympathie wekkend' },
  { word: 'Innig', pos: 'adjective', definition: 'Diep en warm gevoeld' },
  { word: 'Inschikkelijk', pos: 'adjective', definition: 'Bereid toe te geven en mee te bewegen' },
  { word: 'Integriteit', pos: 'noun', definition: 'Onkreukbare eerlijkheid' },
  { word: 'Intrigeren', pos: 'verb', definition: 'Sterk de nieuwsgierigheid prikkelen' },
  { word: 'Introspectie', pos: 'noun', definition: 'Onderzoekende blik naar het eigen innerlijk' },
  { word: 'Inventief', pos: 'adjective', definition: 'Vindingrijk in oplossingen' },
  { word: 'Jeugdig', pos: 'adjective', definition: 'Fris en levendig als de jeugd' },
  { word: 'Jofel', pos: 'adjective', definition: 'Prettig en tof, op zijn Amsterdams' },
  { word: 'Jolig', pos: 'adjective', definition: 'Uitgelaten vrolijk' },
  { word: 'Jolijt', pos: 'noun', definition: 'Uitgelaten vreugde en plezier' },
  { word: 'Joviaal', pos: 'adjective', definition: 'Hartelijk en gul in de omgang' },
  { word: 'Jubelen', pos: 'verb', definition: 'Luid juichen van vreugde' },
  { word: 'Juweeltje', pos: 'noun', definition: 'Klein ding van bijzondere schoonheid' },
  { word: 'Kaarslicht', pos: 'noun', definition: 'Zacht, warm licht van kaarsen' },
  { word: 'Kalligrafie', pos: 'noun', definition: 'Kunst van het sierlijke schoonschrift' },
  { word: 'Kameraadschap', pos: 'noun', definition: 'Trouwe vriendschap tussen gelijken' },
  { word: 'Karaktervol', pos: 'adjective', definition: 'Met een uitgesproken eigen karakter' },
  { word: 'Karig', pos: 'adjective', definition: 'Sober en spaarzaam bemeten' },
  { word: 'Kernachtig', pos: 'adjective', definition: 'Bondig en raak geformuleerd' },
  { word: 'Keuvelen', pos: 'verb', definition: 'Gezellig en ontspannen praten' },
  { word: 'Kien', pos: 'adjective', definition: 'Scherpzinnig en alert' },
  { word: 'Kittig', pos: 'adjective', definition: 'Levendig en parmantig' },
  { word: 'Klankrijk', pos: 'adjective', definition: 'Vol en fraai van klank' },
  { word: 'Klaterend', pos: 'adjective', definition: 'Helder en sprankelend van klank' },
  { word: 'Kleinood', pos: 'noun', definition: 'Kostbaar sieraad of dierbaar voorwerp' },
  { word: 'Kleurenpracht', pos: 'noun', definition: 'Weelde van schitterende kleuren' },
  { word: 'Kleurrijk', pos: 'adjective', definition: 'Vol kleur en levendige afwisseling' },
  { word: 'Kloek', pos: 'adjective', definition: 'Flink en moedig' },
  { word: 'Knipoog', pos: 'noun', definition: 'Snelle oogwenk van verstandhouding' },
  { word: 'Knus', pos: 'adjective', definition: 'Klein, warm en behaaglijk' },
  { word: 'Koddig', pos: 'adjective', definition: 'Grappig op een aandoenlijke manier' },
  { word: 'Koelbloedigheid', pos: 'noun', definition: 'Kalmte onder grote druk' },
  { word: 'Koesteren', pos: 'verb', definition: 'Liefdevol verzorgen en warm houden' },
  { word: 'Koket', pos: 'adjective', definition: 'Behaagziek en zwierig gekleed' },
  { word: 'Kordaat', pos: 'adjective', definition: 'Flink en doortastend' },
  { word: 'Kortstondig', pos: 'adjective', definition: 'Van korte duur' },
  { word: 'Kostelijk', pos: 'adjective', definition: 'Heerlijk en vermakelijk' },
  { word: 'Kraakhelder', pos: 'adjective', definition: 'Volkomen schoon en helder' },
  { word: 'Krachtdadig', pos: 'adjective', definition: 'Met kracht en daadkracht optredend' },
  { word: 'Kranig', pos: 'adjective', definition: 'Flink en dapper' },
  { word: 'Kristalhelder', pos: 'adjective', definition: 'Volstrekt helder en duidelijk' },
  { word: 'Kundig', pos: 'adjective', definition: 'Bekwaam en deskundig' },
  { word: 'Kunstzinnig', pos: 'adjective', definition: 'Met gevoel en aanleg voor kunst' },
  { word: 'Kwetteren', pos: 'verb', definition: 'Levendig door elkaar tsjilpen en praten' },
  { word: 'Kwiek', pos: 'adjective', definition: 'Vlot en levendig, jong van geest' },
  { word: 'Kwinkslag', pos: 'noun', definition: 'Geestige, gevatte opmerking' },
  { word: 'Laaiend', pos: 'adjective', definition: 'Hevig oplaaiend van vuur of enthousiasme' },
  { word: 'Labyrint', pos: 'noun', definition: 'Doolhof van gangen en paden' },
  { word: 'Landerig', pos: 'adjective', definition: 'Lusteloos en hangerig van stemming' },
  { word: 'Lankmoedig', pos: 'adjective', definition: 'Geduldig en verdraagzaam bij fouten van anderen' },
  { word: 'Laven', pos: 'verb', definition: 'Verkwikken met drank of verfrissing' },
  { word: 'Laveren', pos: 'verb', definition: 'Behendig koersen tussen moeilijkheden door' },
  { word: 'Leergierigheid', pos: 'noun', definition: 'Gretige honger naar kennis' },
  { word: 'Lenig', pos: 'adjective', definition: 'Soepel en buigzaam' },
  { word: 'Lentekriebels', pos: 'noun', definition: 'Onrustig verlangen dat de lente wekt' },
  { word: 'Levenslust', pos: 'noun', definition: 'Blije zin in het leven' },
  { word: 'Lichtelijk', pos: 'adverb', definition: 'In geringe mate, enigszins' },
  { word: 'Lichtvoetig', pos: 'adjective', definition: 'Luchtig en speels van toon' },
  { word: 'Lieflijk', pos: 'adjective', definition: 'Zacht en bekoorlijk' },
  { word: 'Loepzuiver', pos: 'adjective', definition: 'Volmaakt zuiver, zonder enige smet' },
  { word: 'Lokroep', pos: 'noun', definition: 'Verleidelijke roep die aantrekt' },
  { word: 'Lommerrijk', pos: 'adjective', definition: 'Rijk aan schaduwgevend geboomte' },
  { word: 'Lonken', pos: 'verb', definition: 'Verleidelijk toelachen of wenken' },
  { word: 'Louter', pos: 'adverb', definition: 'Enkel en alleen, niets anders dan' },
  { word: 'Loutering', pos: 'noun', definition: 'Zuivering en verheffing door beproeving' },
  { word: 'Loyaal', pos: 'adjective', definition: 'Trouw aan wie of wat je verbonden bent' },
  { word: 'Luchthartig', pos: 'adjective', definition: 'Zorgeloos en licht van gemoed' },
  { word: 'Luister', pos: 'noun', definition: 'Schitterende pracht en glans' },
  { word: 'Luisterrijk', pos: 'adjective', definition: 'Vol pracht en praal' },
  { word: 'Lumineus', pos: 'adjective', definition: 'Schitterend en verhelderend, van een idee' },
  { word: 'Lustig', pos: 'adjective', definition: 'Monter en vrolijk' },
  { word: 'Luwte', pos: 'noun', definition: 'Beschutte plek buiten de wind' },
  { word: 'Lyrisch', pos: 'adjective', definition: 'Vol verrukking en dichterlijke vervoering' },
  { word: 'Magisch', pos: 'adjective', definition: 'Betoverend als door toverkracht' },
  { word: 'Magistraal', pos: 'adjective', definition: 'Meesterlijk van uitvoering' },
  { word: 'Majestueus', pos: 'adjective', definition: 'Groots en koninklijk van verschijning' },
  { word: 'Manmoedig', pos: 'adjective', definition: 'Kloek en onversaagd' },
  { word: 'Marskramer', pos: 'noun', definition: 'Rondtrekkende koopman van weleer' },
  { word: 'Mateloos', pos: 'adjective', definition: 'Zonder maat, grenzeloos' },
  { word: 'Mededogen', pos: 'noun', definition: 'Diep meeleven met andermans leed' },
  { word: 'Mediteren', pos: 'verb', definition: 'In stilte de geest tot rust brengen' },
  { word: 'Meeslepend', pos: 'adjective', definition: 'Zo boeiend dat het je volledig meevoert' },
  { word: 'Meesterschap', pos: 'noun', definition: 'Volmaakte beheersing van een kunst of vak' },
  { word: 'Meevaller', pos: 'noun', definition: 'Onverwacht gunstige uitkomst' },
  { word: 'Melancholie', pos: 'noun', definition: 'Zachte, dromerige zwaarmoedigheid' },
  { word: 'Melodieus', pos: 'adjective', definition: 'Welluidend als een melodie' },
  { word: 'Menslievend', pos: 'adjective', definition: 'Vol liefde voor de medemens' },
  { word: 'Merkwaardig', pos: 'adjective', definition: 'Opmerkelijk en het onthouden waard' },
  { word: 'Metafoor', pos: 'noun', definition: 'Beeldspraak waarbij het ene voor het andere staat' },
  { word: 'Mettertijd', pos: 'adverb', definition: 'Na verloop van tijd, gaandeweg' },
  { word: 'Mijlpaal', pos: 'noun', definition: 'Gedenkwaardig moment op een levensweg' },
  { word: 'Mijmeren', pos: 'verb', definition: 'Dromerig en stil nadenken' },
  { word: 'Mild', pos: 'adjective', definition: 'Zacht en vergevingsgezind in het oordeel' },
  { word: 'Milddadig', pos: 'adjective', definition: 'Gul in het geven aan wie het nodig heeft' },
  { word: 'Mimiek', pos: 'noun', definition: 'Sprekende uitdrukking van het gezicht' },
  { word: 'Minutieus', pos: 'adjective', definition: 'Tot in de kleinste details nauwkeurig' },
  { word: 'Minzaam', pos: 'adjective', definition: 'Vriendelijk en welwillend, met lichte voornaamheid' },
  { word: 'Mirakel', pos: 'noun', definition: 'Wonderbaarlijke gebeurtenis' },
  { word: 'Mondain', pos: 'adjective', definition: 'Werelds en chic' },
  { word: 'Monkelen', pos: 'verb', definition: 'Stilletjes en fijntjes glimlachen' },
  { word: 'Monnikenwerk', pos: 'noun', definition: 'Werk dat eindeloos geduld vergt' },
  { word: 'Monter', pos: 'adjective', definition: 'Fris en opgewekt' },
  { word: 'Monumentaal', pos: 'adjective', definition: 'Groots en indrukwekkend als een monument' },
  { word: 'Morgenstond', pos: 'noun', definition: 'De vroege ochtend' },
  { word: 'Mozaïek', pos: 'noun', definition: 'Kunstwerk van talloze kleine steentjes' },
  { word: 'Muisstil', pos: 'adjective', definition: 'Volkomen stil' },
  { word: 'Murmelen', pos: 'verb', definition: 'Zacht en gelijkmatig ruisen of prevelen' },
  { word: 'Mysterieus', pos: 'adjective', definition: 'Geheimzinnig en raadselachtig' },
  { word: 'Mystiek', pos: 'noun', definition: 'Beleving van het ondoorgrondelijke geheim' },
  { word: 'Naarstig', pos: 'adjective', definition: 'Vlijtig en ijverig' },
  { word: 'Nabijheid', pos: 'noun', definition: 'Vertrouwde aanwezigheid dichtbij' },
  { word: 'Nachtbraken', pos: 'verb', definition: 'Tot diep in de nacht opblijven' },
  { word: 'Nachtegaal', pos: 'noun', definition: 'Zangvogel beroemd om zijn nachtelijke lied' },
  { word: 'Nagalm', pos: 'noun', definition: 'Klank die na blijft klinken' },
  { word: 'Nagenieten', pos: 'verb', definition: 'Achteraf nog genieten van iets moois' },
  { word: 'Natuurschoon', pos: 'noun', definition: 'Schoonheid van het landschap' },
  { word: 'Nauwgezet', pos: 'adjective', definition: 'Stipt en zorgvuldig' },
  { word: 'Nazomer', pos: 'noun', definition: 'Milde zomerse periode aan het begin van de herfst' },
  { word: 'Nederig', pos: 'adjective', definition: 'Bescheiden zonder eigenwaan' },
  { word: 'Neuriën', pos: 'verb', definition: 'Zachtjes een melodie zingen zonder woorden' },
  { word: 'Nietsvermoedend', pos: 'adjective', definition: 'Zonder enig vermoeden van wat komt' },
  { word: 'Nijver', pos: 'adjective', definition: 'Vlijtig aan het werk' },
  { word: 'Niksen', pos: 'verb', definition: 'Bewust lekker niets doen' },
  { word: 'Nimmer', pos: 'adverb', definition: 'Nooit, in verheven taal' },
  { word: 'Nobel', pos: 'adjective', definition: 'Edel van karakter' },
  { word: 'Nochtans', pos: 'adverb', definition: 'Toch, desondanks' },
  { word: 'Noest', pos: 'adjective', definition: 'Onvermoeibaar hard werkend' },
  { word: 'Nonchalant', pos: 'adjective', definition: 'Achteloos en ongedwongen' },
  { word: 'Nostalgie', pos: 'noun', definition: 'Weemoedig verlangen naar vroeger' },
  { word: 'Nuance', pos: 'noun', definition: 'Fijn verschil in betekenis of tint' },
  { word: 'Nuchter', pos: 'adjective', definition: 'Zakelijk en met beide benen op de grond' },
  { word: 'Oase', pos: 'noun', definition: 'Verkwikkende plek van rust te midden van drukte' },
  { word: 'Ochtendgloren', pos: 'noun', definition: 'Het eerste licht van de ochtend' },
  { word: 'Odyssee', pos: 'noun', definition: 'Lange, avontuurlijke zwerftocht' },
  { word: 'Oerkracht', pos: 'noun', definition: 'Elementaire, oorspronkelijke kracht' },
  { word: 'Ogenschijnlijk', pos: 'adverb', definition: 'Naar het zich laat aanzien' },
  { word: 'Olijk', pos: 'adjective', definition: 'Guitig en snaaks' },
  { word: 'Omarmen', pos: 'verb', definition: 'Liefdevol omhelzen, ook figuurlijk verwelkomen' },
  { word: 'Omfloerst', pos: 'adjective', definition: 'Gedempt en met een waas van weemoed omhuld' },
  { word: 'Onbaatzuchtig', pos: 'adjective', definition: 'Zonder eigenbelang handelend' },
  { word: 'Onbedaarlijk', pos: 'adjective', definition: 'Niet tot bedaren te brengen' },
  { word: 'Onbekommerd', pos: 'adjective', definition: 'Vrij van zorgen' },
  { word: 'Onberispelijk', pos: 'adjective', definition: 'Zonder enige fout of smet' },
  { word: 'Onbevangenheid', pos: 'noun', definition: 'Openheid zonder vooroordeel' },
  { word: 'Ondernemend', pos: 'adjective', definition: 'Vol initiatief en durf' },
  { word: 'Onderonsje', pos: 'noun', definition: 'Vertrouwelijk gesprekje in kleine kring' },
  { word: 'Ondeugend', pos: 'adjective', definition: 'Speels stout op een innemende manier' },
  { word: 'Ongedwongenheid', pos: 'noun', definition: 'Natuurlijke, ontspannen omgang zonder formaliteit' },
  { word: 'Ongenaakbaar', pos: 'adjective', definition: 'Onbereikbaar hoog en niet te benaderen' },
  { word: 'Ongerept', pos: 'adjective', definition: 'Zuiver en onaangetast, als wilde natuur' },
  { word: 'Onnavolgbaar', pos: 'adjective', definition: 'Zo bijzonder dat niemand het kan evenaren' },
  { word: 'Onomwonden', pos: 'adverb', definition: 'Ronduit en zonder omhaal' },
  { word: 'Onstuimig', pos: 'adjective', definition: 'Wild en hartstochtelijk bewogen' },
  { word: 'Ontberen', pos: 'verb', definition: 'Node moeten missen' },
  { word: 'Ontboezeming', pos: 'noun', definition: 'Openhartige uiting van gevoelens' },
  { word: 'Ontegenzeggelijk', pos: 'adverb', definition: 'Zonder enige twijfel' },
  { word: 'Onthaasten', pos: 'verb', definition: 'Bewust het levenstempo vertragen' },
  { word: 'Ontluiken', pos: 'verb', definition: 'Zich openen en tot bloei komen' },
  { word: 'Ontplooien', pos: 'verb', definition: 'Tot volle ontwikkeling brengen' },
  { word: 'Ontroeren', pos: 'verb', definition: 'Zacht en diep het gemoed raken' },
  { word: 'Ontwapenend', pos: 'adjective', definition: 'Zo oprecht dat alle weerstand smelt' },
  { word: 'Ontzag', pos: 'noun', definition: 'Diep respect vermengd met bewondering' },
  { word: 'Onvergetelijk', pos: 'adjective', definition: 'Voorgoed in de herinnering gegrift' },
  { word: 'Onverschrokken', pos: 'adjective', definition: 'Zonder vrees voor gevaar' },
  { word: 'Onverzettelijk', pos: 'adjective', definition: 'Niet van zijn koers af te brengen' },
  { word: 'Onwrikbaar', pos: 'adjective', definition: 'Onbeweeglijk vast in overtuiging' },
  { word: 'Oogluikend', pos: 'adverb', definition: 'Stilzwijgend toelatend, alsof men het niet ziet' },
  { word: 'Oogstrelend', pos: 'adjective', definition: 'Prachtig om naar te kijken' },
  { word: 'Ootmoed', pos: 'noun', definition: 'Diepe, stille nederigheid' },
  { word: 'Opbeuren', pos: 'verb', definition: 'Iemand troosten en moed geven' },
  { word: 'Opborrelen', pos: 'verb', definition: 'Spontaan naar boven komen als bubbels' },
  { word: 'Openhartigheid', pos: 'noun', definition: 'Vrijmoedige openheid over eigen gevoelens' },
  { word: 'Opgeruimd', pos: 'adjective', definition: 'Blijmoedig en helder van stemming' },
  { word: 'Opgetogen', pos: 'adjective', definition: 'Blij verrukt' },
  { word: 'Opgewekt', pos: 'adjective', definition: 'Vrolijk gestemd' },
  { word: 'Opklaren', pos: 'verb', definition: 'Helder worden na somberheid, als de lucht na regen' },
  { word: 'Opmerkzaam', pos: 'adjective', definition: 'Scherp waarnemend' },
  { word: 'Opperbest', pos: 'adjective', definition: 'Uitstekend, in de beste orde' },
  { word: 'Orakel', pos: 'noun', definition: 'Raadselachtige bron van wijze uitspraken' },
  { word: 'Ordentelijk', pos: 'adjective', definition: 'Netjes en naar behoren' },
  { word: 'Ornaat', pos: 'noun', definition: 'Plechtige ambtskledij' },
  { word: 'Overdaad', pos: 'noun', definition: 'Weelderige overvloed' },
  { word: 'Overgave', pos: 'noun', definition: 'Volledige toewijding zonder terughouding' },
  { word: 'Overpeinzing', pos: 'noun', definition: 'Stille, diepe gedachte' },
  { word: 'Overrompelen', pos: 'verb', definition: 'Volkomen verrassen en overweldigen' },
  { word: 'Parel', pos: 'noun', definition: 'Kostbaar kleinood, ook figuurlijk iets voortreffelijks' },
  { word: 'Parelmoer', pos: 'noun', definition: 'Regenboogglanzende binnenlaag van schelpen' },
  { word: 'Parmantig', pos: 'adjective', definition: 'Zelfbewust en kwiek van houding' },
  { word: 'Peinzen', pos: 'verb', definition: 'Diep en stil nadenken' },
  { word: 'Penseelstreek', pos: 'noun', definition: 'Enkele streek van het penseel' },
  { word: 'Pienter', pos: 'adjective', definition: 'Slim en vlug van begrip' },
  { word: 'Piëteit', pos: 'noun', definition: 'Eerbiedige zorg voor de nagedachtenis' },
  { word: 'Pionier', pos: 'noun', definition: 'Iemand die als eerste nieuwe wegen baant' },
  { word: 'Pittoresk', pos: 'adjective', definition: 'Schilderachtig mooi' },
  { word: 'Plechtigheid', pos: 'noun', definition: 'Ceremonie vol waardigheid' },
  { word: 'Plechtstatig', pos: 'adjective', definition: 'Statig en ceremonieel' },
  { word: 'Poeslief', pos: 'adjective', definition: 'Overdreven vriendelijk op fluwelen toon' },
  { word: 'Poëtisch', pos: 'adjective', definition: 'Dichterlijk van schoonheid' },
  { word: 'Polderen', pos: 'verb', definition: 'Net zo lang overleggen tot iedereen kan instemmen' },
  { word: 'Pracht', pos: 'noun', definition: 'Schitterende schoonheid' },
  { word: 'Prakkiseren', pos: 'verb', definition: 'Diep piekeren en nadenken, in de volkstaal' },
  { word: 'Pralen', pos: 'verb', definition: 'Schitteren en pronken' },
  { word: 'Prevelen', pos: 'verb', definition: 'Zacht en binnensmonds woorden uitspreken' },
  { word: 'Prieel', pos: 'noun', definition: 'Begroeid tuinhuisje van latwerk' },
  { word: 'Prijzenswaardig', pos: 'adjective', definition: 'Lof verdienend' },
  { word: 'Pril', pos: 'adjective', definition: 'Jong en teer in het eerste begin' },
  { word: 'Proesten', pos: 'verb', definition: 'Onbedaarlijk uitbarsten in lachen' },
  { word: 'Prompt', pos: 'adverb', definition: 'Onmiddellijk en stipt' },
  { word: 'Pronkstuk', pos: 'noun', definition: 'Mooiste stuk van een verzameling' },
  { word: 'Prozaïsch', pos: 'adjective', definition: 'Nuchter en alledaags, zonder poëzie' },
  { word: 'Puik', pos: 'adjective', definition: 'Voortreffelijk van kwaliteit' },
  { word: 'Puntgaaf', pos: 'adjective', definition: 'Volkomen gaaf en onbeschadigd' },
  { word: 'Quintessens', pos: 'noun', definition: 'De kern waar alles om draait' },
  { word: 'Rank', pos: 'adjective', definition: 'Slank en sierlijk van vorm' },
  { word: 'Rechtschapenheid', pos: 'noun', definition: 'Eerlijkheid en rechtvaardigheid van karakter' },
  { word: 'Reikhalzend', pos: 'adverb', definition: 'Vol gespannen verlangen uitkijkend' },
  { word: 'Reislustig', pos: 'adjective', definition: 'Vol verlangen om op reis te gaan' },
  { word: 'Repliek', pos: 'noun', definition: 'Gevat weerwoord' },
  { word: 'Reuring', pos: 'noun', definition: 'Levendige drukte en bedrijvigheid' },
  { word: 'Riant', pos: 'adjective', definition: 'Ruim en weelderig' },
  { word: 'Rimpelloos', pos: 'adjective', definition: 'Volkomen glad en ongestoord' },
  { word: 'Ritselen', pos: 'verb', definition: 'Zacht geluid maken als droge bladeren' },
  { word: 'Robuust', pos: 'adjective', definition: 'Stevig en tegen een stootje bestand' },
  { word: 'Roemrijk', pos: 'adjective', definition: 'Vol roem en eer' },
  { word: 'Roerend', pos: 'adjective', definition: 'Ontroerend teder of aandoenlijk' },
  { word: 'Roezemoezig', pos: 'adjective', definition: 'Gonzend van stemmen en gezelligheid' },
  { word: 'Rondborstig', pos: 'adjective', definition: 'Openhartig en eerlijk zonder terughouding' },
  { word: 'Rooskleurig', pos: 'adjective', definition: 'Gunstig en hoopvol van vooruitzicht' },
  { word: 'Royaal', pos: 'adjective', definition: 'Gul en ruimhartig' },
  { word: 'Ruimdenkend', pos: 'adjective', definition: 'Open voor andere opvattingen' },
  { word: 'Ruisen', pos: 'verb', definition: 'Zacht en gelijkmatig geluid maken als wind of water' },
  { word: 'Rustiek', pos: 'adjective', definition: 'Landelijk en eenvoudig van charme' },
  { word: 'Saamhorigheid', pos: 'noun', definition: 'Gevoel van onderlinge verbondenheid' },
  { word: 'Sacraal', pos: 'adjective', definition: 'Gewijd en heilig van sfeer' },
  { word: 'Sage', pos: 'noun', definition: 'Oud volksverhaal met een kern van waarheid' },
  { word: 'Salomonsoordeel', pos: 'noun', definition: 'Wijs oordeel in een schier onoplosbaar geschil' },
  { word: 'Savoureren', pos: 'verb', definition: 'Met volle aandacht proeven en genieten' },
  { word: 'Schalks', pos: 'adjective', definition: 'Guitig en plagerig' },
  { word: 'Scharrelen', pos: 'verb', definition: 'Rustig rondlopen en her en der bezig zijn' },
  { word: 'Schaterlach', pos: 'noun', definition: 'Luide, onbedaarlijke lach' },
  { word: 'Schatplichtig', pos: 'adjective', definition: 'Veel verschuldigd aan wie voorging' },
  { word: 'Schemering', pos: 'noun', definition: 'Zachte overgang tussen dag en nacht' },
  { word: 'Schemerlamp', pos: 'noun', definition: 'Lamp die zacht, warm licht verspreidt' },
  { word: 'Scherpzinnigheid', pos: 'noun', definition: 'Scherp doordringend verstand' },
  { word: 'Schielijk', pos: 'adverb', definition: 'Haastig en plotseling, in oude taal' },
  { word: 'Schilderachtig', pos: 'adjective', definition: 'Mooi als op een schilderij' },
  { word: 'Schitteren', pos: 'verb', definition: 'Helder stralen en uitblinken' },
  { word: 'Schoorvoetend', pos: 'adverb', definition: 'Aarzelend en met tegenzin' },
  { word: 'Schouwspel', pos: 'noun', definition: 'Boeiend tafereel om naar te kijken' },
  { word: 'Schrander', pos: 'adjective', definition: 'Scherp van verstand' },
  { word: 'Schroom', pos: 'noun', definition: 'Verlegen aarzeling uit eerbied' },
  { word: 'Schuchter', pos: 'adjective', definition: 'Verlegen en terughoudend' },
  { word: 'Sereen', pos: 'adjective', definition: 'Kalm, helder en vredig' },
  { word: 'Serendipiteit', pos: 'noun', definition: 'Het vinden van iets waardevols zonder ernaar te zoeken' },
  { word: 'Sierlijk', pos: 'adjective', definition: 'Elegant van lijn en beweging' },
  { word: 'Slagvaardig', pos: 'adjective', definition: 'Snel en doeltreffend reagerend' },
  { word: 'Slenteren', pos: 'verb', definition: 'Traag en doelloos wandelen' },
  { word: 'Sluier', pos: 'noun', definition: 'Fijn doorschijnend weefsel dat zacht verhult' },
  { word: 'Sluimeren', pos: 'verb', definition: 'Licht slapen, ook verborgen aanwezig zijn' },
  { word: 'Smaakvol', pos: 'adjective', definition: 'Met verfijnde smaak gekozen' },
  { word: 'Smachten', pos: 'verb', definition: 'Hevig en hunkerend verlangen' },
  { word: 'Smeuïg', pos: 'adjective', definition: 'Sappig en smakelijk, ook van verhalen' },
  { word: 'Smoorverliefd', pos: 'adjective', definition: 'Tot over de oren verliefd' },
  { word: 'Snaaks', pos: 'adjective', definition: 'Grappig en guitig' },
  { word: 'Snoeshaan', pos: 'noun', definition: 'Vreemde, zonderlinge kerel' },
  { word: 'Snoezig', pos: 'adjective', definition: 'Schattig en vertederend' },
  { word: 'Snugger', pos: 'adjective', definition: 'Slim en vlug van begrip' },
  { word: 'Soelaas', pos: 'noun', definition: 'Troost en verlichting' },
  { word: 'Soeverein', pos: 'adjective', definition: 'Oppermachtig en volkomen onafhankelijk' },
  { word: 'Soezen', pos: 'verb', definition: 'Behaaglijk half wegdommelen' },
  { word: 'Sonoor', pos: 'adjective', definition: 'Diep en vol van klank' },
  { word: 'Speelsheid', pos: 'noun', definition: 'Vrolijke zin in spel en fantasie' },
  { word: 'Spitsvondig', pos: 'adjective', definition: 'Vernuftig en scherp gevonden' },
  { word: 'Spraakwaterval', pos: 'noun', definition: 'Iemand die honderduit blijft praten' },
  { word: 'Sprakeloos', pos: 'adjective', definition: 'Met stomheid geslagen van verbazing' },
  { word: 'Sprankelen', pos: 'verb', definition: 'Levendig schitteren en bruisen' },
  { word: 'Sprookjesachtig', pos: 'adjective', definition: 'Betoverend mooi als in een sprookje' },
  { word: 'Standvastigheid', pos: 'noun', definition: 'Onwankelbare trouw aan de eigen koers' },
  { word: 'Statig', pos: 'adjective', definition: 'Waardig en indrukwekkend van verschijning' },
  { word: 'Stemmig', pos: 'adjective', definition: 'Ingetogen en sfeervol gedempt' },
  { word: 'Sterrenhemel', pos: 'noun', definition: 'De met sterren bezaaide nachtelijke hemel' },
  { word: 'Stijlvol', pos: 'adjective', definition: 'Met verzorgde, elegante stijl' },
  { word: 'Stilleven', pos: 'noun', definition: 'Schilderij van roerloze voorwerpen' },
  { word: 'Stoïcijns', pos: 'adjective', definition: 'Onverstoorbaar kalm onder alle omstandigheden' },
  { word: 'Stoutmoedig', pos: 'adjective', definition: 'Dapper en vermetel' },
  { word: 'Struinen', pos: 'verb', definition: 'Op zijn gemak rondzwerven en speuren' },
  { word: 'Subliem', pos: 'adjective', definition: 'Van de allerhoogste schoonheid of kwaliteit' },
  { word: 'Subtiel', pos: 'adjective', definition: 'Fijnzinnig en nauwelijks merkbaar' },
  { word: 'Suizen', pos: 'verb', definition: 'Zacht ruisend geluid maken' },
  { word: 'Summum', pos: 'noun', definition: 'Het allerhoogste toppunt' },
  { word: 'Sussen', pos: 'verb', definition: 'Kalmeren en tot bedaren brengen' },
  { word: 'Symfonie', pos: 'noun', definition: 'Groots samenklinkend geheel' },
  { word: 'Tafelen', pos: 'verb', definition: 'Lang en genoeglijk aan tafel zitten' },
  { word: 'Tafereel', pos: 'noun', definition: 'Levendig beeld van een scène' },
  { word: 'Tederheid', pos: 'noun', definition: 'Zachte, liefdevolle genegenheid' },
  { word: 'Telg', pos: 'noun', definition: 'Nakomeling van een geslacht' },
  { word: 'Temperament', pos: 'noun', definition: 'Vurige levendigheid van aard' },
  { word: 'Tenger', pos: 'adjective', definition: 'Fijn en slank gebouwd' },
  { word: 'Terdege', pos: 'adverb', definition: 'Grondig en zeer zeker' },
  { word: 'Terloops', pos: 'adverb', definition: 'In het voorbijgaan, zonder nadruk' },
  { word: 'Tersluiks', pos: 'adverb', definition: 'Steels en onopgemerkt' },
  { word: 'Thuishaven', pos: 'noun', definition: 'Veilige plek waar je altijd kunt terugkeren' },
  { word: 'Tijdloos', pos: 'adjective', definition: 'Boven mode en tijd verheven' },
  { word: 'Tijdverdrijf', pos: 'noun', definition: 'Aangename bezigheid voor lege uren' },
  { word: 'Tinkelen', pos: 'verb', definition: 'Helder en fijn klinken als belletjes' },
  { word: 'Tintelen', pos: 'verb', definition: 'Prikkelend sprankelen van leven' },
  { word: 'Toegenegen', pos: 'adjective', definition: 'Hartelijk gezind' },
  { word: 'Toekomstmuziek', pos: 'noun', definition: 'Iets moois dat nu nog niet haalbaar is' },
  { word: 'Toeverlaat', pos: 'noun', definition: 'Persoon of zaak waarop je altijd kunt steunen' },
  { word: 'Toewijding', pos: 'noun', definition: 'Volledige inzet met hart en ziel' },
  { word: 'Tomeloos', pos: 'adjective', definition: 'Onstuitbaar en zonder rem' },
  { word: 'Toonbeeld', pos: 'noun', definition: 'Volmaakt voorbeeld van iets' },
  { word: 'Toost', pos: 'noun', definition: 'Feestelijke heildronk' },
  { word: 'Tortelduif', pos: 'noun', definition: 'Duif die symbool staat voor tedere liefde' },
  { word: 'Tragikomisch', pos: 'adjective', definition: 'Tegelijk droevig en komisch' },
  { word: 'Trakteren', pos: 'verb', definition: 'Anderen op iets lekkers onthalen' },
  { word: 'Treffend', pos: 'adjective', definition: 'Raak en precies typerend' },
  { word: 'Treuzelen', pos: 'verb', definition: 'Langzaam dralen en tijd rekken' },
  { word: 'Triomf', pos: 'noun', definition: 'Glorieuze overwinning' },
  { word: 'Troetelnaam', pos: 'noun', definition: 'Lief koosnaampje voor een dierbare' },
  { word: 'Trouwhartig', pos: 'adjective', definition: 'Oprecht en trouw van gemoed' },
  { word: 'Turen', pos: 'verb', definition: 'Ingespannen in de verte kijken' },
  { word: 'Tweestrijd', pos: 'noun', definition: 'Innerlijke strijd tussen twee verlangens' },
  { word: 'Twinkeling', pos: 'noun', definition: 'Levendige fonkeling in de ogen' },
  { word: 'Uitblinker', pos: 'noun', definition: 'Iemand die boven allen uitsteekt' },
  { word: 'Uitbuiken', pos: 'verb', definition: 'Na een overvloedige maaltijd rustig laten zakken' },
  { word: 'Uitbundigheid', pos: 'noun', definition: 'Uitgelaten, overvloedige vrolijkheid' },
  { word: 'Uitdossen', pos: 'verb', definition: 'Feestelijk en opvallend aankleden' },
  { word: 'Uitgekiend', pos: 'adjective', definition: 'Tot in de puntjes slim bedacht' },
  { word: 'Uitgelezen', pos: 'adjective', definition: 'Zorgvuldig gekozen en voortreffelijk' },
  { word: 'Uitgeslapen', pos: 'adjective', definition: 'Slim en niet te bedotten' },
  { word: 'Uitgestrekt', pos: 'adjective', definition: 'Zich wijd naar alle kanten uitstrekkend' },
  { word: 'Uithoek', pos: 'noun', definition: 'Ver en afgelegen plek' },
  { word: 'Uitmuntend', pos: 'adjective', definition: 'Van uitzonderlijke kwaliteit' },
  { word: 'Uitpluizen', pos: 'verb', definition: 'Tot op de bodem uitzoeken' },
  { word: 'Uitspanning', pos: 'noun', definition: 'Ouderwetse pleisterplaats voor rust en vertier' },
  { word: 'Uitstraling', pos: 'noun', definition: 'Werking die iemand op anderen heeft' },
  { word: 'Uitverkoren', pos: 'adjective', definition: 'Met zorg boven allen verkozen' },
  { word: 'Uitwaaien', pos: 'verb', definition: 'Buiten in de wind het hoofd leegmaken' },
  { word: 'Uitweiden', pos: 'verb', definition: 'Uitvoerig over iets doorpraten' },
  { word: 'Unisono', pos: 'adverb', definition: 'Eenstemmig en volkomen eensgezind' },
  { word: 'Utopie', pos: 'noun', definition: 'Droombeeld van een volmaakte wereld' },
  { word: 'Vakmanschap', pos: 'noun', definition: 'Meesterlijke beheersing van een ambacht' },
  { word: 'Vederlicht', pos: 'adjective', definition: 'Licht als een veer' },
  { word: 'Veerkracht', pos: 'noun', definition: 'Vermogen om na tegenslag terug te veren' },
  { word: 'Verademing', pos: 'noun', definition: 'Weldadige opluchting' },
  { word: 'Verbeelding', pos: 'noun', definition: 'Scheppende kracht van de fantasie' },
  { word: 'Verbluffend', pos: 'adjective', definition: 'Zo knap dat het verbaast' },
  { word: 'Verfijning', pos: 'noun', definition: 'Beschaafde subtiliteit tot in de details' },
  { word: 'Vergevingsgezind', pos: 'adjective', definition: 'Bereid fouten te vergeven' },
  { word: 'Vergezicht', pos: 'noun', definition: 'Wijds uitzicht tot ver aan de horizon' },
  { word: 'Verguld', pos: 'adjective', definition: 'Blij vereerd en ingenomen' },
  { word: 'Verkwikkend', pos: 'adjective', definition: 'Verfrissend en nieuwe kracht gevend' },
  { word: 'Verlangen', pos: 'noun', definition: 'Zacht trekkend gemis naar wat je liefhebt' },
  { word: 'Vermaard', pos: 'adjective', definition: 'Wijd en zijd vermaard om zijn faam' },
  { word: 'Vermetel', pos: 'adjective', definition: 'Stoutmoedig tot op het roekeloze af' },
  { word: 'Vernuft', pos: 'noun', definition: 'Scherp, vindingrijk verstand' },
  { word: 'Verpozen', pos: 'verb', definition: 'Rust en ontspanning nemen' },
  { word: 'Verrukkelijk', pos: 'adjective', definition: 'Heerlijk en verrukking wekkend' },
  { word: 'Verstild', pos: 'adjective', definition: 'Tot rust gekomen in stille schoonheid' },
  { word: 'Vertederen', pos: 'verb', definition: 'Zacht gevoel van ontroering opwekken' },
  { word: 'Vertier', pos: 'noun', definition: 'Levendig vermaak en bedrijvigheid' },
  { word: 'Vertoeven', pos: 'verb', definition: 'Ergens met genoegen verblijven' },
  { word: 'Vertrouweling', pos: 'noun', definition: 'Iemand aan wie je je geheimen toevertrouwt' },
  { word: 'Vervoering', pos: 'noun', definition: 'Staat van intense verrukking' },
  { word: 'Verwondering', pos: 'noun', definition: 'Open verbazing over het wonderlijke van gewone dingen' },
  { word: 'Verzoenen', pos: 'verb', definition: 'Weer in vrede en harmonie brengen' },
  { word: 'Vindingrijkheid', pos: 'noun', definition: 'Rijkdom aan slimme oplossingen' },
  { word: 'Vlijt', pos: 'noun', definition: 'Toegewijde arbeidzaamheid' },
  { word: 'Voldoening', pos: 'noun', definition: 'Diep gevoel van tevredenheid over wat volbracht is' },
  { word: 'Volgaarne', pos: 'adverb', definition: 'Zeer graag, van harte' },
  { word: 'Volharden', pos: 'verb', definition: 'Standvastig doorzetten tot het einde' },
  { word: 'Volmaakt', pos: 'adjective', definition: 'Zonder enig gebrek' },
  { word: 'Voorliefde', pos: 'noun', definition: 'Bijzondere voorkeur van het hart' },
  { word: 'Voorpret', pos: 'noun', definition: 'Vreugde vooraf om iets moois dat komen gaat' },
  { word: 'Voortreffelijk', pos: 'adjective', definition: 'Van uitstekende kwaliteit' },
  { word: 'Voortvarend', pos: 'adjective', definition: 'Energiek en zonder dralen aanpakkend' },
  { word: 'Vooruitziend', pos: 'adjective', definition: 'Met blik op wat komen gaat' },
  { word: 'Vredig', pos: 'adjective', definition: 'Rustig en van vrede vervuld' },
  { word: 'Vreugdevuur', pos: 'noun', definition: 'Feestelijk vuur ter viering' },
  { word: 'Vrijbuiter', pos: 'noun', definition: 'Iemand die onafhankelijk zijn eigen weg gaat' },
  { word: 'Vroegte', pos: 'noun', definition: 'De vroege ochtenduren' },
  { word: 'Vurig', pos: 'adjective', definition: 'Vol vuur en hartstocht' },
  { word: 'Vuurtoren', pos: 'noun', definition: 'Toren die schepen met zijn licht de weg wijst' },
  { word: 'Waardigheid', pos: 'noun', definition: 'Kalm en zelfbewust eerbiedwaardig voorkomen' },
  { word: 'Weelde', pos: 'noun', definition: 'Rijke overvloed en luxe' },
  { word: 'Weemoed', pos: 'noun', definition: 'Zachte droefheid om wat voorbij is' },
  { word: 'Weerbarstig', pos: 'adjective', definition: 'Stug en zich niet gemakkelijk voegend' },
  { word: 'Weergaloos', pos: 'adjective', definition: 'Zonder gelijke, onovertroffen' },
  { word: 'Weerzien', pos: 'noun', definition: 'Vreugdevol elkaar terugzien na lange tijd' },
  { word: 'Weifelen', pos: 'verb', definition: 'Aarzelend heen en weer twijfelen' },
  { word: 'Welbespraakt', pos: 'adjective', definition: 'Vaardig en vloeiend in het spreken' },
  { word: 'Weldaad', pos: 'noun', definition: 'Daad die goeddoet' },
  { word: 'Weldadig', pos: 'adjective', definition: 'Aangenaam en goeddoend voor lichaam of geest' },
  { word: 'Welgemoed', pos: 'adjective', definition: 'Opgewekt en vol goede moed' },
  { word: 'Weliswaar', pos: 'adverb', definition: 'Toegegeven, het is waar dat' },
  { word: 'Welluidend', pos: 'adjective', definition: 'Aangenaam van klank' },
  { word: 'Welwillendheid', pos: 'noun', definition: 'Vriendelijke, gunstige gezindheid' },
  { word: 'Wenken', pos: 'verb', definition: 'Met een gebaar uitnodigend roepen' },
  { word: 'Wereldwijs', pos: 'adjective', definition: 'Door ervaring bekend met het leven' },
  { word: 'Wervelen', pos: 'verb', definition: 'In snelle kringen ronddraaien' },
  { word: 'Wervelwind', pos: 'noun', definition: 'Iemand of iets vol onstuimige energie' },
  { word: 'Wiegen', pos: 'verb', definition: 'Zacht heen en weer laten deinen' },
  { word: 'Wijsgeer', pos: 'noun', definition: 'Filosoof, beoefenaar van de wijsbegeerte' },
  { word: 'Wilskracht', pos: 'noun', definition: 'Sterke kracht van de wil' },
  { word: 'Windstilte', pos: 'noun', definition: 'Volkomen rust zonder wind' },
  { word: 'Wolkeloos', pos: 'adjective', definition: 'Onbewolkt helder en onbezorgd' },
  { word: 'Wonderbaarlijk', pos: 'adjective', definition: 'Zo bijzonder dat het aan een wonder grenst' },
  { word: 'Wonderschoon', pos: 'adjective', definition: 'Wonderlijk mooi' },
  { word: 'Woordkunstenaar', pos: 'noun', definition: 'Iemand die meesterlijk met taal speelt' },
  { word: 'Wuiven', pos: 'verb', definition: 'Groetend met de hand zwaaien' },
  { word: 'Zachtmoedigheid', pos: 'noun', definition: 'Milde vriendelijkheid van aard' },
  { word: 'Zeegezicht', pos: 'noun', definition: 'Schilderij of uitzicht van de zee' },
  { word: 'Zegetocht', pos: 'noun', definition: 'Reeks van glorieuze successen' },
  { word: 'Zielsverwant', pos: 'noun', definition: 'Iemand met wie je je ten diepste verbonden voelt' },
  { word: 'Zilt', pos: 'adjective', definition: 'Zout als de zee' },
  { word: 'Zinderen', pos: 'verb', definition: 'Trillen van hitte of spanning' },
  { word: 'Zinnebeeld', pos: 'noun', definition: 'Symbool dat een idee verbeeldt' },
  { word: 'Zomeravond', pos: 'noun', definition: 'Lange, zachte avond in de zomer' },
  { word: 'Zonderling', pos: 'noun', definition: 'Excentriek persoon die eigen wegen gaat' },
  { word: 'Zwerven', pos: 'verb', definition: 'Vrij rondtrekken zonder vast doel' },
  { word: 'Zwierig', pos: 'adjective', definition: 'Elegant en losjes van beweging' },
];
