import type { WordEntry } from './types';

export const PT_BR_WORDS: WordEntry[] = [
  { word: 'Abastança', pos: 'noun', definition: 'Fartura de bens; riqueza abundante' },
  { word: 'Abissal', pos: 'adjective', definition: 'Relativo às profundezas do mar; imensamente profundo' },
  { word: 'Abnegação', pos: 'noun', definition: 'Renúncia aos próprios interesses em favor dos outros' },
  { word: 'Abnegado', pos: 'adjective', definition: 'Que se dedica aos outros sem esperar recompensa' },
  { word: 'Abrasador', pos: 'adjective', definition: 'Que queima como brasa; ardente e intenso' },
  { word: 'Absorto', pos: 'adjective', definition: 'Mergulhado em pensamentos; alheio ao que o cerca' },
  { word: 'Acalanto', pos: 'noun', definition: 'Canção suave para embalar o sono; cantiga de ninar' },
  { word: 'Acalentar', pos: 'verb', definition: 'Embalar com carinho; nutrir um sonho ou esperança' },
  { word: 'Acalorado', pos: 'adjective', definition: 'Cheio de entusiasmo ou paixão; inflamado' },
  { word: 'Acerbo', pos: 'adjective', definition: 'Amargo e áspero; rigoroso' },
  { word: 'Acicate', pos: 'noun', definition: 'Estímulo que impele à ação; incentivo' },
  { word: 'Acinte', pos: 'adverb', definition: 'De caso pensado, para provocar' },
  { word: 'Aconchego', pos: 'noun', definition: 'Sensação de abrigo confortável; bem-estar acolhedor' },
  { word: 'Acrisolar', pos: 'verb', definition: 'Purificar; apurar como o ouro no crisol' },
  { word: 'Adágio', pos: 'noun', definition: 'Provérbio antigo que condensa sabedoria popular' },
  { word: 'Adamantino', pos: 'adjective', definition: 'Duro ou brilhante como o diamante; inquebrantável' },
  { word: 'Adejar', pos: 'verb', definition: 'Bater as asas suavemente; esvoaçar' },
  { word: 'Ademais', pos: 'adverb', definition: 'Além disso; ainda por cima' },
  { word: 'Adrede', pos: 'adverb', definition: 'De propósito; deliberadamente' },
  { word: 'Afago', pos: 'noun', definition: 'Carícia suave; demonstração de carinho' },
  { word: 'Afável', pos: 'adjective', definition: 'Gentil e cordial no trato; acolhedor' },
  { word: 'Aforismo', pos: 'noun', definition: 'Frase breve que condensa uma verdade ou princípio' },
  { word: 'Afortunado', pos: 'adjective', definition: 'Favorecido pela sorte; venturoso' },
  { word: 'Ágape', pos: 'noun', definition: 'Refeição fraterna; amor desinteressado pelo próximo' },
  { word: 'Agreste', pos: 'adjective', definition: 'Rústico e áspero; próprio do campo bravio' },
  { word: 'Agridoce', pos: 'adjective', definition: 'Que mistura doçura e amargor' },
  { word: 'Airoso', pos: 'adjective', definition: 'De porte gracioso e elegante; garboso' },
  { word: 'Alacridade', pos: 'noun', definition: 'Alegria viva; disposição animada e pronta' },
  { word: 'Alado', pos: 'adjective', definition: 'Que tem asas; leve e etéreo como o voo' },
  { word: 'Albor', pos: 'noun', definition: 'Primeira claridade do dia; brancura' },
  { word: 'Alento', pos: 'noun', definition: 'Ânimo que renova as forças; fôlego' },
  { word: 'Alfarrábio', pos: 'noun', definition: 'Livro antigo, volumoso e de páginas amareladas' },
  { word: 'Algaravia', pos: 'noun', definition: 'Fala confusa e ruidosa; mistura ininteligível de vozes' },
  { word: 'Algures', pos: 'adverb', definition: 'Em algum lugar' },
  { word: 'Alheamento', pos: 'noun', definition: 'Estado de quem se desliga do mundo ao redor' },
  { word: 'Alhures', pos: 'adverb', definition: 'Em outro lugar' },
  { word: 'Almejar', pos: 'verb', definition: 'Desejar intensamente; aspirar a' },
  { word: 'Altaneiro', pos: 'adjective', definition: 'Que voa ou se ergue bem alto; altivo' },
  { word: 'Altivez', pos: 'noun', definition: 'Dignidade elevada; orgulho nobre' },
  { word: 'Altruísmo', pos: 'noun', definition: 'Dedicação ao bem-estar alheio; generosidade desinteressada' },
  { word: 'Alumbramento', pos: 'noun', definition: 'Deslumbramento súbito; encantamento que ilumina' },
  { word: 'Alvíssaras', pos: 'noun', definition: 'Recompensa a quem traz boa notícia; júbilo' },
  { word: 'Alvorada', pos: 'noun', definition: 'O romper do dia; os primeiros claros da manhã' },
  { word: 'Alvorecer', pos: 'verb', definition: 'Começar a amanhecer; despontar' },
  { word: 'Alvura', pos: 'noun', definition: 'Brancura pura e luminosa' },
  { word: 'Amainar', pos: 'verb', definition: 'Perder a força; acalmar-se, como o vento' },
  { word: 'Amálgama', pos: 'noun', definition: 'Mistura de elementos distintos que formam um todo' },
  { word: 'Ameno', pos: 'adjective', definition: 'Agradável e suave; aprazível' },
  { word: 'Amiúde', pos: 'adverb', definition: 'Com frequência; repetidas vezes' },
  { word: 'Anacoreta', pos: 'noun', definition: 'Quem vive isolado em contemplação; eremita' },
  { word: 'Anelar', pos: 'verb', definition: 'Desejar com ardor; ansiar' },
  { word: 'Anelo', pos: 'noun', definition: 'Desejo ardente; aspiração' },
  { word: 'Animoso', pos: 'adjective', definition: 'Cheio de coragem e ânimo; valente' },
  { word: 'Antanho', pos: 'adverb', definition: 'Em tempos antigos; antigamente' },
  { word: 'Apanágio', pos: 'noun', definition: 'Qualidade própria e exclusiva de alguém ou algo' },
  { word: 'Apogeu', pos: 'noun', definition: 'Ponto mais alto; auge de uma trajetória' },
  { word: 'Apoteose', pos: 'noun', definition: 'Consagração grandiosa; momento de glória máxima' },
  { word: 'Aprazível', pos: 'adjective', definition: 'Que agrada aos sentidos; ameno e acolhedor' },
  { word: 'Aquém', pos: 'adverb', definition: 'Do lado de cá; abaixo do esperado' },
  { word: 'Aquiescer', pos: 'verb', definition: 'Consentir de bom grado; concordar' },
  { word: 'Aquilatar', pos: 'verb', definition: 'Avaliar o valor ou o mérito de; aferir' },
  { word: 'Arauto', pos: 'noun', definition: 'Mensageiro que anuncia; precursor de algo novo' },
  { word: 'Arcano', pos: 'noun', definition: 'Segredo profundo; mistério reservado a poucos' },
  { word: 'Ardil', pos: 'noun', definition: 'Estratagema engenhoso; astúcia' },
  { word: 'Ardiloso', pos: 'adjective', definition: 'Cheio de ardis; astuto e manhoso' },
  { word: 'Argúcia', pos: 'noun', definition: 'Sutileza de raciocínio; perspicácia fina' },
  { word: 'Arguto', pos: 'adjective', definition: 'De inteligência aguda e penetrante; perspicaz' },
  { word: 'Arrebatador', pos: 'adjective', definition: 'Que arrebata de emoção; empolgante' },
  { word: 'Arrebol', pos: 'noun', definition: 'Vermelhidão do céu ao nascer ou ao pôr do sol' },
  { word: 'Arrefecer', pos: 'verb', definition: 'Perder o calor ou o entusiasmo; esfriar' },
  { word: 'Arroubo', pos: 'noun', definition: 'Impulso súbito de entusiasmo; êxtase' },
  { word: 'Assaz', pos: 'adverb', definition: 'Suficientemente; bastante' },
  { word: 'Atavio', pos: 'noun', definition: 'Enfeite esmerado; adorno' },
  { word: 'Audácia', pos: 'noun', definition: 'Coragem ousada; atrevimento' },
  { word: 'Augúrio', pos: 'noun', definition: 'Sinal do que está por vir; presságio' },
  { word: 'Aura', pos: 'noun', definition: 'Atmosfera sutil que envolve alguém ou algo; halo' },
  { word: 'Áureo', pos: 'adjective', definition: 'De ouro; dourado e esplêndido' },
  { word: 'Aurora', pos: 'noun', definition: 'Claridade que antecede o nascer do sol; começo promissor' },
  { word: 'Auspicioso', pos: 'adjective', definition: 'Que promete bom resultado; favorável' },
  { word: 'Austero', pos: 'adjective', definition: 'Rigoroso e sóbrio; sem luxo nem adornos' },
  { word: 'Aveludado', pos: 'adjective', definition: 'Macio como veludo; suave ao toque' },
  { word: 'Avidez', pos: 'noun', definition: 'Desejo intenso e impaciente; sofreguidão' },
  { word: 'Azáfama', pos: 'noun', definition: 'Atividade intensa e apressada; correria' },
  { word: 'Bafejo', pos: 'noun', definition: 'Sopro leve; favor inesperado do destino' },
  { word: 'Bailado', pos: 'noun', definition: 'Dança elaborada; balé' },
  { word: 'Bailar', pos: 'verb', definition: 'Dançar com leveza e graça' },
  { word: 'Balbuciar', pos: 'verb', definition: 'Falar de modo hesitante; articular com dificuldade' },
  { word: 'Bálsamo', pos: 'noun', definition: 'Alívio que suaviza dores; consolo' },
  { word: 'Baluarte', pos: 'noun', definition: 'Fortaleza; quem defende algo com firmeza' },
  { word: 'Beatitude', pos: 'noun', definition: 'Felicidade serena e completa' },
  { word: 'Belicoso', pos: 'adjective', definition: 'Inclinado à guerra; combativo' },
  { word: 'Benevolência', pos: 'noun', definition: 'Boa vontade para com os outros; bondade indulgente' },
  { word: 'Benévolo', pos: 'adjective', definition: 'Que quer bem; indulgente e generoso' },
  { word: 'Benfazejo', pos: 'adjective', definition: 'Que faz o bem; benéfico' },
  { word: 'Benquisto', pos: 'adjective', definition: 'Estimado por todos; querido' },
  { word: 'Bisonho', pos: 'adjective', definition: 'Inexperiente e acanhado; novato' },
  { word: 'Bizantino', pos: 'adjective', definition: 'De discussão inútil e minuciosa; excessivamente rebuscado' },
  { word: 'Boêmio', pos: 'adjective', definition: 'Que vive a noite e as artes; avesso a convenções' },
  { word: 'Bonachão', pos: 'adjective', definition: 'De bondade simples e pacata; afável' },
  { word: 'Bonança', pos: 'noun', definition: 'Tranquilidade após a tempestade; período próspero' },
  { word: 'Bonomia', pos: 'noun', definition: 'Bondade simples; simplicidade afável no trato' },
  { word: 'Boquiaberto', pos: 'adjective', definition: 'De boca aberta por espanto; pasmo' },
  { word: 'Borbulhar', pos: 'verb', definition: 'Formar bolhas; surgir com efervescência' },
  { word: 'Brando', pos: 'adjective', definition: 'Suave e macio; sem aspereza' },
  { word: 'Bravata', pos: 'noun', definition: 'Ostentação de coragem; fanfarronice' },
  { word: 'Bravura', pos: 'noun', definition: 'Coragem valente; intrepidez' },
  { word: 'Brejeiro', pos: 'adjective', definition: 'Maliciosamente gracioso; travesso' },
  { word: 'Brioso', pos: 'adjective', definition: 'Cheio de brio; altivo e valente' },
  { word: 'Bruma', pos: 'noun', definition: 'Névoa leve que envolve a paisagem' },
  { word: 'Brumoso', pos: 'adjective', definition: 'Coberto de bruma; nebuloso' },
  { word: 'Bruxulear', pos: 'verb', definition: 'Tremeluzir como chama prestes a apagar' },
  { word: 'Bucólico', pos: 'adjective', definition: 'Relativo à vida campestre; sereno e pastoral' },
  { word: 'Burilar', pos: 'verb', definition: 'Aperfeiçoar com esmero; lapidar' },
  { word: 'Cabal', pos: 'adjective', definition: 'Completo e exato; pleno' },
  { word: 'Cabotino', pos: 'adjective', definition: 'Que busca exibir-se; teatral e vaidoso' },
  { word: 'Cadência', pos: 'noun', definition: 'Ritmo regular e harmonioso' },
  { word: 'Cadenciado', pos: 'adjective', definition: 'Que segue uma cadência; ritmado' },
  { word: 'Cadente', pos: 'adjective', definition: 'Que cai, como estrela que risca o céu' },
  { word: 'Cafuné', pos: 'noun', definition: 'Carinho feito com os dedos nos cabelos de alguém' },
  { word: 'Calidez', pos: 'noun', definition: 'Calor acolhedor; ternura afetuosa' },
  { word: 'Cálido', pos: 'adjective', definition: 'Quente e acolhedor; caloroso' },
  { word: 'Caligem', pos: 'noun', definition: 'Névoa escura; escuridão densa' },
  { word: 'Candeia', pos: 'noun', definition: 'Pequena lamparina; luz humilde' },
  { word: 'Cândido', pos: 'adjective', definition: 'Puro e ingênuo; alvo como a neve' },
  { word: 'Candura', pos: 'noun', definition: 'Pureza de espírito; inocência' },
  { word: 'Canícula', pos: 'noun', definition: 'Calor intenso do auge do verão' },
  { word: 'Casmurro', pos: 'adjective', definition: 'Teimoso e fechado em si; sorumbático' },
  { word: 'Castiço', pos: 'adjective', definition: 'De origem pura; genuinamente vernáculo' },
  { word: 'Cativante', pos: 'adjective', definition: 'Que cativa; encantador e sedutor' },
  { word: 'Caudal', pos: 'noun', definition: 'Torrente volumosa; fluxo abundante' },
  { word: 'Caudaloso', pos: 'adjective', definition: 'De grande volume de água; abundante' },
  { word: 'Caviloso', pos: 'adjective', definition: 'Que arma ciladas; ardiloso e enganador' },
  { word: 'Celagem', pos: 'noun', definition: 'Aspecto do céu colorido de nuvens' },
  { word: 'Celeuma', pos: 'noun', definition: 'Discussão ruidosa; polêmica acalorada' },
  { word: 'Cerne', pos: 'noun', definition: 'Parte central e essencial de algo' },
  { word: 'Ceticismo', pos: 'noun', definition: 'Atitude de quem duvida; descrença metódica' },
  { word: 'Chamego', pos: 'noun', definition: 'Carinho afetuoso; demonstração de ternura' },
  { word: 'Chispa', pos: 'noun', definition: 'Faísca; centelha breve' },
  { word: 'Ciclópico', pos: 'adjective', definition: 'De proporções gigantescas; colossal' },
  { word: 'Cingir', pos: 'verb', definition: 'Rodear; apertar em volta' },
  { word: 'Cintilante', pos: 'adjective', definition: 'Que brilha em lampejos; reluzente' },
  { word: 'Cintilar', pos: 'verb', definition: 'Brilhar com pequenos lampejos; faiscar' },
  { word: 'Circunlóquio', pos: 'noun', definition: 'Rodeio de palavras para dizer algo simples' },
  { word: 'Circunspecto', pos: 'adjective', definition: 'Prudente e reservado; ponderado' },
  { word: 'Cismar', pos: 'verb', definition: 'Pensar insistentemente em algo; matutar' },
  { word: 'Cizânia', pos: 'noun', definition: 'Discórdia semeada entre pessoas' },
  { word: 'Clangor', pos: 'noun', definition: 'Som forte de trombeta; estrondo metálico' },
  { word: 'Clarão', pos: 'noun', definition: 'Luz súbita e intensa; brilho repentino' },
  { word: 'Clarividência', pos: 'noun', definition: 'Capacidade de perceber com lucidez o que escapa aos outros' },
  { word: 'Clemência', pos: 'noun', definition: 'Disposição para perdoar; brandura' },
  { word: 'Colossal', pos: 'adjective', definition: 'De tamanho descomunal; gigantesco' },
  { word: 'Comedido', pos: 'adjective', definition: 'Que age com moderação; contido' },
  { word: 'Comiseração', pos: 'noun', definition: 'Compaixão pela desgraça alheia' },
  { word: 'Comovente', pos: 'adjective', definition: 'Que toca profundamente; emocionante' },
  { word: 'Compassivo', pos: 'adjective', definition: 'Que sente compaixão; piedoso' },
  { word: 'Complacente', pos: 'adjective', definition: 'Que cede com benevolência; condescendente' },
  { word: 'Concisão', pos: 'noun', definition: 'Arte de dizer muito em poucas palavras' },
  { word: 'Condão', pos: 'noun', definition: 'Poder mágico; dom especial' },
  { word: 'Confabular', pos: 'verb', definition: 'Conversar em segredo; tramar' },
  { word: 'Congraçar', pos: 'verb', definition: 'Reconciliar; unir em harmonia' },
  { word: 'Conluio', pos: 'noun', definition: 'Acordo secreto para enganar; trama' },
  { word: 'Constelado', pos: 'adjective', definition: 'Semeado de estrelas; salpicado de pontos brilhantes' },
  { word: 'Consternado', pos: 'adjective', definition: 'Abatido por profunda tristeza' },
  { word: 'Contemplar', pos: 'verb', definition: 'Olhar com atenção e encanto; admirar demoradamente' },
  { word: 'Contrito', pos: 'adjective', definition: 'Arrependido de coração; compungido' },
  { word: 'Contumaz', pos: 'adjective', definition: 'Que insiste teimosamente; obstinado' },
  { word: 'Convalescer', pos: 'verb', definition: 'Recuperar as forças após uma doença' },
  { word: 'Copioso', pos: 'adjective', definition: 'Abundante; farto' },
  { word: 'Cordato', pos: 'adjective', definition: 'Sensato e prudente; conciliador' },
  { word: 'Corriqueiro', pos: 'adjective', definition: 'Comum e habitual; trivial' },
  { word: 'Cortejar', pos: 'verb', definition: 'Fazer a corte; galantear' },
  { word: 'Coruscante', pos: 'adjective', definition: 'Que fulgura; brilhante como relâmpago' },
  { word: 'Crédulo', pos: 'adjective', definition: 'Que acredita com facilidade; ingênuo' },
  { word: 'Crepitar', pos: 'verb', definition: 'Estalar como lenha ao fogo' },
  { word: 'Crepúsculo', pos: 'noun', definition: 'Luz entre o dia e a noite; entardecer' },
  { word: 'Cristalino', pos: 'adjective', definition: 'Claro e transparente como cristal' },
  { word: 'Crivar', pos: 'verb', definition: 'Encher de furos ou de perguntas; cravejar' },
  { word: 'Cumplicidade', pos: 'noun', definition: 'Entendimento tácito entre pessoas próximas' },
  { word: 'Dádiva', pos: 'noun', definition: 'Presente generoso; dom' },
  { word: 'Dadivoso', pos: 'adjective', definition: 'Generoso em dar; liberal' },
  { word: 'Deambular', pos: 'verb', definition: 'Passear a esmo; perambular' },
  { word: 'Debalde', pos: 'adverb', definition: 'Em vão; inutilmente' },
  { word: 'Deblaterar', pos: 'verb', definition: 'Falar com veemência contra algo; protestar ruidosamente' },
  { word: 'Debruçar', pos: 'verb', definition: 'Inclinar-se sobre; dedicar-se com atenção a' },
  { word: 'Decantado', pos: 'adjective', definition: 'Celebrado; louvado repetidamente' },
  { word: 'Decoro', pos: 'noun', definition: 'Compostura digna; respeito às conveniências' },
  { word: 'Deferência', pos: 'noun', definition: 'Respeito atencioso; consideração' },
  { word: 'Defronte', pos: 'adverb', definition: 'Em frente; face a face' },
  { word: 'Deleitar', pos: 'verb', definition: 'Dar deleite; encantar os sentidos' },
  { word: 'Deleite', pos: 'noun', definition: 'Prazer intenso; delícia' },
  { word: 'Deleitoso', pos: 'adjective', definition: 'Que dá prazer; delicioso' },
  { word: 'Dengoso', pos: 'adjective', definition: 'Cheio de dengo; manhoso e mimoso' },
  { word: 'Denodado', pos: 'adjective', definition: 'Corajoso e decidido; intrépido' },
  { word: 'Denodo', pos: 'noun', definition: 'Coragem esforçada; bravura' },
  { word: 'Derradeiro', pos: 'adjective', definition: 'O último; final' },
  { word: 'Desabrido', pos: 'adjective', definition: 'Áspero e violento; descortês' },
  { word: 'Desabrochar', pos: 'verb', definition: 'Abrir-se como flor; revelar-se plenamente' },
  { word: 'Desalento', pos: 'noun', definition: 'Perda de ânimo; desânimo' },
  { word: 'Desassossego', pos: 'noun', definition: 'Falta de sossego; inquietação' },
  { word: 'Desbravar', pos: 'verb', definition: 'Explorar terras desconhecidas; abrir caminho' },
  { word: 'Descomunal', pos: 'adjective', definition: 'Fora do comum; enorme' },
  { word: 'Descortinar', pos: 'verb', definition: 'Revelar ao olhar; avistar amplamente' },
  { word: 'Descortino', pos: 'noun', definition: 'Perspicácia para ver longe; discernimento' },
  { word: 'Desdém', pos: 'noun', definition: 'Indiferença altiva; desprezo' },
  { word: 'Desdenhar', pos: 'verb', definition: 'Tratar com desdém; menosprezar' },
  { word: 'Desditoso', pos: 'adjective', definition: 'Sem sorte; infeliz' },
  { word: 'Desfaçatez', pos: 'noun', definition: 'Atrevimento cínico; descaramento' },
  { word: 'Desiderato', pos: 'noun', definition: 'Aquilo que se deseja alcançar; objetivo almejado' },
  { word: 'Deslumbrar', pos: 'verb', definition: 'Ofuscar de admiração; encantar intensamente' },
  { word: 'Deslumbre', pos: 'noun', definition: 'Encantamento diante do que ofusca de tão belo' },
  { word: 'Desmesurado', pos: 'adjective', definition: 'Sem medida; exagerado' },
  { word: 'Despautério', pos: 'noun', definition: 'Disparate; absurdo completo' },
  { word: 'Despretensioso', pos: 'adjective', definition: 'Sem pretensões; simples e modesto' },
  { word: 'Destarte', pos: 'adverb', definition: 'Desse modo; assim sendo' },
  { word: 'Destemor', pos: 'noun', definition: 'Ausência de medo; coragem' },
  { word: 'Desvanecer', pos: 'verb', definition: 'Dissipar-se aos poucos; esvaecer' },
  { word: 'Desvelo', pos: 'noun', definition: 'Cuidado zeloso e dedicado' },
  { word: 'Devanear', pos: 'verb', definition: 'Entregar-se a devaneios; fantasiar' },
  { word: 'Devaneio', pos: 'noun', definition: 'Sonho acordado; fantasia da imaginação' },
  { word: 'Deveras', pos: 'adverb', definition: 'Verdadeiramente; de fato' },
  { word: 'Devotar', pos: 'verb', definition: 'Dedicar com devoção; consagrar' },
  { word: 'Diáfano', pos: 'adjective', definition: 'Que deixa passar a luz; translúcido e delicado' },
  { word: 'Dileto', pos: 'adjective', definition: 'Muito querido; predileto' },
  { word: 'Diligência', pos: 'noun', definition: 'Zelo ativo; presteza cuidadosa' },
  { word: 'Diligente', pos: 'adjective', definition: 'Que trabalha com zelo e presteza' },
  { word: 'Dirimir', pos: 'verb', definition: 'Resolver um conflito; extinguir uma dúvida' },
  { word: 'Ditoso', pos: 'adjective', definition: 'Cheio de dita; feliz e afortunado' },
  { word: 'Divagar', pos: 'verb', definition: 'Vagar em pensamentos; discorrer sem rumo fixo' },
  { word: 'Docilidade', pos: 'noun', definition: 'Índole branda; suavidade de gênio' },
  { word: 'Donaire', pos: 'noun', definition: 'Elegância graciosa nos gestos e no porte' },
  { word: 'Doravante', pos: 'adverb', definition: 'De agora em diante; daqui para a frente' },
  { word: 'Dúctil', pos: 'adjective', definition: 'Que se molda com facilidade; flexível' },
  { word: 'Dulçor', pos: 'noun', definition: 'Doçura suave; brandura' },
  { word: 'Ebulição', pos: 'noun', definition: 'Estado do que ferve; agitação intensa' },
  { word: 'Ebúrneo', pos: 'adjective', definition: 'De marfim; branco e liso como o marfim' },
  { word: 'Eclético', pos: 'adjective', definition: 'Que reúne estilos ou gostos diversos' },
  { word: 'Eclosão', pos: 'noun', definition: 'Surgimento repentino; nascimento' },
  { word: 'Edificante', pos: 'adjective', definition: 'Que eleva moralmente; exemplar' },
  { word: 'Efeméride', pos: 'noun', definition: 'Data que celebra um acontecimento memorável' },
  { word: 'Efêmero', pos: 'adjective', definition: 'Que dura pouco; passageiro' },
  { word: 'Efervescência', pos: 'noun', definition: 'Agitação borbulhante; entusiasmo fervilhante' },
  { word: 'Eflúvio', pos: 'noun', definition: 'Emanação sutil; perfume que se espalha no ar' },
  { word: 'Efusivo', pos: 'adjective', definition: 'Que expressa sentimentos com calor; expansivo' },
  { word: 'Egrégio', pos: 'adjective', definition: 'Notável; ilustre e distinto' },
  { word: 'Elã', pos: 'noun', definition: 'Impulso entusiasmado; vigor arrebatador' },
  { word: 'Elegia', pos: 'noun', definition: 'Poema melancólico de lamento e saudade' },
  { word: 'Eloquência', pos: 'noun', definition: 'Arte de falar com força e beleza' },
  { word: 'Elucidar', pos: 'verb', definition: 'Tornar claro; esclarecer' },
  { word: 'Elucubração', pos: 'noun', definition: 'Reflexão trabalhosa e profunda; devaneio intelectual' },
  { word: 'Embevecer', pos: 'verb', definition: 'Encantar profundamente; arrebatar de admiração' },
  { word: 'Embotar', pos: 'verb', definition: 'Tornar menos agudo; enfraquecer a sensibilidade' },
  { word: 'Embrenhar', pos: 'verb', definition: 'Meter-se mata adentro; internar-se profundamente' },
  { word: 'Emérito', pos: 'adjective', definition: 'De mérito reconhecido; exímio' },
  { word: 'Encapelado', pos: 'adjective', definition: 'De mar agitado; revolto' },
  { word: 'Encômio', pos: 'noun', definition: 'Elogio solene; louvor entusiástico' },
  { word: 'Enevoado', pos: 'adjective', definition: 'Coberto de névoa; toldado' },
  { word: 'Engenho', pos: 'noun', definition: 'Talento inventivo; habilidade criadora' },
  { word: 'Engenhoso', pos: 'adjective', definition: 'Cheio de engenho; criativo e habilidoso' },
  { word: 'Enlace', pos: 'noun', definition: 'União; laço que une duas vidas' },
  { word: 'Enlevo', pos: 'noun', definition: 'Êxtase suave; arrebatamento contemplativo' },
  { word: 'Enobrecer', pos: 'verb', definition: 'Tornar nobre; dignificar' },
  { word: 'Enseada', pos: 'noun', definition: 'Pequena baía abrigada' },
  { word: 'Ensejar', pos: 'verb', definition: 'Dar ocasião a; propiciar' },
  { word: 'Ensejo', pos: 'noun', definition: 'Oportunidade; ocasião propícia' },
  { word: 'Ensimesmado', pos: 'adjective', definition: 'Voltado para dentro de si; absorto' },
  { word: 'Entardecer', pos: 'noun', definition: 'Fim da tarde; declínio suave do dia' },
  { word: 'Enternecer', pos: 'verb', definition: 'Comover de ternura; abrandar o coração' },
  { word: 'Entoar', pos: 'verb', definition: 'Começar a cantar; cantar em tom certo' },
  { word: 'Entrementes', pos: 'adverb', definition: 'Nesse meio-tempo; enquanto isso' },
  { word: 'Epifania', pos: 'noun', definition: 'Revelação súbita e iluminadora' },
  { word: 'Epíteto', pos: 'noun', definition: 'Palavra que qualifica; alcunha expressiva' },
  { word: 'Epopeia', pos: 'noun', definition: 'Narrativa heroica; feito grandioso' },
  { word: 'Equânime', pos: 'adjective', definition: 'Que julga com equilíbrio; imparcial' },
  { word: 'Equidade', pos: 'noun', definition: 'Justiça com senso de igualdade' },
  { word: 'Errância', pos: 'noun', definition: 'Ato de vagar; vida sem pouso fixo' },
  { word: 'Errante', pos: 'adjective', definition: 'Que vagueia sem destino fixo' },
  { word: 'Erudito', pos: 'adjective', definition: 'De vasto saber; profundamente culto' },
  { word: 'Escarcéu', pos: 'noun', definition: 'Alvoroço exagerado; alarde' },
  { word: 'Escarpado', pos: 'adjective', definition: 'Íngreme; de encosta abrupta' },
  { word: 'Escrutinar', pos: 'verb', definition: 'Examinar minuciosamente; investigar a fundo' },
  { word: 'Esgueirar', pos: 'verb', definition: 'Escapar furtivamente; sair de mansinho' },
  { word: 'Esmaecer', pos: 'verb', definition: 'Perder a cor ou a força; desbotar' },
  { word: 'Esmerar', pos: 'verb', definition: 'Executar com o máximo capricho; aprimorar' },
  { word: 'Esmero', pos: 'noun', definition: 'Cuidado extremo; capricho apurado' },
  { word: 'Esmiuçar', pos: 'verb', definition: 'Examinar em detalhes; explicar minuciosamente' },
  { word: 'Espargir', pos: 'verb', definition: 'Espalhar em gotas; derramar ao redor' },
  { word: 'Esplendor', pos: 'noun', definition: 'Brilho magnífico; grandiosidade' },
  { word: 'Espraiar', pos: 'verb', definition: 'Estender-se como a onda pela praia; espalhar-se' },
  { word: 'Esquadrinhar', pos: 'verb', definition: 'Examinar palmo a palmo; vasculhar' },
  { word: 'Esquivo', pos: 'adjective', definition: 'Que evita contato; arisco' },
  { word: 'Estirpe', pos: 'noun', definition: 'Linhagem; origem familiar' },
  { word: 'Estival', pos: 'adjective', definition: 'Relativo ao verão' },
  { word: 'Estoico', pos: 'adjective', definition: 'Que suporta a dor com firmeza; impassível' },
  { word: 'Estrépito', pos: 'noun', definition: 'Ruído forte; estrondo' },
  { word: 'Esvair', pos: 'verb', definition: 'Dissipar-se; esgotar-se aos poucos' },
  { word: 'Esvoaçante', pos: 'adjective', definition: 'Que flutua ao vento; que adeja' },
  { word: 'Etéreo', pos: 'adjective', definition: 'Leve e sutil como o éter; celestial' },
  { word: 'Eufonia', pos: 'noun', definition: 'Sonoridade agradável aos ouvidos' },
  { word: 'Evanescente', pos: 'adjective', definition: 'Que se desvanece; fugidio' },
  { word: 'Evocar', pos: 'verb', definition: 'Trazer à lembrança; invocar' },
  { word: 'Exalar', pos: 'verb', definition: 'Desprender de si; emanar' },
  { word: 'Excelso', pos: 'adjective', definition: 'Muito elevado; sublime' },
  { word: 'Exíguo', pos: 'adjective', definition: 'Muito pequeno; escasso' },
  { word: 'Exímio', pos: 'adjective', definition: 'Excelente em seu ofício; exemplar' },
  { word: 'Exorbitante', pos: 'adjective', definition: 'Que ultrapassa toda medida; excessivo' },
  { word: 'Exórdio', pos: 'noun', definition: 'Início de um discurso; começo' },
  { word: 'Exuberante', pos: 'adjective', definition: 'Que transborda vitalidade; abundante' },
  { word: 'Exultar', pos: 'verb', definition: 'Alegrar-se intensamente; rejubilar' },
  { word: 'Fabular', pos: 'verb', definition: 'Inventar histórias; narrar fábulas' },
  { word: 'Faceiro', pos: 'adjective', definition: 'Elegante e alegre; garboso' },
  { word: 'Faceto', pos: 'adjective', definition: 'Gracioso; espirituoso' },
  { word: 'Facúndia', pos: 'noun', definition: 'Facilidade de falar; eloquência abundante' },
  { word: 'Fadário', pos: 'noun', definition: 'Destino penoso; sina' },
  { word: 'Fado', pos: 'noun', definition: 'Destino; sorte traçada' },
  { word: 'Fagueiro', pos: 'adjective', definition: 'Meigo e acariciante; aprazível' },
  { word: 'Fagulha', pos: 'noun', definition: 'Partícula incandescente; faísca' },
  { word: 'Faina', pos: 'noun', definition: 'Trabalho árduo; lida diária' },
  { word: 'Faiscar', pos: 'verb', definition: 'Soltar faíscas; cintilar' },
  { word: 'Falaz', pos: 'adjective', definition: 'Enganoso; ilusório' },
  { word: 'Falésia', pos: 'noun', definition: 'Penhasco abrupto à beira-mar' },
  { word: 'Fanal', pos: 'noun', definition: 'Farol; luz que guia' },
  { word: 'Farfalhar', pos: 'verb', definition: 'Produzir rumor de folhas ao vento' },
  { word: 'Fascínio', pos: 'noun', definition: 'Atração irresistível; encanto' },
  { word: 'Fastio', pos: 'noun', definition: 'Falta de apetite ou de interesse; tédio' },
  { word: 'Fatídico', pos: 'adjective', definition: 'Marcado pelo destino; funesto' },
  { word: 'Fátuo', pos: 'adjective', definition: 'Presunçoso e vazio; tolo' },
  { word: 'Fausto', pos: 'noun', definition: 'Luxo ostentoso; pompa' },
  { word: 'Fecundo', pos: 'adjective', definition: 'Fértil; que produz em abundância' },
  { word: 'Feérico', pos: 'adjective', definition: 'Deslumbrante como um conto de fadas; mágico' },
  { word: 'Feitiço', pos: 'noun', definition: 'Encantamento mágico; fascínio irresistível' },
  { word: 'Fenecer', pos: 'verb', definition: 'Chegar ao fim; murchar' },
  { word: 'Férvido', pos: 'adjective', definition: 'Ardente; fervoroso' },
  { word: 'Fervor', pos: 'noun', definition: 'Ardor intenso; devoção calorosa' },
  { word: 'Festim', pos: 'noun', definition: 'Banquete festivo; celebração' },
  { word: 'Fidalgo', pos: 'noun', definition: 'Nobre; pessoa de conduta distinta' },
  { word: 'Fidedigno', pos: 'adjective', definition: 'Digno de fé; confiável' },
  { word: 'Filantropia', pos: 'noun', definition: 'Amor à humanidade; generosidade social' },
  { word: 'Filigrana', pos: 'noun', definition: 'Ornamento delicado de fios finos; detalhe minucioso' },
  { word: 'Firmamento', pos: 'noun', definition: 'Abóbada celeste; o céu estrelado' },
  { word: 'Flanar', pos: 'verb', definition: 'Passear sem rumo, observando a cidade' },
  { word: 'Fleuma', pos: 'noun', definition: 'Calma imperturbável; serenidade fria' },
  { word: 'Floreio', pos: 'noun', definition: 'Ornamento gracioso; gesto elegante' },
  { word: 'Florescer', pos: 'verb', definition: 'Cobrir-se de flores; prosperar' },
  { word: 'Fluidez', pos: 'noun', definition: 'Qualidade do que corre com facilidade e leveza' },
  { word: 'Folgazão', pos: 'adjective', definition: 'Amigo de folias; brincalhão' },
  { word: 'Folguedo', pos: 'noun', definition: 'Brincadeira festiva; divertimento popular' },
  { word: 'Formosura', pos: 'noun', definition: 'Beleza; qualidade do que é formoso' },
  { word: 'Fortuito', pos: 'adjective', definition: 'Que acontece por acaso; casual' },
  { word: 'Fragor', pos: 'noun', definition: 'Estrondo; ruído de coisas que se quebram' },
  { word: 'Fragrância', pos: 'noun', definition: 'Perfume agradável; aroma suave' },
  { word: 'Franzino', pos: 'adjective', definition: 'De constituição frágil; delgado' },
  { word: 'Fremir', pos: 'verb', definition: 'Vibrar de emoção; estremecer' },
  { word: 'Frêmito', pos: 'noun', definition: 'Estremecimento; vibração intensa' },
  { word: 'Frugal', pos: 'adjective', definition: 'Simples e moderado, sobretudo no comer' },
  { word: 'Fruir', pos: 'verb', definition: 'Desfrutar; gozar de algo com prazer' },
  { word: 'Fugaz', pos: 'adjective', definition: 'Que passa depressa; efêmero' },
  { word: 'Fulcro', pos: 'noun', definition: 'Ponto de apoio; base essencial' },
  { word: 'Fulgor', pos: 'noun', definition: 'Brilho intenso; resplendor' },
  { word: 'Fulgurante', pos: 'adjective', definition: 'Que brilha como relâmpago; deslumbrante' },
  { word: 'Furtivo', pos: 'adjective', definition: 'Feito às escondidas; sorrateiro' },
  { word: 'Gaiato', pos: 'adjective', definition: 'Brincalhão; engraçado e travesso' },
  { word: 'Galante', pos: 'adjective', definition: 'Cortês e sedutor; elegante no trato' },
  { word: 'Galardão', pos: 'noun', definition: 'Prêmio honroso; recompensa por mérito' },
  { word: 'Galhardia', pos: 'noun', definition: 'Elegância valente; garbo destemido' },
  { word: 'Galhofeiro', pos: 'adjective', definition: 'Que gosta de galhofa; zombeteiro e alegre' },
  { word: 'Garbo', pos: 'noun', definition: 'Elegância no porte; distinção' },
  { word: 'Garboso', pos: 'adjective', definition: 'Que tem garbo; elegante e airoso' },
  { word: 'Garoar', pos: 'verb', definition: 'Chover fino e manso' },
  { word: 'Garrido', pos: 'adjective', definition: 'Vistoso e alegre; enfeitado' },
  { word: 'Gárrulo', pos: 'adjective', definition: 'Que fala ou canta sem parar; tagarela' },
  { word: 'Gáudio', pos: 'noun', definition: 'Alegria intensa; júbilo' },
  { word: 'Gênese', pos: 'noun', definition: 'Origem; processo de formação' },
  { word: 'Genuíno', pos: 'adjective', definition: 'Autêntico; verdadeiro' },
  { word: 'Germinar', pos: 'verb', definition: 'Começar a brotar; desenvolver-se' },
  { word: 'Glacial', pos: 'adjective', definition: 'Frio como o gelo; indiferente' },
  { word: 'Gorjear', pos: 'verb', definition: 'Cantar como os pássaros; trinar' },
  { word: 'Gorjeio', pos: 'noun', definition: 'Canto dos pássaros; trinado melodioso' },
  { word: 'Gracejo', pos: 'noun', definition: 'Dito espirituoso; brincadeira leve' },
  { word: 'Grácil', pos: 'adjective', definition: 'Delicado e esbelto; fino' },
  { word: 'Gradação', pos: 'noun', definition: 'Passagem gradual entre estados; nuance' },
  { word: 'Grandiloquente', pos: 'adjective', definition: 'De estilo pomposo; empolado' },
  { word: 'Granjear', pos: 'verb', definition: 'Conquistar aos poucos; obter com esforço' },
  { word: 'Grinalda', pos: 'noun', definition: 'Coroa de flores' },
  { word: 'Guapo', pos: 'adjective', definition: 'Valente; belo e airoso' },
  { word: 'Guarida', pos: 'noun', definition: 'Abrigo; refúgio protetor' },
  { word: 'Gume', pos: 'noun', definition: 'Fio cortante da lâmina; agudeza' },
  { word: 'Halo', pos: 'noun', definition: 'Círculo luminoso; auréola' },
  { word: 'Harmonizar', pos: 'verb', definition: 'Pôr em harmonia; conciliar' },
  { word: 'Haurir', pos: 'verb', definition: 'Beber; extrair do fundo' },
  { word: 'Hausto', pos: 'noun', definition: 'Gole profundo; sorvo de ar' },
  { word: 'Hedonismo', pos: 'noun', definition: 'Busca do prazer como bem supremo' },
  { word: 'Hercúleo', pos: 'adjective', definition: 'De força descomunal; que exige esforço enorme' },
  { word: 'Hermético', pos: 'adjective', definition: 'Perfeitamente fechado; de sentido obscuro' },
  { word: 'Hialino', pos: 'adjective', definition: 'Transparente como o vidro' },
  { word: 'Hibernal', pos: 'adjective', definition: 'Relativo ao inverno; invernal' },
  { word: 'Hilaridade', pos: 'noun', definition: 'Riso alegre e contagiante' },
  { word: 'Hodierno', pos: 'adjective', definition: 'Do dia de hoje; atual' },
  { word: 'Hombridade', pos: 'noun', definition: 'Dignidade firme; retidão de caráter' },
  { word: 'Homérico', pos: 'adjective', definition: 'Grandioso como os poemas de Homero; épico' },
  { word: 'Honradez', pos: 'noun', definition: 'Integridade de caráter; probidade' },
  { word: 'Idílico', pos: 'adjective', definition: 'Digno de um idílio; encantadoramente sereno' },
  { word: 'Idílio', pos: 'noun', definition: 'Amor terno e sonhador; cena bucólica' },
  { word: 'Idiossincrasia', pos: 'noun', definition: 'Característica peculiar de cada pessoa' },
  { word: 'Idôneo', pos: 'adjective', definition: 'Apto e íntegro; adequado' },
  { word: 'Ignoto', pos: 'adjective', definition: 'Desconhecido; inexplorado' },
  { word: 'Iluminura', pos: 'noun', definition: 'Pintura ornamental em manuscritos antigos' },
  { word: 'Ilustre', pos: 'adjective', definition: 'Célebre; distinto por seus méritos' },
  { word: 'Imaculado', pos: 'adjective', definition: 'Sem mancha; puro' },
  { word: 'Imarcescível', pos: 'adjective', definition: 'Que não murcha; eternamente viçoso' },
  { word: 'Imbuir', pos: 'verb', definition: 'Impregnar de um sentimento ou ideia' },
  { word: 'Imemorial', pos: 'adjective', definition: 'Tão antigo que escapa à memória' },
  { word: 'Imensidão', pos: 'noun', definition: 'Extensão sem limites; vastidão' },
  { word: 'Imorredouro', pos: 'adjective', definition: 'Que não morre; imortal na lembrança' },
  { word: 'Impassível', pos: 'adjective', definition: 'Que não demonstra emoção; imperturbável' },
  { word: 'Impávido', pos: 'adjective', definition: 'Que não sente medo; destemido' },
  { word: 'Imperecível', pos: 'adjective', definition: 'Que não perece; duradouro' },
  { word: 'Ímpeto', pos: 'noun', definition: 'Impulso súbito e forte; arranco' },
  { word: 'Impetuoso', pos: 'adjective', definition: 'Que age com ímpeto; arrebatado' },
  { word: 'Impoluto', pos: 'adjective', definition: 'Sem mácula; íntegro' },
  { word: 'Imponderável', pos: 'adjective', definition: 'Que não se pode pesar nem prever' },
  { word: 'Imponente', pos: 'adjective', definition: 'Que impõe respeito; grandioso' },
  { word: 'Inaudito', pos: 'adjective', definition: 'Nunca ouvido; extraordinário' },
  { word: 'Incandescente', pos: 'adjective', definition: 'Que brilha de tão quente; ardente' },
  { word: 'Incauto', pos: 'adjective', definition: 'Sem cautela; ingênuo' },
  { word: 'Incipiente', pos: 'adjective', definition: 'Que está começando; inicial' },
  { word: 'Ínclito', pos: 'adjective', definition: 'Ilustre; célebre por seus feitos' },
  { word: 'Incólume', pos: 'adjective', definition: 'Livre de dano; são e salvo' },
  { word: 'Incomensurável', pos: 'adjective', definition: 'Que não se pode medir; imenso' },
  { word: 'Incontinenti', pos: 'adverb', definition: 'Imediatamente; sem demora' },
  { word: 'Incorruptível', pos: 'adjective', definition: 'Que não se corrompe; íntegro' },
  { word: 'Indelével', pos: 'adjective', definition: 'Que não se apaga; permanente' },
  { word: 'Indizível', pos: 'adjective', definition: 'Que não se pode dizer; inefável' },
  { word: 'Indômito', pos: 'adjective', definition: 'Que não se deixa domar; selvagem' },
  { word: 'Indulgência', pos: 'noun', definition: 'Disposição para perdoar; tolerância' },
  { word: 'Inebriante', pos: 'adjective', definition: 'Que embriaga os sentidos; arrebatador' },
  { word: 'Inefável', pos: 'adjective', definition: 'Que não se consegue exprimir em palavras' },
  { word: 'Inenarrável', pos: 'adjective', definition: 'Impossível de narrar; extraordinário' },
  { word: 'Inexorável', pos: 'adjective', definition: 'Que não se deixa demover; implacável' },
  { word: 'Infausto', pos: 'adjective', definition: 'De má sorte; funesto' },
  { word: 'Infindo', pos: 'adjective', definition: 'Sem fim; infinito' },
  { word: 'Infinitude', pos: 'noun', definition: 'Qualidade do que não tem fim' },
  { word: 'Ingente', pos: 'adjective', definition: 'Muito grande; descomunal' },
  { word: 'Inopinado', pos: 'adjective', definition: 'Inesperado; súbito' },
  { word: 'Inquebrantável', pos: 'adjective', definition: 'Que não se quebra; firme e constante' },
  { word: 'Insigne', pos: 'adjective', definition: 'Notável; distinto' },
  { word: 'Insólito', pos: 'adjective', definition: 'Fora do comum; inusitado' },
  { word: 'Insondável', pos: 'adjective', definition: 'Que não se pode sondar; impenetrável' },
  { word: 'Intangível', pos: 'adjective', definition: 'Que não se pode tocar; imaterial' },
  { word: 'Intempérie', pos: 'noun', definition: 'Rigor do tempo; mau tempo' },
  { word: 'Interlúdio', pos: 'noun', definition: 'Intervalo entre dois momentos; pausa musical' },
  { word: 'Intimorato', pos: 'adjective', definition: 'Sem temor; destemido' },
  { word: 'Intrépido', pos: 'adjective', definition: 'Corajoso diante do perigo; audaz' },
  { word: 'Inusitado', pos: 'adjective', definition: 'Não habitual; surpreendente' },
  { word: 'Ínvio', pos: 'adjective', definition: 'Sem caminho; impenetrável' },
  { word: 'Iridescente', pos: 'adjective', definition: 'Que reflete as cores do arco-íris' },
  { word: 'Irradiar', pos: 'verb', definition: 'Emitir raios; espalhar ao redor' },
  { word: 'Irrequieto', pos: 'adjective', definition: 'Que não sossega; buliçoso' },
  { word: 'Irretocável', pos: 'adjective', definition: 'Perfeito; que dispensa retoques' },
  { word: 'Jactância', pos: 'noun', definition: 'Vanglória; ostentação de si mesmo' },
  { word: 'Jaez', pos: 'noun', definition: 'Qualidade; tipo ou índole' },
  { word: 'Janota', pos: 'adjective', definition: 'Que se veste com apuro exagerado' },
  { word: 'Jeitoso', pos: 'adjective', definition: 'Que tem jeito; habilidoso e gracioso' },
  { word: 'Jocoso', pos: 'adjective', definition: 'Que provoca riso; engraçado' },
  { word: 'Jorrar', pos: 'verb', definition: 'Sair em jato abundante; brotar com força' },
  { word: 'Jovial', pos: 'adjective', definition: 'Alegre e descontraído; bem-humorado' },
  { word: 'Jubilar', pos: 'verb', definition: 'Encher de júbilo; celebrar com alegria' },
  { word: 'Júbilo', pos: 'noun', definition: 'Alegria intensa; regozijo' },
  { word: 'Jubiloso', pos: 'adjective', definition: 'Cheio de júbilo; exultante' },
  { word: 'Judicioso', pos: 'adjective', definition: 'Que julga com bom senso; sensato' },
  { word: 'Jusante', pos: 'noun', definition: 'Direção para onde corre o rio; o curso abaixo' },
  { word: 'Labareda', pos: 'noun', definition: 'Chama grande e viva' },
  { word: 'Labor', pos: 'noun', definition: 'Trabalho dedicado; labuta' },
  { word: 'Laborioso', pos: 'adjective', definition: 'Trabalhador; que exige muito esforço' },
  { word: 'Labuta', pos: 'noun', definition: 'Trabalho penoso do dia a dia' },
  { word: 'Lacônico', pos: 'adjective', definition: 'Que fala pouco; breve e seco' },
  { word: 'Ladino', pos: 'adjective', definition: 'Esperto e astuto; vivo' },
  { word: 'Laivo', pos: 'noun', definition: 'Traço leve; vestígio' },
  { word: 'Lampejo', pos: 'noun', definition: 'Clarão breve; ideia súbita' },
  { word: 'Lancinante', pos: 'adjective', definition: 'Que fere como lança; agudo e pungente' },
  { word: 'Languidez', pos: 'noun', definition: 'Moleza suave; abandono sonhador' },
  { word: 'Lânguido', pos: 'adjective', definition: 'Sem vigor; suave e abandonado' },
  { word: 'Lapidar', pos: 'verb', definition: 'Polir pedra preciosa; aperfeiçoar' },
  { word: 'Largueza', pos: 'noun', definition: 'Generosidade; amplitude' },
  { word: 'Láurea', pos: 'noun', definition: 'Honra conquistada; prêmio' },
  { word: 'Lauto', pos: 'adjective', definition: 'Abundante e luxuoso; farto' },
  { word: 'Lavor', pos: 'noun', definition: 'Trabalho ornamental delicado; lavra artística' },
  { word: 'Ledo', pos: 'adjective', definition: 'Alegre; contente' },
  { word: 'Legado', pos: 'noun', definition: 'Herança deixada às gerações futuras' },
  { word: 'Leniência', pos: 'noun', definition: 'Suavidade no julgar; brandura' },
  { word: 'Lenitivo', pos: 'noun', definition: 'O que abranda a dor; alívio' },
  { word: 'Lépido', pos: 'adjective', definition: 'Ágil e alegre; vivaz' },
  { word: 'Letargia', pos: 'noun', definition: 'Sono profundo; apatia prolongada' },
  { word: 'Lhaneza', pos: 'noun', definition: 'Sinceridade simples; franqueza afável' },
  { word: 'Liame', pos: 'noun', definition: 'Vínculo; laço que liga' },
  { word: 'Liberalidade', pos: 'noun', definition: 'Generosidade em dar; largueza' },
  { word: 'Lídimo', pos: 'adjective', definition: 'Legítimo; autêntico' },
  { word: 'Limiar', pos: 'noun', definition: 'Ponto de entrada; começo de algo' },
  { word: 'Límpido', pos: 'adjective', definition: 'Perfeitamente claro; puro' },
  { word: 'Lisonja', pos: 'noun', definition: 'Elogio interesseiro; adulação' },
  { word: 'Lisura', pos: 'noun', definition: 'Honestidade transparente; retidão' },
  { word: 'Lobrigar', pos: 'verb', definition: 'Enxergar com dificuldade; entrever' },
  { word: 'Longevo', pos: 'adjective', definition: 'De vida longa; muito duradouro' },
  { word: 'Longínquo', pos: 'adjective', definition: 'Muito distante; remoto' },
  { word: 'Loquaz', pos: 'adjective', definition: 'Que fala muito; eloquente' },
  { word: 'Louvável', pos: 'adjective', definition: 'Digno de louvor; meritório' },
  { word: 'Lucidez', pos: 'noun', definition: 'Clareza de raciocínio; discernimento' },
  { word: 'Ludibriar', pos: 'verb', definition: 'Enganar com astúcia; iludir' },
  { word: 'Lúdico', pos: 'adjective', definition: 'Relativo ao jogo e à brincadeira' },
  { word: 'Lufada', pos: 'noun', definition: 'Sopro forte e repentino de vento' },
  { word: 'Lume', pos: 'noun', definition: 'Fogo; luz acesa' },
  { word: 'Luzidio', pos: 'adjective', definition: 'Que reluz; brilhante e polido' },
  { word: 'Luzir', pos: 'verb', definition: 'Emitir luz; brilhar' },
  { word: 'Macambúzio', pos: 'adjective', definition: 'Tristonho e calado; melancólico' },
  { word: 'Magnânimo', pos: 'adjective', definition: 'De alma grande; generoso no perdão' },
  { word: 'Majestoso', pos: 'adjective', definition: 'Imponente como a majestade; grandioso' },
  { word: 'Maleável', pos: 'adjective', definition: 'Que se molda com facilidade; adaptável' },
  { word: 'Mansidão', pos: 'noun', definition: 'Índole mansa; docilidade serena' },
  { word: 'Maresia', pos: 'noun', definition: 'Cheiro do mar; brisa salgada do litoral' },
  { word: 'Marulhar', pos: 'verb', definition: 'Produzir o som ritmado das ondas' },
  { word: 'Matinal', pos: 'adjective', definition: 'Da manhã; madrugador' },
  { word: 'Matiz', pos: 'noun', definition: 'Gradação sutil de cor ou de sentido' },
  { word: 'Matreiro', pos: 'adjective', definition: 'Astuto e desconfiado; esperto' },
  { word: 'Matutar', pos: 'verb', definition: 'Pensar com insistência; refletir demoradamente' },
  { word: 'Mavioso', pos: 'adjective', definition: 'Suave e terno; melodioso' },
  { word: 'Máxime', pos: 'adverb', definition: 'Principalmente; acima de tudo' },
  { word: 'Meditabundo', pos: 'adjective', definition: 'Mergulhado em meditação; pensativo' },
  { word: 'Meigo', pos: 'adjective', definition: 'Terno e suave; carinhoso' },
  { word: 'Melancolia', pos: 'noun', definition: 'Tristeza suave e contemplativa' },
  { word: 'Melífluo', pos: 'adjective', definition: 'Doce como o mel; suave em excesso' },
  { word: 'Melodioso', pos: 'adjective', definition: 'De som agradável; harmonioso' },
  { word: 'Memorável', pos: 'adjective', definition: 'Digno de memória; inesquecível' },
  { word: 'Meticuloso', pos: 'adjective', definition: 'Escrupulosamente cuidadoso; esmerado' },
  { word: 'Mimoso', pos: 'adjective', definition: 'Delicado e terno; gracioso' },
  { word: 'Minucioso', pos: 'adjective', definition: 'Que atenta aos mínimos detalhes; detalhista' },
  { word: 'Mirabolante', pos: 'adjective', definition: 'Espantoso e extravagante; fantasioso' },
  { word: 'Miríade', pos: 'noun', definition: 'Quantidade imensa; multidão incontável' },
  { word: 'Místico', pos: 'adjective', definition: 'Ligado ao mistério espiritual; contemplativo' },
  { word: 'Mitigar', pos: 'verb', definition: 'Tornar mais brando; aliviar' },
  { word: 'Moirejar', pos: 'verb', definition: 'Trabalhar sem descanso; labutar' },
  { word: 'Monumental', pos: 'adjective', definition: 'Grandioso como um monumento; imponente' },
  { word: 'Mordaz', pos: 'adjective', definition: 'Que critica com ironia afiada; sarcástico' },
  { word: 'Mormente', pos: 'adverb', definition: 'Sobretudo; em especial' },
  { word: 'Nebuloso', pos: 'adjective', definition: 'Coberto de nuvens; obscuro e incerto' },
  { word: 'Nefelibata', pos: 'noun', definition: 'Quem vive nas nuvens; sonhador' },
  { word: 'Nenhures', pos: 'adverb', definition: 'Em lugar nenhum' },
  { word: 'Nesga', pos: 'noun', definition: 'Tira estreita; pequena porção visível' },
  { word: 'Nevoento', pos: 'adjective', definition: 'Envolto em névoa; de contornos difusos' },
  { word: 'Níveo', pos: 'adjective', definition: 'Branco como a neve' },
  { word: 'Noctívago', pos: 'adjective', definition: 'Que vagueia pela noite; notívago' },
  { word: 'Nostalgia', pos: 'noun', definition: 'Saudade melancólica do passado' },
  { word: 'Nuança', pos: 'noun', definition: 'Diferença sutil; matiz delicado' },
  { word: 'Nutrir', pos: 'verb', definition: 'Alimentar; cultivar um sentimento' },
  { word: 'Oásis', pos: 'noun', definition: 'Refúgio fértil no deserto; alívio em meio à aridez' },
  { word: 'Oblíquo', pos: 'adjective', definition: 'Inclinado; indireto' },
  { word: 'Obstinado', pos: 'adjective', definition: 'Que persiste com firmeza inabalável; tenaz' },
  { word: 'Ocaso', pos: 'noun', definition: 'Pôr do sol; declínio' },
  { word: 'Odisseia', pos: 'noun', definition: 'Jornada longa e cheia de aventuras' },
  { word: 'Olvidar', pos: 'verb', definition: 'Esquecer; deixar cair no esquecimento' },
  { word: 'Onírico', pos: 'adjective', definition: 'Relativo aos sonhos; fantasioso' },
  { word: 'Opalescente', pos: 'adjective', definition: 'Com reflexos leitosos e cambiantes de opala' },
  { word: 'Opíparo', pos: 'adjective', definition: 'Farto e esplêndido, como um banquete' },
  { word: 'Opulento', pos: 'adjective', definition: 'Muito rico; abundante e suntuoso' },
  { word: 'Oráculo', pos: 'noun', definition: 'Fonte de respostas infalíveis; voz que revela o destino' },
  { word: 'Orvalho', pos: 'noun', definition: 'Gotas de umidade que a madrugada deixa; rocio' },
  { word: 'Ousadia', pos: 'noun', definition: 'Coragem atrevida; audácia' },
  { word: 'Outrora', pos: 'adverb', definition: 'Em tempos passados; antigamente' },
  { word: 'Outrossim', pos: 'adverb', definition: 'Igualmente; além disso' },
  { word: 'Ovacionar', pos: 'verb', definition: 'Aplaudir com entusiasmo; aclamar' },
  { word: 'Pacato', pos: 'adjective', definition: 'De índole tranquila; sossegado' },
  { word: 'Palmilhar', pos: 'verb', definition: 'Percorrer a pé; trilhar passo a passo' },
  { word: 'Panaceia', pos: 'noun', definition: 'Remédio imaginário para todos os males' },
  { word: 'Parcimonioso', pos: 'adjective', definition: 'Que usa com moderação; econômico e sóbrio' },
  { word: 'Passional', pos: 'adjective', definition: 'Movido pela paixão; ardente' },
  { word: 'Paulatino', pos: 'adjective', definition: 'Que avança devagar; gradual' },
  { word: 'Peculiar', pos: 'adjective', definition: 'Próprio de alguém ou de algo; característico' },
  { word: 'Peralta', pos: 'adjective', definition: 'Travesso; brincalhão' },
  { word: 'Peregrino', pos: 'adjective', definition: 'Que viaja por devoção; raro e singular' },
  { word: 'Peremptório', pos: 'adjective', definition: 'Decisivo; que não admite réplica' },
  { word: 'Perene', pos: 'adjective', definition: 'Que dura para sempre; contínuo' },
  { word: 'Pérfido', pos: 'adjective', definition: 'Traiçoeiro; desleal' },
  { word: 'Perfunctório', pos: 'adjective', definition: 'Feito por alto; superficial' },
  { word: 'Perscrutar', pos: 'verb', definition: 'Examinar em profundidade; sondar' },
  { word: 'Perspicácia', pos: 'noun', definition: 'Agudeza de percepção; sagacidade' },
  { word: 'Perspicaz', pos: 'adjective', definition: 'Que percebe com agudeza; arguto' },
  { word: 'Pertinaz', pos: 'adjective', definition: 'Que persiste com tenacidade; obstinado' },
  { word: 'Plácido', pos: 'adjective', definition: 'Tranquilo e sereno; sem agitação' },
  { word: 'Plangente', pos: 'adjective', definition: 'Que soa como lamento; choroso' },
  { word: 'Platônico', pos: 'adjective', definition: 'De amor idealizado; puramente espiritual' },
  { word: 'Plenitude', pos: 'noun', definition: 'Estado de completude; inteireza' },
  { word: 'Poente', pos: 'noun', definition: 'O lado do horizonte onde o sol se deita' },
  { word: 'Ponderar', pos: 'verb', definition: 'Avaliar com cuidado; refletir antes de decidir' },
  { word: 'Porfiar', pos: 'verb', definition: 'Insistir com empenho; teimar em alcançar' },
  { word: 'Porventura', pos: 'adverb', definition: 'Por acaso; eventualmente' },
  { word: 'Prelúdio', pos: 'noun', definition: 'O que antecede e anuncia; introdução' },
  { word: 'Presságio', pos: 'noun', definition: 'Sinal do que está por vir; pressentimento' },
  { word: 'Primor', pos: 'noun', definition: 'Perfeição delicada; excelência' },
  { word: 'Primoroso', pos: 'adjective', definition: 'Feito com primor; excelente' },
  { word: 'Pródigo', pos: 'adjective', definition: 'Que dá sem medida; generoso em excesso' },
  { word: 'Proeza', pos: 'noun', definition: 'Feito notável; façanha' },
  { word: 'Profícuo', pos: 'adjective', definition: 'Que traz proveito; produtivo' },
  { word: 'Prolixo', pos: 'adjective', definition: 'Que se alonga demais nas palavras' },
  { word: 'Prosaico', pos: 'adjective', definition: 'Sem poesia; comum e trivial' },
  { word: 'Providencial', pos: 'adjective', definition: 'Que chega na hora certa; oportuno' },
  { word: 'Pueril', pos: 'adjective', definition: 'Próprio de criança; ingênuo' },
  { word: 'Pujante', pos: 'adjective', definition: 'De grande vigor; forte e próspero' },
  { word: 'Pungente', pos: 'adjective', definition: 'Que fere fundo; comovente e doloroso' },
  { word: 'Purpúreo', pos: 'adjective', definition: 'Da cor da púrpura; avermelhado' },
  { word: 'Pusilânime', pos: 'adjective', definition: 'De ânimo fraco; covarde' },
  { word: 'Quebranto', pos: 'noun', definition: 'Abatimento do corpo e do ânimo; mau-olhado' },
  { word: 'Querência', pos: 'noun', definition: 'Lugar a que se pertence; apego à terra natal' },
  { word: 'Quiçá', pos: 'adverb', definition: 'Talvez; quem sabe' },
  { word: 'Quietude', pos: 'noun', definition: 'Calma profunda; sossego' },
  { word: 'Quimera', pos: 'noun', definition: 'Sonho impossível; fantasia' },
  { word: 'Quimérico', pos: 'adjective', definition: 'Próprio de quimera; fantasioso e irreal' },
  { word: 'Quintessência', pos: 'noun', definition: 'O que há de mais puro e essencial' },
  { word: 'Quiproquó', pos: 'noun', definition: 'Confusão de uma coisa por outra; mal-entendido' },
  { word: 'Quixotesco', pos: 'adjective', definition: 'Idealista e sonhador como Dom Quixote' },
  { word: 'Radiante', pos: 'adjective', definition: 'Que irradia luz ou alegria; resplandecente' },
  { word: 'Rarefeito', pos: 'adjective', definition: 'Pouco denso; escasso' },
  { word: 'Recatado', pos: 'adjective', definition: 'Que tem recato; discreto' },
  { word: 'Recender', pos: 'verb', definition: 'Exalar cheiro agradável; perfumar o ar' },
  { word: 'Recôndito', pos: 'adjective', definition: 'Escondido nas profundezas; íntimo' },
  { word: 'Redivivo', pos: 'adjective', definition: 'Que parece voltar à vida; renascido' },
  { word: 'Refulgir', pos: 'verb', definition: 'Brilhar intensamente; resplandecer' },
  { word: 'Regaço', pos: 'noun', definition: 'Colo acolhedor; abrigo materno' },
  { word: 'Regozijo', pos: 'noun', definition: 'Alegria compartilhada; contentamento' },
  { word: 'Relento', pos: 'noun', definition: 'Umidade da noite ao ar livre; sereno da madrugada' },
  { word: 'Reluzente', pos: 'adjective', definition: 'Que reluz; brilhante' },
  { word: 'Remanso', pos: 'noun', definition: 'Trecho calmo do rio; lugar de sossego' },
  { word: 'Rememorar', pos: 'verb', definition: 'Trazer de novo à memória; recordar' },
  { word: 'Reminiscência', pos: 'noun', definition: 'Lembrança vaga; eco do passado' },
  { word: 'Repontar', pos: 'verb', definition: 'Começar a despontar; surgir no horizonte' },
  { word: 'Requinte', pos: 'noun', definition: 'Refinamento apurado; elegância' },
  { word: 'Resoluto', pos: 'adjective', definition: 'Firme nas decisões; decidido' },
  { word: 'Resplendor', pos: 'noun', definition: 'Brilho glorioso; fulgor' },
  { word: 'Retumbante', pos: 'adjective', definition: 'Que ressoa alto; estrondoso' },
  { word: 'Reverberar', pos: 'verb', definition: 'Refletir luz ou som; repercutir' },
  { word: 'Reverência', pos: 'noun', definition: 'Respeito profundo; inclinação de cortesia' },
  { word: 'Risonho', pos: 'adjective', definition: 'Que sorri com frequência; alegre e promissor' },
  { word: 'Rutilante', pos: 'adjective', definition: 'Que brilha intensamente; cintilante como ouro' },
  { word: 'Sagaz', pos: 'adjective', definition: 'De percepção rápida; astuto e fino' },
  { word: 'Salpicar', pos: 'verb', definition: 'Espalhar em pingos; polvilhar' },
  { word: 'Salutar', pos: 'adjective', definition: 'Que faz bem; benéfico' },
  { word: 'Sapiência', pos: 'noun', definition: 'Sabedoria profunda; erudição' },
  { word: 'Sarau', pos: 'noun', definition: 'Reunião noturna com música e poesia' },
  { word: 'Saudade', pos: 'noun', definition: 'Sentimento terno de falta de alguém ou de algo querido' },
  { word: 'Seara', pos: 'noun', definition: 'Campo de cereais; domínio de atuação' },
  { word: 'Semblante', pos: 'noun', definition: 'Expressão do rosto; fisionomia' },
  { word: 'Sempiterno', pos: 'adjective', definition: 'Que dura para sempre; eterno' },
  { word: 'Seráfico', pos: 'adjective', definition: 'Puro como um serafim; angelical' },
  { word: 'Serelepe', pos: 'adjective', definition: 'Vivo e buliçoso; esperto' },
  { word: 'Serenidade', pos: 'noun', definition: 'Calma tranquila; paz interior' },
  { word: 'Serpentear', pos: 'verb', definition: 'Mover-se em curvas como uma serpente' },
  { word: 'Sibilar', pos: 'verb', definition: 'Emitir som agudo como o vento; assobiar' },
  { word: 'Silente', pos: 'adjective', definition: 'Que está em silêncio; calado' },
  { word: 'Silhueta', pos: 'noun', definition: 'Contorno de uma figura contra a luz' },
  { word: 'Singelo', pos: 'adjective', definition: 'Simples e puro; sem artifícios' },
  { word: 'Sinuoso', pos: 'adjective', definition: 'Cheio de curvas; serpenteante' },
  { word: 'Sobejamente', pos: 'adverb', definition: 'Mais que suficientemente; de sobra' },
  { word: 'Sobranceiro', pos: 'adjective', definition: 'Que fica acima; altivo' },
  { word: 'Sobremaneira', pos: 'adverb', definition: 'Excessivamente; em alto grau' },
  { word: 'Sobremodo', pos: 'adverb', definition: 'Em excesso; muitíssimo' },
  { word: 'Sobrepujar', pos: 'verb', definition: 'Superar; exceder em força ou valor' },
  { word: 'Sôfrego', pos: 'adjective', definition: 'Que deseja com avidez; impaciente' },
  { word: 'Solene', pos: 'adjective', definition: 'Cerimonioso e grave; majestoso' },
  { word: 'Solícito', pos: 'adjective', definition: 'Pronto a servir; atencioso' },
  { word: 'Sonso', pos: 'adjective', definition: 'Que finge inocência; dissimulado' },
  { word: 'Sortilégio', pos: 'noun', definition: 'Encantamento mágico; feitiço' },
  { word: 'Sorumbático', pos: 'adjective', definition: 'Triste e sombrio; melancólico' },
  { word: 'Soturno', pos: 'adjective', definition: 'Sombrio e melancólico; lúgubre' },
  { word: 'Sublime', pos: 'adjective', definition: 'De grandeza que eleva o espírito; excelso' },
  { word: 'Sucinto', pos: 'adjective', definition: 'Breve e direto; conciso' },
  { word: 'Sussurro', pos: 'noun', definition: 'Fala em voz baixíssima; murmúrio' },
  { word: 'Sutileza', pos: 'noun', definition: 'Delicadeza fina; finura de espírito' },
  { word: 'Tácito', pos: 'adjective', definition: 'Subentendido sem palavras; implícito' },
  { word: 'Taciturno', pos: 'adjective', definition: 'Calado e sombrio; de poucas palavras' },
  { word: 'Tampouco', pos: 'adverb', definition: 'Também não; nem sequer' },
  { word: 'Telúrico', pos: 'adjective', definition: 'Relativo à terra; profundo como ela' },
  { word: 'Temerário', pos: 'adjective', definition: 'Ousado além da prudência; arriscado' },
  { word: 'Tempestuoso', pos: 'adjective', definition: 'De tempestade; agitado e impetuoso' },
  { word: 'Tenaz', pos: 'adjective', definition: 'Que não desiste; persistente' },
  { word: 'Tênue', pos: 'adjective', definition: 'Muito fino; delicado e leve' },
  { word: 'Terno', pos: 'adjective', definition: 'Cheio de ternura; afetuoso' },
  { word: 'Ternura', pos: 'noun', definition: 'Afeto suave; carinho delicado' },
  { word: 'Tertúlia', pos: 'noun', definition: 'Reunião de amigos para conversar sobre arte e ideias' },
  { word: 'Tino', pos: 'noun', definition: 'Juízo prudente; bom senso' },
  { word: 'Tirocínio', pos: 'noun', definition: 'Aprendizado prático; experiência adquirida' },
  { word: 'Titânico', pos: 'adjective', definition: 'De força ou proporção colossal' },
  { word: 'Tonitruante', pos: 'adjective', definition: 'Que troveja; de voz estrondosa' },
  { word: 'Torpor', pos: 'noun', definition: 'Entorpecimento; lentidão dos sentidos' },
  { word: 'Transcendente', pos: 'adjective', definition: 'Que ultrapassa os limites comuns; superior' },
  { word: 'Translúcido', pos: 'adjective', definition: 'Que deixa passar a luz sem ser transparente' },
  { word: 'Trêfego', pos: 'adjective', definition: 'Irrequieto; traquinas' },
  { word: 'Tremeluzir', pos: 'verb', definition: 'Brilhar com luz trêmula; bruxulear' },
  { word: 'Turbilhão', pos: 'noun', definition: 'Redemoinho impetuoso; agitação intensa' },
  { word: 'Ubíquo', pos: 'adjective', definition: 'Que está em toda parte ao mesmo tempo' },
  { word: 'Ufano', pos: 'adjective', definition: 'Orgulhoso; cheio de contentamento por algo seu' },
  { word: 'Ultramarino', pos: 'adjective', definition: 'De além-mar; de um azul profundo' },
  { word: 'Umbroso', pos: 'adjective', definition: 'Cheio de sombra; sombreado e fresco' },
  { word: 'Urbanidade', pos: 'noun', definition: 'Cortesia civilizada no trato' },
  { word: 'Urdir', pos: 'verb', definition: 'Tecer; tramar planos com engenho' },
  { word: 'Utopia', pos: 'noun', definition: 'Ideal irrealizável; sonho de perfeição' },
  { word: 'Valoroso', pos: 'adjective', definition: 'Cheio de valor; corajoso' },
  { word: 'Vastidão', pos: 'noun', definition: 'Extensão imensa; imensidade' },
  { word: 'Vaticinar', pos: 'verb', definition: 'Predizer o futuro; profetizar' },
  { word: 'Veemente', pos: 'adjective', definition: 'Intenso e apaixonado na expressão' },
  { word: 'Venturoso', pos: 'adjective', definition: 'Afortunado; feliz' },
  { word: 'Verdejante', pos: 'adjective', definition: 'Coberto de verde vivo; que verdeja' },
  { word: 'Vereda', pos: 'noun', definition: 'Caminho estreito; atalho entre campos' },
  { word: 'Vernáculo', pos: 'adjective', definition: 'Próprio da língua nacional; castiço' },
  { word: 'Verossímil', pos: 'adjective', definition: 'Que parece verdadeiro; crível' },
  { word: 'Versátil', pos: 'adjective', definition: 'Que se adapta a muitas funções; multiforme' },
  { word: 'Vertiginoso', pos: 'adjective', definition: 'Que dá vertigem; extremamente veloz' },
  { word: 'Verve', pos: 'noun', definition: 'Inspiração espirituosa; vivacidade no falar' },
  { word: 'Vetusto', pos: 'adjective', definition: 'Muito antigo e respeitável' },
  { word: 'Vicejar', pos: 'verb', definition: 'Crescer com viço; florescer' },
  { word: 'Viçoso', pos: 'adjective', definition: 'Cheio de viço; exuberante e fresco' },
  { word: 'Vigília', pos: 'noun', definition: 'Estado de quem permanece acordado; véspera' },
  { word: 'Vindouro', pos: 'adjective', definition: 'Que há de vir; futuro' },
  { word: 'Visceral', pos: 'adjective', definition: 'Profundo como as entranhas; intenso' },
  { word: 'Vislumbrar', pos: 'verb', definition: 'Ver de forma breve e imprecisa; entrever' },
  { word: 'Vivaz', pos: 'adjective', definition: 'Cheio de vida; animado' },
  { word: 'Vivificar', pos: 'verb', definition: 'Dar vida a; revigorar' },
  { word: 'Volúpia', pos: 'noun', definition: 'Prazer intenso dos sentidos; deleite' },
  { word: 'Voraz', pos: 'adjective', definition: 'Que devora com avidez; insaciável' },
  { word: 'Xará', pos: 'noun', definition: 'Pessoa que tem o mesmo nome que outra' },
  { word: 'Zéfiro', pos: 'noun', definition: 'Vento suave do oeste; brisa branda' },
  { word: 'Zelo', pos: 'noun', definition: 'Cuidado dedicado; empenho amoroso' },
  { word: 'Zeloso', pos: 'adjective', definition: 'Que cuida com zelo; dedicado' },
  { word: 'Zênite', pos: 'noun', definition: 'Ponto mais alto do céu; apogeu' },
  { word: 'Zombeteiro', pos: 'adjective', definition: 'Que zomba; trocista' },
  { word: 'Zunir', pos: 'verb', definition: 'Produzir som agudo cortando o ar' },
];
