import type { AffirmationEntry } from './types';

// ---------------------------------------------------------------------------
// Built-in content library — da-DK (198 entries)
// ---------------------------------------------------------------------------

export const DA_DK_AFFIRMATIONS: AffirmationEntry[] = [
  // ── Affirmations ──────────────────────────────────────────────
  { text: 'Jeg er værdig til kærlighed og venlighed.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg stoler på rejsen, selv når jeg ikke kan se vejen.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg bliver til den, jeg gerne vil være.', category: 'affirmations', time: 'anytime' },
  { text: 'Mit potentiale er grænseløst.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg slipper det, der ikke længere gavner mig.', category: 'affirmations', time: 'evening' },
  { text: 'Jeg vælger ro frem for perfektion.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg må gerne fylde.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg er nok, præcis som jeg er.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg tiltrækker positiv energi i mit liv.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Jeg er robust, stærk og modig.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg giver mig selv lov til at hvile.', category: 'affirmations', time: 'evening', weather: 'rain' },
  { text: 'Jeg respekterer mine egne grænser.', category: 'affirmations', time: 'anytime' },
  { text: 'Ethvert tilbageslag baner vejen for et comeback.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg er i fred med, hvem jeg er.', category: 'affirmations', time: 'night' },
  { text: 'Min stemme betyder noget. Min historie betyder noget.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg byder overflod velkommen i alle dens former.', category: 'affirmations', time: 'morning' },
  { text: 'Jeg fortjener de gode ting i mit liv.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg tilgiver mig selv for tidligere fejl. De hjalp mig med at vokse.', category: 'affirmations', time: 'evening' },
  { text: 'Min krop er sund, mit sind er skarpt, min sjæl er rolig.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Jeg udstråler selvtillid og selvrespekt.', category: 'affirmations', time: 'morning' },
  { text: 'Jeg er åben for nye eventyr og oplevelser.', category: 'affirmations', time: 'morning' },
  { text: 'Jeg slipper sammenligning. Min vej er min egen.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg er et værk under udvikling, og det er helt fint.', category: 'affirmations', time: 'anytime' },
  { text: 'Mine fejl definerer mig ikke. Min udvikling gør.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg har kraften til at skabe det liv, jeg ønsker.', category: 'affirmations', time: 'morning' },
  { text: 'Jeg vælger at fokusere på det, jeg kan ændre.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeg er omgivet af kærlighed, selv når jeg ikke kan mærke den.', category: 'affirmations', time: 'night' },
  { text: 'I dag vil jeg være god ved mig selv.', category: 'affirmations', time: 'morning' },
  { text: 'Jeg er stærkere end min tvivl.', category: 'affirmations', time: 'anytime' },
  { text: 'Min lykke er mit ansvar, og jeg tager det til mig.', category: 'affirmations', time: 'anytime' },
  { text: 'Regnen skyller det væk, jeg ikke længere har brug for.', category: 'affirmations', time: 'anytime', weather: 'rain' },
  { text: 'Jeg finder skønhed i enhver slags himmel.', category: 'affirmations', time: 'anytime', weather: 'clouds' },

  // ── Compliments ───────────────────────────────────────────────
  { text: 'Du lyser ethvert rum op, du træder ind i.', category: 'compliments', time: 'anytime' },
  { text: 'Dit smil smitter; hold aldrig op med at dele det.', category: 'compliments', time: 'morning' },
  { text: 'Du har en evne til at få andre til at føle sig set.', category: 'compliments', time: 'anytime' },
  { text: 'Verden er bedre, fordi du er her.', category: 'compliments', time: 'anytime' },
  { text: 'Din venlighed breder sig længere ud, end du aner.', category: 'compliments', time: 'anytime' },
  { text: 'Du håndterer udfordringer med bemærkelsesværdig ynde.', category: 'compliments', time: 'afternoon' },
  { text: 'Folk er heldige at kende dig.', category: 'compliments', time: 'anytime' },
  { text: 'Din energi er magnetisk.', category: 'compliments', time: 'anytime' },
  { text: 'Du får svære ting til at se lette ud.', category: 'compliments', time: 'afternoon' },
  { text: 'Du har en fantastisk smag.', category: 'compliments', time: 'anytime' },
  { text: 'Din kreativitet inspirerer alle omkring dig.', category: 'compliments', time: 'anytime' },
  { text: 'Du får det bedste frem i folk.', category: 'compliments', time: 'anytime' },
  { text: 'Du fortjener alt det gode, der kommer din vej.', category: 'compliments', time: 'anytime' },
  { text: 'Din latter er den bedste lyd.', category: 'compliments', time: 'anytime' },
  { text: 'Du gør det virkelig godt.', category: 'compliments', time: 'afternoon' },
  { text: 'Din tålmodighed er en superkraft.', category: 'compliments', time: 'afternoon' },
  { text: 'Du har en smuk måde at se verden på.', category: 'compliments', time: 'anytime' },
  { text: 'Din viljestyrke er inspirerende.', category: 'compliments', time: 'anytime' },
  { text: 'Du får folk til at føle sig trygge og værdsatte.', category: 'compliments', time: 'anytime' },
  { text: 'Du har modet til at være dig selv, og det er sjældent.', category: 'compliments', time: 'anytime' },
  { text: 'Dit perspektiv er unikt, og det betyder noget.', category: 'compliments', time: 'anytime' },
  { text: 'Du leder med empati, og det kan mærkes.', category: 'compliments', time: 'afternoon' },
  { text: 'Der er ingen anden som dig. Det er din styrke.', category: 'compliments', time: 'anytime' },
  { text: 'Du udstråler en stille selvtillid.', category: 'compliments', time: 'anytime' },
  { text: 'Den indsats, du yder, går ikke ubemærket hen.', category: 'compliments', time: 'afternoon' },
  { text: 'Dit hjerte er større, end du giver dig selv kredit for.', category: 'compliments', time: 'evening' },
  { text: 'Du har gode instinkter. Stol mere på dem.', category: 'compliments', time: 'anytime' },
  { text: 'Din begejstring smitter.', category: 'compliments', time: 'morning' },
  { text: 'Du håndterer pres bedre, end du tror.', category: 'compliments', time: 'afternoon' },
  { text: 'Du er en, folk kan regne med.', category: 'compliments', time: 'anytime' },

  // ── Motivational ──────────────────────────────────────────────
  { text: 'Start der, hvor du er. Brug det, du har. Gør det, du kan.', category: 'motivational', attribution: 'Arthur Ashe', time: 'morning' },
  { text: 'Den eneste måde at lave godt arbejde på er at elske det, du laver.', category: 'motivational', attribution: 'Steve Jobs', time: 'morning' },
  { text: 'Det er ligegyldigt, hvor langsomt du går, så længe du ikke stopper.', category: 'motivational', attribution: 'Confucius', time: 'anytime' },
  { text: 'Det, du får ved at nå dine mål, er ikke så vigtigt som det, du bliver til.', category: 'motivational', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Tro på, at du kan, så er du allerede halvvejs.', category: 'motivational', attribution: 'Theodore Roosevelt', time: 'morning' },
  { text: 'Små daglige forbedringer er nøglen til forbløffende resultater på lang sigt.', category: 'motivational', time: 'morning' },
  { text: 'Disciplin er at vælge mellem det, du vil have nu, og det, du vil have allermest.', category: 'motivational', attribution: 'Abraham Lincoln', time: 'anytime' },
  { text: 'Du er ikke nået så langt for kun at nå så langt.', category: 'motivational', time: 'afternoon' },
  { text: 'Drøm stort. Start småt. Handl nu.', category: 'motivational', time: 'morning' },
  { text: 'Hemmeligheden bag at komme foran er at komme i gang.', category: 'motivational', attribution: 'Mark Twain', time: 'morning' },
  { text: 'Dit fremtidige jeg ser dig lige nu gennem minder.', category: 'motivational', time: 'anytime' },
  { text: 'Det bedste tidspunkt at plante et træ på var for 20 år siden. Det næstbedste er nu.', category: 'motivational', time: 'anytime' },
  { text: 'Fremskridt, ikke perfektion.', category: 'motivational', time: 'anytime' },
  { text: 'Modgang forbereder ofte almindelige mennesker på en ekstraordinær skæbne.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'Bliv så god, at de ikke kan ignorere dig.', category: 'motivational', attribution: 'Steve Martin', time: 'morning' },
  { text: 'Du er aldrig for gammel til at sætte dig et nyt mål eller drømme en ny drøm.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'Den kamp, du kæmper i dag, opbygger den styrke, du får brug for i morgen.', category: 'motivational', time: 'afternoon' },
  { text: 'Gør noget i dag, som dit fremtidige jeg vil takke dig for.', category: 'motivational', time: 'morning' },
  { text: 'Succes er summen af små indsatser, gentaget dag ud og dag ind.', category: 'motivational', attribution: 'Robert Collier', time: 'morning' },
  { text: 'Fald syv gange, rejs dig otte.', category: 'motivational', time: 'anytime' },
  { text: 'Det, der virker umuligt i dag, bliver en dag din opvarmning.', category: 'motivational', time: 'morning' },
  { text: 'Du behøver ikke være perfekt for at være fantastisk.', category: 'motivational', time: 'anytime' },
  { text: 'Handling er den grundlæggende nøgle til al succes.', category: 'motivational', attribution: 'Pablo Picasso', time: 'morning' },
  { text: 'Comebacket er altid stærkere end tilbageslaget.', category: 'motivational', time: 'anytime' },
  { text: 'Om et år vil du ønske, at du var begyndt i dag.', category: 'motivational', time: 'morning' },
  { text: 'Alt, hvad du nogensinde har ønsket dig, ligger på den anden side af frygten.', category: 'motivational', attribution: 'George Addair', time: 'anytime' },
  { text: 'Energien flyder derhen, hvor opmærksomheden går.', category: 'motivational', time: 'morning' },
  { text: 'Tvivl dræber flere drømme, end fiasko nogensinde vil.', category: 'motivational', attribution: 'Suzy Kassem', time: 'anytime' },
  { text: 'Hvis det var let, ville alle gøre det. Bliv ved.', category: 'motivational', time: 'afternoon' },
  { text: 'Du er én beslutning fra et helt andet liv.', category: 'motivational', time: 'anytime' },
  { text: 'Færdig er bedre end perfekt.', category: 'motivational', time: 'afternoon' },
  { text: 'Den eneste grænse for vores morgendag bliver vores tvivl i dag.', category: 'motivational', attribution: 'Franklin D. Roosevelt', time: 'anytime' },
  { text: 'Stjerner kan ikke skinne uden mørke.', category: 'motivational', time: 'evening' },
  { text: 'Mod er ikke fravær af frygt. Det er at handle på trods af den.', category: 'motivational', attribution: 'Mark Twain', time: 'anytime' },
  { text: 'Hvad ville du forsøge dig med, hvis du vidste, at du ikke kunne fejle?', category: 'motivational', time: 'morning' },
  { text: 'Måden at komme i gang på er at holde op med at tale og begynde at handle.', category: 'motivational', attribution: 'Walt Disney', time: 'morning' },

  // ── Day-of-week motivation ────────────────────────────────────
  { text: 'Ny uge, nye muligheder. Få denne her til at tælle.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Mandage er til friske starter og modige træk.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Sæt tonen for ugen. Du har styr på det.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Tirsdag: bevis på, at du overlevede mandag og kørte videre.', category: 'compliments', time: 'morning', days: [2] },
  { text: 'Midtvejstjek: du er tættere på, end du tror.', category: 'motivational', time: 'anytime', days: [3] },
  { text: 'Onsdag, halvvejsmærket. Du klarer det flot.', category: 'compliments', time: 'afternoon', days: [3] },
  { text: 'Snart i mål. Afslut ugen stærkt.', category: 'motivational', time: 'morning', days: [4] },
  { text: 'Torsdagsenergi: weekenden er i sigte.', category: 'motivational', time: 'afternoon', days: [4] },
  { text: 'Du kom igennem ugen. Vær stolt af dig selv.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'God fredag. Du har fortjent hver bid af denne weekend.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Nyd weekenden, du har fortjent den.', category: 'compliments', time: 'anytime', days: [5, 6, 0] },
  { text: 'Lørdage er til at lade op. Gør det, der fylder dig med energi.', category: 'mindfulness', time: 'morning', days: [6] },
  { text: 'Søndag: hvil, reflekter, og gør dig klar til at stråle igen.', category: 'mindfulness', time: 'morning', days: [0] },
  { text: 'Brug i dag på at gøre dig klar til en god uge forude.', category: 'motivational', time: 'afternoon', days: [0] },

  // ── Gratitude ─────────────────────────────────────────────────
  { text: 'Hvad er tre ting, du er taknemmelig for lige nu?', category: 'gratitude', time: 'morning' },
  { text: 'Tag et øjeblik til at værdsætte, hvor langt du er nået.', category: 'gratitude', time: 'evening' },
  { text: 'Taknemmelighed gør det, vi har, til nok.', category: 'gratitude', time: 'anytime' },
  { text: 'Læg i dag mærke til én lille ting, der giver dig glæde.', category: 'gratitude', time: 'morning' },
  { text: 'Hvem fik dig til at smile i dag? Hold fast i den følelse.', category: 'gratitude', time: 'evening' },
  { text: 'De helt almindelige øjeblikke er ofte de smukkeste.', category: 'gratitude', time: 'anytime' },
  { text: 'Værdsæt de lektioner, der gemmer sig i udfordringer.', category: 'gratitude', time: 'anytime' },
  { text: 'Du har så meget at være taknemmelig for.', category: 'gratitude', time: 'anytime' },
  { text: 'Det, der føltes umuligt sidste år, er din virkelighed i dag.', category: 'gratitude', time: 'anytime' },
  { text: 'Lad taknemmelighed være din grundindstilling.', category: 'gratitude', time: 'morning' },
  { text: 'Tænk på et venligt ord, nogen sagde til dig for nylig.', category: 'gratitude', time: 'evening' },
  { text: 'Dit liv er fyldt med stille mirakler. Se efter dem.', category: 'gratitude', time: 'anytime' },
  { text: 'Nævn én person, der gjorde dit liv bedre i år.', category: 'gratitude', time: 'evening' },
  { text: 'Taget over dit hoved, maden på dit bord; det er ikke småting.', category: 'gratitude', time: 'anytime' },
  { text: 'Tænk på en udfordring, der gjorde dig stærkere. Vær taknemmelig for den.', category: 'gratitude', time: 'evening' },
  { text: 'Taknemmelighed er den sundeste af alle menneskelige følelser.', category: 'gratitude', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Hvad er én ting, du har i dag, som du engang ønskede dig?', category: 'gratitude', time: 'morning' },
  { text: 'Hver solopgang er en invitation til at lyse op i nogens dag.', category: 'gratitude', time: 'morning' },
  { text: 'I dag var en gave. Hvad var din yndlingsdel?', category: 'gratitude', time: 'evening' },
  { text: 'Menneskene i dit liv elsker dig mere, end du er klar over.', category: 'gratitude', time: 'anytime' },
  { text: 'Læg mærke til skønheden i noget, du ser hver dag.', category: 'gratitude', time: 'anytime' },
  { text: 'Et taknemmeligt hjerte er en magnet for vidunderlige ting.', category: 'gratitude', time: 'morning' },
  { text: 'Hvilken lille fornøjelse nød du i dag?', category: 'gratitude', time: 'evening' },
  { text: 'Husk: nogen derude er inspireret af dig.', category: 'gratitude', time: 'anytime' },
  { text: 'Jeg er taknemmelig for solrige dage, der løfter mit humør.', category: 'gratitude', time: 'anytime', weather: 'clear' },
  { text: 'Jeg er taknemmelig for regnfulde dage, der nærer jorden.', category: 'gratitude', time: 'anytime', weather: 'rain' },

  // ── Mindfulness ───────────────────────────────────────────────
  { text: 'Træk vejret dybt. Du er præcis, hvor du skal være.', category: 'mindfulness', time: 'anytime' },
  { text: 'Vær til stede. Dette øjeblik er alt, der er.', category: 'mindfulness', time: 'anytime' },
  { text: 'Ånd ro ind. Ånd spænding ud.', category: 'mindfulness', time: 'anytime' },
  { text: 'Sæt farten ned. Der er ingen hast med at være andre steder.', category: 'mindfulness', time: 'evening' },
  { text: 'Læg mærke til fem ting, du kan se lige nu.', category: 'mindfulness', time: 'anytime' },
  { text: 'Slip det, du ikke kan styre.', category: 'mindfulness', time: 'anytime' },
  { text: 'Dine tanker er skyer. Lad dem drive forbi.', category: 'mindfulness', time: 'anytime' },
  { text: 'Fred er ikke fravær af kaos; det er roen indeni.', category: 'mindfulness', time: 'anytime' },
  { text: 'Lige nu, i dette øjeblik, er du tryg.', category: 'mindfulness', time: 'night' },
  { text: 'Stilhed er ikke tom; den er fuld af svar.', category: 'mindfulness', time: 'evening' },
  { text: 'Mærk dine fødder mod jorden. Du er forankret.', category: 'mindfulness', time: 'anytime' },
  { text: 'Hold pause. Træk vejret. Fortsæt.', category: 'mindfulness', time: 'anytime' },
  { text: 'Du er ikke dine tanker. Du er bevidstheden bag dem.', category: 'mindfulness', time: 'anytime' },
  { text: 'Læg mærke til rummet mellem dine tanker. Det er der, freden bor.', category: 'mindfulness', time: 'evening' },
  { text: 'Lyt til lydene omkring dig uden at sætte navn på dem.', category: 'mindfulness', time: 'anytime' },
  { text: 'Læg en hånd på brystet. Mærk dit hjerteslag. Du er i live.', category: 'mindfulness', time: 'anytime' },
  { text: 'Det nuværende øjeblik er det eneste øjeblik, der virkelig findes.', category: 'mindfulness', time: 'anytime' },
  { text: 'Hvor sidder spændingen i din krop lige nu? Ånd ind i den.', category: 'mindfulness', time: 'afternoon' },
  { text: 'Mellem stimulus og reaktion er der et rum. I det rum ligger din kraft.', category: 'mindfulness', attribution: 'Viktor Frankl', time: 'anytime' },
  { text: 'Ånd ind, mens du tæller til fire. Hold i fire. Ånd ud på fire. Gentag.', category: 'mindfulness', time: 'anytime' },
  { text: 'Lån ikke bekymringer fra i morgen. I dag er nok.', category: 'mindfulness', time: 'evening' },
  { text: 'Alt er midlertidigt. Det gode og det svære. Nyd og hold ud.', category: 'mindfulness', time: 'anytime' },
  { text: 'Du behøver ikke have styr på det hele. Tag bare det næste skridt.', category: 'mindfulness', time: 'anytime' },
  { text: 'Dit åndedræt er der altid for dig. Vend tilbage til det.', category: 'mindfulness', time: 'anytime' },
  { text: 'Hvad er én ting, du kan gøre lige nu for at passe på dig selv?', category: 'mindfulness', time: 'afternoon' },
  { text: 'Intet i naturen blomstrer hele året. Vær tålmodig med dig selv.', category: 'mindfulness', time: 'anytime' },
  { text: 'Stilhed er ikke dovenskab. Det er sådan, din sjæl indhenter dig.', category: 'mindfulness', time: 'evening' },
  { text: 'Du må gerne vokse fra rum, der ikke længere passer til dig.', category: 'mindfulness', time: 'anytime' },
  { text: 'Lyt til regnen. Lad den få dine tanker til at falde til ro.', category: 'mindfulness', time: 'anytime', weather: 'rain' },
  { text: 'Sneen minder mig om at sætte farten ned og være stille.', category: 'mindfulness', time: 'anytime', weather: 'snow' },
  { text: 'Mærk solens varme på din hud. Du er her.', category: 'mindfulness', time: 'anytime', weather: 'clear' },

  // ── Season-aware entries ──────────────────────────────────────
  { text: 'Foråret minder os om, at nye begyndelser altid er mulige.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'Ligesom blomsterne blomstrer også du i dit eget tempo.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'Jorden vågner. Lad dig selv vågne med den.', category: 'mindfulness', time: 'morning', season: 'spring' },
  { text: 'Frisk luft, friske starter. Foråret er på din side.', category: 'motivational', time: 'morning', season: 'spring' },
  { text: 'Lad sommerens varme fylde din sjæl.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Lange dage, varme nætter. Sug det hele til dig.', category: 'gratitude', time: 'evening', season: 'summer' },
  { text: 'Sommerlyset minder dig om, at der altid er mere dag forude.', category: 'motivational', time: 'morning', season: 'summer' },
  { text: 'Solen er fremme. Lad den varme mere end blot din hud.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Ligesom efterårsløvet, slip det, der er klar til at falde.', category: 'mindfulness', time: 'anytime', season: 'fall' },
  { text: 'Efteråret lærer os, at det at give slip kan være smukt.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'Verden skifter farver. Du må også gerne forandre dig.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'Høsttid; saml frugterne af dit hårde arbejde.', category: 'gratitude', time: 'anytime', season: 'fall' },
  { text: 'Selv om vinteren sker der vækst under overfladen.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'Vinterens stilhed er en invitation til at vende blikket indad.', category: 'mindfulness', time: 'evening', season: 'winter' },
  { text: 'Koldt udenfor, varmt indeni. Pas på din indre ild.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'Vinternætter er til hvile. Foråret kommer igen.', category: 'mindfulness', time: 'night', season: 'winter' },

  // ── Night-specific ────────────────────────────────────────────
  { text: 'Sov godt. I morgen er en frisk start.', category: 'affirmations', time: 'night' },
  { text: 'Du har udrettet nok i dag. Giv dig selv lov til at sove.', category: 'mindfulness', time: 'night' },
  { text: 'Natten er til at komme sig, ikke til bekymring.', category: 'mindfulness', time: 'night' },
  { text: 'Luk øjnene i visheden om, at du gjorde dit bedste i dag.', category: 'affirmations', time: 'night' },
  { text: 'Lad nattens stilhed få dit sind til at falde til ro.', category: 'mindfulness', time: 'night' },
  { text: 'Søvn er ikke en luksus. Det er sådan, du lader op til storhed.', category: 'affirmations', time: 'night' },
  { text: 'Giv slip på alle bekymringer i aften. I morgen kan du prøve igen.', category: 'mindfulness', time: 'night' },

  // ── Morning-specific ──────────────────────────────────────────
  { text: 'Godmorgen. I dag er fuld af muligheder.', category: 'affirmations', time: 'morning' },
  { text: 'Morgenen er din. Sæt en intention, og følg den.', category: 'motivational', time: 'morning' },
  { text: 'Stå op og strål, ikke fordi du skal, men fordi du får lov.', category: 'gratitude', time: 'morning' },
  { text: 'Hvad er én ting, du gerne vil føle i dag? Bevæg dig hen imod det.', category: 'mindfulness', time: 'morning' },
  { text: 'En ny dag betyder en ny chance for at skabe noget vidunderligt.', category: 'motivational', time: 'morning' },
  { text: 'Din morgenrutine er et udtryk for kærlighed til dig selv.', category: 'affirmations', time: 'morning' },
];
