import type { AffirmationEntry } from './types';

// ---------------------------------------------------------------------------
// Built-in content library — de-DE (198 entries)
// ---------------------------------------------------------------------------

export const DE_DE_AFFIRMATIONS: AffirmationEntry[] = [
  // ── Affirmations ──────────────────────────────────────────────
  { text: 'Ich bin Liebe und Freundlichkeit wert.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich vertraue dem Weg, auch wenn ich ihn nicht sehen kann.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich werde zu dem Menschen, der ich sein möchte.', category: 'affirmations', time: 'anytime' },
  { text: 'Mein Potenzial ist grenzenlos.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich lasse los, was mir nicht mehr dient.', category: 'affirmations', time: 'evening' },
  { text: 'Ich wähle Frieden statt Perfektion.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich darf Raum einnehmen.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich bin genug, genau so, wie ich bin.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich ziehe positive Energie in mein Leben.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Ich bin widerstandsfähig, stark und mutig.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich erlaube mir, mich auszuruhen.', category: 'affirmations', time: 'evening', weather: 'rain' },
  { text: 'Ich achte meine eigenen Grenzen.', category: 'affirmations', time: 'anytime' },
  { text: 'Jeder Rückschlag ist der Auftakt zu einem Comeback.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich bin im Reinen damit, wer ich bin.', category: 'affirmations', time: 'night' },
  { text: 'Meine Stimme zählt. Meine Geschichte zählt.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich heiße Fülle in all ihren Formen willkommen.', category: 'affirmations', time: 'morning' },
  { text: 'Ich habe die guten Dinge in meinem Leben verdient.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich vergebe mir vergangene Fehler. Sie haben mich wachsen lassen.', category: 'affirmations', time: 'evening' },
  { text: 'Mein Körper ist gesund, mein Geist ist klar, meine Seele ist ruhig.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Ich strahle Selbstvertrauen und Selbstachtung aus.', category: 'affirmations', time: 'morning' },
  { text: 'Ich bin offen für neue Abenteuer und Erfahrungen.', category: 'affirmations', time: 'morning' },
  { text: 'Ich lasse Vergleiche los. Mein Weg ist mein eigener.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich bin ein Werk im Werden, und das ist völlig in Ordnung.', category: 'affirmations', time: 'anytime' },
  { text: 'Meine Fehler bestimmen mich nicht. Mein Wachstum tut es.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich habe die Kraft, das Leben zu erschaffen, das ich will.', category: 'affirmations', time: 'morning' },
  { text: 'Ich wähle, mich auf das zu konzentrieren, was ich ändern kann.', category: 'affirmations', time: 'anytime' },
  { text: 'Ich bin von Liebe umgeben, auch wenn ich sie nicht spüren kann.', category: 'affirmations', time: 'night' },
  { text: 'Heute bin ich freundlich zu mir selbst.', category: 'affirmations', time: 'morning' },
  { text: 'Ich bin stärker als meine Zweifel.', category: 'affirmations', time: 'anytime' },
  { text: 'Mein Glück liegt in meiner Verantwortung, und ich nehme sie an.', category: 'affirmations', time: 'anytime' },
  { text: 'Der Regen wäscht weg, was ich nicht mehr brauche.', category: 'affirmations', time: 'anytime', weather: 'rain' },
  { text: 'Ich finde Schönheit in jedem Himmel.', category: 'affirmations', time: 'anytime', weather: 'clouds' },

  // ── Compliments ───────────────────────────────────────────────
  { text: 'Du erhellst jeden Raum, den du betrittst.', category: 'compliments', time: 'anytime' },
  { text: 'Dein Lächeln ist ansteckend — hör nie auf, es zu teilen.', category: 'compliments', time: 'morning' },
  { text: 'Du hast ein Gespür dafür, anderen das Gefühl zu geben, gesehen zu werden.', category: 'compliments', time: 'anytime' },
  { text: 'Die Welt ist besser, weil es dich gibt.', category: 'compliments', time: 'anytime' },
  { text: 'Deine Freundlichkeit zieht weitere Kreise, als du ahnst.', category: 'compliments', time: 'anytime' },
  { text: 'Du meisterst Herausforderungen mit bemerkenswerter Anmut.', category: 'compliments', time: 'afternoon' },
  { text: 'Menschen können sich glücklich schätzen, dich zu kennen.', category: 'compliments', time: 'anytime' },
  { text: 'Deine Ausstrahlung ist magnetisch.', category: 'compliments', time: 'anytime' },
  { text: 'Du lässt schwierige Dinge leicht aussehen.', category: 'compliments', time: 'afternoon' },
  { text: 'Du hast einen unglaublich guten Geschmack.', category: 'compliments', time: 'anytime' },
  { text: 'Deine Kreativität inspiriert alle um dich herum.', category: 'compliments', time: 'anytime' },
  { text: 'Du bringst das Beste in den Menschen zum Vorschein.', category: 'compliments', time: 'anytime' },
  { text: 'Du verdienst all das Gute, das auf dich zukommt.', category: 'compliments', time: 'anytime' },
  { text: 'Dein Lachen ist der schönste Klang.', category: 'compliments', time: 'anytime' },
  { text: 'Du machst das ganz wunderbar.', category: 'compliments', time: 'afternoon' },
  { text: 'Deine Geduld ist eine Superkraft.', category: 'compliments', time: 'afternoon' },
  { text: 'Du hast eine wunderbare Art, die Welt zu sehen.', category: 'compliments', time: 'anytime' },
  { text: 'Deine Entschlossenheit ist inspirierend.', category: 'compliments', time: 'anytime' },
  { text: 'Du gibst Menschen das Gefühl, sicher und wertgeschätzt zu sein.', category: 'compliments', time: 'anytime' },
  { text: 'Du hast den Mut, du selbst zu sein, und das ist selten.', category: 'compliments', time: 'anytime' },
  { text: 'Deine Sichtweise ist einzigartig und sie zählt.', category: 'compliments', time: 'anytime' },
  { text: 'Du führst mit Empathie, und man merkt es.', category: 'compliments', time: 'afternoon' },
  { text: 'Es gibt niemanden, der so ist wie du. Das ist deine Stärke.', category: 'compliments', time: 'anytime' },
  { text: 'Du trägst eine stille Zuversicht in dir.', category: 'compliments', time: 'anytime' },
  { text: 'Die Mühe, die du dir gibst, bleibt nicht unbemerkt.', category: 'compliments', time: 'afternoon' },
  { text: 'Dein Herz ist größer, als du dir selbst zugestehst.', category: 'compliments', time: 'evening' },
  { text: 'Du hast ein gutes Gespür. Vertraue ihm mehr.', category: 'compliments', time: 'anytime' },
  { text: 'Deine Begeisterung ist ansteckend.', category: 'compliments', time: 'morning' },
  { text: 'Du gehst mit Druck besser um, als du denkst.', category: 'compliments', time: 'afternoon' },
  { text: 'Du bist jemand, auf den man sich verlassen kann.', category: 'compliments', time: 'anytime' },

  // ── Motivational ──────────────────────────────────────────────
  { text: 'Beginne dort, wo du bist. Nutze, was du hast. Tu, was du kannst.', category: 'motivational', attribution: 'Arthur Ashe', time: 'morning' },
  { text: 'Der einzige Weg, großartige Arbeit zu leisten, ist zu lieben, was du tust.', category: 'motivational', attribution: 'Steve Jobs', time: 'morning' },
  { text: 'Es ist egal, wie langsam du gehst, solange du nicht stehen bleibst.', category: 'motivational', attribution: 'Confucius', time: 'anytime' },
  { text: 'Was du durch das Erreichen deiner Ziele bekommst, ist nicht so wichtig wie das, was du dabei wirst.', category: 'motivational', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Glaube, dass du es kannst, und du bist schon halb am Ziel.', category: 'motivational', attribution: 'Theodore Roosevelt', time: 'morning' },
  { text: 'Kleine tägliche Verbesserungen sind der Schlüssel zu überwältigenden Langzeitergebnissen.', category: 'motivational', time: 'morning' },
  { text: 'Disziplin heißt, zwischen dem zu wählen, was du jetzt willst, und dem, was du am meisten willst.', category: 'motivational', attribution: 'Abraham Lincoln', time: 'anytime' },
  { text: 'Du bist nicht so weit gekommen, um nur so weit zu kommen.', category: 'motivational', time: 'afternoon' },
  { text: 'Träume groß. Fang klein an. Handle jetzt.', category: 'motivational', time: 'morning' },
  { text: 'Das Geheimnis des Vorankommens liegt darin, anzufangen.', category: 'motivational', attribution: 'Mark Twain', time: 'morning' },
  { text: 'Dein zukünftiges Ich beobachtet dich gerade jetzt durch Erinnerungen.', category: 'motivational', time: 'anytime' },
  { text: 'Die beste Zeit, einen Baum zu pflanzen, war vor 20 Jahren. Die zweitbeste Zeit ist jetzt.', category: 'motivational', time: 'anytime' },
  { text: 'Fortschritt, nicht Perfektion.', category: 'motivational', time: 'anytime' },
  { text: 'Schwierigkeiten bereiten gewöhnliche Menschen oft auf ein außergewöhnliches Schicksal vor.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'Sei so gut, dass sie dich nicht ignorieren können.', category: 'motivational', attribution: 'Steve Martin', time: 'morning' },
  { text: 'Du bist nie zu alt, um dir ein neues Ziel zu setzen oder einen neuen Traum zu träumen.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'Der Kampf, in dem du heute steckst, entwickelt die Stärke, die du morgen brauchst.', category: 'motivational', time: 'afternoon' },
  { text: 'Tu heute etwas, wofür dein zukünftiges Ich dir danken wird.', category: 'motivational', time: 'morning' },
  { text: 'Erfolg ist die Summe kleiner Anstrengungen, Tag für Tag wiederholt.', category: 'motivational', attribution: 'Robert Collier', time: 'morning' },
  { text: 'Fall siebenmal hin, steh achtmal auf.', category: 'motivational', time: 'anytime' },
  { text: 'Was heute unmöglich scheint, wird eines Tages dein Aufwärmen sein.', category: 'motivational', time: 'morning' },
  { text: 'Du musst nicht perfekt sein, um großartig zu sein.', category: 'motivational', time: 'anytime' },
  { text: 'Handeln ist der Grundstein für jeden Erfolg.', category: 'motivational', attribution: 'Pablo Picasso', time: 'morning' },
  { text: 'Das Comeback ist immer stärker als der Rückschlag.', category: 'motivational', time: 'anytime' },
  { text: 'In einem Jahr wirst du dir wünschen, du hättest heute angefangen.', category: 'motivational', time: 'morning' },
  { text: 'Alles, was du je wolltest, liegt auf der anderen Seite der Angst.', category: 'motivational', attribution: 'George Addair', time: 'anytime' },
  { text: 'Energie fließt dorthin, wo die Aufmerksamkeit hingeht.', category: 'motivational', time: 'morning' },
  { text: 'Zweifel tötet mehr Träume, als es das Scheitern je könnte.', category: 'motivational', attribution: 'Suzy Kassem', time: 'anytime' },
  { text: 'Wäre es leicht, würde es jeder tun. Mach weiter.', category: 'motivational', time: 'afternoon' },
  { text: 'Du bist nur eine Entscheidung von einem völlig anderen Leben entfernt.', category: 'motivational', time: 'anytime' },
  { text: 'Fertig ist besser als perfekt.', category: 'motivational', time: 'afternoon' },
  { text: 'Die einzige Grenze für unser Morgen sind unsere Zweifel von heute.', category: 'motivational', attribution: 'Franklin D. Roosevelt', time: 'anytime' },
  { text: 'Sterne können ohne Dunkelheit nicht leuchten.', category: 'motivational', time: 'evening' },
  { text: 'Mut ist nicht das Fehlen von Angst. Es ist, trotz ihr zu handeln.', category: 'motivational', attribution: 'Mark Twain', time: 'anytime' },
  { text: 'Was würdest du versuchen, wenn du wüsstest, dass du nicht scheitern kannst?', category: 'motivational', time: 'morning' },
  { text: 'Der Weg, anzufangen, ist aufzuhören zu reden und zu beginnen zu handeln.', category: 'motivational', attribution: 'Walt Disney', time: 'morning' },

  // ── Day-of-week motivation ────────────────────────────────────
  { text: 'Neue Woche, neue Möglichkeiten. Mach diese zu etwas Besonderem.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Montage sind für Neuanfänge und mutige Schritte da.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Gib den Ton für die Woche an. Du schaffst das.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Dienstag: der Beweis, dass du den Montag überstanden hast und weitermachst.', category: 'compliments', time: 'morning', days: [2] },
  { text: 'Wochenmitte: Du bist näher dran, als du denkst.', category: 'motivational', time: 'anytime', days: [3] },
  { text: 'Mittwoch — die Hälfte ist geschafft. Du machst das großartig.', category: 'compliments', time: 'afternoon', days: [3] },
  { text: 'Fast geschafft. Beende die Woche stark.', category: 'motivational', time: 'morning', days: [4] },
  { text: 'Donnerstagsenergie: Das Wochenende ist in Sicht.', category: 'motivational', time: 'afternoon', days: [4] },
  { text: 'Du hast die Woche geschafft. Sei stolz auf dich.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Schönen Freitag. Du hast dir jedes bisschen dieses Wochenendes verdient.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Genieße das Wochenende — du hast es dir verdient.', category: 'compliments', time: 'anytime', days: [5, 6, 0] },
  { text: 'Samstage sind zum Auftanken da. Tu, was dir guttut.', category: 'mindfulness', time: 'morning', days: [6] },
  { text: 'Sonntag: ruh dich aus, denk nach und bereite dich darauf vor, wieder zu strahlen.', category: 'mindfulness', time: 'morning', days: [0] },
  { text: 'Nutze den heutigen Tag, um dich auf eine großartige Woche vorzubereiten.', category: 'motivational', time: 'afternoon', days: [0] },

  // ── Gratitude ─────────────────────────────────────────────────
  { text: 'Wofür bist du gerade jetzt dankbar? Nenne drei Dinge.', category: 'gratitude', time: 'morning' },
  { text: 'Nimm dir einen Moment, um zu würdigen, wie weit du gekommen bist.', category: 'gratitude', time: 'evening' },
  { text: 'Dankbarkeit macht aus dem, was wir haben, genug.', category: 'gratitude', time: 'anytime' },
  { text: 'Bemerke heute eine kleine Sache, die dir Freude bereitet.', category: 'gratitude', time: 'morning' },
  { text: 'Wer hat dich heute zum Lächeln gebracht? Halte dieses Gefühl fest.', category: 'gratitude', time: 'evening' },
  { text: 'Die gewöhnlichen Momente sind oft die schönsten.', category: 'gratitude', time: 'anytime' },
  { text: 'Würdige die Lektionen, die in Herausforderungen verborgen sind.', category: 'gratitude', time: 'anytime' },
  { text: 'Du hast so viel, wofür du dankbar sein kannst.', category: 'gratitude', time: 'anytime' },
  { text: 'Was sich letztes Jahr unmöglich anfühlte, ist heute deine Realität.', category: 'gratitude', time: 'anytime' },
  { text: 'Lass Dankbarkeit deine Grundhaltung sein.', category: 'gratitude', time: 'morning' },
  { text: 'Denk an ein freundliches Wort, das dir kürzlich jemand gesagt hat.', category: 'gratitude', time: 'evening' },
  { text: 'Dein Leben ist voller leiser Wunder. Halte Ausschau nach ihnen.', category: 'gratitude', time: 'anytime' },
  { text: 'Nenne einen Menschen, der dein Leben dieses Jahr besser gemacht hat.', category: 'gratitude', time: 'evening' },
  { text: 'Das Dach über deinem Kopf, das Essen auf deinem Tisch — das sind keine Kleinigkeiten.', category: 'gratitude', time: 'anytime' },
  { text: 'Denk an eine Herausforderung, die dich stärker gemacht hat. Sei dankbar dafür.', category: 'gratitude', time: 'evening' },
  { text: 'Dankbarkeit ist die gesündeste aller menschlichen Emotionen.', category: 'gratitude', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Was hast du heute, das du dir einst gewünscht hast?', category: 'gratitude', time: 'morning' },
  { text: 'Jeder Sonnenaufgang ist eine Einladung, jemandem den Tag zu verschönern.', category: 'gratitude', time: 'morning' },
  { text: 'Heute war ein Geschenk. Was war dein liebster Moment?', category: 'gratitude', time: 'evening' },
  { text: 'Die Menschen in deinem Leben lieben dich mehr, als dir bewusst ist.', category: 'gratitude', time: 'anytime' },
  { text: 'Bemerke die Schönheit in etwas, das du jeden Tag siehst.', category: 'gratitude', time: 'anytime' },
  { text: 'Ein dankbares Herz ist ein Magnet für wunderbare Dinge.', category: 'gratitude', time: 'morning' },
  { text: 'Welche kleine Freude hast du heute genossen?', category: 'gratitude', time: 'evening' },
  { text: 'Denk daran: Irgendwo da draußen inspirierst du jemanden.', category: 'gratitude', time: 'anytime' },
  { text: 'Ich bin dankbar für sonnige Tage, die meine Stimmung heben.', category: 'gratitude', time: 'anytime', weather: 'clear' },
  { text: 'Ich bin dankbar für regnerische Tage, die die Erde nähren.', category: 'gratitude', time: 'anytime', weather: 'rain' },

  // ── Mindfulness ───────────────────────────────────────────────
  { text: 'Atme tief durch. Du bist genau dort, wo du sein sollst.', category: 'mindfulness', time: 'anytime' },
  { text: 'Sei präsent. Dieser Moment ist alles, was es gibt.', category: 'mindfulness', time: 'anytime' },
  { text: 'Atme Ruhe ein. Atme Anspannung aus.', category: 'mindfulness', time: 'anytime' },
  { text: 'Werde langsamer. Es gibt keine Eile, irgendwo anders zu sein.', category: 'mindfulness', time: 'evening' },
  { text: 'Bemerke fünf Dinge, die du gerade jetzt sehen kannst.', category: 'mindfulness', time: 'anytime' },
  { text: 'Lass los, was du nicht kontrollieren kannst.', category: 'mindfulness', time: 'anytime' },
  { text: 'Deine Gedanken sind Wolken. Lass sie vorüberziehen.', category: 'mindfulness', time: 'anytime' },
  { text: 'Frieden ist nicht das Fehlen von Chaos — es ist die Ruhe in dir.', category: 'mindfulness', time: 'anytime' },
  { text: 'Gerade jetzt, in diesem Moment, bist du sicher.', category: 'mindfulness', time: 'night' },
  { text: 'Stille ist nicht leer — sie ist voller Antworten.', category: 'mindfulness', time: 'evening' },
  { text: 'Spüre deine Füße auf dem Boden. Du bist verankert.', category: 'mindfulness', time: 'anytime' },
  { text: 'Innehalten. Atmen. Weitermachen.', category: 'mindfulness', time: 'anytime' },
  { text: 'Du bist nicht deine Gedanken. Du bist das Bewusstsein dahinter.', category: 'mindfulness', time: 'anytime' },
  { text: 'Bemerke den Raum zwischen deinen Gedanken. Dort wohnt der Frieden.', category: 'mindfulness', time: 'evening' },
  { text: 'Höre den Klängen um dich herum zu, ohne sie zu benennen.', category: 'mindfulness', time: 'anytime' },
  { text: 'Leg eine Hand auf deine Brust. Spüre deinen Herzschlag. Du lebst.', category: 'mindfulness', time: 'anytime' },
  { text: 'Der gegenwärtige Moment ist der einzige, der wirklich existiert.', category: 'mindfulness', time: 'anytime' },
  { text: 'Wo sitzt gerade Anspannung in deinem Körper? Atme in sie hinein.', category: 'mindfulness', time: 'afternoon' },
  { text: 'Zwischen Reiz und Reaktion liegt ein Raum. In diesem Raum liegt deine Kraft.', category: 'mindfulness', attribution: 'Viktor Frankl', time: 'anytime' },
  { text: 'Atme vier Zählzeiten ein. Halte vier. Atme vier aus. Wiederhole.', category: 'mindfulness', time: 'anytime' },
  { text: 'Borg dir keine Sorgen vom morgigen Tag. Heute ist genug.', category: 'mindfulness', time: 'evening' },
  { text: 'Alles ist vergänglich. Das Gute und das Schwere. Genieße und ertrage.', category: 'mindfulness', time: 'anytime' },
  { text: 'Du musst nicht alles durchschaut haben. Mach einfach den nächsten Schritt.', category: 'mindfulness', time: 'anytime' },
  { text: 'Dein Atem ist immer für dich da. Kehre zu ihm zurück.', category: 'mindfulness', time: 'anytime' },
  { text: 'Was kannst du gerade jetzt tun, um für dich zu sorgen?', category: 'mindfulness', time: 'afternoon' },
  { text: 'Nichts in der Natur blüht das ganze Jahr. Sei geduldig mit dir.', category: 'mindfulness', time: 'anytime' },
  { text: 'Stille ist keine Faulheit. So holt deine Seele auf.', category: 'mindfulness', time: 'evening' },
  { text: 'Du darfst über Orte hinauswachsen, die nicht mehr zu dir passen.', category: 'mindfulness', time: 'anytime' },
  { text: 'Höre dem Regen zu. Lass ihn deine Gedanken beruhigen.', category: 'mindfulness', time: 'anytime', weather: 'rain' },
  { text: 'Der Schnee erinnert mich daran, langsamer zu werden und still zu sein.', category: 'mindfulness', time: 'anytime', weather: 'snow' },
  { text: 'Spüre die Wärme der Sonne auf deiner Haut. Du bist hier.', category: 'mindfulness', time: 'anytime', weather: 'clear' },

  // ── Season-aware entries ──────────────────────────────────────
  { text: 'Der Frühling erinnert uns daran, dass Neuanfänge immer möglich sind.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'Wie die Blumen erblühst auch du in deinem eigenen Tempo.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'Die Erde erwacht. Erwache mit ihr.', category: 'mindfulness', time: 'morning', season: 'spring' },
  { text: 'Frische Luft, frische Anfänge. Der Frühling ist auf deiner Seite.', category: 'motivational', time: 'morning', season: 'spring' },
  { text: 'Lass die Wärme des Sommers deine Seele erfüllen.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Lange Tage, warme Nächte. Sauge alles in dich auf.', category: 'gratitude', time: 'evening', season: 'summer' },
  { text: 'Das Sommerlicht erinnert dich daran, dass immer mehr Tag vor dir liegt.', category: 'motivational', time: 'morning', season: 'summer' },
  { text: 'Die Sonne scheint. Lass sie mehr als nur deine Haut wärmen.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Wie das Herbstlaub, lass los, was bereit ist zu fallen.', category: 'mindfulness', time: 'anytime', season: 'fall' },
  { text: 'Der Herbst lehrt uns, dass Loslassen schön sein kann.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'Die Welt verändert ihre Farben. Auch du darfst dich verändern.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'Erntezeit — sammle die Früchte deiner harten Arbeit.', category: 'gratitude', time: 'anytime', season: 'fall' },
  { text: 'Selbst im Winter geschieht Wachstum unter der Oberfläche.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'Die Stille des Winters ist eine Einladung, nach innen zu gehen.', category: 'mindfulness', time: 'evening', season: 'winter' },
  { text: 'Draußen kalt, innen warm. Hüte dein inneres Feuer.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'Winternächte sind zum Ausruhen. Der Frühling kommt wieder.', category: 'mindfulness', time: 'night', season: 'winter' },

  // ── Night-specific ────────────────────────────────────────────
  { text: 'Ruh dich gut aus. Morgen ist ein Neuanfang.', category: 'affirmations', time: 'night' },
  { text: 'Du hast heute genug geschafft. Gönn dir jetzt Schlaf.', category: 'mindfulness', time: 'night' },
  { text: 'Die Nacht ist zum Erholen da, nicht zum Sorgen.', category: 'mindfulness', time: 'night' },
  { text: 'Schließ die Augen im Wissen, dass du heute dein Bestes gegeben hast.', category: 'affirmations', time: 'night' },
  { text: 'Lass die Stille der Nacht deinen Geist zur Ruhe bringen.', category: 'mindfulness', time: 'night' },
  { text: 'Schlaf ist kein Luxus. So tankst du Kraft für Großes.', category: 'affirmations', time: 'night' },
  { text: 'Lass heute Nacht jede Sorge los. Morgen kannst du es wieder versuchen.', category: 'mindfulness', time: 'night' },

  // ── Morning-specific ──────────────────────────────────────────
  { text: 'Guten Morgen. Dieser Tag steckt voller Möglichkeiten.', category: 'affirmations', time: 'morning' },
  { text: 'Der Morgen gehört dir. Setz dir dein Ziel und nimm ihn in Besitz.', category: 'motivational', time: 'morning' },
  { text: 'Aufstehen und strahlen — nicht weil du musst, sondern weil du darfst.', category: 'gratitude', time: 'morning' },
  { text: 'Was möchtest du heute fühlen? Geh darauf zu.', category: 'mindfulness', time: 'morning' },
  { text: 'Ein neuer Tag bedeutet eine neue Chance, etwas Wunderbares zu schaffen.', category: 'motivational', time: 'morning' },
  { text: 'Deine Morgenroutine ist ein Akt der Selbstliebe.', category: 'affirmations', time: 'morning' },
];
