import type { AffirmationEntry } from './types';

// ---------------------------------------------------------------------------
// Built-in content library — es-ES (198 entries)
// ---------------------------------------------------------------------------

export const ES_ES_AFFIRMATIONS: AffirmationEntry[] = [
  // ── Affirmations ──────────────────────────────────────────────
  { text: 'Merezco amor y bondad.', category: 'affirmations', time: 'anytime' },
  { text: 'Confío en el camino, aunque no pueda verlo.', category: 'affirmations', time: 'anytime' },
  { text: 'Me estoy convirtiendo en la persona que quiero ser.', category: 'affirmations', time: 'anytime' },
  { text: 'Mi potencial no tiene límites.', category: 'affirmations', time: 'anytime' },
  { text: 'Suelto lo que ya no me sirve.', category: 'affirmations', time: 'evening' },
  { text: 'Elijo la paz antes que la perfección.', category: 'affirmations', time: 'anytime' },
  { text: 'Tengo derecho a ocupar mi espacio.', category: 'affirmations', time: 'anytime' },
  { text: 'Soy suficiente, tal y como soy.', category: 'affirmations', time: 'anytime' },
  { text: 'Atraigo energía positiva a mi vida.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Soy resiliente, fuerte y valiente.', category: 'affirmations', time: 'anytime' },
  { text: 'Me doy permiso para descansar.', category: 'affirmations', time: 'evening', weather: 'rain' },
  { text: 'Respeto mis propios límites.', category: 'affirmations', time: 'anytime' },
  { text: 'Cada revés prepara el terreno para una gran remontada.', category: 'affirmations', time: 'anytime' },
  { text: 'Estoy en paz con quien soy.', category: 'affirmations', time: 'night' },
  { text: 'Mi voz importa. Mi historia importa.', category: 'affirmations', time: 'anytime' },
  { text: 'Doy la bienvenida a la abundancia en todas sus formas.', category: 'affirmations', time: 'morning' },
  { text: 'Merezco las cosas buenas de mi vida.', category: 'affirmations', time: 'anytime' },
  { text: 'Me perdono por mis errores pasados. Me ayudaron a crecer.', category: 'affirmations', time: 'evening' },
  { text: 'Mi cuerpo está sano, mi mente lúcida y mi espíritu en calma.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Irradio confianza y amor propio.', category: 'affirmations', time: 'morning' },
  { text: 'Estoy abierto a nuevas aventuras y experiencias.', category: 'affirmations', time: 'morning' },
  { text: 'Dejo de compararme. Mi camino es solo mío.', category: 'affirmations', time: 'anytime' },
  { text: 'Estoy en construcción, y eso está perfectamente bien.', category: 'affirmations', time: 'anytime' },
  { text: 'Mis errores no me definen. Mi crecimiento sí.', category: 'affirmations', time: 'anytime' },
  { text: 'Tengo el poder de crear la vida que quiero.', category: 'affirmations', time: 'morning' },
  { text: 'Elijo centrarme en lo que puedo cambiar.', category: 'affirmations', time: 'anytime' },
  { text: 'Estoy rodeado de amor, aunque no siempre pueda sentirlo.', category: 'affirmations', time: 'night' },
  { text: 'Hoy voy a ser amable conmigo mismo.', category: 'affirmations', time: 'morning' },
  { text: 'Soy más fuerte que mis dudas.', category: 'affirmations', time: 'anytime' },
  { text: 'Mi felicidad es mi responsabilidad, y la asumo.', category: 'affirmations', time: 'anytime' },
  { text: 'La lluvia se lleva lo que ya no necesito.', category: 'affirmations', time: 'anytime', weather: 'rain' },
  { text: 'Encuentro belleza en cualquier tipo de cielo.', category: 'affirmations', time: 'anytime', weather: 'clouds' },

  // ── Compliments ───────────────────────────────────────────────
  { text: 'Iluminas cada lugar al que llegas.', category: 'compliments', time: 'anytime' },
  { text: 'Tu sonrisa es contagiosa, no dejes de compartirla nunca.', category: 'compliments', time: 'morning' },
  { text: 'Tienes el don de hacer que los demás se sientan vistos.', category: 'compliments', time: 'anytime' },
  { text: 'El mundo es mejor porque tú estás en él.', category: 'compliments', time: 'anytime' },
  { text: 'Tu amabilidad llega más lejos de lo que imaginas.', category: 'compliments', time: 'anytime' },
  { text: 'Afrontas los retos con una elegancia admirable.', category: 'compliments', time: 'afternoon' },
  { text: 'La gente tiene suerte de conocerte.', category: 'compliments', time: 'anytime' },
  { text: 'Tu energía es magnética.', category: 'compliments', time: 'anytime' },
  { text: 'Haces que lo difícil parezca fácil.', category: 'compliments', time: 'afternoon' },
  { text: 'Tienes un gusto increíble.', category: 'compliments', time: 'anytime' },
  { text: 'Tu creatividad inspira a todos los que te rodean.', category: 'compliments', time: 'anytime' },
  { text: 'Sacas lo mejor de las personas.', category: 'compliments', time: 'anytime' },
  { text: 'Mereces todo lo bueno que está por llegarte.', category: 'compliments', time: 'anytime' },
  { text: 'Tu risa es el mejor sonido del mundo.', category: 'compliments', time: 'anytime' },
  { text: 'Lo estás haciendo de maravilla.', category: 'compliments', time: 'afternoon' },
  { text: 'Tu paciencia es un superpoder.', category: 'compliments', time: 'afternoon' },
  { text: 'Tienes una forma preciosa de mirar el mundo.', category: 'compliments', time: 'anytime' },
  { text: 'Tu determinación es inspiradora.', category: 'compliments', time: 'anytime' },
  { text: 'Haces que la gente se sienta segura y valorada.', category: 'compliments', time: 'anytime' },
  { text: 'Tienes el valor de ser tú mismo, y eso es poco común.', category: 'compliments', time: 'anytime' },
  { text: 'Tu perspectiva es única e importa.', category: 'compliments', time: 'anytime' },
  { text: 'Lideras con empatía y se nota.', category: 'compliments', time: 'afternoon' },
  { text: 'No hay nadie como tú. Esa es tu fuerza.', category: 'compliments', time: 'anytime' },
  { text: 'Te desenvuelves con una confianza serena.', category: 'compliments', time: 'anytime' },
  { text: 'El esfuerzo que pones no pasa desapercibido.', category: 'compliments', time: 'afternoon' },
  { text: 'Tu corazón es más grande de lo que crees.', category: 'compliments', time: 'evening' },
  { text: 'Tienes muy buen instinto. Confía más en él.', category: 'compliments', time: 'anytime' },
  { text: 'Tu entusiasmo se contagia.', category: 'compliments', time: 'morning' },
  { text: 'Manejas la presión mejor de lo que crees.', category: 'compliments', time: 'afternoon' },
  { text: 'Eres alguien en quien la gente puede confiar.', category: 'compliments', time: 'anytime' },

  // ── Motivational ──────────────────────────────────────────────
  { text: 'Empieza donde estás. Usa lo que tienes. Haz lo que puedas.', category: 'motivational', attribution: 'Arthur Ashe', time: 'morning' },
  { text: 'La única forma de hacer un gran trabajo es amar lo que haces.', category: 'motivational', attribution: 'Steve Jobs', time: 'morning' },
  { text: 'No importa lo despacio que vayas, siempre que no te detengas.', category: 'motivational', attribution: 'Confucius', time: 'anytime' },
  { text: 'Lo que consigues al alcanzar tus metas no es tan importante como en quien te conviertes.', category: 'motivational', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Cree que puedes y ya estarás a medio camino.', category: 'motivational', attribution: 'Theodore Roosevelt', time: 'morning' },
  { text: 'Las pequeñas mejoras diarias son la clave de unos resultados asombrosos a largo plazo.', category: 'motivational', time: 'morning' },
  { text: 'La disciplina es elegir entre lo que quieres ahora y lo que más deseas.', category: 'motivational', attribution: 'Abraham Lincoln', time: 'anytime' },
  { text: 'No has llegado hasta aquí para quedarte solo aquí.', category: 'motivational', time: 'afternoon' },
  { text: 'Sueña a lo grande. Empieza poco a poco. Actúa ahora.', category: 'motivational', time: 'morning' },
  { text: 'El secreto para salir adelante es empezar.', category: 'motivational', attribution: 'Mark Twain', time: 'morning' },
  { text: 'Tu yo del futuro te observa ahora mismo a través de los recuerdos.', category: 'motivational', time: 'anytime' },
  { text: 'El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.', category: 'motivational', time: 'anytime' },
  { text: 'Progreso, no perfección.', category: 'motivational', time: 'anytime' },
  { text: 'Las dificultades a menudo preparan a personas comunes para un destino extraordinario.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'Sé tan bueno que no puedan ignorarte.', category: 'motivational', attribution: 'Steve Martin', time: 'morning' },
  { text: 'Nunca eres demasiado mayor para fijarte otra meta o soñar un nuevo sueño.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'La lucha de hoy está forjando la fuerza que necesitarás mañana.', category: 'motivational', time: 'afternoon' },
  { text: 'Haz hoy algo que tu yo del futuro te agradecerá.', category: 'motivational', time: 'morning' },
  { text: 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', category: 'motivational', attribution: 'Robert Collier', time: 'morning' },
  { text: 'Cae siete veces y levántate ocho.', category: 'motivational', time: 'anytime' },
  { text: 'Lo que hoy parece imposible algún día será tu calentamiento.', category: 'motivational', time: 'morning' },
  { text: 'No tienes que ser perfecto para ser increíble.', category: 'motivational', time: 'anytime' },
  { text: 'La acción es la clave fundamental de todo éxito.', category: 'motivational', attribution: 'Pablo Picasso', time: 'morning' },
  { text: 'La remontada siempre es más fuerte que el revés.', category: 'motivational', time: 'anytime' },
  { text: 'Dentro de un año desearás haber empezado hoy.', category: 'motivational', time: 'morning' },
  { text: 'Todo lo que siempre has deseado está al otro lado del miedo.', category: 'motivational', attribution: 'George Addair', time: 'anytime' },
  { text: 'La energía fluye hacia donde va la atención.', category: 'motivational', time: 'morning' },
  { text: 'La duda mata más sueños que el fracaso.', category: 'motivational', attribution: 'Suzy Kassem', time: 'anytime' },
  { text: 'Si fuera fácil, todo el mundo lo haría. Sigue adelante.', category: 'motivational', time: 'afternoon' },
  { text: 'Estás a una sola decisión de una vida completamente distinta.', category: 'motivational', time: 'anytime' },
  { text: 'Hecho es mejor que perfecto.', category: 'motivational', time: 'afternoon' },
  { text: 'El único límite para nuestros logros de mañana serán nuestras dudas de hoy.', category: 'motivational', attribution: 'Franklin D. Roosevelt', time: 'anytime' },
  { text: 'Las estrellas no pueden brillar sin oscuridad.', category: 'motivational', time: 'evening' },
  { text: 'El valor no es la ausencia de miedo. Es actuar a pesar de él.', category: 'motivational', attribution: 'Mark Twain', time: 'anytime' },
  { text: '¿Qué te atreverías a hacer si supieras que no puedes fracasar?', category: 'motivational', time: 'morning' },
  { text: 'La forma de empezar es dejar de hablar y ponerse a hacer.', category: 'motivational', attribution: 'Walt Disney', time: 'morning' },

  // ── Day-of-week motivation ────────────────────────────────────
  { text: 'Nueva semana, nuevas posibilidades. Haz que esta cuente.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Los lunes son para empezar de nuevo y tomar decisiones valientes.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Marca el ritmo de la semana. Tú puedes con esto.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Martes: la prueba de que sobreviviste al lunes y seguiste adelante.', category: 'compliments', time: 'morning', days: [2] },
  { text: 'A mitad de semana: estás más cerca de lo que crees.', category: 'motivational', time: 'anytime', days: [3] },
  { text: 'Miércoles, el ecuador de la semana. Lo estás haciendo genial.', category: 'compliments', time: 'afternoon', days: [3] },
  { text: 'Ya casi está. Termina la semana con fuerza.', category: 'motivational', time: 'morning', days: [4] },
  { text: 'Energía de jueves: el fin de semana ya se ve cerca.', category: 'motivational', time: 'afternoon', days: [4] },
  { text: 'Has superado la semana. Siéntete orgulloso de ti.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Feliz viernes. Te has ganado cada momento de este fin de semana.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Disfruta del fin de semana, te lo has ganado.', category: 'compliments', time: 'anytime', days: [5, 6, 0] },
  { text: 'Los sábados son para recargar energías. Haz lo que te llene.', category: 'mindfulness', time: 'morning', days: [6] },
  { text: 'Domingo: descansa, reflexiona y prepárate para brillar de nuevo.', category: 'mindfulness', time: 'morning', days: [0] },
  { text: 'Aprovecha hoy para preparar una gran semana.', category: 'motivational', time: 'afternoon', days: [0] },

  // ── Gratitude ─────────────────────────────────────────────────
  { text: '¿Cuáles son tres cosas por las que estás agradecido ahora mismo?', category: 'gratitude', time: 'morning' },
  { text: 'Tómate un momento para valorar lo lejos que has llegado.', category: 'gratitude', time: 'evening' },
  { text: 'La gratitud convierte lo que tenemos en suficiente.', category: 'gratitude', time: 'anytime' },
  { text: 'Hoy, fíjate en una pequeña cosa que te dé alegría.', category: 'gratitude', time: 'morning' },
  { text: '¿Quién te ha hecho sonreír hoy? Guarda esa sensación.', category: 'gratitude', time: 'evening' },
  { text: 'Los momentos corrientes suelen ser los más bonitos.', category: 'gratitude', time: 'anytime' },
  { text: 'Valora las lecciones que se esconden en los retos.', category: 'gratitude', time: 'anytime' },
  { text: 'Tienes mucho por lo que estar agradecido.', category: 'gratitude', time: 'anytime' },
  { text: 'Lo que el año pasado parecía imposible hoy es tu realidad.', category: 'gratitude', time: 'anytime' },
  { text: 'Que el agradecimiento sea tu estado natural.', category: 'gratitude', time: 'morning' },
  { text: 'Piensa en una palabra amable que alguien te haya dicho hace poco.', category: 'gratitude', time: 'evening' },
  { text: 'Tu vida está llena de pequeños milagros. Búscalos.', category: 'gratitude', time: 'anytime' },
  { text: 'Nombra a una persona que haya mejorado tu vida este año.', category: 'gratitude', time: 'evening' },
  { text: 'El techo que te cobija, la comida en tu mesa: no son cosas pequeñas.', category: 'gratitude', time: 'anytime' },
  { text: 'Piensa en un reto que te hizo más fuerte. Agradécelo.', category: 'gratitude', time: 'evening' },
  { text: 'La gratitud es la más sana de todas las emociones humanas.', category: 'gratitude', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: '¿Qué tienes hoy que en su día deseaste tener?', category: 'gratitude', time: 'morning' },
  { text: 'Cada amanecer es una invitación a alegrarle el día a alguien.', category: 'gratitude', time: 'morning' },
  { text: 'Hoy ha sido un regalo. ¿Cuál ha sido tu parte favorita?', category: 'gratitude', time: 'evening' },
  { text: 'Las personas de tu vida te quieren más de lo que crees.', category: 'gratitude', time: 'anytime' },
  { text: 'Fíjate en la belleza de algo que ves cada día.', category: 'gratitude', time: 'anytime' },
  { text: 'Un corazón agradecido es un imán para las cosas maravillosas.', category: 'gratitude', time: 'morning' },
  { text: '¿Qué placer sencillo has disfrutado hoy?', category: 'gratitude', time: 'evening' },
  { text: 'Recuerda: hay alguien que se inspira en ti.', category: 'gratitude', time: 'anytime' },
  { text: 'Agradezco los días soleados que me levantan el ánimo.', category: 'gratitude', time: 'anytime', weather: 'clear' },
  { text: 'Agradezco los días de lluvia que nutren la tierra.', category: 'gratitude', time: 'anytime', weather: 'rain' },

  // ── Mindfulness ───────────────────────────────────────────────
  { text: 'Respira hondo. Estás justo donde tienes que estar.', category: 'mindfulness', time: 'anytime' },
  { text: 'Vive el presente. Este momento es lo único que hay.', category: 'mindfulness', time: 'anytime' },
  { text: 'Inspira calma. Espira tensión.', category: 'mindfulness', time: 'anytime' },
  { text: 'Ve más despacio. No hay prisa por estar en otra parte.', category: 'mindfulness', time: 'evening' },
  { text: 'Fíjate en cinco cosas que puedas ver ahora mismo.', category: 'mindfulness', time: 'anytime' },
  { text: 'Suelta lo que no puedes controlar.', category: 'mindfulness', time: 'anytime' },
  { text: 'Tus pensamientos son nubes. Déjalos pasar.', category: 'mindfulness', time: 'anytime' },
  { text: 'La paz no es la ausencia de caos, es la calma interior.', category: 'mindfulness', time: 'anytime' },
  { text: 'Ahora mismo, en este instante, estás a salvo.', category: 'mindfulness', time: 'night' },
  { text: 'El silencio no está vacío, está lleno de respuestas.', category: 'mindfulness', time: 'evening' },
  { text: 'Siente los pies en el suelo. Estás firme.', category: 'mindfulness', time: 'anytime' },
  { text: 'Detente. Respira. Continúa.', category: 'mindfulness', time: 'anytime' },
  { text: 'No eres tus pensamientos. Eres la conciencia que hay tras ellos.', category: 'mindfulness', time: 'anytime' },
  { text: 'Fíjate en el espacio entre tus pensamientos. Ahí vive la paz.', category: 'mindfulness', time: 'evening' },
  { text: 'Escucha los sonidos que te rodean sin ponerles nombre.', category: 'mindfulness', time: 'anytime' },
  { text: 'Pon una mano en el pecho. Siente tus latidos. Estás vivo.', category: 'mindfulness', time: 'anytime' },
  { text: 'El momento presente es el único que existe de verdad.', category: 'mindfulness', time: 'anytime' },
  { text: '¿Dónde se aloja la tensión en tu cuerpo ahora mismo? Respira hacia ahí.', category: 'mindfulness', time: 'afternoon' },
  { text: 'Entre el estímulo y la respuesta hay un espacio. En ese espacio está tu poder.', category: 'mindfulness', attribution: 'Viktor Frankl', time: 'anytime' },
  { text: 'Inspira contando hasta cuatro. Aguanta cuatro. Espira cuatro. Repite.', category: 'mindfulness', time: 'anytime' },
  { text: 'No te adelantes a los problemas de mañana. Hoy es suficiente.', category: 'mindfulness', time: 'evening' },
  { text: 'Todo es pasajero. Lo bueno y lo difícil. Saborea y resiste.', category: 'mindfulness', time: 'anytime' },
  { text: 'No necesitas tenerlo todo resuelto. Solo da el siguiente paso.', category: 'mindfulness', time: 'anytime' },
  { text: 'Tu respiración siempre está ahí para ti. Vuelve a ella.', category: 'mindfulness', time: 'anytime' },
  { text: '¿Qué es una cosa que puedes hacer ahora mismo para cuidarte?', category: 'mindfulness', time: 'afternoon' },
  { text: 'Nada en la naturaleza florece todo el año. Ten paciencia contigo.', category: 'mindfulness', time: 'anytime' },
  { text: 'La quietud no es pereza. Así es como tu alma se pone al día.', category: 'mindfulness', time: 'evening' },
  { text: 'Tienes derecho a dejar atrás los espacios que ya no te encajan.', category: 'mindfulness', time: 'anytime' },
  { text: 'Escucha la lluvia. Deja que aquiete tus pensamientos.', category: 'mindfulness', time: 'anytime', weather: 'rain' },
  { text: 'La nieve me recuerda que hay que ir despacio y quedarse quieto.', category: 'mindfulness', time: 'anytime', weather: 'snow' },
  { text: 'Siente el calor del sol en la piel. Estás aquí.', category: 'mindfulness', time: 'anytime', weather: 'clear' },

  // ── Season-aware entries ──────────────────────────────────────
  { text: 'La primavera nos recuerda que los nuevos comienzos siempre son posibles.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'Como las flores, tú también floreces a tu propio ritmo.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'La tierra está despertando. Despierta tú con ella.', category: 'mindfulness', time: 'morning', season: 'spring' },
  { text: 'Aire nuevo, nuevos comienzos. La primavera está de tu lado.', category: 'motivational', time: 'morning', season: 'spring' },
  { text: 'Deja que el calor del verano llene tu espíritu.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Días largos, noches cálidas. Disfrútalo todo.', category: 'gratitude', time: 'evening', season: 'summer' },
  { text: 'La luz del verano te recuerda que siempre queda más día por delante.', category: 'motivational', time: 'morning', season: 'summer' },
  { text: 'El sol brilla. Deja que caliente algo más que tu piel.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Como las hojas de otoño, suelta lo que está listo para caer.', category: 'mindfulness', time: 'anytime', season: 'fall' },
  { text: 'El otoño nos enseña que soltar puede ser hermoso.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'El mundo cambia de color. Tú también tienes permiso para cambiar.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'Época de cosecha: recoge los frutos de tu esfuerzo.', category: 'gratitude', time: 'anytime', season: 'fall' },
  { text: 'Incluso en invierno, el crecimiento ocurre bajo la superficie.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'La quietud del invierno es una invitación a mirar hacia dentro.', category: 'mindfulness', time: 'evening', season: 'winter' },
  { text: 'Frío fuera, calor dentro. Cuida tu fuego interior.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'Las noches de invierno son para descansar. La primavera volverá.', category: 'mindfulness', time: 'night', season: 'winter' },

  // ── Night-specific ────────────────────────────────────────────
  { text: 'Descansa bien. Mañana es un nuevo comienzo.', category: 'affirmations', time: 'night' },
  { text: 'Hoy has hecho suficiente. Permítete dormir.', category: 'mindfulness', time: 'night' },
  { text: 'La noche es para recuperarse, no para preocuparse.', category: 'mindfulness', time: 'night' },
  { text: 'Cierra los ojos sabiendo que hoy diste lo mejor de ti.', category: 'affirmations', time: 'night' },
  { text: 'Deja que la calma de la noche serene tu mente.', category: 'mindfulness', time: 'night' },
  { text: 'Dormir no es un lujo. Así es como te recargas para lograr grandes cosas.', category: 'affirmations', time: 'night' },
  { text: 'Esta noche, suelta cada preocupación. Mañana podrás volver a intentarlo.', category: 'mindfulness', time: 'night' },

  // ── Morning-specific ──────────────────────────────────────────
  { text: 'Buenos días. Hoy está lleno de posibilidades.', category: 'affirmations', time: 'morning' },
  { text: 'La mañana es tuya. Marca tu intención y hazla tuya.', category: 'motivational', time: 'morning' },
  { text: 'Levántate y brilla, no porque tengas que hacerlo, sino porque puedes.', category: 'gratitude', time: 'morning' },
  { text: '¿Qué es una cosa que quieres sentir hoy? Camina hacia ello.', category: 'mindfulness', time: 'morning' },
  { text: 'Un nuevo día es una nueva oportunidad de crear algo maravilloso.', category: 'motivational', time: 'morning' },
  { text: 'Tu rutina matutina es un acto de amor propio.', category: 'affirmations', time: 'morning' },
];
