import type { AffirmationEntry } from './types';

// ---------------------------------------------------------------------------
// Built-in content library — fr-FR (198 entries)
// ---------------------------------------------------------------------------

export const FR_FR_AFFIRMATIONS: AffirmationEntry[] = [
  // ── Affirmations ──────────────────────────────────────────────
  { text: 'Je mérite l\'amour et la bienveillance.', category: 'affirmations', time: 'anytime' },
  { text: 'Je fais confiance au chemin, même quand je ne le vois pas.', category: 'affirmations', time: 'anytime' },
  { text: 'Je deviens la personne que je veux être.', category: 'affirmations', time: 'anytime' },
  { text: 'Mon potentiel est sans limites.', category: 'affirmations', time: 'anytime' },
  { text: 'Je me libère de ce qui ne me sert plus.', category: 'affirmations', time: 'evening' },
  { text: 'Je choisis la paix plutôt que la perfection.', category: 'affirmations', time: 'anytime' },
  { text: 'J\'ai le droit de prendre ma place.', category: 'affirmations', time: 'anytime' },
  { text: 'Je suffis, exactement tel que je suis.', category: 'affirmations', time: 'anytime' },
  { text: 'J\'attire l\'énergie positive dans ma vie.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Je suis résilient, fort et courageux.', category: 'affirmations', time: 'anytime' },
  { text: 'Je m\'autorise à me reposer.', category: 'affirmations', time: 'evening', weather: 'rain' },
  { text: 'Je respecte mes propres limites.', category: 'affirmations', time: 'anytime' },
  { text: 'Chaque revers prépare un retour.', category: 'affirmations', time: 'anytime' },
  { text: 'Je suis en paix avec qui je suis.', category: 'affirmations', time: 'night' },
  { text: 'Ma voix compte. Mon histoire compte.', category: 'affirmations', time: 'anytime' },
  { text: 'J\'accueille l\'abondance sous toutes ses formes.', category: 'affirmations', time: 'morning' },
  { text: 'Je mérite les belles choses de ma vie.', category: 'affirmations', time: 'anytime' },
  { text: 'Je me pardonne mes erreurs passées. Elles m\'ont fait grandir.', category: 'affirmations', time: 'evening' },
  { text: 'Mon corps est sain, mon esprit est vif, mon âme est calme.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Je rayonne de confiance et de respect de moi-même.', category: 'affirmations', time: 'morning' },
  { text: 'Je suis ouvert aux nouvelles aventures et expériences.', category: 'affirmations', time: 'morning' },
  { text: 'Je lâche la comparaison. Mon chemin m\'appartient.', category: 'affirmations', time: 'anytime' },
  { text: 'Je suis en construction, et c\'est très bien ainsi.', category: 'affirmations', time: 'anytime' },
  { text: 'Mes erreurs ne me définissent pas. Ma croissance, oui.', category: 'affirmations', time: 'anytime' },
  { text: 'J\'ai le pouvoir de créer la vie que je veux.', category: 'affirmations', time: 'morning' },
  { text: 'Je choisis de me concentrer sur ce que je peux changer.', category: 'affirmations', time: 'anytime' },
  { text: 'Je suis entouré d\'amour, même quand je ne le sens pas.', category: 'affirmations', time: 'night' },
  { text: 'Aujourd\'hui, je serai bienveillant envers moi-même.', category: 'affirmations', time: 'morning' },
  { text: 'Je suis plus fort que mes doutes.', category: 'affirmations', time: 'anytime' },
  { text: 'Mon bonheur est ma responsabilité, et je l\'assume pleinement.', category: 'affirmations', time: 'anytime' },
  { text: 'La pluie emporte ce dont je n\'ai plus besoin.', category: 'affirmations', time: 'anytime', weather: 'rain' },
  { text: 'Je trouve de la beauté dans chaque ciel.', category: 'affirmations', time: 'anytime', weather: 'clouds' },

  // ── Compliments ───────────────────────────────────────────────
  { text: 'Tu illumines chaque pièce où tu entres.', category: 'compliments', time: 'anytime' },
  { text: 'Ton sourire est contagieux, ne cesse jamais de le partager.', category: 'compliments', time: 'morning' },
  { text: 'Tu as le don de faire sentir aux autres qu\'ils existent.', category: 'compliments', time: 'anytime' },
  { text: 'Le monde est meilleur parce que tu en fais partie.', category: 'compliments', time: 'anytime' },
  { text: 'Ta gentillesse se propage plus loin que tu ne l\'imagines.', category: 'compliments', time: 'anytime' },
  { text: 'Tu affrontes les défis avec une grâce remarquable.', category: 'compliments', time: 'afternoon' },
  { text: 'Les gens ont de la chance de te connaître.', category: 'compliments', time: 'anytime' },
  { text: 'Ton énergie est magnétique.', category: 'compliments', time: 'anytime' },
  { text: 'Tu rends faciles les choses difficiles.', category: 'compliments', time: 'afternoon' },
  { text: 'Tu as un goût incroyable.', category: 'compliments', time: 'anytime' },
  { text: 'Ta créativité inspire tout le monde autour de toi.', category: 'compliments', time: 'anytime' },
  { text: 'Tu fais ressortir le meilleur des gens.', category: 'compliments', time: 'anytime' },
  { text: 'Tu mérites toutes les belles choses qui viennent à toi.', category: 'compliments', time: 'anytime' },
  { text: 'Ton rire est le plus beau des sons.', category: 'compliments', time: 'anytime' },
  { text: 'Tu fais un travail formidable.', category: 'compliments', time: 'afternoon' },
  { text: 'Ta patience est un superpouvoir.', category: 'compliments', time: 'afternoon' },
  { text: 'Tu as une belle façon de regarder le monde.', category: 'compliments', time: 'anytime' },
  { text: 'Ta détermination est inspirante.', category: 'compliments', time: 'anytime' },
  { text: 'Tu fais sentir aux gens qu\'ils sont en sécurité et appréciés.', category: 'compliments', time: 'anytime' },
  { text: 'Tu as le courage d\'être toi-même, et c\'est rare.', category: 'compliments', time: 'anytime' },
  { text: 'Ton regard est unique et il compte.', category: 'compliments', time: 'anytime' },
  { text: 'Tu guides avec empathie et cela se voit.', category: 'compliments', time: 'afternoon' },
  { text: 'Personne n\'est tout à fait comme toi. C\'est ta force.', category: 'compliments', time: 'anytime' },
  { text: 'Tu dégages une confiance tranquille.', category: 'compliments', time: 'anytime' },
  { text: 'Les efforts que tu fournis ne passent pas inaperçus.', category: 'compliments', time: 'afternoon' },
  { text: 'Ton cœur est plus grand que tu ne le crois.', category: 'compliments', time: 'evening' },
  { text: 'Tu as un bon instinct. Fais-lui davantage confiance.', category: 'compliments', time: 'anytime' },
  { text: 'Ton enthousiasme est communicatif.', category: 'compliments', time: 'morning' },
  { text: 'Tu gères la pression mieux que tu ne le penses.', category: 'compliments', time: 'afternoon' },
  { text: 'Tu es quelqu\'un sur qui on peut compter.', category: 'compliments', time: 'anytime' },

  // ── Motivational ──────────────────────────────────────────────
  { text: 'Commence là où tu es. Utilise ce que tu as. Fais ce que tu peux.', category: 'motivational', attribution: 'Arthur Ashe', time: 'morning' },
  { text: 'La seule façon de faire du bon travail est d\'aimer ce que l\'on fait.', category: 'motivational', attribution: 'Steve Jobs', time: 'morning' },
  { text: 'Peu importe la lenteur avec laquelle tu avances, tant que tu ne t\'arrêtes pas.', category: 'motivational', attribution: 'Confucius', time: 'anytime' },
  { text: 'Ce que tu obtiens en atteignant tes objectifs compte moins que ce que tu deviens.', category: 'motivational', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Crois que tu en es capable et tu as déjà fait la moitié du chemin.', category: 'motivational', attribution: 'Theodore Roosevelt', time: 'morning' },
  { text: 'De petits progrès quotidiens sont la clé de résultats spectaculaires à long terme.', category: 'motivational', time: 'morning' },
  { text: 'La discipline, c\'est choisir entre ce que tu veux maintenant et ce que tu veux le plus.', category: 'motivational', attribution: 'Abraham Lincoln', time: 'anytime' },
  { text: 'Tu n\'es pas allé si loin pour t\'arrêter en si bon chemin.', category: 'motivational', time: 'afternoon' },
  { text: 'Rêve grand. Commence petit. Agis maintenant.', category: 'motivational', time: 'morning' },
  { text: 'Le secret pour avancer, c\'est de commencer.', category: 'motivational', attribution: 'Mark Twain', time: 'morning' },
  { text: 'La personne que tu seras demain t\'observe en ce moment à travers ses souvenirs.', category: 'motivational', time: 'anytime' },
  { text: 'Le meilleur moment pour planter un arbre était il y a 20 ans. Le deuxième meilleur, c\'est maintenant.', category: 'motivational', time: 'anytime' },
  { text: 'Le progrès, pas la perfection.', category: 'motivational', time: 'anytime' },
  { text: 'Les épreuves préparent souvent des gens ordinaires à un destin extraordinaire.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'Sois si bon qu\'ils ne pourront pas t\'ignorer.', category: 'motivational', attribution: 'Steve Martin', time: 'morning' },
  { text: 'On n\'est jamais trop vieux pour se fixer un nouvel objectif ou rêver un nouveau rêve.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'Le combat que tu mènes aujourd\'hui forge la force dont tu auras besoin demain.', category: 'motivational', time: 'afternoon' },
  { text: 'Fais aujourd\'hui quelque chose dont tu te remercieras demain.', category: 'motivational', time: 'morning' },
  { text: 'Le succès est la somme de petits efforts répétés jour après jour.', category: 'motivational', attribution: 'Robert Collier', time: 'morning' },
  { text: 'Tombe sept fois, relève-toi huit.', category: 'motivational', time: 'anytime' },
  { text: 'Ce qui semble impossible aujourd\'hui deviendra un jour ton échauffement.', category: 'motivational', time: 'morning' },
  { text: 'Tu n\'as pas besoin d\'être parfait pour être formidable.', category: 'motivational', time: 'anytime' },
  { text: 'L\'action est la clé fondamentale de toute réussite.', category: 'motivational', attribution: 'Pablo Picasso', time: 'morning' },
  { text: 'Le retour est toujours plus fort que la chute.', category: 'motivational', time: 'anytime' },
  { text: 'Dans un an, tu regretteras de ne pas avoir commencé aujourd\'hui.', category: 'motivational', time: 'morning' },
  { text: 'Tout ce que tu as toujours voulu se trouve de l\'autre côté de la peur.', category: 'motivational', attribution: 'George Addair', time: 'anytime' },
  { text: 'L\'énergie va là où va l\'attention.', category: 'motivational', time: 'morning' },
  { text: 'Le doute tue plus de rêves que l\'échec ne le fera jamais.', category: 'motivational', attribution: 'Suzy Kassem', time: 'anytime' },
  { text: 'Si c\'était facile, tout le monde le ferait. Continue.', category: 'motivational', time: 'afternoon' },
  { text: 'Une seule décision te sépare d\'une vie complètement différente.', category: 'motivational', time: 'anytime' },
  { text: 'Fait vaut mieux que parfait.', category: 'motivational', time: 'afternoon' },
  { text: 'La seule limite à nos réalisations de demain sera nos doutes d\'aujourd\'hui.', category: 'motivational', attribution: 'Franklin D. Roosevelt', time: 'anytime' },
  { text: 'Les étoiles ne peuvent briller sans l\'obscurité.', category: 'motivational', time: 'evening' },
  { text: 'Le courage n\'est pas l\'absence de peur. C\'est agir malgré elle.', category: 'motivational', attribution: 'Mark Twain', time: 'anytime' },
  { text: 'Qu\'essaierais-tu de faire si tu savais que tu ne pouvais pas échouer ?', category: 'motivational', time: 'morning' },
  { text: 'Pour commencer, il faut cesser de parler et se mettre à agir.', category: 'motivational', attribution: 'Walt Disney', time: 'morning' },

  // ── Day-of-week motivation ────────────────────────────────────
  { text: 'Nouvelle semaine, nouvelles possibilités. Fais que celle-ci compte.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Le lundi est fait pour les nouveaux départs et les décisions audacieuses.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Donne le ton de la semaine. Tu vas y arriver.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Mardi : la preuve que tu as survécu à lundi et que tu continues.', category: 'compliments', time: 'morning', days: [2] },
  { text: 'Petit bilan de mi-semaine : tu es plus près que tu ne le crois.', category: 'motivational', time: 'anytime', days: [3] },
  { text: 'Mercredi, la moitié du chemin. Tu t\'en sors très bien.', category: 'compliments', time: 'afternoon', days: [3] },
  { text: 'Presque au bout. Termine la semaine en force.', category: 'motivational', time: 'morning', days: [4] },
  { text: 'Énergie du jeudi : le week-end est en vue.', category: 'motivational', time: 'afternoon', days: [4] },
  { text: 'Tu as tenu toute la semaine. Sois fier de toi.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Bon vendredi. Tu as mérité chaque instant de ce week-end.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Profite du week-end, tu l\'as bien mérité.', category: 'compliments', time: 'anytime', days: [5, 6, 0] },
  { text: 'Le samedi est fait pour se ressourcer. Fais ce qui te remplit de joie.', category: 'mindfulness', time: 'morning', days: [6] },
  { text: 'Dimanche : repose-toi, réfléchis et prépare-toi à briller de nouveau.', category: 'mindfulness', time: 'morning', days: [0] },
  { text: 'Profite d\'aujourd\'hui pour préparer une belle semaine à venir.', category: 'motivational', time: 'afternoon', days: [0] },

  // ── Gratitude ─────────────────────────────────────────────────
  { text: 'Quelles sont trois choses pour lesquelles tu es reconnaissant en ce moment ?', category: 'gratitude', time: 'morning' },
  { text: 'Prends un instant pour apprécier le chemin parcouru.', category: 'gratitude', time: 'evening' },
  { text: 'La gratitude rend suffisant ce que nous avons.', category: 'gratitude', time: 'anytime' },
  { text: 'Aujourd\'hui, remarque une petite chose qui t\'apporte de la joie.', category: 'gratitude', time: 'morning' },
  { text: 'Qui t\'a fait sourire aujourd\'hui ? Garde ce sentiment.', category: 'gratitude', time: 'evening' },
  { text: 'Les moments ordinaires sont souvent les plus beaux.', category: 'gratitude', time: 'anytime' },
  { text: 'Apprécie les leçons cachées dans les épreuves.', category: 'gratitude', time: 'anytime' },
  { text: 'Tu as tant de raisons d\'être reconnaissant.', category: 'gratitude', time: 'anytime' },
  { text: 'Ce qui semblait impossible l\'an dernier est ta réalité aujourd\'hui.', category: 'gratitude', time: 'anytime' },
  { text: 'Fais de la gratitude ton état par défaut.', category: 'gratitude', time: 'morning' },
  { text: 'Repense à un mot gentil qu\'on t\'a dit récemment.', category: 'gratitude', time: 'evening' },
  { text: 'Ta vie est pleine de petits miracles discrets. Cherche-les.', category: 'gratitude', time: 'anytime' },
  { text: 'Nomme une personne qui a amélioré ta vie cette année.', category: 'gratitude', time: 'evening' },
  { text: 'Le toit au-dessus de ta tête, la nourriture sur ta table : ce ne sont pas de petites choses.', category: 'gratitude', time: 'anytime' },
  { text: 'Pense à une épreuve qui t\'a rendu plus fort. Sois-en reconnaissant.', category: 'gratitude', time: 'evening' },
  { text: 'La gratitude est la plus saine de toutes les émotions humaines.', category: 'gratitude', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Quelle chose que tu possèdes aujourd\'hui as-tu autrefois désirée ?', category: 'gratitude', time: 'morning' },
  { text: 'Chaque lever de soleil est une invitation à égayer la journée de quelqu\'un.', category: 'gratitude', time: 'morning' },
  { text: 'Aujourd\'hui était un cadeau. Quel a été ton moment préféré ?', category: 'gratitude', time: 'evening' },
  { text: 'Les gens de ta vie t\'aiment plus que tu ne l\'imagines.', category: 'gratitude', time: 'anytime' },
  { text: 'Remarque la beauté d\'une chose que tu vois chaque jour.', category: 'gratitude', time: 'anytime' },
  { text: 'Un cœur reconnaissant attire les merveilles.', category: 'gratitude', time: 'morning' },
  { text: 'Quel plaisir simple as-tu savouré aujourd\'hui ?', category: 'gratitude', time: 'evening' },
  { text: 'Souviens-toi : quelque part, quelqu\'un s\'inspire de toi.', category: 'gratitude', time: 'anytime' },
  { text: 'Je suis reconnaissant pour les journées ensoleillées qui me remontent le moral.', category: 'gratitude', time: 'anytime', weather: 'clear' },
  { text: 'Je suis reconnaissant pour les jours de pluie qui nourrissent la terre.', category: 'gratitude', time: 'anytime', weather: 'rain' },

  // ── Mindfulness ───────────────────────────────────────────────
  { text: 'Respire profondément. Tu es exactement là où tu dois être.', category: 'mindfulness', time: 'anytime' },
  { text: 'Sois présent. Cet instant est tout ce qui existe.', category: 'mindfulness', time: 'anytime' },
  { text: 'Inspire le calme. Expire la tension.', category: 'mindfulness', time: 'anytime' },
  { text: 'Ralentis. Rien ne presse d\'être ailleurs.', category: 'mindfulness', time: 'evening' },
  { text: 'Remarque cinq choses que tu peux voir en ce moment.', category: 'mindfulness', time: 'anytime' },
  { text: 'Lâche prise sur ce que tu ne peux pas contrôler.', category: 'mindfulness', time: 'anytime' },
  { text: 'Tes pensées sont des nuages. Laisse-les passer.', category: 'mindfulness', time: 'anytime' },
  { text: 'La paix n\'est pas l\'absence de chaos, c\'est le calme intérieur.', category: 'mindfulness', time: 'anytime' },
  { text: 'En ce moment précis, tu es en sécurité.', category: 'mindfulness', time: 'night' },
  { text: 'Le silence n\'est pas vide, il est plein de réponses.', category: 'mindfulness', time: 'evening' },
  { text: 'Sens tes pieds sur le sol. Tu es ancré.', category: 'mindfulness', time: 'anytime' },
  { text: 'Pause. Respire. Continue.', category: 'mindfulness', time: 'anytime' },
  { text: 'Tu n\'es pas tes pensées. Tu es la conscience qui les observe.', category: 'mindfulness', time: 'anytime' },
  { text: 'Remarque l\'espace entre tes pensées. C\'est là que vit la paix.', category: 'mindfulness', time: 'evening' },
  { text: 'Écoute les sons autour de toi sans les nommer.', category: 'mindfulness', time: 'anytime' },
  { text: 'Pose une main sur ta poitrine. Sens ton cœur battre. Tu es vivant.', category: 'mindfulness', time: 'anytime' },
  { text: 'Le moment présent est le seul qui existe vraiment.', category: 'mindfulness', time: 'anytime' },
  { text: 'Où se loge la tension dans ton corps en ce moment ? Respire à cet endroit.', category: 'mindfulness', time: 'afternoon' },
  { text: 'Entre le stimulus et la réponse, il y a un espace. Dans cet espace réside ton pouvoir.', category: 'mindfulness', attribution: 'Viktor Frankl', time: 'anytime' },
  { text: 'Inspire sur quatre temps. Retiens sur quatre. Expire sur quatre. Recommence.', category: 'mindfulness', time: 'anytime' },
  { text: 'N\'emprunte pas les soucis de demain. Aujourd\'hui suffit.', category: 'mindfulness', time: 'evening' },
  { text: 'Tout est temporaire. Le bon comme le difficile. Savoure et endure.', category: 'mindfulness', time: 'anytime' },
  { text: 'Tu n\'as pas besoin de tout comprendre. Fais simplement le prochain pas.', category: 'mindfulness', time: 'anytime' },
  { text: 'Ta respiration est toujours là pour toi. Reviens-y.', category: 'mindfulness', time: 'anytime' },
  { text: 'Quelle est une chose que tu peux faire maintenant pour prendre soin de toi ?', category: 'mindfulness', time: 'afternoon' },
  { text: 'Rien dans la nature ne fleurit toute l\'année. Sois patient avec toi-même.', category: 'mindfulness', time: 'anytime' },
  { text: 'L\'immobilité n\'est pas de la paresse. C\'est ainsi que ton âme se ressource.', category: 'mindfulness', time: 'evening' },
  { text: 'Tu as le droit de quitter les espaces qui ne te conviennent plus.', category: 'mindfulness', time: 'anytime' },
  { text: 'Écoute la pluie. Laisse-la apaiser tes pensées.', category: 'mindfulness', time: 'anytime', weather: 'rain' },
  { text: 'La neige me rappelle de ralentir et de rester tranquille.', category: 'mindfulness', time: 'anytime', weather: 'snow' },
  { text: 'Sens la chaleur du soleil sur ta peau. Tu es là.', category: 'mindfulness', time: 'anytime', weather: 'clear' },

  // ── Season-aware entries ──────────────────────────────────────
  { text: 'Le printemps nous rappelle que de nouveaux départs sont toujours possibles.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'Comme les fleurs, tu t\'épanouis toi aussi à ton propre rythme.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'La terre se réveille. Réveille-toi avec elle.', category: 'mindfulness', time: 'morning', season: 'spring' },
  { text: 'Air frais, nouveaux départs. Le printemps est de ton côté.', category: 'motivational', time: 'morning', season: 'spring' },
  { text: 'Laisse la chaleur de l\'été emplir ton âme.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Longues journées, nuits douces. Savoure tout cela.', category: 'gratitude', time: 'evening', season: 'summer' },
  { text: 'La lumière de l\'été te rappelle qu\'il reste toujours du jour devant toi.', category: 'motivational', time: 'morning', season: 'summer' },
  { text: 'Le soleil brille. Laisse-le réchauffer plus que ta peau.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Comme les feuilles d\'automne, laisse partir ce qui est prêt à tomber.', category: 'mindfulness', time: 'anytime', season: 'fall' },
  { text: 'L\'automne nous apprend que lâcher prise peut être beau.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'Le monde change de couleurs. Tu as le droit de changer aussi.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'Saison des récoltes : cueille les fruits de ton travail.', category: 'gratitude', time: 'anytime', season: 'fall' },
  { text: 'Même en hiver, la croissance se poursuit sous la surface.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'Le calme de l\'hiver est une invitation à se tourner vers soi.', category: 'mindfulness', time: 'evening', season: 'winter' },
  { text: 'Froid dehors, chaleur dedans. Entretiens ton feu intérieur.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'Les nuits d\'hiver sont faites pour le repos. Le printemps reviendra.', category: 'mindfulness', time: 'night', season: 'winter' },

  // ── Night-specific ────────────────────────────────────────────
  { text: 'Repose-toi bien. Demain est un nouveau départ.', category: 'affirmations', time: 'night' },
  { text: 'Tu as accompli assez aujourd\'hui. Autorise-toi à dormir.', category: 'mindfulness', time: 'night' },
  { text: 'La nuit est faite pour récupérer, pas pour s\'inquiéter.', category: 'mindfulness', time: 'night' },
  { text: 'Ferme les yeux en sachant que tu as fait de ton mieux aujourd\'hui.', category: 'affirmations', time: 'night' },
  { text: 'Laisse le calme de la nuit apaiser ton esprit.', category: 'mindfulness', time: 'night' },
  { text: 'Le sommeil n\'est pas un luxe. C\'est ainsi que tu recharges tes forces.', category: 'affirmations', time: 'night' },
  { text: 'Ce soir, libère-toi de chaque souci. Demain, tu pourras réessayer.', category: 'mindfulness', time: 'night' },

  // ── Morning-specific ──────────────────────────────────────────
  { text: 'Bonjour. Aujourd\'hui est plein de possibilités.', category: 'affirmations', time: 'morning' },
  { text: 'Le matin t\'appartient. Fixe ton intention et assume-la.', category: 'motivational', time: 'morning' },
  { text: 'Lève-toi et brille, non parce qu\'il le faut, mais parce que tu en as la chance.', category: 'gratitude', time: 'morning' },
  { text: 'Quelle émotion veux-tu ressentir aujourd\'hui ? Avance vers elle.', category: 'mindfulness', time: 'morning' },
  { text: 'Un nouveau jour, c\'est une nouvelle occasion de créer quelque chose de merveilleux.', category: 'motivational', time: 'morning' },
  { text: 'Ta routine du matin est un acte d\'amour de soi.', category: 'affirmations', time: 'morning' },
];
