import type { AffirmationEntry } from './types';

// ---------------------------------------------------------------------------
// Built-in content library — nl-NL (198 entries)
// ---------------------------------------------------------------------------

export const NL_NL_AFFIRMATIONS: AffirmationEntry[] = [
  // ── Affirmations ──────────────────────────────────────────────
  { text: 'Ik ben liefde en vriendelijkheid waard.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik vertrouw op de reis, ook als ik het pad niet kan zien.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik word de persoon die ik wil zijn.', category: 'affirmations', time: 'anytime' },
  { text: 'Mijn mogelijkheden zijn grenzeloos.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik laat los wat me niet langer dient.', category: 'affirmations', time: 'evening' },
  { text: 'Ik kies voor rust boven perfectie.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik mag ruimte innemen.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik ben genoeg, precies zoals ik ben.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik trek positieve energie aan in mijn leven.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Ik ben veerkrachtig, sterk en moedig.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik geef mezelf toestemming om te rusten.', category: 'affirmations', time: 'evening', weather: 'rain' },
  { text: 'Ik respecteer mijn eigen grenzen.', category: 'affirmations', time: 'anytime' },
  { text: 'Elke tegenslag is de aanzet tot een comeback.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik ben in vrede met wie ik ben.', category: 'affirmations', time: 'night' },
  { text: 'Mijn stem telt. Mijn verhaal telt.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik verwelkom overvloed in al haar vormen.', category: 'affirmations', time: 'morning' },
  { text: 'Ik verdien de goede dingen in mijn leven.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik vergeef mezelf mijn fouten uit het verleden. Ze hielpen me groeien.', category: 'affirmations', time: 'evening' },
  { text: 'Mijn lichaam is gezond, mijn geest is scherp, mijn ziel is kalm.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Ik straal zelfvertrouwen en zelfrespect uit.', category: 'affirmations', time: 'morning' },
  { text: 'Ik sta open voor nieuwe avonturen en ervaringen.', category: 'affirmations', time: 'morning' },
  { text: 'Ik laat vergelijken los. Mijn pad is van mij.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik ben nog in ontwikkeling, en dat is helemaal prima.', category: 'affirmations', time: 'anytime' },
  { text: 'Mijn fouten bepalen niet wie ik ben. Mijn groei wel.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik heb de kracht om het leven te creëren dat ik wil.', category: 'affirmations', time: 'morning' },
  { text: 'Ik kies ervoor om me te richten op wat ik kan veranderen.', category: 'affirmations', time: 'anytime' },
  { text: 'Ik word omringd door liefde, ook als ik het niet kan voelen.', category: 'affirmations', time: 'night' },
  { text: 'Vandaag ben ik lief voor mezelf.', category: 'affirmations', time: 'morning' },
  { text: 'Ik ben sterker dan mijn twijfels.', category: 'affirmations', time: 'anytime' },
  { text: 'Mijn geluk is mijn verantwoordelijkheid, en die omarm ik.', category: 'affirmations', time: 'anytime' },
  { text: 'De regen spoelt weg wat ik niet meer nodig heb.', category: 'affirmations', time: 'anytime', weather: 'rain' },
  { text: 'Ik vind schoonheid in elke soort lucht.', category: 'affirmations', time: 'anytime', weather: 'clouds' },

  // ── Compliments ───────────────────────────────────────────────
  { text: 'Je verlicht elke kamer die je binnenloopt.', category: 'compliments', time: 'anytime' },
  { text: 'Je glimlach is aanstekelijk, blijf hem delen.', category: 'compliments', time: 'morning' },
  { text: 'Je hebt een gave om anderen zich gezien te laten voelen.', category: 'compliments', time: 'anytime' },
  { text: 'De wereld is beter omdat jij erin bent.', category: 'compliments', time: 'anytime' },
  { text: 'Je vriendelijkheid reikt verder dan je beseft.', category: 'compliments', time: 'anytime' },
  { text: 'Je gaat met uitdagingen om met opmerkelijke gratie.', category: 'compliments', time: 'afternoon' },
  { text: 'Mensen mogen blij zijn dat ze je kennen.', category: 'compliments', time: 'anytime' },
  { text: 'Je energie is magnetisch.', category: 'compliments', time: 'anytime' },
  { text: 'Je laat moeilijke dingen makkelijk lijken.', category: 'compliments', time: 'afternoon' },
  { text: 'Je hebt een geweldige smaak.', category: 'compliments', time: 'anytime' },
  { text: 'Je creativiteit inspireert iedereen om je heen.', category: 'compliments', time: 'anytime' },
  { text: 'Je haalt het beste in mensen naar boven.', category: 'compliments', time: 'anytime' },
  { text: 'Je verdient al het moois dat op je pad komt.', category: 'compliments', time: 'anytime' },
  { text: 'Je lach is het mooiste geluid.', category: 'compliments', time: 'anytime' },
  { text: 'Je doet het geweldig.', category: 'compliments', time: 'afternoon' },
  { text: 'Je geduld is een superkracht.', category: 'compliments', time: 'afternoon' },
  { text: 'Je hebt een prachtige manier om naar de wereld te kijken.', category: 'compliments', time: 'anytime' },
  { text: 'Je vastberadenheid is inspirerend.', category: 'compliments', time: 'anytime' },
  { text: 'Je laat mensen zich veilig en gewaardeerd voelen.', category: 'compliments', time: 'anytime' },
  { text: 'Je hebt de moed om jezelf te zijn, en dat is zeldzaam.', category: 'compliments', time: 'anytime' },
  { text: 'Jouw kijk is uniek en die telt.', category: 'compliments', time: 'anytime' },
  { text: 'Je leidt met empathie en dat is te zien.', category: 'compliments', time: 'afternoon' },
  { text: 'Er is niemand anders zoals jij. Dat is je kracht.', category: 'compliments', time: 'anytime' },
  { text: 'Er gaat een rustige zelfverzekerdheid van je uit.', category: 'compliments', time: 'anytime' },
  { text: 'De moeite die je erin stopt blijft niet onopgemerkt.', category: 'compliments', time: 'afternoon' },
  { text: 'Je hart is groter dan je jezelf toedicht.', category: 'compliments', time: 'evening' },
  { text: 'Je instinct zit goed. Vertrouw er vaker op.', category: 'compliments', time: 'anytime' },
  { text: 'Je enthousiasme is aanstekelijk.', category: 'compliments', time: 'morning' },
  { text: 'Je gaat beter met druk om dan je denkt.', category: 'compliments', time: 'afternoon' },
  { text: 'Je bent iemand op wie mensen kunnen rekenen.', category: 'compliments', time: 'anytime' },

  // ── Motivational ──────────────────────────────────────────────
  { text: 'Begin waar je bent. Gebruik wat je hebt. Doe wat je kunt.', category: 'motivational', attribution: 'Arthur Ashe', time: 'morning' },
  { text: 'De enige manier om geweldig werk te doen is houden van wat je doet.', category: 'motivational', attribution: 'Steve Jobs', time: 'morning' },
  { text: 'Het maakt niet uit hoe langzaam je gaat, zolang je maar niet stopt.', category: 'motivational', attribution: 'Confucius', time: 'anytime' },
  { text: 'Wat je bereikt met je doelen is minder belangrijk dan wat je erdoor wordt.', category: 'motivational', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Geloof dat je het kunt en je bent al halverwege.', category: 'motivational', attribution: 'Theodore Roosevelt', time: 'morning' },
  { text: 'Kleine dagelijkse verbeteringen zijn de sleutel tot verbluffende resultaten op lange termijn.', category: 'motivational', time: 'morning' },
  { text: 'Discipline is kiezen tussen wat je nu wilt en wat je het meest wilt.', category: 'motivational', attribution: 'Abraham Lincoln', time: 'anytime' },
  { text: 'Je bent niet zover gekomen om alleen maar zover te komen.', category: 'motivational', time: 'afternoon' },
  { text: 'Droom groot. Begin klein. Doe het nu.', category: 'motivational', time: 'morning' },
  { text: 'Het geheim van vooruitkomen is beginnen.', category: 'motivational', attribution: 'Mark Twain', time: 'morning' },
  { text: 'Je toekomstige zelf kijkt op dit moment naar je via herinneringen.', category: 'motivational', time: 'anytime' },
  { text: 'De beste tijd om een boom te planten was 20 jaar geleden. De op een na beste tijd is nu.', category: 'motivational', time: 'anytime' },
  { text: 'Vooruitgang, geen perfectie.', category: 'motivational', time: 'anytime' },
  { text: 'Ontberingen bereiden gewone mensen vaak voor op een buitengewone bestemming.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'Wees zo goed dat ze je niet kunnen negeren.', category: 'motivational', attribution: 'Steve Martin', time: 'morning' },
  { text: 'Je bent nooit te oud om een nieuw doel te stellen of een nieuwe droom te dromen.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'De strijd die je vandaag voert bouwt de kracht op die je morgen nodig hebt.', category: 'motivational', time: 'afternoon' },
  { text: 'Doe vandaag iets waar je toekomstige zelf je dankbaar voor zal zijn.', category: 'motivational', time: 'morning' },
  { text: 'Succes is de som van kleine inspanningen, dag in dag uit herhaald.', category: 'motivational', attribution: 'Robert Collier', time: 'morning' },
  { text: 'Val zeven keer, sta acht keer op.', category: 'motivational', time: 'anytime' },
  { text: 'Wat vandaag onmogelijk lijkt, wordt ooit je warming-up.', category: 'motivational', time: 'morning' },
  { text: 'Je hoeft niet perfect te zijn om geweldig te zijn.', category: 'motivational', time: 'anytime' },
  { text: 'Actie is de fundamentele sleutel tot alle succes.', category: 'motivational', attribution: 'Pablo Picasso', time: 'morning' },
  { text: 'De comeback is altijd sterker dan de tegenslag.', category: 'motivational', time: 'anytime' },
  { text: 'Over een jaar zul je willen dat je vandaag begonnen was.', category: 'motivational', time: 'morning' },
  { text: 'Alles wat je ooit hebt gewild ligt aan de andere kant van je angst.', category: 'motivational', attribution: 'George Addair', time: 'anytime' },
  { text: 'Energie stroomt waar aandacht heen gaat.', category: 'motivational', time: 'morning' },
  { text: 'Twijfel doodt meer dromen dan mislukking ooit zal doen.', category: 'motivational', attribution: 'Suzy Kassem', time: 'anytime' },
  { text: 'Als het makkelijk was, deed iedereen het. Ga door.', category: 'motivational', time: 'afternoon' },
  { text: 'Je bent één beslissing verwijderd van een compleet ander leven.', category: 'motivational', time: 'anytime' },
  { text: 'Klaar is beter dan perfect.', category: 'motivational', time: 'afternoon' },
  { text: 'De enige grens aan onze verwezenlijking van morgen zijn onze twijfels van vandaag.', category: 'motivational', attribution: 'Franklin D. Roosevelt', time: 'anytime' },
  { text: 'Sterren kunnen niet schijnen zonder duisternis.', category: 'motivational', time: 'evening' },
  { text: 'Moed is niet de afwezigheid van angst. Het is handelen ondanks die angst.', category: 'motivational', attribution: 'Mark Twain', time: 'anytime' },
  { text: 'Wat zou je proberen te doen als je wist dat je niet kon falen?', category: 'motivational', time: 'morning' },
  { text: 'De manier om te beginnen is stoppen met praten en beginnen met doen.', category: 'motivational', attribution: 'Walt Disney', time: 'morning' },

  // ── Day-of-week motivation ────────────────────────────────────
  { text: 'Nieuwe week, nieuwe kansen. Maak er iets moois van.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Maandagen zijn er voor frisse starts en gedurfde stappen.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Zet de toon voor de week. Jij kunt dit.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Dinsdag: het bewijs dat je maandag hebt overleefd en bent doorgegaan.', category: 'compliments', time: 'morning', days: [2] },
  { text: 'Halverwege de week: je bent dichterbij dan je denkt.', category: 'motivational', time: 'anytime', days: [3] },
  { text: 'Woensdag, het halverwegepunt. Je doet het geweldig.', category: 'compliments', time: 'afternoon', days: [3] },
  { text: 'Bijna zover. Maak de week sterk af.', category: 'motivational', time: 'morning', days: [4] },
  { text: 'Donderdagenergie: het weekend is in zicht.', category: 'motivational', time: 'afternoon', days: [4] },
  { text: 'Je hebt de week doorstaan. Wees trots op jezelf.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Fijne vrijdag. Je hebt elk stukje van dit weekend verdiend.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Geniet van het weekend, je hebt het verdiend.', category: 'compliments', time: 'anytime', days: [5, 6, 0] },
  { text: 'Zaterdagen zijn om op te laden. Doe wat jou energie geeft.', category: 'mindfulness', time: 'morning', days: [6] },
  { text: 'Zondag: rust, reflecteer en maak je klaar om weer te stralen.', category: 'mindfulness', time: 'morning', days: [0] },
  { text: 'Gebruik vandaag om je klaar te maken voor een geweldige week.', category: 'motivational', time: 'afternoon', days: [0] },

  // ── Gratitude ─────────────────────────────────────────────────
  { text: 'Wat zijn drie dingen waar je nu dankbaar voor bent?', category: 'gratitude', time: 'morning' },
  { text: 'Neem even de tijd om te waarderen hoe ver je bent gekomen.', category: 'gratitude', time: 'evening' },
  { text: 'Dankbaarheid maakt van wat we hebben genoeg.', category: 'gratitude', time: 'anytime' },
  { text: 'Merk vandaag één klein ding op dat je vreugde brengt.', category: 'gratitude', time: 'morning' },
  { text: 'Wie liet je vandaag glimlachen? Houd dat gevoel vast.', category: 'gratitude', time: 'evening' },
  { text: 'De gewone momenten zijn vaak het mooist.', category: 'gratitude', time: 'anytime' },
  { text: 'Waardeer de lessen die verborgen zitten in uitdagingen.', category: 'gratitude', time: 'anytime' },
  { text: 'Je hebt zoveel om dankbaar voor te zijn.', category: 'gratitude', time: 'anytime' },
  { text: 'Wat vorig jaar onmogelijk voelde is vandaag je werkelijkheid.', category: 'gratitude', time: 'anytime' },
  { text: 'Laat dankbaarheid je standaardinstelling zijn.', category: 'gratitude', time: 'morning' },
  { text: 'Denk terug aan een lief woord dat iemand onlangs tegen je zei.', category: 'gratitude', time: 'evening' },
  { text: 'Je leven zit vol stille wonderen. Zoek ze op.', category: 'gratitude', time: 'anytime' },
  { text: 'Noem één persoon die je leven dit jaar beter maakte.', category: 'gratitude', time: 'evening' },
  { text: 'Het dak boven je hoofd, het eten op je tafel, dat zijn geen kleine dingen.', category: 'gratitude', time: 'anytime' },
  { text: 'Denk aan een uitdaging die je sterker maakte. Wees er dankbaar voor.', category: 'gratitude', time: 'evening' },
  { text: 'Dankbaarheid is de gezondste van alle menselijke emoties.', category: 'gratitude', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Wat heb je vandaag dat je ooit hebt gewenst?', category: 'gratitude', time: 'morning' },
  { text: 'Elke zonsopgang is een uitnodiging om iemands dag op te fleuren.', category: 'gratitude', time: 'morning' },
  { text: 'Vandaag was een cadeau. Wat was je favoriete deel?', category: 'gratitude', time: 'evening' },
  { text: 'De mensen in je leven houden meer van je dan je beseft.', category: 'gratitude', time: 'anytime' },
  { text: 'Merk de schoonheid op in iets dat je elke dag ziet.', category: 'gratitude', time: 'anytime' },
  { text: 'Een dankbaar hart is een magneet voor prachtige dingen.', category: 'gratitude', time: 'morning' },
  { text: 'Van welk klein genoegen heb je vandaag genoten?', category: 'gratitude', time: 'evening' },
  { text: 'Onthoud: iemand daarbuiten wordt door jou geïnspireerd.', category: 'gratitude', time: 'anytime' },
  { text: 'Ik ben dankbaar voor zonnige dagen die mijn humeur opfleuren.', category: 'gratitude', time: 'anytime', weather: 'clear' },
  { text: 'Ik ben dankbaar voor regenachtige dagen die de aarde voeden.', category: 'gratitude', time: 'anytime', weather: 'rain' },

  // ── Mindfulness ───────────────────────────────────────────────
  { text: 'Haal diep adem. Je bent precies waar je moet zijn.', category: 'mindfulness', time: 'anytime' },
  { text: 'Wees aanwezig. Dit moment is alles wat er is.', category: 'mindfulness', time: 'anytime' },
  { text: 'Adem rust in. Adem spanning uit.', category: 'mindfulness', time: 'anytime' },
  { text: 'Vertraag. Er is geen haast om ergens anders te zijn.', category: 'mindfulness', time: 'evening' },
  { text: 'Merk vijf dingen op die je nu kunt zien.', category: 'mindfulness', time: 'anytime' },
  { text: 'Laat los wat je niet in de hand hebt.', category: 'mindfulness', time: 'anytime' },
  { text: 'Je gedachten zijn wolken. Laat ze voorbijtrekken.', category: 'mindfulness', time: 'anytime' },
  { text: 'Vrede is niet de afwezigheid van chaos, het is de rust van binnen.', category: 'mindfulness', time: 'anytime' },
  { text: 'Op dit moment, hier en nu, ben je veilig.', category: 'mindfulness', time: 'night' },
  { text: 'Stilte is niet leeg, ze zit vol antwoorden.', category: 'mindfulness', time: 'evening' },
  { text: 'Voel je voeten op de grond. Je bent geworteld.', category: 'mindfulness', time: 'anytime' },
  { text: 'Pauzeer. Adem. Ga verder.', category: 'mindfulness', time: 'anytime' },
  { text: 'Je bent niet je gedachten. Je bent het bewustzijn erachter.', category: 'mindfulness', time: 'anytime' },
  { text: 'Merk de ruimte tussen je gedachten op. Daar leeft de rust.', category: 'mindfulness', time: 'evening' },
  { text: 'Luister naar de geluiden om je heen zonder ze te benoemen.', category: 'mindfulness', time: 'anytime' },
  { text: 'Leg één hand op je borst. Voel je hartslag. Je leeft.', category: 'mindfulness', time: 'anytime' },
  { text: 'Het huidige moment is het enige moment dat echt bestaat.', category: 'mindfulness', time: 'anytime' },
  { text: 'Waar zit er spanning in je lichaam op dit moment? Adem erin.', category: 'mindfulness', time: 'afternoon' },
  { text: 'Tussen prikkel en reactie zit een ruimte. In die ruimte ligt je kracht.', category: 'mindfulness', attribution: 'Viktor Frankl', time: 'anytime' },
  { text: 'Adem vier tellen in. Houd vier tellen vast. Adem vier tellen uit. Herhaal.', category: 'mindfulness', time: 'anytime' },
  { text: 'Leen geen zorgen van morgen. Vandaag is genoeg.', category: 'mindfulness', time: 'evening' },
  { text: 'Alles is tijdelijk. Het goede en het moeilijke. Geniet en verdraag.', category: 'mindfulness', time: 'anytime' },
  { text: 'Je hoeft het niet allemaal uitgedokterd te hebben. Zet gewoon de volgende stap.', category: 'mindfulness', time: 'anytime' },
  { text: 'Je adem is er altijd voor je. Kom ernaar terug.', category: 'mindfulness', time: 'anytime' },
  { text: 'Wat kun je nu doen om voor jezelf te zorgen?', category: 'mindfulness', time: 'afternoon' },
  { text: 'Niets in de natuur bloeit het hele jaar. Wees geduldig met jezelf.', category: 'mindfulness', time: 'anytime' },
  { text: 'Stilstand is geen luiheid. Zo haalt je ziel je in.', category: 'mindfulness', time: 'evening' },
  { text: 'Je mag ontgroeien wat niet meer bij je past.', category: 'mindfulness', time: 'anytime' },
  { text: 'Luister naar de regen. Laat hem je gedachten tot rust brengen.', category: 'mindfulness', time: 'anytime', weather: 'rain' },
  { text: 'De sneeuw herinnert me eraan te vertragen en stil te zijn.', category: 'mindfulness', time: 'anytime', weather: 'snow' },
  { text: 'Voel de warmte van de zon op je huid. Je bent hier.', category: 'mindfulness', time: 'anytime', weather: 'clear' },

  // ── Season-aware entries ──────────────────────────────────────
  { text: 'De lente herinnert ons eraan dat een nieuw begin altijd mogelijk is.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'Net als de bloemen bloei ook jij op je eigen tempo.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'De aarde ontwaakt. Laat jezelf met haar ontwaken.', category: 'mindfulness', time: 'morning', season: 'spring' },
  { text: 'Frisse lucht, frisse starts. De lente staat aan jouw kant.', category: 'motivational', time: 'morning', season: 'spring' },
  { text: 'Laat de warmte van de zomer je geest vullen.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Lange dagen, warme nachten. Neem het allemaal in je op.', category: 'gratitude', time: 'evening', season: 'summer' },
  { text: 'Het zomerlicht herinnert je eraan dat er altijd meer dag voor je ligt.', category: 'motivational', time: 'morning', season: 'summer' },
  { text: 'De zon schijnt. Laat hem meer verwarmen dan alleen je huid.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Laat, net als de herfstbladeren, los wat klaar is om te vallen.', category: 'mindfulness', time: 'anytime', season: 'fall' },
  { text: 'De herfst leert ons dat loslaten mooi kan zijn.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'De wereld verandert van kleur. Jij mag ook veranderen.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'Oogstseizoen, verzamel de vruchten van je harde werk.', category: 'gratitude', time: 'anytime', season: 'fall' },
  { text: 'Zelfs in de winter vindt groei plaats onder de oppervlakte.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'De stilte van de winter is een uitnodiging om naar binnen te keren.', category: 'mindfulness', time: 'evening', season: 'winter' },
  { text: 'Koud buiten, warm van binnen. Voed je innerlijke vuur.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'Winternachten zijn om te rusten. De lente komt weer.', category: 'mindfulness', time: 'night', season: 'winter' },

  // ── Night-specific ────────────────────────────────────────────
  { text: 'Rust goed uit. Morgen is een frisse start.', category: 'affirmations', time: 'night' },
  { text: 'Je hebt vandaag genoeg bereikt. Gun jezelf slaap.', category: 'mindfulness', time: 'night' },
  { text: 'De nacht is er voor herstel, niet voor zorgen.', category: 'mindfulness', time: 'night' },
  { text: 'Sluit je ogen in de wetenschap dat je vandaag je best hebt gedaan.', category: 'affirmations', time: 'night' },
  { text: 'Laat de stilte van de nacht je geest tot rust brengen.', category: 'mindfulness', time: 'night' },
  { text: 'Slaap is geen luxe. Zo laad je op voor grootse dingen.', category: 'affirmations', time: 'night' },
  { text: 'Laat vanavond elke zorg los. Morgen kun je het opnieuw proberen.', category: 'mindfulness', time: 'night' },

  // ── Morning-specific ──────────────────────────────────────────
  { text: 'Goedemorgen. Vandaag zit vol mogelijkheden.', category: 'affirmations', time: 'morning' },
  { text: 'De ochtend is van jou. Bepaal je intentie en maak hem waar.', category: 'motivational', time: 'morning' },
  { text: 'Sta op en straal, niet omdat het moet, maar omdat je het mag.', category: 'gratitude', time: 'morning' },
  { text: 'Wat wil je vandaag voelen? Beweeg ernaartoe.', category: 'mindfulness', time: 'morning' },
  { text: 'Een nieuwe dag betekent een nieuwe kans om iets moois te maken.', category: 'motivational', time: 'morning' },
  { text: 'Je ochtendroutine is een daad van zelfliefde.', category: 'affirmations', time: 'morning' },
];
