import type { AffirmationEntry } from './types';

// ---------------------------------------------------------------------------
// Built-in content library — pt-BR (198 entries)
// ---------------------------------------------------------------------------

export const PT_BR_AFFIRMATIONS: AffirmationEntry[] = [
  // ── Affirmations ──────────────────────────────────────────────
  { text: 'Sou digno de amor e carinho.', category: 'affirmations', time: 'anytime' },
  { text: 'Confio na jornada, mesmo quando não consigo ver o caminho.', category: 'affirmations', time: 'anytime' },
  { text: 'Estou me tornando a pessoa que quero ser.', category: 'affirmations', time: 'anytime' },
  { text: 'Meu potencial não tem limites.', category: 'affirmations', time: 'anytime' },
  { text: 'Solto o que não me serve mais.', category: 'affirmations', time: 'evening' },
  { text: 'Escolho a paz em vez da perfeição.', category: 'affirmations', time: 'anytime' },
  { text: 'Tenho o direito de ocupar o meu espaço.', category: 'affirmations', time: 'anytime' },
  { text: 'Sou suficiente, exatamente como sou.', category: 'affirmations', time: 'anytime' },
  { text: 'Atraio energia positiva para a minha vida.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Sou resiliente, forte e corajoso.', category: 'affirmations', time: 'anytime' },
  { text: 'Dou a mim mesmo permissão para descansar.', category: 'affirmations', time: 'evening', weather: 'rain' },
  { text: 'Respeito os meus próprios limites.', category: 'affirmations', time: 'anytime' },
  { text: 'Todo revés é o começo de uma virada.', category: 'affirmations', time: 'anytime' },
  { text: 'Estou em paz com quem sou.', category: 'affirmations', time: 'night' },
  { text: 'Minha voz importa. Minha história importa.', category: 'affirmations', time: 'anytime' },
  { text: 'Acolho a abundância em todas as suas formas.', category: 'affirmations', time: 'morning' },
  { text: 'Mereço as coisas boas da minha vida.', category: 'affirmations', time: 'anytime' },
  { text: 'Perdoo a mim mesmo pelos erros do passado. Eles me ajudaram a crescer.', category: 'affirmations', time: 'evening' },
  { text: 'Meu corpo é saudável, minha mente é afiada, meu espírito é tranquilo.', category: 'affirmations', time: 'morning', weather: 'clear' },
  { text: 'Irradio confiança e respeito próprio.', category: 'affirmations', time: 'morning' },
  { text: 'Estou aberto a novas aventuras e experiências.', category: 'affirmations', time: 'morning' },
  { text: 'Abandono as comparações. Meu caminho é só meu.', category: 'affirmations', time: 'anytime' },
  { text: 'Sou um trabalho em andamento, e está tudo bem assim.', category: 'affirmations', time: 'anytime' },
  { text: 'Meus erros não me definem. Meu crescimento, sim.', category: 'affirmations', time: 'anytime' },
  { text: 'Tenho o poder de criar a vida que quero.', category: 'affirmations', time: 'morning' },
  { text: 'Escolho focar naquilo que posso mudar.', category: 'affirmations', time: 'anytime' },
  { text: 'Estou cercado de amor, mesmo quando não consigo senti-lo.', category: 'affirmations', time: 'night' },
  { text: 'Hoje serei gentil comigo mesmo.', category: 'affirmations', time: 'morning' },
  { text: 'Sou mais forte que as minhas dúvidas.', category: 'affirmations', time: 'anytime' },
  { text: 'Minha felicidade é minha responsabilidade, e eu a abraço.', category: 'affirmations', time: 'anytime' },
  { text: 'A chuva leva embora aquilo de que não preciso mais.', category: 'affirmations', time: 'anytime', weather: 'rain' },
  { text: 'Encontro beleza em qualquer tipo de céu.', category: 'affirmations', time: 'anytime', weather: 'clouds' },

  // ── Compliments ───────────────────────────────────────────────
  { text: 'Você ilumina todo ambiente em que entra.', category: 'compliments', time: 'anytime' },
  { text: 'Seu sorriso é contagiante — nunca deixe de compartilhá-lo.', category: 'compliments', time: 'morning' },
  { text: 'Você tem o dom de fazer os outros se sentirem vistos.', category: 'compliments', time: 'anytime' },
  { text: 'O mundo é melhor porque você existe nele.', category: 'compliments', time: 'anytime' },
  { text: 'Sua gentileza se espalha mais longe do que você imagina.', category: 'compliments', time: 'anytime' },
  { text: 'Você enfrenta os desafios com uma graça admirável.', category: 'compliments', time: 'afternoon' },
  { text: 'As pessoas têm sorte de conhecer você.', category: 'compliments', time: 'anytime' },
  { text: 'Sua energia é magnética.', category: 'compliments', time: 'anytime' },
  { text: 'Você faz as coisas difíceis parecerem fáceis.', category: 'compliments', time: 'afternoon' },
  { text: 'Você tem um gosto incrível.', category: 'compliments', time: 'anytime' },
  { text: 'Sua criatividade inspira todos ao seu redor.', category: 'compliments', time: 'anytime' },
  { text: 'Você traz o melhor das pessoas à tona.', category: 'compliments', time: 'anytime' },
  { text: 'Você merece cada coisa boa que está a caminho.', category: 'compliments', time: 'anytime' },
  { text: 'Sua risada é o melhor dos sons.', category: 'compliments', time: 'anytime' },
  { text: 'Você está fazendo um trabalho incrível.', category: 'compliments', time: 'afternoon' },
  { text: 'Sua paciência é um superpoder.', category: 'compliments', time: 'afternoon' },
  { text: 'Você tem um jeito lindo de enxergar o mundo.', category: 'compliments', time: 'anytime' },
  { text: 'Sua determinação é inspiradora.', category: 'compliments', time: 'anytime' },
  { text: 'Você faz as pessoas se sentirem seguras e valorizadas.', category: 'compliments', time: 'anytime' },
  { text: 'Você tem a coragem de ser você mesmo, e isso é raro.', category: 'compliments', time: 'anytime' },
  { text: 'Sua perspectiva é única e ela importa.', category: 'compliments', time: 'anytime' },
  { text: 'Você lidera com empatia e isso se nota.', category: 'compliments', time: 'afternoon' },
  { text: 'Não há mais ninguém como você. Essa é a sua força.', category: 'compliments', time: 'anytime' },
  { text: 'Você se porta com uma confiança serena.', category: 'compliments', time: 'anytime' },
  { text: 'O esforço que você dedica não passa despercebido.', category: 'compliments', time: 'afternoon' },
  { text: 'Seu coração é maior do que você reconhece.', category: 'compliments', time: 'evening' },
  { text: 'Você tem ótimos instintos. Confie mais neles.', category: 'compliments', time: 'anytime' },
  { text: 'Seu entusiasmo é contagiante.', category: 'compliments', time: 'morning' },
  { text: 'Você lida com a pressão melhor do que imagina.', category: 'compliments', time: 'afternoon' },
  { text: 'Você é alguém em quem as pessoas podem confiar.', category: 'compliments', time: 'anytime' },

  // ── Motivational ──────────────────────────────────────────────
  { text: 'Comece de onde você está. Use o que você tem. Faça o que você pode.', category: 'motivational', attribution: 'Arthur Ashe', time: 'morning' },
  { text: 'A única maneira de fazer um trabalho excelente é amar o que você faz.', category: 'motivational', attribution: 'Steve Jobs', time: 'morning' },
  { text: 'Não importa o quão devagar você vá, contanto que não pare.', category: 'motivational', attribution: 'Confucius', time: 'anytime' },
  { text: 'O que você conquista ao alcançar suas metas não é tão importante quanto aquilo em que você se torna.', category: 'motivational', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Acredite que consegue e você já estará na metade do caminho.', category: 'motivational', attribution: 'Theodore Roosevelt', time: 'morning' },
  { text: 'Pequenas melhorias diárias são a chave para resultados impressionantes a longo prazo.', category: 'motivational', time: 'morning' },
  { text: 'Disciplina é escolher entre o que você quer agora e o que você mais quer.', category: 'motivational', attribution: 'Abraham Lincoln', time: 'anytime' },
  { text: 'Você não chegou tão longe só para chegar até aqui.', category: 'motivational', time: 'afternoon' },
  { text: 'Sonhe grande. Comece pequeno. Aja agora.', category: 'motivational', time: 'morning' },
  { text: 'O segredo para sair na frente é começar.', category: 'motivational', attribution: 'Mark Twain', time: 'morning' },
  { text: 'Seu eu do futuro está te observando agora através das lembranças.', category: 'motivational', time: 'anytime' },
  { text: 'O melhor momento para plantar uma árvore foi há 20 anos. O segundo melhor é agora.', category: 'motivational', time: 'anytime' },
  { text: 'Progresso, não perfeição.', category: 'motivational', time: 'anytime' },
  { text: 'As dificuldades muitas vezes preparam pessoas comuns para um destino extraordinário.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'Seja tão bom que não possam te ignorar.', category: 'motivational', attribution: 'Steve Martin', time: 'morning' },
  { text: 'Você nunca é velho demais para traçar uma nova meta ou sonhar um novo sonho.', category: 'motivational', attribution: 'C.S. Lewis', time: 'anytime' },
  { text: 'A luta que você enfrenta hoje está desenvolvendo a força de que você precisará amanhã.', category: 'motivational', time: 'afternoon' },
  { text: 'Faça hoje algo pelo qual seu eu do futuro vai te agradecer.', category: 'motivational', time: 'morning' },
  { text: 'O sucesso é a soma de pequenos esforços, repetidos dia após dia.', category: 'motivational', attribution: 'Robert Collier', time: 'morning' },
  { text: 'Caia sete vezes, levante-se oito.', category: 'motivational', time: 'anytime' },
  { text: 'O que hoje parece impossível um dia vai virar seu aquecimento.', category: 'motivational', time: 'morning' },
  { text: 'Você não precisa ser perfeito para ser incrível.', category: 'motivational', time: 'anytime' },
  { text: 'A ação é a chave fundamental para todo sucesso.', category: 'motivational', attribution: 'Pablo Picasso', time: 'morning' },
  { text: 'A volta por cima é sempre mais forte que a queda.', category: 'motivational', time: 'anytime' },
  { text: 'Daqui a um ano você vai desejar ter começado hoje.', category: 'motivational', time: 'morning' },
  { text: 'Tudo o que você sempre quis está do outro lado do medo.', category: 'motivational', attribution: 'George Addair', time: 'anytime' },
  { text: 'A energia flui para onde vai a atenção.', category: 'motivational', time: 'morning' },
  { text: 'A dúvida mata mais sonhos do que o fracasso jamais matará.', category: 'motivational', attribution: 'Suzy Kassem', time: 'anytime' },
  { text: 'Se fosse fácil, todo mundo faria. Continue firme.', category: 'motivational', time: 'afternoon' },
  { text: 'Você está a uma decisão de uma vida completamente diferente.', category: 'motivational', time: 'anytime' },
  { text: 'Feito é melhor que perfeito.', category: 'motivational', time: 'afternoon' },
  { text: 'O único limite para a realização do nosso amanhã serão as nossas dúvidas de hoje.', category: 'motivational', attribution: 'Franklin D. Roosevelt', time: 'anytime' },
  { text: 'As estrelas não brilham sem a escuridão.', category: 'motivational', time: 'evening' },
  { text: 'Coragem não é a ausência de medo. É agir apesar dele.', category: 'motivational', attribution: 'Mark Twain', time: 'anytime' },
  { text: 'O que você tentaria fazer se soubesse que não poderia falhar?', category: 'motivational', time: 'morning' },
  { text: 'A maneira de começar é parar de falar e começar a fazer.', category: 'motivational', attribution: 'Walt Disney', time: 'morning' },

  // ── Day-of-week motivation ────────────────────────────────────
  { text: 'Nova semana, novas possibilidades. Faça esta valer a pena.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Segundas-feiras são para recomeços e atitudes ousadas.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Defina o tom da semana. Você dá conta.', category: 'motivational', time: 'morning', days: [1] },
  { text: 'Terça: a prova de que você sobreviveu à segunda e seguiu em frente.', category: 'compliments', time: 'morning', days: [2] },
  { text: 'Balanço do meio da semana: você está mais perto do que pensa.', category: 'motivational', time: 'anytime', days: [3] },
  { text: 'Quarta — a metade do caminho. Você está indo muito bem.', category: 'compliments', time: 'afternoon', days: [3] },
  { text: 'Quase lá. Termine a semana com força total.', category: 'motivational', time: 'morning', days: [4] },
  { text: 'Energia de quinta: o fim de semana já está à vista.', category: 'motivational', time: 'afternoon', days: [4] },
  { text: 'Você venceu a semana. Orgulhe-se de si mesmo.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Feliz sexta-feira. Você mereceu cada pedacinho deste fim de semana.', category: 'compliments', time: 'afternoon', days: [5] },
  { text: 'Aproveite o fim de semana — você mereceu.', category: 'compliments', time: 'anytime', days: [5, 6, 0] },
  { text: 'Sábados são para recarregar as energias. Faça o que enche o seu coração.', category: 'mindfulness', time: 'morning', days: [6] },
  { text: 'Domingo: descanse, reflita e prepare-se para brilhar de novo.', category: 'mindfulness', time: 'morning', days: [0] },
  { text: 'Use o dia de hoje para preparar uma ótima semana pela frente.', category: 'motivational', time: 'afternoon', days: [0] },

  // ── Gratitude ─────────────────────────────────────────────────
  { text: 'Quais são três coisas pelas quais você é grato agora?', category: 'gratitude', time: 'morning' },
  { text: 'Reserve um momento para valorizar o quanto você já avançou.', category: 'gratitude', time: 'evening' },
  { text: 'A gratidão transforma o que temos em suficiente.', category: 'gratitude', time: 'anytime' },
  { text: 'Hoje, repare em uma pequena coisa que te traz alegria.', category: 'gratitude', time: 'morning' },
  { text: 'Quem fez você sorrir hoje? Guarde esse sentimento.', category: 'gratitude', time: 'evening' },
  { text: 'Os momentos comuns costumam ser os mais bonitos.', category: 'gratitude', time: 'anytime' },
  { text: 'Valorize as lições escondidas nos desafios.', category: 'gratitude', time: 'anytime' },
  { text: 'Você tem tanto pelo que ser grato.', category: 'gratitude', time: 'anytime' },
  { text: 'O que parecia impossível no ano passado é a sua realidade hoje.', category: 'gratitude', time: 'anytime' },
  { text: 'Que a gratidão seja o seu estado padrão.', category: 'gratitude', time: 'morning' },
  { text: 'Lembre-se de uma palavra gentil que alguém te disse recentemente.', category: 'gratitude', time: 'evening' },
  { text: 'Sua vida está cheia de pequenos milagres silenciosos. Procure por eles.', category: 'gratitude', time: 'anytime' },
  { text: 'Cite uma pessoa que tornou sua vida melhor neste ano.', category: 'gratitude', time: 'evening' },
  { text: 'O teto sobre a sua cabeça, a comida na sua mesa — essas não são coisas pequenas.', category: 'gratitude', time: 'anytime' },
  { text: 'Pense em um desafio que te tornou mais forte. Seja grato por ele.', category: 'gratitude', time: 'evening' },
  { text: 'A gratidão é a mais saudável de todas as emoções humanas.', category: 'gratitude', attribution: 'Zig Ziglar', time: 'anytime' },
  { text: 'Qual é uma coisa que você tem hoje e que um dia desejou?', category: 'gratitude', time: 'morning' },
  { text: 'Cada nascer do sol é um convite para alegrar o dia de alguém.', category: 'gratitude', time: 'morning' },
  { text: 'Hoje foi um presente. Qual foi a sua parte favorita?', category: 'gratitude', time: 'evening' },
  { text: 'As pessoas na sua vida amam você mais do que você imagina.', category: 'gratitude', time: 'anytime' },
  { text: 'Repare na beleza de algo que você vê todos os dias.', category: 'gratitude', time: 'anytime' },
  { text: 'Um coração grato é um ímã para coisas maravilhosas.', category: 'gratitude', time: 'morning' },
  { text: 'Qual prazer simples você aproveitou hoje?', category: 'gratitude', time: 'evening' },
  { text: 'Lembre-se: alguém por aí se inspira em você.', category: 'gratitude', time: 'anytime' },
  { text: 'Sou grato pelos dias de sol que levantam o meu ânimo.', category: 'gratitude', time: 'anytime', weather: 'clear' },
  { text: 'Sou grato pelos dias de chuva que nutrem a terra.', category: 'gratitude', time: 'anytime', weather: 'rain' },

  // ── Mindfulness ───────────────────────────────────────────────
  { text: 'Respire fundo. Você está exatamente onde precisa estar.', category: 'mindfulness', time: 'anytime' },
  { text: 'Esteja presente. Este momento é tudo o que existe.', category: 'mindfulness', time: 'anytime' },
  { text: 'Inspire calma. Expire tensão.', category: 'mindfulness', time: 'anytime' },
  { text: 'Vá com calma. Não há pressa para estar em outro lugar.', category: 'mindfulness', time: 'evening' },
  { text: 'Repare em cinco coisas que você consegue ver agora.', category: 'mindfulness', time: 'anytime' },
  { text: 'Solte aquilo que você não pode controlar.', category: 'mindfulness', time: 'anytime' },
  { text: 'Seus pensamentos são nuvens. Deixe-os passar.', category: 'mindfulness', time: 'anytime' },
  { text: 'A paz não é a ausência de caos — é a calma interior.', category: 'mindfulness', time: 'anytime' },
  { text: 'Agora, neste momento, você está seguro.', category: 'mindfulness', time: 'night' },
  { text: 'O silêncio não é vazio — está cheio de respostas.', category: 'mindfulness', time: 'evening' },
  { text: 'Sinta seus pés no chão. Você está firme.', category: 'mindfulness', time: 'anytime' },
  { text: 'Pause. Respire. Continue.', category: 'mindfulness', time: 'anytime' },
  { text: 'Você não é seus pensamentos. Você é a consciência por trás deles.', category: 'mindfulness', time: 'anytime' },
  { text: 'Repare no espaço entre seus pensamentos. É ali que a paz mora.', category: 'mindfulness', time: 'evening' },
  { text: 'Ouça os sons ao seu redor sem nomeá-los.', category: 'mindfulness', time: 'anytime' },
  { text: 'Coloque uma das mãos sobre o peito. Sinta seu coração bater. Você está vivo.', category: 'mindfulness', time: 'anytime' },
  { text: 'O momento presente é o único momento que realmente existe.', category: 'mindfulness', time: 'anytime' },
  { text: 'Onde está a tensão no seu corpo agora? Respire para dentro dela.', category: 'mindfulness', time: 'afternoon' },
  { text: 'Entre o estímulo e a resposta existe um espaço. Nesse espaço está o seu poder.', category: 'mindfulness', attribution: 'Viktor Frankl', time: 'anytime' },
  { text: 'Inspire contando até quatro. Segure por quatro. Expire por quatro. Repita.', category: 'mindfulness', time: 'anytime' },
  { text: 'Não pegue emprestada a preocupação de amanhã. Hoje já basta.', category: 'mindfulness', time: 'evening' },
  { text: 'Tudo é passageiro. O bom e o difícil. Saboreie e persevere.', category: 'mindfulness', time: 'anytime' },
  { text: 'Você não precisa ter tudo resolvido. Basta dar o próximo passo.', category: 'mindfulness', time: 'anytime' },
  { text: 'Sua respiração está sempre ali por você. Volte a ela.', category: 'mindfulness', time: 'anytime' },
  { text: 'Qual é uma coisa que você pode fazer agora para cuidar de si mesmo?', category: 'mindfulness', time: 'afternoon' },
  { text: 'Nada na natureza floresce o ano inteiro. Tenha paciência consigo mesmo.', category: 'mindfulness', time: 'anytime' },
  { text: 'A quietude não é preguiça. É como a sua alma se recupera.', category: 'mindfulness', time: 'evening' },
  { text: 'Você tem o direito de crescer além de espaços que já não te servem.', category: 'mindfulness', time: 'anytime' },
  { text: 'Ouça a chuva. Deixe-a acalmar seus pensamentos.', category: 'mindfulness', time: 'anytime', weather: 'rain' },
  { text: 'A neve me lembra de ir com calma e ficar em silêncio.', category: 'mindfulness', time: 'anytime', weather: 'snow' },
  { text: 'Sinta o calor do sol na sua pele. Você está aqui.', category: 'mindfulness', time: 'anytime', weather: 'clear' },

  // ── Season-aware entries ──────────────────────────────────────
  { text: 'A primavera nos lembra que recomeços são sempre possíveis.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'Como as flores, você também está desabrochando no seu próprio ritmo.', category: 'affirmations', time: 'anytime', season: 'spring' },
  { text: 'A terra está despertando. Deixe-se despertar com ela.', category: 'mindfulness', time: 'morning', season: 'spring' },
  { text: 'Ar novo, começos novos. A primavera está do seu lado.', category: 'motivational', time: 'morning', season: 'spring' },
  { text: 'Deixe o calor do verão preencher o seu espírito.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Dias longos, noites quentes. Absorva tudo isso.', category: 'gratitude', time: 'evening', season: 'summer' },
  { text: 'A luz do verão te lembra de que sempre há mais dia pela frente.', category: 'motivational', time: 'morning', season: 'summer' },
  { text: 'O sol apareceu. Deixe-o aquecer mais do que apenas a sua pele.', category: 'mindfulness', time: 'anytime', season: 'summer' },
  { text: 'Como as folhas do outono, solte o que já está pronto para cair.', category: 'mindfulness', time: 'anytime', season: 'fall' },
  { text: 'O outono nos ensina que soltar pode ser bonito.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'O mundo está mudando de cores. Você também tem o direito de mudar.', category: 'affirmations', time: 'anytime', season: 'fall' },
  { text: 'Tempo de colheita — recolha os frutos do seu trabalho árduo.', category: 'gratitude', time: 'anytime', season: 'fall' },
  { text: 'Mesmo no inverno, o crescimento acontece sob a superfície.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'A quietude do inverno é um convite para olhar para dentro.', category: 'mindfulness', time: 'evening', season: 'winter' },
  { text: 'Frio lá fora, calor por dentro. Cuide do seu fogo interior.', category: 'affirmations', time: 'anytime', season: 'winter' },
  { text: 'As noites de inverno são para descansar. A primavera voltará.', category: 'mindfulness', time: 'night', season: 'winter' },

  // ── Night-specific ────────────────────────────────────────────
  { text: 'Descanse bem. Amanhã é um novo começo.', category: 'affirmations', time: 'night' },
  { text: 'Você realizou o suficiente hoje. Permita-se dormir.', category: 'mindfulness', time: 'night' },
  { text: 'A noite é para se recuperar, não para se preocupar.', category: 'mindfulness', time: 'night' },
  { text: 'Feche os olhos sabendo que deu o seu melhor hoje.', category: 'affirmations', time: 'night' },
  { text: 'Deixe a quietude da noite acalmar a sua mente.', category: 'mindfulness', time: 'night' },
  { text: 'O sono não é um luxo. É como você recarrega para a grandeza.', category: 'affirmations', time: 'night' },
  { text: 'Hoje à noite, solte toda preocupação. Amanhã você pode tentar de novo.', category: 'mindfulness', time: 'night' },

  // ── Morning-specific ──────────────────────────────────────────
  { text: 'Bom dia. Hoje está cheio de possibilidades.', category: 'affirmations', time: 'morning' },
  { text: 'A manhã é sua. Defina sua intenção e assuma o controle.', category: 'motivational', time: 'morning' },
  { text: 'Acorde e brilhe — não porque você tem que fazer isso, mas porque você pode.', category: 'gratitude', time: 'morning' },
  { text: 'Qual é uma coisa que você quer sentir hoje? Caminhe em direção a ela.', category: 'mindfulness', time: 'morning' },
  { text: 'Um novo dia significa uma nova chance de criar algo maravilhoso.', category: 'motivational', time: 'morning' },
  { text: 'Sua rotina matinal é um ato de amor-próprio.', category: 'affirmations', time: 'morning' },
];
