import http from 'node:http';
import type { AddressInfo } from 'node:net';
import { readFileSync, mkdtempSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import os from 'node:os';
import path from 'node:path';
import { test, expect } from '../fixtures';
import type { APIRequestContext } from '@playwright/test';
import { putConfig } from '../helpers/api';
import { baseConfig, makeScreen, textModule } from '../helpers/config-fixtures';
import { MANIFEST as FIXTURE_MANIFEST, BUNDLE as FIXTURE_BUNDLE } from '../helpers/fixture-plugin';
import { DEFAULT_MODULE_STYLE } from '@/types/config';
import type { ModuleInstance } from '@/types/config';

/**
 * Plugin lifecycle, end to end.
 *
 * Unlike display/plugins.spec.ts (which pre-seeds the fixture plugin straight
 * onto disk with seedFixturePlugin, skipping the install pipeline), these specs
 * drive the *real* install path: a committed .tar.gz is downloaded and run
 * through `/api/plugins/install-external` (extract → validate → promote →
 * installed.json) before the plugin ever renders.
 *
 * The download is normally a server-side fetch Playwright can't intercept, but
 * `validateExternalUrl` deliberately allows `http://127.0.0.1` as a
 * dev/test escape hatch (and the SSRF IP guard only runs for https), so a
 * throwaway loopback HTTP server serving the tarball bytes lets the Next
 * server fetch it exactly as it would a marketplace CDN.
 *
 * The install fixtures live in e2e/fixtures/plugins/ and are regenerated by
 * build-plugin-fixtures.mjs; the minimal one mirrors seedFixturePlugin's
 * content byte-for-byte so "the fixture plugin" behaves identically whether
 * seeded or installed.
 */

const FIXTURES_DIR = path.join(__dirname, '..', 'fixtures', 'plugins');
const MINIMAL_TARBALL = path.join(FIXTURES_DIR, 'e2e-fixture-plugin.tar.gz');
const RICH_TARBALL = path.join(FIXTURES_DIR, 'e2e-fixture-rich-plugin.tar.gz');

const MINIMAL_TYPE = 'plugin:e2e-fixture';
const RICH_TYPE = 'plugin:e2e-fixture-rich';
const RICH_GREETING = 'GREETING FROM PLUGIN I18N';

interface LocalServer {
  origin: string;
  close: () => Promise<void>;
}

/**
 * A loopback HTTP server with permissive CORS (dev plugins fetch cross-origin).
 * Binds on all interfaces so either `127.0.0.1` or `localhost` reaches it; the
 * `hostname` only picks which name goes in the returned origin. Server-side
 * downloads (install-external) use `127.0.0.1`; browser fetches (dev mode) must
 * use `localhost` because the app CSP's connect-src allows `http://localhost:*`
 * but not the raw loopback IP.
 */
async function startServer(handler: http.RequestListener, hostname = '127.0.0.1'): Promise<LocalServer> {
  const server = http.createServer((req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET,HEAD,OPTIONS');
    res.setHeader('Access-Control-Expose-Headers', 'ETag, Content-Length');
    if (req.method === 'OPTIONS') {
      res.writeHead(204);
      res.end();
      return;
    }
    handler(req, res);
  });
  await new Promise<void>((resolve) => server.listen(0, resolve));
  const { port } = server.address() as AddressInfo;
  return {
    origin: `http://${hostname}:${port}`,
    close: () => new Promise<void>((resolve) => server.close(() => resolve())),
  };
}

/** Serve a single tarball file's bytes for any request path. */
async function serveTarball(tarballPath: string): Promise<LocalServer> {
  const bytes = readFileSync(tarballPath);
  return startServer((req, res) => {
    const headers = { 'content-type': 'application/gzip', 'content-length': String(bytes.length) };
    if (req.method === 'HEAD') {
      res.writeHead(200, headers);
      res.end();
      return;
    }
    res.writeHead(200, headers);
    res.end(bytes);
  });
}

/** Install a plugin tarball through the real install-external pipeline. */
async function installTarball(
  request: APIRequestContext,
  origin: string,
): Promise<{ pluginId: string; version: string }> {
  const res = await request.post('/api/plugins/install-external', {
    data: { tarballUrl: `${origin}/plugin.tar.gz` },
  });
  expect(res.ok()).toBe(true);
  const body = await res.json();
  expect(body).toMatchObject({ ok: true });
  return body;
}

function pluginModule(type: string, overrides: Partial<ModuleInstance> = {}): ModuleInstance {
  return {
    id: 'plugin-instance',
    type,
    position: { x: 100, y: 100 },
    size: { w: 320, h: 200 },
    zIndex: 1,
    style: { ...DEFAULT_MODULE_STYLE },
    config: {},
    ...overrides,
  } as ModuleInstance;
}

// ---------------------------------------------------------------------------
// Install happy path — real tarball through the install pipeline, then render
// ---------------------------------------------------------------------------

test('installing a tarball registers the module type and renders it on the display', async ({ page, request }) => {
  const server = await serveTarball(MINIMAL_TARBALL);
  try {
    const installed = await installTarball(request, server.origin);
    expect(installed).toMatchObject({ pluginId: 'e2e-fixture', version: '1.0.0' });

    // Install persisted an enabled entry (module type now registrable).
    const listRes = await request.get('/api/plugins/installed');
    expect(listRes.ok()).toBe(true);
    const list = await listRes.json();
    expect(list.plugins).toContainEqual(
      expect.objectContaining({ id: 'e2e-fixture', moduleType: 'e2e-fixture', enabled: true }),
    );

    await putConfig(request, baseConfig({
      screens: [makeScreen('s1', 'S1', [pluginModule(MINIMAL_TYPE, { config: { label: 'INSTALLED RENDER OK' } })])],
    }));
    await page.goto('/display');

    // The loader fetches the just-installed manifest + bundle and renders it.
    await expect(page.locator('[data-plugin-marker="e2e"]')).toBeVisible();
    await expect(page.getByText('INSTALLED RENDER OK')).toBeVisible();
  } finally {
    await server.close();
  }
});

// The committed tarball is generated from seedFixturePlugin's exported source,
// but it's a static binary — nothing regenerates it at test time. Without this
// guard, editing the seed bundle would silently leave the tarball stale (the
// install path and the seed path read different byte sources, so no other test
// would catch it). Untar and compare to fail loudly on drift instead.
test('the committed install tarball has not drifted from the seedFixturePlugin source', () => {
  const tmp = mkdtempSync(path.join(os.tmpdir(), 'hs-tarball-parity-'));
  try {
    execFileSync('tar', ['-xzf', MINIMAL_TARBALL, '-C', tmp]);
    const root = path.join(tmp, 'e2e-fixture');
    const manifest = JSON.parse(readFileSync(path.join(root, 'manifest.json'), 'utf-8'));
    const bundle = readFileSync(path.join(root, 'dist', 'bundle.js'), 'utf-8');
    expect(manifest).toEqual(FIXTURE_MANIFEST);
    expect(bundle).toBe(FIXTURE_BUNDLE);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
});

// ---------------------------------------------------------------------------
// Manifest translations — installed plugin exposes __HS_SDK__.translate
// ---------------------------------------------------------------------------

test('an installed plugin renders a string resolved through __HS_SDK__.translate', async ({ page, request }) => {
  const server = await serveTarball(RICH_TARBALL);
  try {
    const installed = await installTarball(request, server.origin);
    expect(installed).toMatchObject({ pluginId: 'e2e-fixture-rich' });

    await putConfig(request, baseConfig({
      screens: [makeScreen('s1', 'S1', [pluginModule(RICH_TYPE, { config: { entity: 'sensor' } })])],
    }));
    await page.goto('/display');

    // The bundle calls SDK.translate('plugin:e2e-fixture-rich.greeting'); the
    // loader registered that namespace from the manifest's translations file
    // (fetched via /api/plugins/asset) before the component mounted.
    await expect(page.locator('[data-plugin-marker="e2e-rich"]')).toBeVisible();
    await expect(page.getByText(RICH_GREETING)).toBeVisible();
  } finally {
    await server.close();
  }
});

// ---------------------------------------------------------------------------
// deriveProvidedKeys — installed plugin advertises config-derived state keys
// ---------------------------------------------------------------------------

test('a plugin exporting deriveProvidedKeys advertises its keys in the condition picker', async ({ page, request }) => {
  const server = await serveTarball(RICH_TARBALL);
  try {
    await installTarball(request, server.origin);

    // A background-provider instance (config.entity=sensor) whose bundle derives
    // a state key from that config, plus a text module whose visibility picker
    // should offer the derived, namespaced key.
    const provider = pluginModule(RICH_TYPE, {
      id: 'rich-provider',
      position: { x: 100, y: 500 },
      backgroundProvider: true,
      config: { entity: 'sensor' },
    });
    const gated = textModule('GATED', {
      visibility: { conditions: [{ kind: 'state', sourceKey: '', equals: '' }] },
    });
    await putConfig(request, baseConfig({ screens: [makeScreen('s1', 'S1', [provider, gated])] }));

    await page.goto('/editor');
    await expect(page.getByTestId('editor-canvas')).toBeVisible();
    // Gate on the plugin actually being loaded/registered: its provider instance
    // renders live on the canvas, so its marker proves registration completed
    // before collectProvidedStateKeys runs for the picker.
    await expect(page.locator('[data-plugin-marker="e2e-rich"]')).toBeVisible();

    await page.locator('[data-module-id="text-gated"]').click();
    await page.getByRole('button', { name: 'Conditions' }).click();

    // Focusing the key input opens the custom suggestion dropdown, sourced from
    // collectProvidedStateKeys → the plugin's namespaced derived key.
    await page.getByLabel('State key').click();
    await expect(
      page.getByRole('option').filter({ hasText: `${RICH_TYPE}:sensor` }),
    ).toBeVisible();
  } finally {
    await server.close();
  }
});

// ---------------------------------------------------------------------------
// Dev mode — load from a dev server, then reload a changed bundle (the swap)
// ---------------------------------------------------------------------------

const DEV_MANIFEST = {
  id: 'e2e-dev',
  name: 'E2E Dev Plugin',
  version: '1.0.0',
  description: 'E2E dev-mode plugin',
  author: 'e2e',
  license: 'MIT',
  minAppVersion: '1.0.0',
  moduleType: 'e2e-dev',
  category: 'Media & Display',
  icon: 'Code2',
  defaultConfig: {},
  defaultSize: { w: 320, h: 200 },
  exports: { component: 'default' },
};

function devBundle(label: string): string {
  return `(function(){var R=window.React;window.__HS_PLUGIN__={default:function(){`
    + `return R.createElement('div',{'data-plugin-marker':'e2e-dev'},'${label}');}};})();`;
}

/** A dev server whose served bundle can be swapped to simulate an edit. */
async function startDevServer(): Promise<LocalServer & { setBundle: (label: string) => void }> {
  let bundle = devBundle('DEV V1');
  let etag = 1;
  const manifestBody = JSON.stringify(DEV_MANIFEST);
  const server = await startServer((req, res) => {
    const url = new URL(req.url ?? '/', 'http://local');
    if (url.pathname === '/manifest.json') {
      const headers = { 'content-type': 'application/json', 'content-length': String(Buffer.byteLength(manifestBody)) };
      res.writeHead(200, headers);
      res.end(req.method === 'HEAD' ? undefined : manifestBody);
      return;
    }
    if (url.pathname === '/dist/bundle.js') {
      const headers = {
        'content-type': 'application/javascript',
        'content-length': String(Buffer.byteLength(bundle)),
        etag: `"${etag}"`,
      };
      res.writeHead(200, headers);
      res.end(req.method === 'HEAD' ? undefined : bundle);
      return;
    }
    res.writeHead(404);
    res.end();
  }, 'localhost');
  return {
    ...server,
    setBundle: (label: string) => {
      bundle = devBundle(label);
      etag += 1;
    },
  };
}

test('a dev-mode plugin loads from a dev server and re-registers a changed bundle', async ({ page, request }) => {
  const dev = await startDevServer();
  try {
    await putConfig(request, baseConfig({
      settings: { advancedMode: true },
      screens: [makeScreen('s1', 'S1', [pluginModule('plugin:e2e-dev', { id: 'dev-mod', config: {} })])],
    }));

    await page.goto('/editor');
    await expect(page.getByTestId('editor-canvas')).toBeVisible();

    const loadDev = async () => {
      await page.getByRole('button', { name: 'Plugins' }).click();
      const dialog = page.getByRole('dialog', { name: 'Plugins' });
      await dialog.getByRole('button', { name: 'Developer' }).click();
      await dialog.getByPlaceholder('http://localhost:5173').fill(dev.origin);
      await dialog.getByRole('button', { name: 'Load', exact: true }).click();
      // Loaded dev plugins are listed by name; wait for it before closing.
      await expect(dialog.getByText('E2E Dev Plugin')).toBeVisible();
      await page.getByRole('button', { name: 'Close dialog' }).click();
      await expect(dialog).toBeHidden();
    };

    // Initial load: the dev bundle registers and renders live on the canvas.
    await loadDev();
    await expect(page.locator('[data-plugin-marker="e2e-dev"]')).toHaveText('DEV V1');

    // Edit the bundle server-side, then reload it. loadDevPlugin re-executes the
    // new bundle and swaps the registered component (the same path the 2s poll
    // takes on an ETag/length change) — the canvas re-renders the new output.
    dev.setBundle('DEV V2');
    await loadDev();
    await expect(page.locator('[data-plugin-marker="e2e-dev"]')).toHaveText('DEV V2');
  } finally {
    await dev.close();
  }
});
