/**
 * GET /api/display/kiosk-bootstrap — a one-shot shell script that puts a
 * pre-self-update Pi onto the self-updating path.
 *
 * Every display-only Pi flashed before self-update existed has no updater and
 * no timer, so it will never notice /api/display/kiosk-bundle on its own.
 * This endpoint closes that gap with a single copy-paste line, surfaced by the
 * editor next to any display that has never reported its display-software
 * version:
 *
 *   curl -fsS "http://<hub>:3000/api/display/kiosk-bootstrap?display=<id>" | bash
 *
 * After it runs once, that Pi is on the zero-touch path forever.
 *
 * The script is deliberately thin: it downloads the bundle, checks it, and
 * hands off to the bundle's own `kiosk-update-install.sh`. That means the
 * migration path and the fresh-install path run byte-identical code, so a
 * migrated Pi is indistinguishable from a newly installed one.
 *
 * Auth: the same adoption gate as the bundle endpoint.
 */

import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { isValidDisplayId } from '@/lib/display-filter';
import { requireAdoptedDisplay } from '@/lib/adopted-display-gate';
import { getKioskBundle } from '@/lib/kiosk-bundle';
import { getPackageVersion } from '@/lib/version';

export const dynamic = 'force-dynamic';

/**
 * The hub's own base URL as the *spoke* would reach it. Taken from the
 * request rather than any configured value: whatever address the admin
 * pasted into their terminal is by definition an address that resolves on
 * this LAN, whereas a stored hub URL may be a hostname only the hub knows.
 */
function hubBaseUrl(request: NextRequest): string {
  const host = request.headers.get('host');
  if (!host) return request.nextUrl.origin;
  const proto = request.headers.get('x-forwarded-proto') ?? request.nextUrl.protocol.replace(':', '');
  return `${proto}://${host}`;
}

export async function GET(request: NextRequest): Promise<NextResponse> {
  const displayId = request.nextUrl.searchParams.get('display');
  if (!displayId || !isValidDisplayId(displayId)) {
    return new NextResponse('echo "Missing or invalid ?display=<id>" >&2; exit 1\n', {
      status: 400,
      headers: { 'Content-Type': 'text/plain; charset=utf-8' },
    });
  }

  const authErr = await requireAdoptedDisplay(displayId);
  if (authErr) {
    // Answer in the caller's language: this response is piped into bash, so a
    // JSON error body would just print as noise.
    return new NextResponse(
      `echo "This display is not adopted on the hub yet. Adopt '${displayId}' first, then run this again." >&2; exit 1\n`,
      { status: 403, headers: { 'Content-Type': 'text/plain; charset=utf-8' } },
    );
  }

  let bundle;
  try {
    bundle = await getKioskBundle({ rootDir: process.cwd(), version: await getPackageVersion() });
  } catch {
    return new NextResponse(
      'echo "The hub cannot build the display software bundle right now. Try again after it finishes updating." >&2; exit 1\n',
      { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } },
    );
  }

  const hub = hubBaseUrl(request);
  const script = `#!/usr/bin/env bash
# Home Screens — put this display on the automatic-update path.
# Generated by the hub at ${hub} for display '${displayId}'.
set -euo pipefail

HUB="${hub}"
DISPLAY_ID="${displayId}"
VERSION="${bundle.version}"
EXPECTED_SHA="${bundle.sha256}"

echo "Setting up automatic updates for display '\${DISPLAY_ID}' (version \${VERSION})..."

for tool in curl tar sha256sum; do
  command -v "\${tool}" >/dev/null 2>&1 || { echo "Missing required tool: \${tool}" >&2; exit 1; }
done
if ! command -v jq >/dev/null 2>&1; then
  echo "Installing jq (needed to read update information)..."
  sudo apt-get update -qq && sudo apt-get install -y -qq jq
fi

TMP="\$(mktemp -d)"
trap 'rm -rf "\${TMP}"' EXIT

curl -fsSL -o "\${TMP}/bundle.tar.gz" "\${HUB}/api/display/kiosk-bundle?display=\${DISPLAY_ID}"

ACTUAL_SHA="\$(sha256sum "\${TMP}/bundle.tar.gz" | cut -d' ' -f1)"
if [ "\${ACTUAL_SHA}" != "\${EXPECTED_SHA}" ]; then
  echo "Download did not match the expected checksum. Nothing was changed." >&2
  exit 1
fi

mkdir -p "\${TMP}/payload"
tar -xzf "\${TMP}/bundle.tar.gz" -C "\${TMP}/payload"

bash "\${TMP}/payload/kiosk-update-install.sh"

# Run one real update check now, rather than leaving it to tonight's timer.
#
# This is what actually finishes the migration. The step above installs the
# machinery but not the hardware reporter, which lives behind the privileged
# helper and is only installed by kiosk-update.sh. Until that runs, this Pi
# keeps running its old reporter, keeps omitting the version fields, and keeps
# showing as "Needs setup" in the editor — so a bootstrap that stopped here
# would look successful and change nothing the user can see.
#
# Going through the normal updater (rather than installing the reporter from
# this script) keeps one code path responsible for what lands where, and
# surfaces a broken update here at the terminal instead of silently at 3am.
# No restart is requested: the files apply at the next natural restart.
echo "Applying the current display software..."
UPDATE_RC=0
"/opt/home-screens/current/scripts/kiosk-update.sh" --timeout 30 || UPDATE_RC=\$?
if [ "\${UPDATE_RC}" -ne 0 ] && [ "\${UPDATE_RC}" -ne 10 ]; then
  echo "Automatic updates are installed, but the first update did not finish." >&2
  echo "The display keeps running what it has and will try again tonight." >&2
  exit 1
fi

echo ""
echo "Done. This display now updates itself whenever the hub is updated."
echo "It will pick up changes overnight, or the next time it restarts."
`;

  return new NextResponse(script, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'no-store',
    },
  });
}
